### ISSUE TITLE
Support cells created from nibs

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#1]
The adapter registers and dequeues cells by converting the class name to a string as the reuse identifier. That means that we can only register class+identifier pairs and not use `-[UICollectionView registerNib:forCellWithReuseIdentifier:]`. Even though we don't use nibs in Instagram.app, it doesn't mean that we support this. It shouldn't be too difficult to add.

**Comment by david6p2** [comment]
I download the pod by adding     

    pod 'IGListKit'

to my Podfile, and follow the example of the SingleSectionViewController.swift where they create a sectionController by using:

    let sectionController = IGListSingleSectionController(nibName: NibCell.nibName,
                                                          bundle: nil,
                                                          configureBlock: configureBlock,
                                                          sizeBlock: sizeBlock)

But that isn't available in the current pod.

How can I fix it?

**Comment by rnystrom** [comment]
@david6p2 you can install the latest master by doing
```
pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'
```

**Comment by jessesquires** [comment]
@david6p2 -- we'll be releasing 2.0 of the library in the coming weeks, which will include this work.

**Comment by david6p2** [comment]
Thanks for your help!

**Comment by jessesquires** [comment]
@david6p2 - done. #241

**Comment by choujar** [comment]
@rnystrom if I'm not wrong, there's still not method for this? I can't seem to find a workaround... Thanks in advance!

**Comment by choujar** [comment]
I'm trying to use this method, but I keep ending up with

`libc++abi.dylib: terminating with uncaught exception of type NSException`

Any ideas folks?
