### ISSUE TITLE
How should I design my ListSectionController model if I want to return dynamic cells 

### ISSUE THREAD

**Issue by joseph-francis** [Instagram/IGListKit#1001]
Let's say I have a `Post` model. `Post` has `image`, `title`, `comment` properties. Comment property is optional. So, in my `PostSectionController` (section controller that manages post model), how many `numberOfItems`, `cellForItem`, `sizeForItem` do I return?  So if comment is an empty string, how should I model the code?

**Comment by rnystrom** [comment]
Hey @joseph-francis, check out our demos, we have something almost exactly like this. You can also check out `IGListBindingSectionController` which does a lot of the dynamic stuff for you. There’s a demo for that too! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SebastianBO** [comment]
Hey @joseph-francis did you manage to get it solved?

**Comment by joseph-francis** [comment]
Yes I have. Thank you so much! I forgot to reply. Please also let Ryan
Nystrom know that I really appreciate his help.

Thank you,
JF
