### ISSUE TITLE
MinimumInteritemSpacing not working in sectionController

### ISSUE THREAD

**Issue by aleksanderaleksic** [Instagram/IGListKit#1003]
## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.1.1
- iOS version(s): 11.01
- CocoaPods/Carthage version: -
- Xcode version: 9
- Devices/Simulators affected: All devices
- Reproducible in the demo project? (Yes/No): No
- Related issues:

## ISSUE

I am not shure if i have misunderstood how the `minimumInterItemSpacing` works on the `UICollectionViewFlowLayout`but I am having a problem with it not changing when I set it inside a section controller. 

I have created a custom FlowLayout, where i override the `layoutAttributesForElements` function.
```
class DashboardCustomFlowLayout : UICollectionViewFlowLayout {
    
    override func layoutAttributesForElements(in rect: CGRect) -> [UICollectionViewLayoutAttributes]? {
        guard let superAttributes = super.layoutAttributesForElements(in: rect) else { return nil }
        
        let leftPadding: CGFloat = 0
        let interItemSpacing : CGFloat = minimumInteritemSpacing
        
       ______MORE CODE_____
      ....
      ....
``` 
The problem is that even if i set `minimumInteritemSpacing = 32` inside the section controller, it is always equal to `10` inside off the `layoutAttributesForElements`function. But my impression is that each section can have its own `minimumInteritemSpacing`value.

#### SectionController
```
class DashboardMeasurementSectionController: DashboardSectionController {
    override init() {
        super.init()
        self.inset = UIEdgeInsets(top: 80.0, left: 0, bottom: 0, right: 0)
        self.minimumInteritemSpacing = 32.0
    }
       ______MORE CODE_____
      ....
      ....
``` 

#### ViewController
```
DashboardCustomFlowLayout *layout = [[DashboardCustomFlowLayout alloc] init];
    UICollectionView *collectionView = [[UICollectionView alloc] initWithFrame:CGRectZero collectionViewLayout:layout];
```

**Comment by rnystrom** [comment]
@aleksanderaleksic when you do

```swift
let interItemSpacing : CGFloat = minimumInteritemSpacing
```

You're accessing the [value on the layout itself](https://developer.apple.com/documentation/uikit/uicollectionviewflowlayout/1617706-minimuminteritemspacing?language=objc) and **not** the response from the delegate. If you're going to subclass the flow layout, you need to do something like this to ask the delegate for the item spacing at each section:

```swift
let interItemSpacing: CGFloat
if let delegate = collectionView?.delegate as? UICollectionViewDelegateFlowLayout {
  interItemSpacing = delegate.collectionView(collectionView, layout: collectionView?.collectionViewLayout, minimumInteritemSpacingForSectionAt: indexPath.section)
} else {
  interItemSpacing = 0
}
```

**Comment by zhengyanWork** [comment]
thanks @rnystrom , that works for me.
