### ISSUE TITLE
When i scroll feed first time it jerks

### ISSUE THREAD

**Issue by SerhiiMatvieiev** [Instagram/IGListKit#1004]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0
- iOS version(s): 11.01
- CocoaPods/Carthage version:
- Xcode version: 9
- Devices/Simulators affected: all
- Reproducible in the demo project? (Yes/No): no
- Related issues:

### ISSUE
I have a screen with a lot of different types of cells, when I start to scroll and new cells begin to appear application starts to slow down, but when I scroll to very bottom and scroll back to top it scrolls smoothly and without problems. Do you know what is the problem?
Maybe i can I load all cells at startup somehow?
Thanks a lot!

**Comment by rnystrom** [comment]
@SerhiiMatvieiev how are you sizing your cells? This sounds like a layout issue.

**Comment by SerhiiMatvieiev** [comment]
All my cells has fixed size. For example:

    override func sizeForItem(at index: Int) -> CGSize {
        guard let context = collectionContext else { return .zero }
        let width = context.containerSize.width
        return CGSize(width: width, height: 420)
    } 

I cache only the size where i do some calculations

**Comment by aleufms** [comment]
This is happening to me this too. Using version 3.1.1 and xcode 9.1. Anybody else?

**Comment by rnystrom** [comment]
@SerhiiMatvieiev you’re saying they all have fixed sizes but some cells have calculations? So are they not all fixed sizes?

It sounds like it might be a performance issue. Have you don’t any profiling to understand where the bottle neck is?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@aleufms is it a performance stutter? Like jerky scrolling? If so, can you do a time profile to find out where the issue is?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aleufms** [comment]
@rnystrom nevermind, I've have found the culprit and it is not the iglistkit.

**Comment by SerhiiMatvieiev** [comment]
@rnystrom Yes, you are right, one cell has calculation, but even without this cell i have this problem (

One more thing ) I tried to do some trick, before i do updating i set height collectionView 2000, and after 0.5 sec i return height to normal size. After this trick scroll very smooth, but i think it's not good solution :)

**Comment by rnystrom** [comment]
@SerhiiMatvieiev are you able to reproduce this in an example issue? It sounds _very_ bizarre and something that I've never seen before. At the moment there isn't enough information for me to be helpful 😢

**Comment by achan** [comment]
@aleufms do you have a description of your culprit? I seem to have the same issue in two separate projects of mine using IGListKit: Scrolling loses inertia and goes to a complete stop when I'm trying to load more items to the feed.

**Comment by rnystrom** [comment]
Closing due to previous inactivity. @achan if you want to open a separate issue w/ some details about your setup, that'd be helpful.
