### ISSUE TITLE
Difference between ListStackedSectionController and ListBindingSectionController

### ISSUE THREAD

**Issue by yusuftor** [Instagram/IGListKit#1014]
Please could someone explain to me the difference between ListStackedSectionController and ListBindingSectionController and when you would choose one over the other? I've been looking at the documentation and it's a bit ambiguous to me?
Thanks!

**Comment by rnystrom** [comment]
`IGListStackedSectionController` is a way to build SCs with _child_ SCs. That lets you decompose your controller logic even further into tiny units.

`IGListBindingSectionController` allows you to model your cells, the number of them _and_ their configuration, with view models. These view models are also diffed, provided cell-level insert/delete/update/move animations! It's my favorite component of this library.

Bear in mind that stacked section controllers are going to be deprecated in 4.0.0. See #1099.

**Comment by leojkwan** [comment]
Thanks for the clarification @rnystrom!
