### ISSUE TITLE
'IGListKit/IGListAdapterUpdateListener.h' file not found

### ISSUE THREAD

**Issue by richgabrielli** [Instagram/IGListKit#1015]
I am trying to get started with IGListKit. I am trying to run the example and am stuck at a build error: 'IGListKit/IGListAdapterUpdateListener.h' file not found (see image).

All help is appreciated.

## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.1.1
- iOS version(s): 9.0+
- CocoaPods/Carthage version: 1.3.1
- Xcode version: 9.1
- Devices/Simulators affected: Y
<img width="1394" alt="screen shot 2017-11-12 at 8 58 52 pm" src="https://user-images.githubusercontent.com/7821160/32706842-e873425e-c7ed-11e7-8440-b314f6f84676.png">

- Reproducible in the demo project? (Yes/No): Y
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by richgabrielli** [comment]
Ran "pod update" in Examples-ios directory. Works fine now.

**Comment by rnystrom** [comment]
Gonna follow up on this, the whole project should be usable after cloning 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by richgabrielli** [comment]
Great. Let me know if I can do anything to help.

**Comment by richgabrielli** [comment]
BTW - the Demos are super slick. I can’t wait to dive in and explore how to use in my apps.

**Comment by LRH-iOS-GreenHand** [comment]
Ran "pod update" in Examples-ios directory. Works fine now.
Remind "Could not find proper version of cocoapods (1.3.0) in any of the sources"
