### ISSUE TITLE
Reload a specific section

### ISSUE THREAD

**Issue by nanjundas** [Instagram/IGListKit#1016]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0
- iOS version(s): 11
- Xcode version: 9.0

Based on Comments from - https://github.com/Instagram/IGListKit/issues/208

Tried below code with IGListKit 3.0, I see following error - **

> "Value of type 'ListCollectionContext' has no member 'reload' "

```
override func didSelectItem(at index: Int) {        
        collectionContext?.reload(self)
}
```

**Comment by bogren** [comment]
As mentioned here https://github.com/Instagram/IGListKit/issues/208#issuecomment-306210021. For 3.0 you need to wrap the reload in batch update.
