### ISSUE TITLE
Scrolling is slightly choppy

### ISSUE THREAD

**Issue by jlanesmith** [Instagram/IGListKit#1018]
I integrated IGListKit into an app but the scrolling is slightly choppy/jerky, even after all the cells have loaded. This "choppiness" wasn't an issue when just using UICollectionView. The sizes of the cells are all constant. Suggestions?

## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.1.1
- iOS version(s): 10.1.1
- CocoaPods/Carthage version: 1.3.1
- Xcode version: 9.0.1
- Devices/Simulators affected: No
- Reproducible in the demo project? (Yes/No):
- Related issues:

**Comment by rnystrom** [comment]
@jlanesmith have you run Time Profiler to see what the issue is? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jlanesmith** [comment]
In the cellForItem() function, each cell needs to load several images, which takes time. Is there anything that IGListKit can do to improve this?

**Comment by rnystrom** [comment]
@jlanesmith image loading is beyond the scope of what IGListKit does (trying to keep the lib very focused). Some thoughts:

- Make sure all of your loading is happening off of the main queue
- Look into libraries that do image loading, my fav is [SDWebImage](https://github.com/rs/SDWebImage)
- Here's a more complicated example used in [GitHawk](https://github.com/rnystrom/GitHawk/blob/master/Classes/Issues/Comments/Images/IssueCommentImageCell.swift)

You could look into the "working range" example in our demos app and see if that's useful, though I'd only recommend prefetching media once you really need it.
