### ISSUE TITLE
Who should I contact?

### ISSUE THREAD

**Issue by ChrisGaddes** [Instagram/IGListKit#1019]
I realize this is not the right place to post this but as a fellow GitHub user I thought you guys might be willing to help me out...

I accidentally clicked the "remove email associated with account" link on an email from Instagram. When I try to login now it says "We Detected An Unusual Login Attempt. To secure your account, you need to request help logging in." Do you know of someone at Instagram I can contact who would be able to actually help me? There appears to be no obvious way to "request help logging in"...  Thanks!!

Again, I really do apologize for posting this here, I am just desperate...

**Comment by rnystrom** [comment]
https://help.instagram.com/

**Comment by ChrisGaddes** [comment]
Thanks, but help.instagram.com doesn't have a solution to my question. Oh well, thanks anyways, and have a good one
