### ISSUE TITLE
Add Danger step when adding files to Source/ to run pod_setup.sh

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#1022]
Faster turnaround and help keep the examples from breaking.

**Comment by jessesquires** [comment]
nice 😎

**Comment by mukeshthawani** [comment]
I started working on this so, just wanted to confirm: When files are added to Source/ then we need to warn if Podfile.lock was not modified. Is it correct or we need to do something else?

**Comment by rnystrom** [comment]
@mukeshthawani awesome! Ya that’s a good idea. Just make sure to check the lock files on the _examples_, not the root. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
