### ISSUE TITLE
Complete Section Controllers are hidden

### ISSUE THREAD

**Issue by Narsail** [Instagram/IGListKit#1024]
## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: newest
- iOS version(s): 11.1
- Xcode version: 9.1

I'm missing SectionControllers on the initial .reloadData() from the adapter. I know the data has been loaded and I know that the invisible section controller even loaded the to be shown cell. I can even tap the free space and trigger the detail view. But it won't be shown until I scrolled down and up again. 

Any ideas why this is happening?

![img_fc8500e08a91-1](https://user-images.githubusercontent.com/7859096/33242563-58077f74-d2d7-11e7-8d72-e9cc81850d5b.jpeg)

**Comment by rnystrom** [comment]
@Narsail can you run the debugger dump and paste the results here?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Narsail** [comment]
@rnystrom I feel kinda stupid but how exactly do I activate the debug logs of IGListKit?

**Comment by Narsail** [comment]
It seems that the error was triggered by something else and not the IGListKit. Can be closed!

**Comment by Bruce-pac** [comment]
> It seems that the error was triggered by something else and not the IGListKit. Can be closed!

What is the reason? Can you tell me? I had a similar problem. Thank you
