### ISSUE TITLE
Architecture for implementing search for nested array within model

### ISSUE THREAD

**Issue by vincent-peng** [Instagram/IGListKit#1026]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

Firstly I do apologize for opening issue for this kind of topic, but I'll appreciate if I get the hints from you all.

So long story short, what's the appropriate architecture if I want to achieve search functionality for nested array within model?
The model setup is very similar to GitHawk's `IssueAssigneesModel` which needs the search functionality for `users`, where it remains the `expanded` state in the `IssueAssigneesSectionController` as well for example.

Again sorry if this is out of topic, I have to say IGListKit is awesome! :)

Thanks,
Vincent

**Comment by rnystrom** [comment]
Thanks @vincent-peng! Definitely not off topic.

Could you provide a little more detail about your search setup that is different from the ones in examples project or GitHawk? Those cover most basic search, let me know if there’s something you’d like to go into more detail over!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vincent-peng** [comment]
Closing this issue now. This can be solved on the model setup.
