### ISSUE TITLE
UISearchBar can adopt ambiguous layout under certain conditions.

### ISSUE THREAD

**Issue by wmcbruce** [Instagram/IGListKit#1027]
## New issue checklist

- [ ✅ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ✅ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0
- iOS version(s): 11
- CocoaPods/Carthage version: 1.3.1
- Xcode version: 9.1
- Devices/Simulators affected: iOS Simulator: iPhone 8Plus, iPhone X
- Reproducible in the demo project? (Yes/No): No
- Related issues: Unknown

### Debug information

```bash
Console Log:
2017-11-28 00:09:49.992191-0600 IGL PL Testing[5450:715022] [LayoutConstraints] View has an ambiguous layout. See "Auto Layout Guide: Ambiguous Layouts" for help debugging. Displaying synopsis from invoking -[UIView _autolayoutTrace] to provide additional detail.

*UISearchBar:0x7fc232010d70- AMBIGUOUS LAYOUT for UISearchBar:0x7fc232010d70.minX{id: 1840}, UISearchBar:0x7fc232010d70.minY{id: 1841}, UISearchBar:0x7fc232010d70.Width{id: 1842}

Legend:
	* - is laid out with auto layout
	+ - is laid out manually, but is represented in the layout engine because translatesAutoresizingMaskIntoConstraints = YES
	• - layout engine host
2017-11-28 00:09:50.372166-0600 IGL PL Testing[5450:715022] [LayoutConstraints] Window has a view with an ambiguous layout. See "Auto Layout Guide: Ambiguous Layouts" for help debugging. Displaying synopsis from invoking -[UIView _autolayoutTrace] to provide additional detail.

*UISearchBar:0x7fc232010d70- AMBIGUOUS LAYOUT for UISearchBar:0x7fc232010d70.minX{id: 1840}, UISearchBar:0x7fc232010d70.minY{id: 1841}, UISearchBar:0x7fc232010d70.Width{id: 1842}

Legend:
	* - is laid out with auto layout
	+ - is laid out manually, but is represented in the layout engine because translatesAutoresizingMaskIntoConstraints = YES
	• - layout engine host
```

### Issue:

When interacting with 3D Touch elements or links within object items, the UISearchBar can adopt an ambiguous layout. My app uses a very vanilla search cell and section controller based on the example documentation.  

####Video showing issue
[https://youtu.be/hfQX5hHRpTQ](https://youtu.be/hfQX5hHRpTQ)

####Video showing view debugging
[https://youtu.be/lC3UdVOj74s](https://youtu.be/lC3UdVOj74s)

-updated video links

**Comment by rnystrom** [comment]
@wmcbruce unfortunately I need to close this as layout issues are beyond IGListKits scope (unless it’s `IGListCollectionViewLayout`).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Pranit-Harekar** [comment]
@wmcbruce Not sure but I think this issue is related to the use of `topLayoutGuide`. Since iOS 11 `topLayoutGuide` is deprecated instead you should use `safeAreaLayoutGuide`. Again, not sure you need to check your layouts.
