### ISSUE TITLE
Update single section continuously

### ISSUE THREAD

**Issue by brurend** [Instagram/IGListKit#1029]
## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.1.1
- iOS version(s): 11.1.2
- Xcode version: 9.1

I have a singleSectionController with a progress bar that I need to update it with the result of a request that is in another viewController. I'm sending the data with NSNotification and calling `
[self.adapter performUpdatesAnimated:YES completion:nil];` but it only instantiate the singleSectionController once and does not update it every time.

Is there other way to update the singleSectionController?

**Comment by rnystrom** [comment]
Hey @brurend! We recommend injecting dependencies to section controllers. Notifications would be a very basic, but functional, version of this too. Just have the section controller listen for changes and reload it’s cells.

Check out our injection demo here:
https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/ViewControllers/AnnouncingDepsViewController.swift

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
