### ISSUE TITLE
Danger is broken? (Needs write access)

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#1030]
```
Danger does not have write access to the PR to set a PR status.
```

Seen here: https://travis-ci.org/Instagram/IGListKit/jobs/298804094

**Comment by rnystrom** [comment]
Dang, will investigate 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@jessesquires so I think this is fine

http://danger.systems/guides/faq.html#why-am-i-seeing-quot-set-status-failed-quot-on-my-github-oss-project

**Comment by jessesquires** [comment]
cool! 👍
