### ISSUE TITLE
Requested support for shouldSelectItem(at index: Int) in ListSectionController

### ISSUE THREAD

**Issue by IntervalsPro** [Instagram/IGListKit#1033]
## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.1.1
- iOS version(s): iOS 11

A ListSectionController has a didSelectItem method, but no shouldSelectItem method.  Is there a reason for that?  We have a need to determine if an item should be selectable and it seems like a natural addition.  If desired, I could take a stab at it.

**Comment by weyert** [comment]
Sounds like a great idea to me!

**Comment by fchauvin** [comment]
This would be great! 

If you haven't gotten around to implementing this yet, I will gladly take the time to add it and throw up a PR.

**Comment by rnystrom** [comment]
Love it! Would be happy to review someone's PR for this. @fchauvin all yours if you want 😄 

Off the top of my head, `IGListSectionController` should implement the base method and return `YES`. Then just forward the delegate method and you're done! (+ unit tests 😇 )

**Comment by fchauvin** [comment]
Sounds good 😄

**Comment by IntervalsPro** [comment]
Hi Forrest,
Sorry for the slow reply.  Lost track of this thread over the holidays.  Feel free to knock this out.  If for some reason you can’t get to it, just let me know.

Thanks!
Jeff

Jeff Bailey
FourthFrame Technologies




On Jan 3, 2018, at 5:28 PM, Forrest Chauvin <notifications@github.com> wrote:

Sounds good 😄

**Comment by mohpor** [comment]
Almost 2 years after last comment. Do you have any news?!
