### ISSUE TITLE
Cannot create cells from Nib in Cocoapods release

### ISSUE THREAD

**Issue by yusuftor** [Instagram/IGListKit#104]
Hi,

I saw that in your example project, you have the following code for creating a cell from a nib:

```
IGListSingleSectionController(nibName: NibCell.nibName,
                              bundle: nil,
                              configureBlock: configureBlock,
                              sizeBlock: sizeBlock)
```

However, in the version of IGListKit downloaded from Cocoapods, the function is no where to be seen. Would it be possible to update the Cocoapods version so that it has this function?
Thanks!

**Comment by rnystrom** [comment]
@yusuftor we should! I'll bump a 1.1 release and include this

**Comment by jessesquires** [comment]
This needs to be 2.0, not 1.1.

This is a breaking change

**Comment by jessesquires** [comment]
@rnystrom - we should probably wait until current PRs are merged.

Since this is a breaking release, we should pack-in as many breaking changes as we can.

There's a 2.0 draft at https://github.com/Instagram/IGListKit/releases

**Comment by jessesquires** [comment]
@yusuftor you can track our progress for the next release here:

https://github.com/Instagram/IGListKit/milestone/1

**Comment by rnystrom** [comment]
@jessesquires actually #56 wasn't breaking, I meant cutting a 1.1.0 and picking the nib feature before we cut 2.0.0. What do you think?

**Comment by jessesquires** [comment]
Ahhh.. I see. 

At this point, I think it's more valuable (and simpler) to just pack up everything into `2.0` and release that. Do we foresee any other major breaking changes coming up?

**Comment by rnystrom** [comment]
No I don't think so

**Comment by jessesquires** [comment]
Also, it's only been 13 days since `1.0` 😄 

I say we wait another week or two, keep merging PRs, then tag and release 2.0.

And honestly, `master` is pretty stable. If anyone needs those features *right now*, then can point CocoaPods/Carthage there for now.

**Comment by yusuftor** [comment]
Ok so which branch should I be directing Cocoapods to to access those features?

**Comment by Sherlouk** [comment]
@yusuftor  
Adding the following:
```pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'```
to your `Podfile` should enable it to get the latest version of Master from the repository.

**Comment by jessesquires** [comment]
Yep -- although master is pretty stable (and tested), it should be used with caution 😄

**Comment by jessesquires** [comment]
Going to go ahead and close this out
