### ISSUE TITLE
How can I store an error message that can be read by the adapter's empty view function ?

### ISSUE THREAD

**Issue by durul** [Instagram/IGListKit#1042]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: IGListKit (~> 3.0)
- iOS version(s): >=9.0
- CocoaPods/Carthage version: 1.3.1
- Xcode version: 9.2 (9C40b)
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): NA
- Related issues: NA

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

Hello Guys,

I work on project used by IGListKit and VIPER. 

Function ```performUpdates``` is called on the adapter, the adapter checks the datasource and see if it's empty, It calls ```func emptyView(for listAdapter: ListAdapter) -> UIView?```

My question is how it is possible to the view itself at that point can store an error message that can be read by the adapter's empty view function.

Best,

**Comment by rnystrom** [comment]
Hey @durul!

The `emptyViewForListAdapter:` method is called every time the list is empty. You're encouraged to return a **new view instance** whenever this method is called. You can configure a new view with whatever labels, images, etc that you want.

For a real-world example, check out how we dynamically configure the empty view in this open source app:

https://github.com/rnystrom/GitHawk/blob/50b6ed75816ff8cd1f0bf6f3f644c2eab819e570/Classes/View%20Controllers/BaseListViewController.swift#L167-L173

**Comment by durul** [comment]
thank you.
