### ISSUE TITLE
minimumInteritemSpacing not being respected on last row

### ISSUE THREAD

**Issue by bernaferrari** [Instagram/IGListKit#1045]
I am having the following issue:

Sample app:
<img width="397" alt="screen shot 2017-12-25 at 22 27 33" src="https://user-images.githubusercontent.com/351125/34343810-f266ada4-e9c2-11e7-9871-63bafed0c2c2.png">
My app (exaggerated):
![img_3568](https://user-images.githubusercontent.com/351125/34343825-52ac5114-e9c3-11e7-941c-9ffb947ba983.PNG)

with the following code:
```
    override init() {
        super.init()
        self.minimumInteritemSpacing = 1
        self.minimumLineSpacing = 1
    }

    override func sizeForItem(at index: Int) -> CGSize {
        let width = collectionContext?.containerSize.width ?? 0
        
        let maxitemsinarow = 3
        // div is the standard value for division
        var div: CGFloat = 3
        
        let itemscount = numberOfItems()
        if (index + 1 > itemscount - (itemscount % maxitemsinarow) && itemscount % maxitemsinarow != 0) {
            div = CGFloat(numberOfItems() % maxitemsinarow)
            print("Div: \(div)")
            if (div == 1.0) {
                // when div is one, there is no reason for division or interitemspacing.
                return CGSize.init(width: width, height: 48)
            }
        }
        return CGSize.init(width: floor(width / div)-1, height: 48)
    }
```

It will set the maximum number of items possible in a row (maxitemsinarow), so no space gets wasted. The problem is, last column's minimumInteritemSpacing is not respected by IGListKit.

**Comment by rnystrom** [comment]
@bernaferrari which `UICollectionViewLayout` are you using?

**Comment by bernaferrari** [comment]
UICollectionViewFlowLayout (is this what you asked?). If you open the MixedDataViewController from samples and paste the code above, you'll get the same result as I'm getting.

**Comment by rnystrom** [comment]
Ah, this is just b/c of the size math going on here. If your width is `414` and you're dividing by 2, then `floor(414 / 2) - 1` == 206. Your layout then looks like:

```
[====206====]-1-[====206====]
```

Where the interitem spacing is `1`. So you're only consuming `413` points of width, leaving a 1pt white line along the right side of the screen. 

This is typical `UICollectionViewFlowLayout` behavior. In Instagram, we actually fudge the math on the last item to be slightly wider 😄  We also added a [stretch-to-edge](https://github.com/Instagram/IGListKit/blob/master/Source/IGListCollectionViewLayout.mm#L521-L523) property to `IGListCollectionViewLayout` for exactly this.

**Comment by bernaferrari** [comment]
Thanks, I was able to find out my mistake (which fortunately had nothing to do with IGListKit)! In the "edges" the width-margin should be computed as half, since they is only one item in its side. By doing this, everything worked fine.
