### ISSUE TITLE
IGLIstCollectionView.m 

### ISSUE THREAD

**Issue by marwahAlenezi** [Instagram/IGListKit#1047]
i can't find the IGListCollectionView.m and .h files in the IGList pods file

**Comment by rnystrom** [comment]
@marwahAlenezi which version are you using?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marwahAlenezi** [comment]
@rnystrom IGListKit (3.1.1)

**Comment by rnystrom** [comment]
`IGListCollectionView` was removed as a requirement previously, so you don’t need to use it. We recently added another version back that improves performance, but isn’t a requirement. Feel free to use vanilla `UICollectionView`, or use the master branch for the latest features.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
