### ISSUE TITLE
How to implement a control that a collection on a UIView.

### ISSUE THREAD

**Issue by AaronZhang2015** [Instagram/IGListKit#1049]
I want implement a control that a collectionView on a UIView.
I don't want declare the adapter in the UIViewController. I pass the data to the view, and the view implemented IGListAdapterDataSource by itself.
But the init method need a viewcontroller. Any recommend implementation?

**Comment by weyert** [comment]
You should be able to pass `nil`. That's what I am doing in my custom views that use `IGListKit`

**Comment by rnystrom** [comment]
Yup @weyert is exactly right!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AaronZhang2015** [comment]
@weyert Thanks
