### ISSUE TITLE
'Tail Loading' example doesn't add new cells the second time you pull the table view

### ISSUE THREAD

**Issue by bonzoq** [Instagram/IGListKit#105]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- Library version(s): 2.0.0
- iOS version(s): 10.1
- Devices/Simulators affected: iPhone 7 Plus simulator (14B70)
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: None

### Repro steps

1. Open 'Tail Loading' example.
2. Pull to add new items.
3. A spinner cell appears at the bottom and after two seconds cells with new words appear.
4. Pull to add new items again.
5. No spinner cell appears and no cells with new words appear the second time you pull the table view.

**Comment by jessesquires** [comment]
Thanks @bonzoq ! 👍
