### ISSUE TITLE
Collectionview doesn't accept IGListCollectionViewLayout as custom class

### ISSUE THREAD

**Issue by JEKos** [Instagram/IGListKit#1053]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.1.1
- iOS version(s): 11.0~
- CocoaPods/Carthage version: 
- Xcode version: 9
- Devices/Simulators affected: -
- Reproducible in the demo project? (Yes/No): No
- Related issues:

### Debug information

I'm trying to add `IGListCollectionViewLayout` as custom class for my collectionview but when I'm pressing Enter, disappears. I tested 2 times with 2 demo projects, and it works without problem, but in my main project doesn't work. I have already done clean Derived Data, clean project and build again, restart Mac, restart Xcode, but still the same.

![alt text](https://media.giphy.com/media/l0HUap5kmoLgiQGWc/giphy.gif)

**Comment by rnystrom** [comment]
@JEKos your base class for that object is `UIcollectionViewFlowLayout`, that’s why it’s disappearing. Our layout inherits from `UICollectionViewLayout`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JEKos** [comment]
No it wasn't that.
I had to change in collectionView from Flow to Custom. The funny thing is, in my demo projects, doesn't need to do that. It says to Flow and the base class is UICollectionViewFlowLayout
![alt text](https://media.giphy.com/media/l0HUee9UeZusfMXK0/giphy.gif)

**Problem solved! Thanks for the help!**
