### ISSUE TITLE
How to pass item's index?

### ISSUE THREAD

**Issue by JEKos** [Instagram/IGListKit#1054]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.1.1
- iOS version(s): 11.0~
- CocoaPods/Carthage version: 
- Xcode version: 9
- Devices/Simulators affected: -
- Reproducible in the demo project? (Yes/No): -
- Related issues:

### Debug information

Hi, I replaced my collectionview with Tail Loading. It's a Grid with photos. When the user press the cell, goes to another ViewController with the image in full screen and swipe left and right to see the photos. 
How can I pass the index of the selected cell to the other View controller?

I used to use this in prepareforSegue for the collectionView :
```
if segue.identifier == "photodetailseg"{
            let detailVC = segue.destination as! ViewController
            let indexPaths : NSArray = self.collectionView.indexPathsForSelectedItems! as NSArray
            let indexPath : IndexPath = indexPaths[0] as! IndexPath
            detailVC.startIndex = indexPath.row
            self.ColView.deselectItem(at: indexPath, animated: true)
        }
```

**Comment by JEKos** [comment]
@rnystrom Can you help me with that please?

**Comment by rnystrom** [comment]
@JEKos are you still using storyboard segues to navigate between view controllers?

**Comment by JEKos** [comment]
Yes

**Comment by JEKos** [comment]
@rnystrom Or my question is, how to add the didSelect method in ListSectionController (This what Tail Loading use)? It's only available in ListSingleSectionControllerDelegate?

**Comment by JEKos** [comment]
I found the solution I added ListSingleSectionControllerDelegate and tried to make it like the SingleSectionStoryboard Example of the Library and then from `didSelect` method I did this:
```
func didSelect(_ sectionController: ListSingleSectionController, with object: Any) {
        let section = adapter.section(for: sectionController)
        let DestViewController = storyboard?.instantiateViewController(withIdentifier: "nextviewcontroller") as! ViewController
        DestViewController.startIndex = section
        self.navigationController?.pushViewController(DestViewController, animated: true)
    }
```
