### ISSUE TITLE
Element Not Accessible from Section Controller

### ISSUE THREAD

**Issue by Smiller193** [Instagram/IGListKit#1073]
Hello, I am having a little problem with my CommentsViewController that is being implemented using the IGListKit. I have created a cell that is being used to render the comments. Each cell contains a picture, the text, and a button that lets you flag inappropriate comments or reply to comments similar to how it is done in instagram.

This is the CollectionVIewCell

    import Foundation
    import UIKit
    import Firebase
    
    protocol CommentCellDelegate: class {
        func optionsButtonTapped(cell: CommentCell)
        func handleProfileTransition(tapGesture: UITapGestureRecognizer)
    }
    class CommentCell: UICollectionViewCell {
        weak var delegate: CommentCellDelegate? = nil
        override var reuseIdentifier : String {
            get {
                return "cellID"
            }
            set {
                // nothing, because only red is allowed
            }
        }
        var didTapOptionsButtonForCell: ((CommentCell) -> Void)?
        
        var comment: CommentGrabbed?{
            didSet{
                guard let comment = comment else{
                    return
                }
              //  print("apples")
                // textLabel.text = comment.content
                //shawn was also here
                profileImageView.loadImage(urlString: comment.user.profilePic!)
                //  print(comment.user.username)
                let attributedText = NSMutableAttributedString(string: comment.user.username!, attributes: [NSAttributedStringKey.font: UIFont.boldSystemFont(ofSize: 14)])
                attributedText.append(NSAttributedString(string: " " + (comment.content), attributes: [NSAttributedStringKey.font: UIFont.systemFont(ofSize: 14)]))
                textView.attributedText = attributedText
            }
        }
        let textView: UITextView = {
            let textView = UITextView()
            textView.font = UIFont.systemFont(ofSize: 14)
            textView.isScrollEnabled = false
            textView.isEditable = false
            return textView
        }()
        lazy var profileImageView: CustomImageView = {
            let iv = CustomImageView()
            iv.clipsToBounds = true
            iv.isUserInteractionEnabled = true
            iv.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(handleProfileTransition)))
            iv.contentMode = .scaleAspectFill
            return iv
        }()
        
        lazy var flagButton: UIButton = {
            let flagButton = UIButton(type: .system)
            flagButton.setImage(#imageLiteral(resourceName: "icons8-Info-64"), for: .normal)
            flagButton.addTarget(self, action: #selector(optionsButtonTapped), for: .touchUpInside)
            return flagButton
        }()
        
        @objc func optionsButtonTapped (){
            didTapOptionsButtonForCell?(self)
        }
        
        @objc func onOptionsTapped() {
            delegate?.optionsButtonTapped(cell: self)
        }
        @objc func handleProfileTransition(tapGesture: UITapGestureRecognizer){
            delegate?.handleProfileTransition(tapGesture: tapGesture)
          //  print("Tapped image")
        }
        override init(frame: CGRect){
            super.init(frame: frame)
            addSubview(textView)
            addSubview(profileImageView)
            addSubview(flagButton)
            textView.anchor(top: topAnchor, left: profileImageView.rightAnchor, bottom: bottomAnchor, right: rightAnchor, paddingTop: 4, paddingLeft: 4, paddingBottom: 4, paddingRight: 4, width: 0, height: 0)
            profileImageView.anchor(top: topAnchor, left: leftAnchor, bottom: nil, right: nil, paddingTop: 8, paddingLeft: 8, paddingBottom: 0, paddingRight: 0, width: 40, height: 40)
            profileImageView.layer.cornerRadius = 40/2
            flagButton.anchor(top: topAnchor, left: nil, bottom: nil, right: rightAnchor, paddingTop: 4, paddingLeft: 0, paddingBottom: 0, paddingRight: 4, width: 40, height: 40)
            flagButton.addTarget(self, action: #selector(CommentCell.onOptionsTapped), for: .touchUpInside)
        }
        required init?(coder aDecoder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }
    }

Now this controller has a delegate method that allows me to do some operation on click of the button. It allows me to present an alertcontroller which asks either reply or flag.
When I click reply I want the textfield to autoGenerate with @someUserName like how Instagram does and then I type some text, hit reply, and send the comment.

Below is my CommentSectionController
[    import UIKit
    import IGListKit
    import Foundation
    import Firebase](url)
    
    protocol CommentsSectionDelegate: class {
        func CommentSectionUpdared(sectionController: CommentsSectionController)
    }
    class CommentsSectionController: ListSectionController,CommentCellDelegate {
        weak var delegate: CommentsSectionDelegate? = nil
        var comment: CommentGrabbed?
        let userProfileController = ProfileeViewController(collectionViewLayout: UICollectionViewFlowLayout())
        var eventKey: String?
        override init() {
            super.init()
            // supplementaryViewSource = self
            //sets the spacing between items in a specfic section controller
            inset = UIEdgeInsets(top: 5, left: 0, bottom: 0, right: 0)
        }
        // MARK: IGListSectionController Overrides
        override func numberOfItems() -> Int {
            return 1
        }
        override func sizeForItem(at index: Int) -> CGSize {
            let frame = CGRect(x: 0, y: 0, width: collectionContext!.containerSize.width, height: 50)
            let dummyCell = CommentCell(frame: frame)
            dummyCell.comment = comment
            dummyCell.layoutIfNeeded()
            let targetSize =  CGSize(width: collectionContext!.containerSize.width, height: 55)
            let estimatedSize = dummyCell.systemLayoutSizeFitting(targetSize)
            let height = max(40+8+8, estimatedSize.height)
            return  CGSize(width: collectionContext!.containerSize.width, height: height)
            
        }
        
        override var minimumLineSpacing: CGFloat {
            get {
                return 0.0
            }
            set {
                self.minimumLineSpacing = 0.0
            }
        }
        
        override func cellForItem(at index: Int) -> UICollectionViewCell {
            guard let cell = collectionContext?.dequeueReusableCell(of: CommentCell.self, for: self, at: index) as? CommentCell else {
                fatalError()
            }
            //  print(comment)
            cell.comment = comment
            cell.delegate = self
            return cell
        }
        override func didUpdate(to object: Any) {
            comment = object as? CommentGrabbed
        }
        override func didSelectItem(at index: Int){
        }
        
        func optionsButtonTapped(cell: CommentCell){
            print("like")
       
            let comment = self.comment
            _ = comment?.uid
            
            // 3
            let alertController = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
            
            // 4
            if comment?.uid != User.current.uid {
                let flagAction = UIAlertAction(title: "Report as Inappropriate", style: .default) { _ in
                    ChatService.flag(comment!)
                    
                    let okAlert = UIAlertController(title: nil, message: "The post has been flagged.", preferredStyle: .alert)
                    okAlert.addAction(UIAlertAction(title: "Ok", style: .default))
                    self.viewController?.present(okAlert, animated: true, completion: nil)
                }
                let cancelAction = UIAlertAction(title: "Cancel", style: .cancel, handler: nil)
                let replyAction = UIAlertAction(title: "Reply to Comment", style: .default, handler: { (_) in
                    //do something here later to facilitate reply comment functionality
                    print("Attempting to reply to user \(comment?.user.username) comment")
                    
                })
                alertController.addAction(replyAction)
                alertController.addAction(cancelAction)
                alertController.addAction(flagAction)
            }else{
                let cancelAction = UIAlertAction(title: "Cancel", style: .cancel, handler: nil)
                let deleteAction = UIAlertAction(title: "Delete Comment", style: .default, handler: { _ in
                    ChatService.deleteComment(comment!, (comment?.eventKey)!)
                    let okAlert = UIAlertController(title: nil, message: "Comment Has Been Deleted", preferredStyle: .alert)
                    okAlert.addAction(UIAlertAction(title: "Ok", style: .default))
                    self.viewController?.present(okAlert, animated: true, completion: nil)
                    self.onItemDeleted()
    
                })
                alertController.addAction(cancelAction)
                alertController.addAction(deleteAction)
                
            }
            self.viewController?.present(alertController, animated: true, completion: nil)
            
        }
        func onItemDeleted() {
            delegate?.CommentSectionUpdared(sectionController: self)
        }
        func handleProfileTransition(tapGesture: UITapGestureRecognizer){
            userProfileController.user = comment?.user
            if Auth.auth().currentUser?.uid != comment?.uid{
                        self.viewController?.present(userProfileController, animated: true, completion: nil)
            }else{
                //do nothing
                
            }
    
            
        }
        
        
    }

Now my textView that I utilize for writing comments is in another file

    import UIKit
    protocol CommentInputAccessoryViewDelegate {
        func handleSubmit(for comment: String?)
    }
    
    class CommentInputAccessoryView: UIView, UITextViewDelegate {
        var delegate: CommentInputAccessoryViewDelegate?
        /*
        // Only override draw() if you perform custom drawing.
        // An empty implementation adversely affects performance during animation.
        override func draw(_ rect: CGRect) {
            // Drawing code
        }
        */
        
       fileprivate let submitButton: UIButton = {
            let submitButton = UIButton(type: .system)
            submitButton.setTitle("Submit", for: .normal)
            submitButton.setTitleColor(.black, for: .normal)
            submitButton.titleLabel?.font = UIFont.boldSystemFont(ofSize: 14)
            submitButton.addTarget(self, action: #selector(handleSubmit), for: .touchUpInside)
            //submitButton.isEnabled = false
            return submitButton
        }()
        
        lazy var commentTextView: CommentInputTextView = {
            let textView = CommentInputTextView()
           // textView.placeholder = "Add a comment"
            textView.delegate = self
            textView.isScrollEnabled = false
            textView.backgroundColor = .white
            textView.font = UIFont.boldSystemFont(ofSize: 15)
            textView.textContainer.lineBreakMode = .byWordWrapping
           // textView.addTarget(self, action: #selector(textFieldDidChange(_:)), for: .editingChanged)
            return textView
        }()
        
        override init(frame: CGRect) {
            super.init(frame: frame)
           // backgroundColor = .red
            //1
            autoresizingMask = .flexibleHeight
            addSubview(submitButton)
            submitButton.anchor(top: topAnchor, left: nil, bottom: bottomAnchor, right:rightAnchor, paddingTop: 0, paddingLeft: 0, paddingBottom: 0, paddingRight: 12, width: 50, height: 0)
            addSubview(commentTextView)
            //3
            if #available(iOS 11.0, *){
                        commentTextView.anchor(top: topAnchor, left: leftAnchor, bottom: safeAreaLayoutGuide.bottomAnchor, right: submitButton.leftAnchor, paddingTop: 8, paddingLeft: 8, paddingBottom: 8, paddingRight: 0, width: 0, height: 0)
            }else{
                //fallback on earlier versions
            }
    
            setupLineSeparatorView()
    
        }
        // 2
        override var intrinsicContentSize: CGSize {
            return .zero
        }
        
        fileprivate func setupLineSeparatorView(){
            let lineSeparatorView = UIView()
            lineSeparatorView.backgroundColor = UIColor.rgb(red: 230, green: 230, blue: 230)
            addSubview(lineSeparatorView)
            lineSeparatorView.anchor(top:topAnchor, left: leftAnchor, bottom: nil, right: rightAnchor, paddingTop: 0, paddingLeft: 0, paddingBottom: 0, paddingRight: 0, width: 0, height: 0.5)
        }
        
        @objc func handleSubmit(){
            guard let commentText = commentTextView.text else{
                return
            }
            delegate?.handleSubmit(for: commentText)
        }
        
        @objc func textFieldDidChange(_ textField: UITextView) {
            let isCommentValid = commentTextView.text?.count ?? 0 > 0
            if isCommentValid {
                submitButton.isEnabled = true
            }else{
                submitButton.isEnabled = false
            }
        }
        func clearCommentTextField(){
            commentTextView.text = nil
            commentTextView.showPlaceholderLabel()
        }
        
        required init?(coder aDecoder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }
        
        
    }

My question is how would I auto populate the textview from my commentsSectionController using IGListKit and keeping the same structure because I don't have access to it from my commentsSectionController

**Comment by rnystrom** [comment]
@Smiller193 did you find an answer? Would love if you could document to help others in case they get stuck!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Smiller193** [comment]
No I didn't I just figured nobody cared to see it or help so I closed it
