### ISSUE TITLE
Officially drop iOS 8 support

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#1078]
- Remove any iOS 8 or 9 specific hacks or (deprecated) API usage
- Update Xcodeproj settings
- Update podspec
- Update travis CI

**Comment by lorixx** [comment]
We should!

**Comment by bdotdub** [comment]
What would be involved in this? Would it simply be removing [this](https://github.com/Instagram/IGListKit/blob/4f9c61a37f088eed5b037ffbb79a47fe58c96989/Source/IGListAdapterUpdater.m#L184-L191)?

**Comment by jessesquires** [comment]
Yes, that and updating CocoaPods and travis CI

**Comment by jessesquires** [comment]
and xcode project settings, etc

**Comment by jessesquires** [comment]
@bdotdub is IG still deploying to iOS 9? If not, it would be nice to drop that too

**Comment by jessesquires** [comment]
Looking at the App Store, it looks like IG is iOS 10+ now

**Comment by bdotdub** [comment]
Ha - you beat me to it!

**Comment by iperry90** [comment]
We'll drop just iOS 8 support for now
