### ISSUE TITLE
Add Danger flag to ignore doc generation PRs

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#1088]
Maybe we can add #docgen to the PR body or something. See #1085 for false-positive

**Comment by jessesquires** [comment]
your title didn't include `#docgen` though... ??

**Comment by rnystrom** [comment]
Haha I know, cause we gotta build it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
@rnystrom ... 🤔 I'm confused. Danger already checks for `#docgen` in the title of a PR...

**Comment by rnystrom** [comment]
LOL ignore me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
