### ISSUE TITLE
Make last section stretchable to superview instead of safe area

### ISSUE THREAD

**Issue by Valerun666** [Instagram/IGListKit#1090]
Is it possible to set constraints for last ListSectionController of UICollectionView to Superview instead of Safe Area. Cause when I set constraints for UICollectionView it stretches as needed, but last section stays on it's place and doesn't stretch. 

**Currently:**

![screen shot 2018-02-07 at 12 41 52 pm](https://user-images.githubusercontent.com/17543683/35912497-6c4a2790-0c05-11e8-8986-0bc39d3e8852.png)

Where pink is UICollectionView and gray is last section.

**Expected:** 

![screen shot 2018-02-07 at 12 43 58 pm](https://user-images.githubusercontent.com/17543683/35912471-582c9a9a-0c05-11e8-8532-e9f5fdc46d4a.png)

**Comment by rnystrom** [comment]
@Valerun666 you probably want to just ignore the bottom safe area insets on the collection view. Would that work?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Valerun666** [comment]
Worked. @rnystrom , thank you so much!
