### ISSUE TITLE
Invalidate ListCollectionViewLayout after device rotation

### ISSUE THREAD

**Issue by jurex** [Instagram/IGListKit#1095]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.2.0
- iOS version(s): 11.2.5
- CocoaPods/Carthage version: CocoaPods 1.3.1
- Xcode version: 9.2
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No): Yes, Storyboard demo for example
- Related issues:

Hello, is there a way to invalidate `ListCollectionViewLayout` after device rotation? It seems that when I use this layout and rotate my device, `sizeForItem` is not triggered in section controllers. It is working fine when switching back to UICollectionViewFlowLayout. Any advice would be appreciated. Thanks!

**Comment by jessesquires** [comment]
Hey @jurex !

You should be able to do this in your view controller. See Apple's `UIViewController` docs and look for the `traitCollectionDidChange` callback.

**Comment by jurex** [comment]
Thanks @jessesquires 👍

I've ended up with something like this:

```
override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
        super.traitCollectionDidChange(previousTraitCollection)
        adapter.reloadData(completion: nil)
}
```

It's not probably the most effective solution, but it's working. Thnx again for great library✌️
