### ISSUE TITLE
Calculate dynamic UICollectionView insets

### ISSUE THREAD

**Issue by dermaaarkus** [Instagram/IGListKit#1096]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.2.0
- iOS version(s): iOS 10, iOS 11
- CocoaPods/Carthage version: 1.4.0
- Xcode version: 9.2 (9C40b)
- Devices/Simulators affected: all
- Reproducible in the demo project? (Yes/No): No
- Related issues: 

### Debug information

> 2018-02-09 15:31:20.898986+0100 WetterApp[22891:908719] *** Assertion failure in -[IGListAdapter setCollectionViewDelegate:] (), -----/Pods/IGListKit/Source/IGListAdapter.m:128
2018-02-09 15:31:20.919973+0100 App[22891:908719] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionViewDelegateFlowLayout conformance is automatically handled by IGListAdapter.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000114a2612b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001140b6f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000114a2b2f2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010da883db -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 165
	4   IGListKit                           0x000000010e0cf0b0 -[IGListAdapter setCollectionViewDelegate:] + 832
>

Hi,

I want to use center my cells in my `UICollectionView` like described in this posts (its not from me but the same idea):
https://stackoverflow.com/a/37065909

However, when I try to Implement the `UICollectionViewDelegateFlowLayout` with the method `func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, insetForSectionAt section: Int) -> UIEdgeInsets` I get an **Assertion failure** (please see the Log above).

1. I can't see that the `IGListAdapter` is handling this delegate calculations, so I assume that this is a bug. Could you please check it?
2. How is it possible to make such dynamic inset calculations?

**Comment by rnystrom** [comment]
Hey @dermaaarkus ! We automatically confirm and implement app flow layout delegate methods to make it easier to use flow layout with IGListKit. The assert is to warn you that your implementation will never get called.

You can set [section insets](https://github.com/Instagram/IGListKit/blob/master/Source/IGListSectionController.h) on the section controller itself. Looking at the SO link you should be able to do exactly this!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dermaaarkus** [comment]
Thanks for your fast response. I've been on vacations... I will give it a try soon and report it!

**Comment by dermaaarkus** [comment]
I figured out how to use it, thanks!
Maybe my solution helps someone, so I post it here and close the issue 👍 

---

I subclassed the the `ListSingleSectionController`, that I used.

```swift
import UIKit
import IGListKit

final class ListInsetSingleSectionController: ListSingleSectionController {
    typealias InsetBlock = (_ item: Any, _ context: ListCollectionContext?) -> UIEdgeInsets
    
    private let insetBlock: InsetBlock
    private var item: Any?
    
    init(storyboardCellIdentifier identifier: String, configureBlock: @escaping ListSingleSectionCellConfigureBlock, sizeBlock: @escaping ListSingleSectionCellSizeBlock, insetBlock: @escaping InsetBlock) {
        self.insetBlock = insetBlock
        super.init(storyboardCellIdentifier: identifier, configureBlock: configureBlock, sizeBlock: sizeBlock)
    }
    
    init(nibName: String, bundle: Bundle?, configureBlock: @escaping ListSingleSectionCellConfigureBlock, sizeBlock: @escaping ListSingleSectionCellSizeBlock, insetBlock: @escaping InsetBlock) {
        self.insetBlock = insetBlock
        super.init(nibName: nibName, bundle: bundle, configureBlock: configureBlock, sizeBlock: sizeBlock)
    }
    
    init(cellClass: AnyClass, configureBlock: @escaping ListSingleSectionCellConfigureBlock, sizeBlock: @escaping ListSingleSectionCellSizeBlock, insetBlock: @escaping InsetBlock) {
        self.insetBlock = insetBlock
        super.init(cellClass: cellClass, configureBlock: configureBlock, sizeBlock: sizeBlock)
    }
    
    override var inset: UIEdgeInsets {
        set {
            fatalError("insets are determined dynamically")
        }
        get {
            if let item = item {
                return insetBlock(item, self.collectionContext)
            } else {
                return .zero
            }
        }
    }
    
    override func didUpdate(to object: Any) {
        super.didUpdate(to: object)
        item = object
    }
}
```

And I use the class like this

```swift
func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController {
        let configureBlock: ListSingleSectionCellConfigureBlock = { (item: Any, cell: UICollectionViewCell) in
            // ...
        }
        let sizeBlock: ListSingleSectionCellSizeBlock = { (item: Any, context: ListCollectionContext?) -> CGSize in
            // ...
        }
        let insetBlock: ListInsetSingleSectionController.InsetBlock = { (item: Any, context: ListCollectionContext?) -> UIEdgeInsets in
            if let item = item as? CellViewModel, item == viewModels.first? {
                let leftInset: CGFloat = 0 // TODO: do your dynamic calculation here
                return UIEdgeInsets(top: 0, left: leftInset, bottom: 0, right: 0)
            } else {
                return .zero
            }
            
        }
        let sectionController = ListInsetSingleSectionController(
            storyboardCellIdentifier: "CollectionViewCell",
            configureBlock: configureBlock,
            sizeBlock: sizeBlock,
            insetBlock: insetBlock
        )
        return sectionController
    }
```
