### ISSUE TITLE
Implementing Protocol inside a Cell Delegate not working

### ISSUE THREAD

**Issue by elrafael16** [Instagram/IGListKit#1100]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```
I'm trying to implement a protocol delegate when a button is tapped inside my HomePostcell.
But it seems the HomePostCellDelegate is not working inside the ListSectionController.

When I run the code, the print statement inside the protocol delegate inside the list section controller, is not printing in the console.

Am I missing some code? Or Am I implementing the Protocol Delegate wrong?

Thanks

```swift
// This is the code for the cell 

import UIKit

protocol HomePostCellDelegate {

    func didTapButton(for cell: HomePostCell)
}

class HomePostCell: UICollectionViewCell {

var delegate: HomePostCellDelegate?

    lazy var Button: UIButton = {
        let button = UIButton(type: .system)
        button.setImage(#imageLiteral(resourceName: "button").withRenderingMode(.alwaysOriginal), for: .normal)
        button.addTarget(self, action: #selector(handlefrwrd), for: .touchUpInside)
        return button
}()

   override init(frame: CGRect) {
        super.init(frame: frame)

   addSubview(Button)
        Button.anchor(top: photoImageView.bottomAnchor, left: nil, bottom: nil, right: rightAnchor, paddingTop: 0, paddingLeft: 0, paddingBottom: 0, paddingRight: 0, width: 40, height: 50)

}

func handleButton() {
        print("handling button")
        delegate?.didTapButton(for: self)
 }

// This the Protocol being implemented inside the list section controller

class FeedSectionController: ListSectionController, ListDisplayDelegate, HomePostCellDelegate {


func didTapButton(for cell: HomePostCell){
          print("didTapButton from Section Controller")
}
```

**Comment by rnystrom** [comment]
@elrafael16 where do you set the `delegate` on the cell? It should be in the `cellForItem(...)` override.

```swift
override func cellForItem(at index: Int) -> UICollectionViewCell {
  let cell = // dequeue cell from self.collectionContext
  cell.delegate = self
  return cell
}
```

**Comment by elrafael16** [comment]
Ok that solved my problem. Thank You Very Much. :)
