### ISSUE TITLE
[RFC] Change -diffIdentifier return type to NSString

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#1101]
Been exploring this idea in #1081 and starting to really like it. If two different models happen to use the same identifier (say some primary key field from a db), we can namespace the identifiers automatically by combining the class string + identifier, reducing implementation complexity and diff collisions.

Also by typing the return value, we remove the ability for overly complicated identifiers (e.g. implementation `-hash` and `-isEqual:` on a custom identifier object).

This might risk performance regressions though. Something to keep in mind.

This would obviously be a pretty huge change (externally and internally) but I think it might be the right call going forward.

**Comment by jessesquires** [comment]
+1

I mean, *in practice*, this is usually always a string right?

Also, using `NSString`/`String` is better for Swift inter-op.

**Comment by rnystrom** [comment]
Ya interior is a huge win here. Mostly always a string. This will be a pain in the butt internally, but we can drive it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by calimarkus** [comment]
❤️- let's do it. Namespacing would make the usage in complex projects much simpler.

If we want an easier transition, we could have an additional `identifierString` API and deprecate `diffIdentifier`. And then maybe in a later release we could completely drop it?

**Comment by rnystrom** [comment]
Tbh I'm fine wrapping up a 3.3 release w/ some iterative improvements and then start landing 4.0, breaking-change stuff like this. Makes it easier on ourselves.

I'm setting a target goal of May-June for 4.0.

**Comment by zhubofei** [comment]
Swift uses Int as hashValue though

**Comment by jessesquires** [comment]
@zhubofei What's your concern? I don't understand your comment.

**Comment by zhubofei** [comment]
@jessesquires nvm😂, wasn't thinking straight last night.

**Comment by rnystrom** [comment]
Received some pushback internally on how much churn this will cause. Plus on another project we've discovered that building your own key object performs MUCH faster than merging strings.

I'm in favor of closing this for now and maybe considering having a special Key type in the Swift bridge (instead of returning `String`).

Any concerns?

**Comment by Ziewvater** [comment]
Closing this out since we haven't heard any requests for this, and it seems like there was pushback internally to the thrash this would cause. We can reopen and reconsider in the future if someone wants this.
