### ISSUE TITLE
Multiple Sections and Proper Implementation

### ISSUE THREAD

**Issue by sasquatchgit** [Instagram/IGListKit#1102]
This is not an issue, I have struggled a lot trying to **implement** the following layout:

![img_8193](https://user-images.githubusercontent.com/9585608/36147336-dd24bfd4-10dd-11e8-9ac0-5f4d967eaf9e.JPG)
**Problems**
1. How to show Flight/Train/Bus data based on button selection. As of now, I have put the buttons in the section header and returning the type of Section Controller based on button selection. But this reloads the whole data again.

2. How to give "Restaurant" a header title? I can't use a section header.

From `MainViewController` I am returning `TravelSectionController` and `ItinerarySectionController`. 
From `TravelSectionController` I am returning `FlightSectionController` or `TrainSectionController` based on header button selection and returning `EmbeddedCollectionViewCell` for horizontal scrolling.

I have seen all the examples and GitHawk App. I am still unable to find an elegant structure for this implementation. Please point me in the right direction.

**Comment by rnystrom** [comment]
@sasquatchgit for 1 that’s basically how I’d do it. Isn’t the point for things to reload? What is reloading that isn’t supposed to?

For 2, sometimes we just insert a really simple section controller between items. Keeps things simple.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sasquatchgit** [comment]
Thanks @rnystrom for replying.
For 1, I was looking for something which mimics UISegmentContol. Specifically, the App crashes by doing following:
i) Start async data fetch
ii) Change the Section (bus to train, eg) before data fetch is complete
iii) It crashes when the background data fetch is complete in previous section controller. Error being invalid update on collection view.
Also, is there a way I don’t have to download the data again if it’s already downloaded when changing section controller?

**Comment by rnystrom** [comment]
How are you updating the collection view when data changes? The purpose of IGListKit is to make that almost impossible.

Re: downloading, you should have an in-memory store of some sort that holds on to all the data and just filter based on the selection of the segmented control.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sasquatchgit** [comment]
I am just loading a new section controller based on button selected in the header. >From TravelSectionController I am returning FlightSectionController or TrainSectionController based on header button selection
