### ISSUE TITLE
Minor Code Analysis Issues

### ISSUE THREAD

**Issue by RamblinWreck77** [Instagram/IGListKit#1103]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.2.0
- iOS version(s): Only tested on 10.3+ project
- CocoaPods/Carthage version: 1.4.0
- Xcode version: 9.2
- Devices/Simulators affected: N/A
- Reproducible in the demo project? (Yes/No): N
- Related issues: N?A

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

Hello! Not sure if these are even worth fixing, but I wanted to point out just incase that the lastest IGListKit produces both a "Memory Error" and "Lexical or Preprocessor Issue".

https://imgur.com/a/kZrgR

**Comment by jessesquires** [comment]
Thanks @RamblinWreck77 !

Please don't attach or link to screenshots. Can you paste the errors here that you're seeing?

**Comment by rnystrom** [comment]
Hmm the nil is fine. But I’m not sure about the import error. How could I repro this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RamblinWreck77** [comment]
Weird, I can't get this to happen in the demo project but it happens in our workspace every time. 

Sorry to waste your time. I'm at a loss to why analysis would yield different results for the same pod in different projects. We're not using any specialized settings

**Comment by rnystrom** [comment]
Hmm, bummer. If you do find out where this is coming from, please let us know!
