### ISSUE TITLE
Choosing right diffIdentifier and isEqual when getting data from network call

### ISSUE THREAD

**Issue by sasquatchgit** [Instagram/IGListKit#1104]
- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

I have display flight info in horizontal section. I have looked up `HorizontalSectionController` from example and using that. Please help me declaring my Section Model. As of now, I am using the following:
```
class FlightData{
    
    var flights : [Flight]!
    var source : PackageLocation?
    var destination : PackageLocation?
    var dummyID = "something"   
}

extension FlightData: Equatable {
    static public func ==(rhs: FlightData, lhs: FlightData) -> Bool {
        return rhs.dummyID == lhs.dummyID
    }
}
extension FlightData: ListDiffable {

    public func diffIdentifier() -> NSObjectProtocol {
        return dummyID as NSObjectProtocol
    }

    public func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
        guard let object = object as? FlightData else {
            return false
        }
        return self == object
    }
}
```
The `flights` array is populated after a network call.

**Comment by rnystrom** [comment]
What I would probably recommend is having your equality check the contents of the `flights` array. To improve performance, maybe create a flattened string of ids for the array contents. That way every equality check is constant vs O(n).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sasquatchgit** [comment]
Thanks for your reply, but doesn't it mean that the whole section will be reloaded even if a single element of `flights` array change?

**Comment by rnystrom** [comment]
@sasquatchgit yes that’s true. In this case I might recommend using `IGListBindingSectionController` so you get automatic cell-level diffing too!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sasquatchgit** [comment]
Ok, Thanks.
