### ISSUE TITLE
Cells do not deselect when scroll view delegate is set for ListStackedSectionController adapter

### ISSUE THREAD

**Issue by yusuftor** [Instagram/IGListKit#1105]
Hi, I am using a `ListStackedSectionController`. One of the section controllers has multiple items. These can be selected, but there should only be one selected at a time (the others should deselect on new item selection). This works fine, until I set `adapter.scrollViewDelegate = self`. For some reason, it makes the collection view act as if `allowsMultipleSelection` is set to true. Even if I explicitly set false to `allowsMultipleSelection` it still allows multiple selection of items within the section controller. This has got to be a bug?

**Comment by rnystrom** [comment]
@yusuftor sounds really bizarre. Could you send us a sample app reproducing the bug? Then I can figure out what’s going on.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yusuftor** [comment]
I think it'll be quicker if I just tell you how to reproduce it using the IGListKitExamples app, it's quite an easy one to reproduce:

1. In `StackedViewController` add `adapter.scrollViewDelegate = self` to `viewDidLoad()`

2. Add the scrollViewDelegate extension:

```
extension StackedViewController : UIScrollViewDelegate {
    func scrollViewDidScroll(_ scrollView: UIScrollView) {}
}
```

3. In `DisplaySectionController` add this code:

```
override func didSelectItem(at index: Int) {
        print("select index", index)
    }
    
override func didDeselectItem(at index: Int) {
    print("deselect index", index)
}
```

Now run the app and go to `Stacked Section Controllers` and click on some of the items like the ones called "Section 0, Cell 0" etc. You'll see that didSelectItem is always called but didDeselectItem isn't. Now remove the line `adapter.scrollViewDelegate = self` and try it again. You should see `didDeselectItem` starts to work! Hope this is an easy fix!

**Comment by yusuftor** [comment]
No worries, your wish is my command! I have set it up as stated above [IGListKit-master-2.zip](https://github.com/Instagram/IGListKit/files/1740357/IGListKit-master-2.zip)

**Comment by rnystrom** [comment]
Ok I can reproduce the behavior. Should note that it happens with any section controller, not just stacked. You can also repro this by setting the `collectionViewDelegate`.

This is a real bug! My bug in fact, introduced in #853 😅

The proxy checks for [didSelect Selectors](https://github.com/Instagram/IGListKit/blob/master/Source/Internal/IGListAdapterProxy.m#L29) but **not** deselect. Will get a PR up with this.

**Comment by ajanuar** [comment]
Hello, is there any timeline for 3.3.0?

**Comment by rnystrom** [comment]
@ajanuar not too long! Wrapping up a few more PRs and internal projects first.

**Comment by sasquatchgit** [comment]
Hey, is this solved? I am still facing this.
