### ISSUE TITLE
Getting the indexPath of a Cell 

### ISSUE THREAD

**Issue by elrafael16** [Instagram/IGListKit#1107]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```
How do I get the indexpath of the cell inside the ListSectionController or ModelController? 
Before with the UICollectionViewController I was using
let indexPath = collectionView.indexPath(for: HomePostCell) with the protocol delegates
but for IGListKit I am confused on how to get the indexPath?

I think the solution is simple but I just cant figure it out. Sorry for the noob question.

Hope you could help me

//This is the Cell Controller

protocol HomePostCellDelegate {
    func handleDelegate(for cell: HomePostCell)
}

class HomePostCell: UICollectionViewCell { 

  var delegate: HomePostCellDelegate?
    
  lazy var Button: UIButton = {
  let button = UIButton(type: .system)
  button.setImage(#imageLiteral(resourceName: "button").withRenderingMode(.alwaysOriginal), 
  for: .normal)
  button.addTarget(self, action: #selector(handleTap), for: .touchUpInside)
  return button
   }()

override init(frame: CGRect) {
        super.init(frame: frame)

  addSubview(Button)
  Button.anchor(top: photoImageView.bottomAnchor, left: leftAnchor, bottom: nil, right: nil, 
  paddingTop: 0, paddingLeft: 4, paddingBottom: 0, paddingRight: 0, width: 120, height: 50)

}

func handleTap() {
        delegate?.handleDelegate(for: self)
  }
}

//This is the FeedSectionController

class FeedSectionController: ListSectionController, ListDisplayDelegate, HomePostCellDelegate {

let post = posts[indexPath.item]

// This is where I get confused
func handleDelegate(for cell: HomePostCell) {

  let indexPath = collectionView.indexPath(for: HomePostCell)
  let post = posts[indexPath.item]

}

// This is the Model Controller

class FeedHomeController: UIViewController {

let collectionView: UICollectionView = {
        let layout = UICollectionViewFlowLayout()
        let view = UICollectionView(frame: CGRect.zero, collectionViewLayout: layout)
        view.backgroundColor = UIColor.white
        return view
    }()
    
    lazy var adapter:ListAdapter = {
        return ListAdapter(updater: ListAdapterUpdater(), viewController: self, workingRangeSize: 1)
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.addSubview(collectionView)
        adapter.collectionView = collectionView
        adapter.dataSource = self
}

extension FeedHomeController: ListAdapterDataSource {
    
func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
  let feedItems: [ListDiffable] = MyVariables.posts
  return feedItem
}
    
func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) ->
ListSectionController {
  return FeedSectionController()
}
    
func emptyView(for listAdapter: ListAdapter) -> UIView? {
  return nil
 }

**Comment by rnystrom** [comment]
Use this API on the `collectionContext` yo get the index. You shouldn’t work with index paths inside the section controller, since it’s section can change. However if you absolutely need an index path, you can access the section via `self.section` inside the controller.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
