### ISSUE TITLE
How to get the height of the cell dynamically？

### ISSUE THREAD

**Issue by honest666** [Instagram/IGListKit#1110]
I use the IGLIstKit framework nested in the Cell CollectionView, which is the height of the cell height, but the height of the IGlistKit cell write a fixed number, if i want to put pictures into the cell, dynamically update the cell height, I do not know if there is any way?

**Comment by rnystrom** [comment]
@honest666 if you want to dynamically update, you can call the invalidate APIs on the `collectionContext` from within a section controller. Check out the examples, we have a few with dynamic, changing heights using images and text.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by honest666** [comment]
## How to make the picture  autoplay？
Like this effect
[](url)https://monosnap.com/file/oQyBhBLaD7p3UrIwFWfxC4WdGsNwOk

**Comment by rnystrom** [comment]
@honest666 there are scrolling APIs that you can use for this with timers or things. There are plenty of examples out there about how to make auto paging views that would be good to check out.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
