### ISSUE TITLE
How to make smooth expandable cell animation? 

### ISSUE THREAD

**Issue by dimaosa** [Instagram/IGListKit#1112]
Hi there, thanks for a great product.

From the example of a Mixed-Data, we could expand and collapse in ExpandableSectionController(), but the duration of animation is not matching with the duration of how cell changed. 

If we change the duration from `0.5` to `4.0` sec. We will see how the cell collapsed immediately and collection view matches the animation duration 4.0 , here is gif with `4.0 sec` http://recordit.co/Im6yNumqHE 

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/8642157/36595121-a6440938-18a9-11e8-90e1-479d24adfc66.gif)

```swift
UIView.animate(withDuration: 4.0,
                       delay: 0,
                       usingSpringWithDamping: 0.4,
                       initialSpringVelocity: 0.6,
                       options: [],
                       animations: {
                        self.collectionContext?.invalidateLayout(for: self)
        })
```

Is it possible to make smooth expand and collapse for **both cell and collectionView**?

**Comment by rnystrom** [comment]
I think you’d want to wrap the invalidation _and_ an animation of the cell contents at the same time.

```swift
UIView.animate(withDuration: 4.0) {
  self.collectionContext?.invalidateLayout(for: self)
  cell.collapse(true)
}
```

The hardest part here is the fact that we’re transition ning between two label truncation states. Might have to get into Core Animation transitions to nail that down.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rayray** [comment]
What does `cell.collapse()` do (in theory)?

I'm calling `invalidateLayout` and the changing the `frame` of the cell, making sure it matches the `sizeForItem`, but the cell itself is still not animating.

```
override func didSelectItem(at index: Int) {
        item.collapsed = !item.collapsed
        
        if let cell = self.cellForItem(at: 0) as? CommentCollectionViewCell {
            UIView.animate(withDuration: 0.3, delay: 0, options: [.curveEaseInOut], animations: {
                self.collectionContext?.invalidateLayout(for: self)
                
                cell.frame = (self.item.collapsed) ? cell.collapsedFrame() : cell.expandedFrame()
            })
        }       
}
```

Running iOS 12.2.

**Comment by rayray** [comment]
@dimaosa What was your solution here? I tried changing the `frame` of the cell in the block as @rnystrom mentioned above but I wasn't able to get it to animate correctly.

**Comment by dimaosa** [comment]
Hi @rayray , I used this soultion https://github.com/Instagram/IGListKit/issues/1112#issuecomment-368003120 , which @rnystrom provided, and it worked fine for me
