### ISSUE TITLE
Show emptyView with one item

### ISSUE THREAD

**Issue by Recouse** [Instagram/IGListKit#1114]
Is it possible to show emptyView with one item that used like header?
<img width="349" alt="screen shot 2018-02-25 at 12 28 29" src="https://user-images.githubusercontent.com/7093328/36639135-71eb746c-1a27-11e8-88cf-ec25f6b0ef62.png">

### New issue checklist

- [✔️] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ✔️] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.2.0

**Comment by rnystrom** [comment]
It’s not, the empty view only shows up when it’s truly empty. I’d recommend using another section controller to display some empty view in this case. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Check out this example that we use in GitHawk

https://github.com/rnystrom/GitHawk/blob/master/Classes/Notifications/NoNewNotificationsSectionController.swift

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Recouse** [comment]
Thanks, I'll check it out.
