### ISSUE TITLE
UIRefresh makes sectionHeadersPinToVisibleBounds be at wrong y position

### ISSUE THREAD

**Issue by JeanVinge** [Instagram/IGListKit#1119]
- `IGListKit` version: 3.1.1
- iOS version(s): 11.2.6
- CocoaPods/Carthage version: 1.4.0
- Xcode version: Version 9.2 (9C40b)
- Devices/Simulators affected: All devices and simulators
- Reproducible in the demo project? (Yes/No): Yes

Add on the SupplementaryViewController available in IGListKit Demo

        let layout = collectionView.collectionViewLayout as? UICollectionViewFlowLayout
        if #available(iOS 9.0, *) {
            layout?.sectionHeadersPinToVisibleBounds = true
        }
        
        if #available(iOS 10.0, *) {
            collectionView.refreshControl = UIRefreshControl()
        }

<img width="598" alt="captura de tela 2018-03-07 as 11 16 26" src="https://user-images.githubusercontent.com/2262712/37096961-0691c156-21f9-11e8-821b-ede3c073c618.png">

**Comment by rnystrom** [comment]
Hmm, I'm not sure if this is an issue w/ IGListKit since its `UICollectionViewFlowLayout` that does the layout. Have you done any debugging? Do you know where the wrong layout attributes are coming from?

**Comment by Ant4116** [comment]
No I don’t know can you fix it
