### ISSUE TITLE
NotificationCenter observer not working inside cell in IGListkit

### ISSUE THREAD

**Issue by elrafael16** [Instagram/IGListKit#1120]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```
I have a notification observer that sends a notification whenever the video inside the cell stops.
I usually do it like this but with IGListKit its not working.
Do I need to something different with the implementation of IGListkit?
```
import UIKit
import AVFoundation

class DetailCell: UICollectionViewCell {
    
    var playerLayer: AVPlayerLayer!
    let player = AVPlayer()

func play() {
        if let videoUrlString = videos?.videoUrl, let url = NSURL(string:videoUrlString) {
            
            let playerItem = AVPlayerItem(url: url as URL!)
            playerLayer = AVPlayerLayer(player: player)
            playerLayer?.frame = photoImageView.bounds
            photoImageView.layer.addSublayer(playerLayer!)
            player.replaceCurrentItem(with: playerItem)
            player.automaticallyWaitsToMinimizeStalling = false
            player.play()
            
            let bounds: CGRect = photoImageView.bounds
            playerLayer.videoGravity = AVLayerVideoGravityResizeAspectFill
            playerLayer.bounds=bounds
            let point = CGPoint(x: bounds.midX,y :bounds.midY)
            playerLayer.position = point
            
             NotificationCenter.default.addObserver(self, selector:#selector(DetailCell.videoEnded),name:NSNotification.Name.AVPlayerItemDidPlayToEndTime,object: nil)
   }

    func videoEnded() {
        print("videoEnded")
    }
}
```

**Comment by heumn** [comment]
Does the video start to play in the cell, you are just missing the callback on `videoEnded`?

**Comment by elrafael16** [comment]
OK i got this. I just moved my NSNotification inside the ListSectionController.
