### ISSUE TITLE
Advice on Small Pagination Tweak Using IGListkit

### ISSUE THREAD

**Issue by Smiller193** [Instagram/IGListKit#1121]
So thanks to IGListKit I have gotten my comments section to load properly in real time with my database. I have also gotten pagination to work thanks to this link/guide
https://github.com/Instagram/IGListKit/issues/237

I only have two problems. Sometimes when I scroll down the spinner gets stuck. Also I want to sort of do what Instagram does where it loads the latest comments and then adds the earlier ones as you scroll up. It seems to be the other way around in the implementation I found here.

I have cut the code down to the primary function responsible for pagination to save everyone some time.

    //    //will use this perform pagination
        func scrollViewWillEndDragging(_ scrollView: UIScrollView,
                                       withVelocity velocity: CGPoint,
                                       targetContentOffset: UnsafeMutablePointer<CGPoint>) {
            
            let distance = scrollView.contentSize.height - (targetContentOffset.pointee.y + scrollView.bounds.height)
            //distance from bottom of screen
            print(distance)
            if !loading && distance < 200 {
                //will begin to add spinning indicatior
                loading = true
                adapter.performUpdates(animated: true, completion: nil)
                DispatchQueue.global(qos: .default).async {
                    // fake background loading task
                    sleep(2)
                    DispatchQueue.main.async {
                        self.loading = false
                        let itemCount = self.comments.count
                        //will append new objects here
    //                    self.comments.append(Array(comments..<itemCount + 5))
                        print("attempting pagiantion")
                        //put true or false condition to stop pagination
                        if !self.isFinishedPaging{
                            ChatService.fetchComments(forChatKey: self.eventKey, currentPostCount: self.comments.count, lastKey: (self.comments.last?.key!)!, isFinishedPaging: self.isFinishedPaging, completion: { (ref, pagComments,boolValue) in
                                self.messagesRef = ref
                                self.isFinishedPaging = boolValue
                                self.comments.append(contentsOf: pagComments)
                                self.adapter.performUpdates(animated: true, completion: nil)
                            })
                        }else{
                            print("did not page")
                        }
    
                    }
                }
            }
        }

**Comment by Smiller193** [comment]
Also somtimes the spinner pops up even when there is no more content to page

**Comment by rnystrom** [comment]
@Smiller193 is there the chance that `ChatService.fetchComments(...)` doesn't execute the completion block? There isn't enough detail here on what could be wrong. It's likely not an issue w/in IGListKit since we do this extensively w/in Instagram.

If you want to reverse your list and do a _head load_, prepending new content, you can do that just fine! Just change your logic a little.

If you want to prepend and maintain your scroll position, that's a little trickier at the moment. See #242.

**Comment by Smiller193** [comment]
static func fetchComments(forChatKey eventKey: String,currentPostCount: Int,lastKey: String,isFinishedPaging:Bool, completion: @escaping ( [CommentGrabbed],Bool) -> Void){
            print(currentPostCount)
            var isFinishedPagingTemp = isFinishedPaging
            var currentCommentsArray = [CommentGrabbed]()
            var currentComment: CommentGrabbed!
            
            let commentRef = Database.database().reference().child("Comments").child(eventKey)
            var query = commentRef.queryOrderedByKey()
            if currentPostCount > 0 {
                print(lastKey)
                query = query.queryStarting(atValue: lastKey)
            }
           
            query.queryLimited(toFirst: 10).observeSingleEvent(of: .value, with: { (commentSnapshot) in
                guard var allComments = commentSnapshot.children.allObjects as? [DataSnapshot] else {
                    return completion( [],true)
                }
                if currentPostCount > 0 {
                    allComments.removeFirst()
                }
                if allComments.count < 1 {
                    isFinishedPagingTemp = true
                    return completion([],true)
                }
                for comments in allComments {
                    currentComment = CommentGrabbed(snapshot: comments)
                    // print(currentComment.key)
                    currentCommentsArray.append(currentComment)
                    print(currentComment)
                }
                
                if currentCommentsArray.count == allComments.count && !isFinishedPagingTemp {
                    completion(currentCommentsArray,false)
                }else{
                    return completion([],true)
                }
            }) { (err) in
                print("Couldn't find comments in DB", err)
            }
            
        }


Well, this is my fetchCommentsFunction the way it works is it fetches a certain number of comments and returns a bool variable that lets me know whether I need to keep paging or not. Inside the previous code block, it seems to change loading to true and then appends it  Inside the else statement it doesn't seem to update the adapter or change loading back to false. I'm not sure if that may be the cause of the spinner not disappearing or not.


Also the nature that I am going for is similar to Instagram where the newest comments are loaded. As you scroll to the top you see a load more comments button. You click it and it loads earlier comments so like load more comments would upload comments from yesterday or an hour ago for example. Like in the comments section

**Comment by rnystrom** [comment]
@Smiller193 hmm so if there's an error is the completion block never called?

**Comment by Smiller193** [comment]
what do you mean by error @rnystrom an error in the sense that it didn't page?
if so then no

**Comment by Smiller193** [comment]
so how should I change  my else block to make it go away

**Comment by Smiller193** [comment]
would it be something like this put in the else block
self.loading = false
seld.adapter.performUpdates

**Comment by rnystrom** [comment]
I think you need to make sure that the completion block of your networking is executed in every possible case (success or failure) so that the update call on the adapter happens.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Smiller193** [comment]
ah okay I fixed that issue thanks
do you have a link to the loading older comments at the top example

**Comment by rnystrom** [comment]
@Smiller193 unfortunately I don't have any examples inverted tail loading 😞
