### ISSUE TITLE
pls Help me 

### ISSUE THREAD

**Issue by Amar04** [Instagram/IGListKit#1123]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'the cell returned from -collectionView:cellForItemAtIndexPath: does not have a reuseIdentifier - cells must be retrieved by calling -dequeueReusableCellWithReuseIdentifier:forIndexPath:'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001111c312b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000110857f41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001111c82f2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00000001102f8d69 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x0000000112827222 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 2702
	5   UIKit                               0x000000011282678e -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:] + 35
	6   UIKit                               0x000000011282bd00 -[UICollectionView _updateVisibleCellsNow:] + 4860
	7   UIKit                               0x0000000112831c21 -[UICollectionView layoutSubviews] + 364
	8   UIKit                               0x0000000111e25a6d -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1439
	9   QuartzCore                          0x000000011a99f61c -[CALayer layoutSublayers] + 159
	10  QuartzCore                          0x000000011a9a37ad _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 401
	11  QuartzCore                          0x000000011a92a86c _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 364
	12  QuartzCore                          0x000000011a957946 _ZN2CA11Transaction6commitEv + 500
	13  UIKit                               0x0000000111d4e7ee _UIApplicationFlushRunLoopCATransactionIfTooLate + 167
	14  UIKit                               0x00000001126bfa1b __handleEventQueueInternal + 6894
	15  CoreFoundation                      0x0000000111166101 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	16  CoreFoundation                      0x0000000111205f71 __CFRunLoopDoSource0 + 81
	17  CoreFoundation                      0x000000011114aa19 __CFRunLoopDoSources0 + 185
	18  CoreFoundation                      0x0000000111149fff __CFRunLoopRun + 1279
	19  CoreFoundation                      0x0000000111149889 CFRunLoopRunSpecific + 409
	20  GraphicsServices                    0x00000001194b79c6 GSEventRunModal + 62
	21  UIKit                               0x0000000111d545d6 UIApplicationMain + 159
	22  ShopperAdd                          0x000000010fa8dcc7 main + 55
	23  libdyld.dylib                       0x0000000115dfcd81 start + 1
	24  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by rnystrom** [comment]
We will need more info to help debug. Repro steps, an example project, sample code... there’s nothing we can do with just a stack trace.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brurend** [comment]
`reason: 'the cell returned from -collectionView:cellForItemAtIndexPath: does not have a reuseIdentifier - cells must be retrieved by calling -dequeueReusableCellWithReuseIdentifier:forIndexPath:'`

@Amar04 The problem seems to be in your `cellForItem` method, could you send it here so we can take a look at it and make sure everything is right?

Also, the stack trace don't seem to have any direct IGListKit call, are you sure the bug is related to it?

**Comment by rnystrom** [comment]
Good call @brurend, no IGListKit in the trace at all. Closing b/c we're lacking info and nothing pointing at an IGLK issue.
