### ISSUE TITLE
A bug was found and the scroll bar was blocked

### ISSUE THREAD

**Issue by honest666** [Instagram/IGListKit#1125]
###A bug was found and the scroll bar was blocked
https://gyazo.com/1b0773543a04812431b2551d458a0c6f

**Comment by rnystrom** [comment]
@honest666 can you tell us how to reproduce this or provide an example project?

**Comment by honest666** [comment]
In IGListKit/Examples/Examples-iOS/IGListKitExamples/SectionControllers/FeedItemSectionController , scrollbars are occluded by headView

**Comment by rnystrom** [comment]
Oh weird, yup I can repro this. Strangely if I switch the layout in that demo to use ours, it works just fine. Hmm.

**Comment by honest666** [comment]
That's an ios original bug

**Comment by rnystrom** [comment]
Going to close as this seems like a UIKit issue

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
