### ISSUE TITLE
How to Pass Back data from Embedded Section Controller to Parent Section Controller

### ISSUE THREAD

**Issue by sasquatchgit** [Instagram/IGListKit#1126]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

I am using Embedded Section Controller for displaying a horizontal list as in Demo Project. I am able to get the selected object in Embedded Section Controller through `func didSelectItem(at index: Int)` but I want to pass back this selected object to Parent Section Controller. How can I achieve this?

**Comment by yusuftor** [comment]
Use a delegate pattern :) Have a look at the `StoryboardLabelSectionController` in the iOS examples app for a similar example of this. Essentially you pass the section controller to the delegate and then you can find the object by querying the adapter for the section index in the parent. In the examples app the delegate happens to be a view controller, but it'll be no different with a parent section controller. Hope that helps..

**Comment by sasquatchgit** [comment]
Thanks!
