### ISSUE TITLE
More descriptive assert messages when collectionView is nil

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#113]
A lot of our `IGAssert` message strings are copy/pasted. Would be great to have more descriptive asserts about what is happening instead of just "Reloading collection view" etc, etc.

[Example](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L720)

**Comment by romankl** [comment]
If this one is still free/ not assigned, could I take a look at it?

**Comment by rnystrom** [comment]
@romankl all yours!
