### ISSUE TITLE
Supplementary views (apparently) don't work with new Swift fork

### ISSUE THREAD

**Issue by AndrewSB** [Instagram/IGListKit#1130]
### General information

- `IGListKit` version: `swift`
- Reproducible in the demo project: Yes, see http://github.com/AndrewSB/SupplementaryViewsNotSelf
- Related issues:

I've created a reduced example that shows the issue I'm running into. I set my section's `supplementaryViewSource`, but the section ends up not showing the supplementary view defined in that source.

**Comment by rnystrom** [comment]
@AndrewSB since that’s all still WIP lets keep the convo in #1081

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
