### ISSUE TITLE
Can you share a swift carousel image code?

### ISSUE THREAD

**Issue by honest666** [Instagram/IGListKit#1133]
## Can you share a swift carousel image code, I didn't find it
Left and right with the kind of gap, showing a middle, left and right exposed a little other cell's

**Comment by rnystrom** [comment]
Check out our [horizontal section controller example](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/HorizontalSectionController.swift) that has a horizontally-scrolling, nested adapter. You can just enable paging on the scroll view and size your cells to be about the width of the parent collection view.
