### ISSUE TITLE
Add unofficial support for Xcode 8?

### ISSUE THREAD

**Issue by ccrazy88** [Instagram/IGListKit#1137]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.2.0
- iOS version(s): N/A
- CocoaPods/Carthage version: N/A
- Xcode version: 8.x
- Devices/Simulators affected: N/A
- Reproducible in the demo project? (Yes/No): N/A
- Related issues: N/A

Hello, I am wondering if it would be possible to add back "unofficial" support for Xcode 8. Unfortunately, at least one of the targets that uses IGListKit as a dependency where I work has still not migrated over to Xcode 9, so if we want to keep our version of IGListKit up-to-date, ensuring that any incompatibilities are resolved upstream whenever we decide to sync would be easiest for us, but we would understand if that's not desired.

As far as I can tell, the minimum that would need to be done involves adding `#ifdef __IPHONE_11_0` in a few places (see example in [UIScrollView+IGListKit.m](https://github.com/Instagram/IGListKit/blob/master/Source/Internal/UIScrollView+IGListKit.m#L16)). I can send out a PR soon if this sounds okay.

**Comment by rnystrom** [comment]
A better option for this would be to make a fork and keep it updated. We don’t use Xcode 8 at Instagram, and by accepting a PR were signing ourselves up to support it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
