### ISSUE TITLE
Config file organization

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#114]
Does anyone have a better idea on how to structure all these `.yml`, `.md`, etc files? Not the biggest issue, but its pushing the README further and further down on desktop.

<img width="236" alt="screen shot 2016-10-24 at 8 30 33 am" src="https://cloud.githubusercontent.com/assets/739696/19630797/561a79d4-99c4-11e6-8879-6c8886ad6936.png">

cc @jessesquires

**Comment by jessesquires** [comment]
`CONTRIBUTING` can move to `.github/`

**Comment by jessesquires** [comment]
unfortunately, i don't think we can do much else
