### ISSUE TITLE
Texture performUpdatesAnimated  crash

### ISSUE THREAD

**Issue by YasinZhou** [Instagram/IGListKit#1145]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.2.0
- iOS version(s):10/11
- CocoaPods/Carthage version:CocoaPods
- Xcode version:9.3
- Devices/Simulators affected:Devices
- Reproducible in the demo project? (Yes/No):No
- Related issues:

First, I found that several of the same return value methods were used for different logical processing.
```
IGListSectionMap -- sectionControllerForSection
IGListAdapter -- sectionControllerForObject
IGListSectionMap -- sectionControllerForObject
```
They all return`IGListSectionController`, but some make `object != nil` judgements.

Second, I use Texture ,then It crashed in `IGListSectionMap -- sectionControllerForSection` and `IGListAdapter (UICollectionView) --- collectionView: cellForItemAtIndexPath:`. I haven't found the exact cause of the crash, just know have a empty sectionMap.objects  and nil of `sectionController` and nil of `cell`.

**Comment by rnystrom** [comment]
Can you file separate issues for these questions? Then we can keep on topic for each thread.

But for both questions we will need more information. I'm not sure what the "same action methods" note is, and to help at all w/ any crashes at the very least we need a stack trace.

**Comment by YasinZhou** [comment]
that mean "the same return value".  the different logical processing   just a small problem.


when the crash happened :
```
//IGListAdapter (UICollectionView) --- collectionView: cellForItemAtIndexPath:
(lldb) po indexPath.section
43

(lldb) po self.sectionMap.objects
<__NSArray0 0x1c40124c0>(

)
```

[screenshots](https://upload-images.jianshu.io/upload_images/1024259-c341c9dcccb00594.png)
