### ISSUE TITLE
Remote API returns duplicate items, triggers objectsWithDuplicateIdentifiersRemoved assertion

### ISSUE THREAD

**Issue by bigship** [Instagram/IGListKit#1147]
The remote API (Unsplash api) I used may actually return duplicate items. IGListKit can catch this and crash the app. 

My question is , in this kind of situation do I need to manually exclude all the duplicate items and then modify my data source array ? Currently I had to use a Set() object to check If I got duplicates. Just want to know the best practice for this.

**Comment by weyert** [comment]
I assume you mean this error: `Duplicate identifier %@ for object %@ with object %@`? This is an assertion added to the code, IGListKit doesn't support duplicate items with the same diffIdentifier best to filter them out manually.

**Comment by bigship** [comment]
@weyert Yes, I already did that.  When the API may return duplicate items, we better filter them out first before performUpdates.   Close issue.
