### ISSUE TITLE
Fast refresh crash

### ISSUE THREAD

**Issue by weikeyan** [Instagram/IGListKit#1149]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:3.0.0
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:9.3
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):NO
- Related issues:
Fast refresh crash
![517e178c-94e3-48e9-bdef-561b5181ea28](https://user-images.githubusercontent.com/7971897/38910006-eef0ca98-42f9-11e8-859f-96610f129816.png)
![245ff667-98fa-4674-9910-f2148574f508](https://user-images.githubusercontent.com/7971897/38910032-0b651670-42fa-11e8-8dcc-20159603a3e2.png)

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by rnystrom** [comment]
Hey @weikeyan! Glad you saw that this is working better in 3.2. I'm not exactly sure what the exact issue and fix was here, but you can check out [IGListAdapter.m's blame here](https://github.com/Instagram/IGListKit/blame/master/Source/IGListAdapter.m) if you're curious!
