### ISSUE TITLE
Whether to support autolayout automatic computing row height？

### ISSUE THREAD

**Issue by weikeyan** [Instagram/IGListKit#1153]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:3.2.0
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:
Whether to support autolayout automatic computing row height？
### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by rnystrom** [comment]
Check out #516 for details on automatic cell sizing. We can’t offer official support for it given that we don’t use AutoLayout at Instagram, but others have documented some ways to make it work with IGListKit.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
