### ISSUE TITLE
Select item from view controller

### ISSUE THREAD

**Issue by Recouse** [Instagram/IGListKit#1157]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.2.0
- iOS version(s): 11
- Carthage version: 0.29.0
- Xcode version: 9.2
- Devices/Simulators affected: iPhone 7
- Reproducible in the demo project? (Yes/No): No

How can I select item from view controller?

```swift
collectionView.selectItem(at: IndexPath(row: 0, section: index), animated: false, scrollPosition: .left)
```
Doesn't work for me. It doesn't call section controller's `didDeselectItem` method.

**Comment by weyert** [comment]
Don't you mean didSelectItem?

**Comment by rnystrom** [comment]
@Recouse can you provide more detail about what you're trying to achieve? Maybe even an example project reproducing the error?

**Comment by Recouse** [comment]
It's not an error. I'm asking how can I select collection view item from view controller.
I can provide an example project, but here is my sketch:
![drawing 1](https://user-images.githubusercontent.com/7093328/39243960-85a5e78a-48a8-11e8-8356-095bed455207.jpeg)
I want to select collection view item on pages swipe.

**Comment by Recouse** [comment]
Anyone?

**Comment by rnystrom** [comment]
@Recouse have you tried calling the cell selection methods on `IGListCollectionContext` from within the section controller? What all have you tried?

**Comment by Recouse** [comment]
Yes, i tried:
```swift
func pageSwiped(toIndex index: Int) {
    collectionContext?.selectItem(at: index, sectionController: self, animated: true, scrollPosition: .centeredHorizontally)
}
```
in section controller.

**Comment by rnystrom** [comment]
@Recouse does this work with normal `UICollectionView`? For context we do all cell and item selection manually since UICV has some funky internal behavior and state tracking.

That might be a better option here.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by popei69** [comment]
Hi there! Is there any update on that subject?

Selecting an item usually works for `UICollectionView`. When I moved my current collectionView to IGListKit, the same selection makes the app crash.
```
collectionView.selectItem(at: IndexPath(row: 0, section: index), animated: false, scrollPosition: .left)
```
I had a look at the adapter or dataSource to see if there is another way to select element but couldn't find one. I would like to avoid having a flag into the model itself to have default selection.

Thanks

**Comment by RagdeSey** [comment]
The question could be a little bit old, but I was looking for this same behavior, I achieved this behavior by calling didSelectItem from the adapter like this:

`adapter.sectionController(forSection:  sectionNumber)?.didSelectItem(at: itemNumber)`

I hope this could help anyone.
