### ISSUE TITLE
Show header with empty data

### ISSUE THREAD

**Issue by brurend** [Instagram/IGListKit#1158]
## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.3.0
- iOS version(s): 11.3.0
- CocoaPods/Carthage version:
- Xcode version: 9.3
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

I'm trying to implement a screen with a search bar as a header for a collection view but I'm having a hard time trying to make the empty screen appear together with the collection view.

```Objective-C
IGListCollectionViewLayout *viewLayout = [[IGListCollectionViewLayout alloc] initWithStickyHeaders:YES topContentInset:0.0f stretchToEdge:NO];
    viewLayout.showHeaderWhenEmpty = YES;
    self.collectionView.collectionViewLayout = viewLayout;
    
    self.adapter = [[IGListAdapter alloc] initWithUpdater:[IGListAdapterUpdater new] viewController:self];
    self.adapter.collectionView = self.collectionView;
    self.adapter.dataSource = self;
```

Thats how I'm initialising my adapter and collection view. Can anyonehelp please?

**Comment by rnystrom** [comment]
@brurend I'm not exactly sure what the issue is here. The header just isn't displaying at all? Is there data in your list?

cc @marcuswu0814

**Comment by brurend** [comment]
There is no data in my list, the empty view is appearing as expected but the sticky header (search bar) is not appearing

**Comment by marcuswu0814** [comment]
Hi @brurend 

I'm not sure how did you implement it, but i guess you given an empty data for `ListAdapterDataSource` method like this:

```
func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
        return []
}
```

if so, no section controller be created and IGListKit didn't know your header view. Thus, empty page show.

Sticky header only show if section controller exists and it's method `numberOfItems()` return `0`.
You can take a look [this example](https://github.com/marcuswu0814/IGListKit_ShowStickyHeaderWhenDataEmpty).

Feel free to tell me if having other questions. 😅

**Comment by brurend** [comment]
I see now what I was doing wrong, thank you for the reply
