### ISSUE TITLE
Question: How to cache horizontal progress of carousels

### ISSUE THREAD

**Issue by siefix** [Instagram/IGListKit#1159]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 4.0
- iOS version(s): 11.2
- Xcode version: 9.2

### Question

I have a general question about maintaining / caching the the progress of horizontal collectionviews embedded in a vertical scrolling collectionview.

In Instagram, your feed is comprised of many different posts. Some posts have one photo, others are a carousel of multiple photos. 

If you swipe (horizontally) to photo 5 out of 10 in a carousel Instagram will remember that position, even if you swipe away to other posts (vertically). The next time you swipe back (vertically) to that same post it will conveniently put you to photo 6 out 10 to show you the content you missed.

**Normally when my vertical CollectionView cells are recycled it completely jumbles up the progress of horizontal swiping. So my question is how to recreate Instagram's behavior? How do you maintain a cache of progress horizontally?** 

I'm currently using the same setup as the "HorizontalSectionController" example in the IGListKitExamples.

1. ViewController - (contains a vertical UICollectionView). The ListAdapter uses a HorizontalSectionController for each cell
2. The [HorizontalSectionController](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/HorizontalSectionController.swift) puts a new UICollectionView in each vertical cell (EmbeddedCollectionViewCell), it also has a new ListAdapter for each horizontal EmbeddedSectionController 
3. The [EmbeddedSectionController](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/EmbeddedSectionController.swift) populates the size and cell for the horizontal cells
4. HorizontalCell

My best guess is to use the ListDisplayDelegate at the HorizontalSectionController level. 

Using the function `func listAdapter(_ listAdapter: ListAdapter,
                     willDisplay sectionController: ListSectionController,
                     cell: UICollectionViewCell,
                     at index: Int)` 

Seems to get me the vertical section that I've scrolled to. Then using the same ListDisplayDelegate at the EmbeddedSectionController level seems to trigger when I scroll horizontally. 

Should I use some custom delegate to pass the furthest Int scrolled at the EmbeddedSectionController level up to the HorizontalSectionController, then combine them into an index path that can be saved? Then does it need to be passed up to the main ViewController?

In terms of actual moving to the right horizontal location when scrolling vertically, do you use

`collectionContext?.scroll(to: ListSectionController, at: Int, scrollPosition: UICollectionViewScrollPosition, animated: Bool)`

If so, each horizontal cell is controlled by a separate EmbeddedSectionController. So this function needs to scroll to a ListSectionController (always Int: 0), not an indexpath. How do you keep track of the SectionController?

Let me know if I'm not being clear in some way! Thank you for all the work you do on IGListKit and being so responsive to questions.

**Comment by alexpersian** [comment]
Have you thought about the possibility of Instagram solving this on the backend through analytics? The behavior seems to indicate that is how they handle this situation.

**Comment by rnystrom** [comment]
@siefix it sounds like you have the gist of it correct:

1. List to scroll events in the nested adapter
2. Save the scrolled-to index (or just the offset) in the horizontal section controller
3. Use the display delegate APIs to setup your cell based on the last seen index (or bump it to the next one, whatever you want to do)

If you find a simple way to do this, I'm happy to review a PR to extend our examples app!

**Comment by siefix** [comment]
Thanks.

Seemed to be able to accomplish this

My solution below (may not be the best way)


---------
At the `HorizontalSectionController` level I created a new property

`var offsets = [Int: CGFloat]()`

And using the `DisplayDelegate`

```
override init() {
        super.init()
        adapter.dataSource = self
        displayDelegate = self
    }
```

I cached the offset in `willDisplay` and `didEndDisplaying`

```
func listAdapter(_ listAdapter: ListAdapter, willDisplay sectionController: ListSectionController, cell: UICollectionViewCell, at index: Int) {
        
        if let cell = cell as? HorizontalCell {
            cell.collectionView.contentOffset.x = offsets[section] ?? 0
        }
 }    
    
    func listAdapter(_ listAdapter: ListAdapter, didEndDisplaying sectionController: ListSectionController, cell: UICollectionViewCell, at index: Int) {
        
        if let cell = cell as? HorizontalCell {
            let offsetX = cell.collectionView.contentOffset.x
            offsets[section] = offsetX
        }
        
 }
```
