### ISSUE TITLE
Custom animation curve and alongside animations for `performUpdates(animated:completion:)`

### ISSUE THREAD

**Issue by brandenlivermore** [Instagram/IGListKit#1167]
## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.3
- iOS version(s): 10.x, 11.x
- CocoaPods/Carthage version: Carthage 0.29.0
- Xcode version: 9.3
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No): N/A

I am looking to use a custom animation curve and duration for `ListAdapter`'s `performUpdates(animated:completion:)` method. With a standard `UICollectionView`, you can wrap the call to `performBatchUpdates(_:completion:)` inside of a `UIView` animation block. This also allows you to do additional animations at the same time, with the same animation curve, such as scrolling to the bottom of the collection view as you insert new cells. Because of the asynchronous updates of `IGListKit`, wrapping the call to perform updates in an animation block has no effect. I am able to get around this by swizzling `performBatchUpdatesWithCollectionView:` in `ListAdapterUpdater`, but I'm wondering if there is a solution better than swizzling or copying the whole class over and changing a tiny part.  

Here is the swizzling code:
```swift
extension ListAdapterUpdater {
    private struct Constants {
        static var ListAdapterUpdaterAnimationBlockKey = "ListAdapterUpdaterAnimationBlock"
    }

    var animationBlock: ((@escaping () -> Void) -> Void)? {
        get {
            return objc_getAssociatedObject(self, &Constants.ListAdapterUpdaterAnimationBlockKey) as? ((() -> Void) -> Void)
        }

        set {
            objc_setAssociatedObject(self, &Constants.ListAdapterUpdaterAnimationBlockKey, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
        }
    }

    public static func swizzle() {
        let selector = NSSelectorFromString("performBatchUpdatesWithCollectionView:")
        let updaterClass = ListAdapterUpdater.self

        let originalMethod = class_getInstanceMethod(updaterClass, selector)!

        let newSelector = #selector(ListAdapterUpdater.replacement_performBatchUpdates(with:))
        let newMethod = class_getInstanceMethod(updaterClass, newSelector)!

        method_exchangeImplementations(originalMethod, newMethod)
    }

    @objc func replacement_performBatchUpdates(with collectionView: UICollectionView) {
        guard let animationBlock = animationBlock else {
            replacement_performBatchUpdates(with: collectionView)
            return
        }

        animationBlock {
            self.replacement_performBatchUpdates(with: collectionView)
        }
    }
}
```

**Comment by rnystrom** [comment]
Right now there's not a better solution. I'd be open to an API on `IGListAdapterUpdater` or something that allows you to optionally wrap the `-[UICollectionView performBatchUpdates:completion:]` call w/ your own block. Maybe it's a param on the updater, or maybe its an optional param on update methods? Would be happy to review some proposals!

I'm going to close this out for now since its not supported. Until an API is proposed + merged, swizzling is your best bet.
