### ISSUE TITLE
Question: Is it safe to pass diffables to sections as data suppliers

### ISSUE THREAD

**Issue by eyzuky** [Instagram/IGListKit#1168]
Hi, as the title implies.
Assuming I have a diffable that carries data. Could I pass the diff to the section, and use it as a view model for my section? Or will I have problems when refreshing with the diffs being destroyed and I might get crashes?

Thanks!

**Comment by rnystrom** [comment]
@eyzuky we sort of do this in Instagram by supplying a diffable data source object that powers an embedded adapter in a horizontally-scrollable list.

If you want the data source to power the `numberOfItems`, I'd recommend using `IGListBindingSectionController`.

Is that what you're asking?

**Comment by eyzuky** [comment]
Hey @rnystrom, thanks for your reply.
Actually it is more a matter of data than delegating the section, eventually we created a protocol like this and we implement it in our ListDiffable:

```
protocol DataSupplierDiffable {
    associatedtype DataType
    var data: DataType { get set }
    var hashValue: Int { get }
    var identifier: Int { get }
}
```
Then inside the implementation we declare the DataType, we init the data and then in section for object we do something in this fashion:
`section.data = diffable.data`
This kind of did it for us.. as to your suggestion, I will look into using the `IGListBindingSectionController` later on :)

Thanks
