### ISSUE TITLE
Using Reordering interactive between two sections with multiple data

### ISSUE THREAD

**Issue by kleiberjp** [Instagram/IGListKit#1172]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:  `3.4.0`
- iOS version(s): `11.3`
- CocoaPods/Carthage version: Cocoapods 1.5.0
- Xcode version: 9.3
- Reproducible in the demo project? (Yes/No): No
- Related issues: #976 

I've seen on the issue #976 , but updated version of framework i can't see a change or update, for trying move a item from a grid section, to another grid section.. There is any example or a guideline for could use this awesome feature with that behavior?

**Comment by rnystrom** [comment]
If you check out the [source code](https://github.com/Instagram/IGListKit/blob/master/Source/Internal/IGListAdapter+UICollectionView.m#L69-L111), you'll see that the only moves supported are inter-section moves (cells w/in the same section) and sections that only have 1 item in them. You can't move items between sections at this time, and we don't have any plans to add that feature.
