### ISSUE TITLE
Question:In this case, How to use IGListKit

### ISSUE THREAD

**Issue by steveszk** [Instagram/IGListKit#1175]
## New issue checklist

- [ X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.4.0
- iOS version(s):iOS 11.3

I want to use IGListKit to do this, but for a sectioncontroller  , it only provider one entity, the second item in the sectioncontroller is the same entity data. please!!! 
![image](https://user-images.githubusercontent.com/25676974/40101136-04d47de8-5919-11e8-98cc-d7495f9c5671.png)

**Comment by rnystrom** [comment]
@steveszk what have you tried so far?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by steveszk** [comment]
@rnystrom i have no idea, one dataModel provided for one sectionController, in this case, there are two items in the sectionController, but only have one dataModel.

**Comment by rnystrom** [comment]
We’re not able to design every app. There are plenty of tutorials and examples out there to help you get started.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
