### ISSUE TITLE
CocoaPods tvOS support

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#118]
We should be tvOS-compliant (AFAIK)

- [x] Add tvOS target to xcodeproj
- [x] Add shared scheme + build on travis
- [x] Update `.podspec` to declare tvOS 9.0+ support

**Comment by rnystrom** [comment]
@timonus wanna poke around at this? 😄

**Comment by timonus** [comment]
Sure, I can take a look! Pretty busy for the next few weeks but will take a crack at it when I can.

**Comment by jessesquires** [comment]
Done in #137

**Comment by timonus** [comment]
Nice

**Comment by Sherlouk** [comment]
@jessesquires Assuming you haven't, would you mind if I had a look at creating a snazzy example for this?

**Comment by jessesquires** [comment]
@Sherlouk 👍 That would be 💯 

Opened #138 to track. Let's discuss there 😄
