### ISSUE TITLE
Create a label for PRed issues 

### ISSUE THREAD

**Issue by zhubofei** [Instagram/IGListKit#1180]
Shall we create a new label to mark issues that are already PRed (waiting for next milestone to be merged)? Otherwise, we have to read through the comments to find out.

**Comment by rnystrom** [comment]
Is this a normal practice? I’m not opposed, just haven’t seen this before.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhubofei** [comment]
nvm, looks like there is already a PR Pending label.
