### ISSUE TITLE
How to get visible cells in ListBindingSectionController

### ISSUE THREAD

**Issue by vicki15** [Instagram/IGListKit#1182]
## New issue checklist

- [√ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [√ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

I am using IGListKit with two types of section controllers. The first is a regular section controller which i use to display an image & some related data, and the second is a ListBindingSectionController and contains a collection of images. Ultimately Id like to know which of my cells have been visible at any point, so that onViewWillDisappear I can log a metric saying which images the user has seen. The way I would like to go about this is maintaining a set of viewed image IDs, and using willDisplayObject in IGListAdapterDelegate to add image IDs to this set when the cell is displayed. Im not sure how to do this for the nested collection cells. From the level of the complete collection, I can get the visible section controllers, but this just tells me if the full collection is visible or not. Within the ListBindingSectionController itself I can set the displayDelegate to self, and implement willDisplay sectionController... but what I really want is willDisplay viewModel. What is the recommended way to do this? Is there an API I am missing? Or will I need to do this with scroll view delegate, and manually checking frames? Thanks!

(This is similar to https://github.com/Instagram/IGListKit/issues/717, but with ListBindingSectionController so I dont have a nested adapter)

**Comment by vicki15** [comment]
Basically, if we look at the sample calendar project. How can I tell when the individual date cells are visible? Either as a delegate method that gets called for the cells, or even just as a getVisibleObjects I can call on scroll? Thanks!

**Comment by rnystrom** [comment]
@vicki15 you can ask the collectionContext for visible cells for the section controller. Is that what you’re looking for?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
