### ISSUE TITLE
Split IGListAdapterDataSource?

### ISSUE THREAD

**Issue by gobetti** [Instagram/IGListKit#1183]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: current master (290d592983713c3ef82eb4950ba773a0059563a2)

### Motivation
Hi! I strongly believe IGListKit is so lightweight, performant and addresses so many troubles we have when using collection views that any app should import this framework. But honestly, that's far from being my actual recommendation to other projects in our company, as currently is.

I've been working on a project for a year and a half now where IGListKit was one of our very first additions (and thankful decisions!) and our whole UI is dependent on it. And for every developer we have to onboard to the project, IGListKit is probably the part with the most difficult learning - at _least_ as difficult as Rx, I'd say, even though Rx introduces a whole new paradigm and IGListKit is just beautiful OOP.

So what if certain entities were revisited in order to make them look closer to known patterns in order to improve the learning process of newcomers?

### Example
My first concern is `IGListAdapterDataSource`. As a data source, I expect it to provide data, which it does via:
`- (NSArray<id <IGListDiffable>> *)objectsForListAdapter:(IGListAdapter *)listAdapter;`
Notice that the `objects` above could be either stored in a property and returned here, or just computed right away. Both are fine and a stored property is most usually the way this is used.

So far so good, but we also see this in the same protocol:
```
- (IGListSectionController *)listAdapter:(IGListAdapter *)listAdapter sectionControllerForObject:(id)object;
```
I'll ask you to try to erase everything you already know about IGListKit and imagine yourself reading this for the very first time. As much as documentation can help and examples _definitely_ do help, one truly needs to slowly digest multiple of them in order to start understanding what's underneath. In Swift, the signature becomes:
```swift
func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController
```
So it needs to return me an object, but where should I take this object from? Should I have a stored property for this too? ... oh! From several examples, I actually see that in every implementation, we actually instantiate a **new** object and return it. So what is this? A **factory method**.

According to the [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/), we should "Begin names of factory methods with `make`, e.g. `x.makeIterator()`", so let's apply it to that method and it now becomes
```swift
func makeSectionController(for object: Any, listAdapter: ListAdapter) -> ListSectionController
```
This even looks self-documented now.

Ok, so we have a factory method required by a protocol `IGListAdapterDataSource`. What is this then? **An abstract factory**! and... does it still make sense to be a _data source_? Maybe, but at least to me, this line smells odd:
```
sectionController = [dataSource listAdapter:self sectionControllerForObject:object];
```
because a _data_ source is also sourcing me a _section controller_ (which turns out to be a factory underneath), i.e. **what** data to display and **how** to display data.

### First suggestion
What do you think of removing from `IGListAdapterDataSource` the responsibility of creating section controllers, and having a new protocol looking something like (in Swift for readability)
```swift
protocol ListSectionControllerFactory {
  func makeSectionController(for object: Any, listAdapter: ListAdapter) -> ListSectionController
}
```

**Comment by rnystrom** [comment]
Returning to this. Love the suggestion! Would it be possible to make this a Swift-only API change? I'm not sure the ObjC API would be as familiar.

If anything, I'd be supportive of moving the `emptyView` API out to another data source. That one has always felt out of place.

**Comment by gobetti** [comment]
Thanks @rnystrom !

Since you can't split the protocol only for Swift, a change would be needed in ObjC too. As for naming, `NS_SWIFT_NAME` may be used:
```objc
@protocol IGListSectionControllerFactory <NSObject>
- (IGListSectionController *)sectionControllerForObject:(id)object NS_SWIFT_NAME(makeSectionController(forObject:));
```
Notice I've omitted the `listAdapter` parameter from the original signature - I'm not sure if it's useful in any scenario, personally I've never used with this method. If necessary, then readability becomes worse in Swift (unless there's a macro that accepts changing the parameters order):
```objc
@protocol IGListSectionControllerFactory <NSObject>
- (IGListSectionController *)listAdapter:(IGListAdapter *)listAdapter sectionControllerForObject:(id)object NS_SWIFT_NAME(makeSectionController(listAdapter:forObject:));
```
but still worth the protocol splitting imho :D

**Comment by rnystrom** [comment]
One big reason I'm hesitant to make any ObjC changes is how many instances and documentation we'll need to update internally (literally hundreds lol). So these big changes have to be done very, very thoughtfully!
