### ISSUE TITLE
Suggestion: simplify IGListAdapter initialization to just pass `viewController`

### ISSUE THREAD

**Issue by kgaidis** [Instagram/IGListKit#1184]
First, thank you for the great library.

In the examples, I noticed that every `IGListAdapter` is initialized like this:
`ListAdapter(updater: ListAdapterUpdater(), viewController: self)`

Every `IGListAdapter` get initialized with the same `ListAdapterUpdater` and it's an extra piece of information that is probably not important to someone just beginning to use `IGListKit`.

My suggestion is to add another default-initializer:
```
- (instancetype)initWithViewController:(nullable UIViewController *)viewController {
    return [self initWithUpdater:[IGListAdapterUpdater new] viewController:viewController];
}
```

This would remove the redundancy, and arguably, make it more friendly to use. Now, initialization would be simplified to just the information that is necessary for basic use (no one has to spend any time thinking about what `IGListAdapterUpdater` is - basic abstraction):
`ListAdapter(viewController: self)`

I could open a PR, but wanted to check first as it could be considered trivial, and highly debatable.

**Comment by rnystrom** [comment]
I do like this idea! To be honest, I’ve been mulling over the idea of removing the updating delegate and making `IGListAdapterUpdater` an explicit type used by `IGListAdapter`...

I’m happy to review a PR for this. My only ask would be to put it in a category so we keep the `IGListAdapter` header and implementation free from the updated type.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kgaidis** [comment]
I will close this since this is answered, and will reference ticket in a PR (soonTM).

Thank you!
