### ISSUE TITLE
Unused variable warning

### ISSUE THREAD

**Issue by zhubofei** [Instagram/IGListKit#1187]
https://github.com/Instagram/IGListKit/blob/290d592983713c3ef82eb4950ba773a0059563a2/Source/IGListAdapter.m#L1083

Travis failed after a swiftlint warning: unused variable `collectionView` [-Wunused-variable]

**Comment by rnystrom** [comment]
Ahh from compiling out the assert. Any interest picking this up and fixing? Should be just changing the assert to use `self.collectionView` instead.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhubofei** [comment]
Sure 😊
