### ISSUE TITLE
didUpdateToObject is meaningless

### ISSUE THREAD

**Issue by YasinZhou** [Instagram/IGListKit#1189]
- `IGListKit` version:3.2.0
If the model changed, the SectionController will be regenerated, so the didUpdateToObject is meaningless. Why not just write it in init

**Comment by rnystrom** [comment]
@YasinZhou sorry can you explain a bit more? Nothing has changed with how models are diffed or how this method is used. It’s still a fundamental method in IGListKit.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@YasinZhou it sounds like your models aren't taking full advantage by using an identifier to uniquely ID data, and then an equality to inform when things change. If you follow the [Getting Started guide](https://github.com/Instagram/IGListKit/blob/master/Guides/Getting%20Started.md#diffing) and [Equality guide](https://github.com/Instagram/IGListKit/blob/master/Guides/IGListDiffable%20and%20Equality.md), that should unblock you. 

Section controllers are reused, but you have to tell them what to reuse and when via the `diffIdentifier`.

**Comment by YasinZhou** [comment]
oh,I might have made a mistake, I'm all `self` returned in `diffIdentifier `, I need to write a test code

**Comment by rnystrom** [comment]
Ya, that uses the object _instance_ as the identifier, which means it'll always be seen as a new object when an instance of that data is recreated.

**Comment by YasinZhou** [comment]
Thank you very much.
