### ISSUE TITLE
not  Adaptive altitude  height issuses?

### ISSUE THREAD

**Issue by weikeyan** [Instagram/IGListKit#1192]
## New issue checklist
![12314](https://user-images.githubusercontent.com/7971897/41346971-dbe668be-6f3a-11e8-9812-03813bb9c6e6.gif)

this issuses？bug?
- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:3.2.0
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information
Adaptive altitude  height  flicker issuses

core code 

- (UICollectionViewLayoutAttributes *)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes *)layoutAttributes{
    [self setNeedsLayout];
    [self layoutIfNeeded];
    CGSize size = [self.contentView systemLayoutSizeFittingSize:layoutAttributes.size];
    CGRect newFrame = layoutAttributes.frame;
//    newFrame.size.width = ceil(size.width);
    newFrame.size.height = ceil(size.height);
    layoutAttributes.frame = newFrame;
    return layoutAttributes;
}

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by rnystrom** [comment]
Looks like this is using self-sizing cells. Check out #516 where we are tracking everything related to self sizing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
