### ISSUE TITLE
didSelectItem and strange behavior

### ISSUE THREAD

**Issue by jboo1212** [Instagram/IGListKit#1198]
### General information

- `IGListKit` version: 3.0
- iOS version(s): 11.2
- CocoaPods/Carthage version: 1.5.2
- Xcode version: 9.4.1 (9F2000)
- Devices/Simulators affected: iPhone 8+
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: didSelectItem/didDeselectItem

Summary of issue: When I'm selecting a Photo grid item from my photo library, I expect to have a checkmark banner image view be added to that cell's subview and when the other cell is deselected, to have that cell remove its checkmark.  In the URL link below, you'll see that towards the end of the video, I select a cell in the bottom-right hand corner and then when I scroll up and down, the bottom-left hand corner cell has the checkmark banner image view.  I've tried two different approaches: I'm unsure which IG recommends, but I'd thought I'd post the first one I tried before I showed the second.

[https://gfycat.com/TheseLinedHalcyon](url)

` 
    
    import UIKit
    import IGListKit
    class PhotosSectionController: ListSectionController {
    
    var photoItem: PhotoItem?
    
    override init() {
        super.init()
        minimumLineSpacing = 1
        minimumInteritemSpacing = 1
    }
    
    override func numberOfItems() -> Int {
        return photoItem?.photos.count ?? 0
    }
    
    override func sizeForItem(at index: Int) -> CGSize {
        var width = collectionContext?.containerSize.width ?? 0
        width = (width - 2) / 3
        let itemSize = floor(width)
        return CGSize(width: itemSize, height: itemSize)
    }
    
    override func cellForItem(at index: Int) -> UICollectionViewCell {
        guard let photoCell = collectionContext?.dequeueReusableCell(of: PhotosCell.self, for: self, at: index) as? PhotosCell else { fatalError("Couldn't return a photo cell")}
       
        photoCell.photoView.image = photoItem?.photos[index]
        return photoCell
       }
   
    override func didUpdate(to object: Any) {
        precondition(object is PhotoItem)
        self.photoItem = object as? PhotoItem
    }
    
    override func didSelectItem(at index: Int) {
        guard let selectedCell = collectionContext?.cellForItem(at: index, sectionController: self) as? PhotosCell else { return }
        selectedCell.setupCheckmarkBanner()
    }
    
    override func didDeselectItem(at index: Int) {
        guard let deselectedCell = collectionContext?.cellForItem(at: index, sectionController: self) as? PhotosCell else { return }
        deselectedCell.removeCheckmarkBanner()
    }
    

    class PhotoItem: ListDiffable {
    
    var photos: [UIImage]
    
    init(photos: [UIImage]) {
        self.photos = photos
    }
    
    func diffIdentifier() -> NSObjectProtocol {
        return "Photos" as NSObjectProtocol
    }
    
    func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
        guard self !== object else { return true }
        guard let object = object as? PhotoItem else { return false }
        return self.photos == object.photos
    }
    }

    class PhotosViewController: UIViewController, ListAdapterDataSource {
  
     var photoChoice: PhotoChoice = .profile
     
     // MARK - Photos framework
     let selectedImageView: UIImageView = {
         let selectedImageView = UIImageView()
         selectedImageView.contentMode = .scaleAspectFill
         selectedImageView.clipsToBounds = true
         return selectedImageView
     }()
     
     var photoAssets: PHFetchResult<PHAsset>?
     let photoManager = PHImageManager.default()
    
     let requestOptions: PHImageRequestOptions = {
         let requestOptions = PHImageRequestOptions()
         requestOptions.isSynchronous = true
         return requestOptions
     }()

     let collectionView: UICollectionView = {
        let collectionViewFlowLayout = UICollectionViewFlowLayout()
        let collectionView = UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewFlowLayout())
         collectionView.backgroundColor = .white
         return collectionView
     }()
     
    lazy var adapter: ListAdapter = { return ListAdapter(updater: ListAdapterUpdater(), viewController: self) }()
   
     private let photoCellReuseIdentifier = "photoCell"
    
    let photoItem = PhotoItem(photos: [])

       override func viewDidLoad() {
         super.viewDidLoad()
         setupViews()
         setupDataSource()
         fetchAssets()
         setupConstraints()
     }
    
    private func setupViews() {
         view.backgroundColor = .white
         view.addSubview(selectedImageView)
         view.addSubview(collectionView)
         collectionView.register(PhotosCell.self, forCellWithReuseIdentifier: photoCellReuseIdentifier)
    }
    }
   
    private func setupDataSource() {
        adapter.dataSource = self
        adapter.collectionView = collectionView
       }
     
     private func setupConstraints() {
        selectedImageView.anchor(top: view.topAnchor, left: view.leadingAnchor, bottom: collectionView.topAnchor, right: view.trailingAnchor, paddingTop: 0, paddingLeft: 2, paddingBottom: 2, paddingRight: 2, width: 0, height: view.bounds.height/2)
        selectedImageView.anchor(top: view.topAnchor, left: view.leadingAnchor, bottom: collectionView.topAnchor, right: view.trailingAnchor, paddingTop: 0, paddingLeft: 0, paddingBottom: 2, paddingRight: 0, width: 0, height: view.bounds.height/2)
         collectionView.anchor(top: nil, left: view.leadingAnchor, bottom: view.bottomAnchor, right: view.trailingAnchor, paddingTop: 5, paddingLeft: 0, paddingBottom: 0, paddingRight: 0, width: 0, height: 0)
     }

     private func fetchAssets() {
         guard let cameraRollPhotoCollection = PHAssetCollection.fetchAssetCollections(with: .smartAlbum, subtype: .smartAlbumUserLibrary, options: nil).firstObject else { return }
         let assetOptions = PHFetchOptions()
             photoAssets.enumerateObjects { (asset, count, stop) in
                 self.photoManager.requestImage(for: asset, targetSize: CGSize(width: 200, height: 200), contentMode: .aspectFit, options: self.requestOptions, resultHandler: { (image, nil) in
                     
                  guard let image = image else { return }
                  self.photos.append(image)
                     
                 })
             }
            
           // Expect only one call.
            DispatchQueue.main.async {
                self.adapter.reloadData(completion: nil)
           }
         }
     }
 

    func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
        guard photoItem.photos.count > 0 else { return [] }
        return [photoItem]
     }

       func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController {
       return PhotosSectionController()
     }
     
    func emptyView(for listAdapter: ListAdapter) -> UIView? { return nil }

    import UIKit

    class PhotosCell: UICollectionViewCell {

    let photoView: UIImageView = {
        let photoView = UIImageView()
        photoView.contentMode = .scaleAspectFill
        photoView.clipsToBounds = true
        return photoView
    }()
    
    var checkmarkBannerImageView: UIImageView?
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        contentView.addSubview(photoView)
        photoView.anchor(top: topAnchor, left: leadingAnchor, bottom: bottomAnchor, right: trailingAnchor, paddingTop: 0, paddingLeft: 0, paddingBottom: 0, paddingRight: 0, width: 0, height: 0)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    func setupCheckmarkBanner() {
        checkmarkBannerImageView = UIImageView(image: #imageLiteral(resourceName: "check").withRenderingMode(.alwaysTemplate))
        checkmarkBannerImageView?.contentMode = .center
        checkmarkBannerImageView?.contentScaleFactor = 4.0
        checkmarkBannerImageView?.tintColor = .white
        checkmarkBannerImageView?.setBottomBorder(for: .white, borderWidth: 1.5)
        checkmarkBannerImageView?.convertToCircle(value: 12)
    
        photoView.addSubview(checkmarkBannerImageView!)
        checkmarkBannerImageView?.anchor(top: photoView.topAnchor, left: nil, bottom: nil, right: photoView.trailingAnchor, paddingTop: 4, paddingLeft: 0, paddingBottom: 0, paddingRight: 4, width: 24, height: 24)
    }
    
    func removeCheckmarkBanner() {
        checkmarkBannerImageView?.removeFromSuperview()
        checkmarkBannerImageView?.constraints.forEach{$0.isActive = false }
        checkmarkBannerImageView = nil
    }
    }`

**Comment by weyert** [comment]
You would need to keep track of the selected items because when you scroll
up and down the cells are getting reused so it will reset the state of the
cell.

**Comment by rnystrom** [comment]
What @weyert said is exactly right. Don't rely on `UICollectionView` selection APIs: they aren't that reliable even without IGListKit. 

Instead, track selection inside your section controller with a `Bool` similar to how we track [expansion in this demo](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/ExpandableSectionController.swift#L20).
