### ISSUE TITLE
Remove IGListDiffOption?

### ISSUE THREAD

**Issue by zhubofei** [Instagram/IGListKit#1199]
Shall we remove `IGListDiffOption` and use `IGListDiffEquality` only? I think rellying on pointer isn't safe. And Swift encourages the use of value-type in its design. Not sure if there is a deeper reason to support `IGListDiffPointerPersonality` in the first place 🤔.

**Comment by rnystrom** [comment]
I'd rather leave the option for people to decide how they want to diff. Maybe we can provide a Swift API that defaults to equality, but I'm not sure there's value in breaking the API at this point.

**Comment by jessesquires** [comment]
Defaulting this to equality seems like the right thing to do, to me.
