### ISSUE TITLE
When hidesBarsOnSwipe is true SelfSizingCells are disrupted

### ISSUE THREAD

**Issue by barankaansert** [Instagram/IGListKit#1202]
Thanks for an amazing library ❤️

When using SelfSizingCell and navigationController?.hidesBarsOnSwipe option is true, cells are distrupted on scrolling like overtaking each other. 

How can i fix it ?

**Comment by rnystrom** [comment]
@barankaansert unfortunately self-sizing cells aren't supported first-class by our team. I'd refer to #516 for some details.
