### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by zhubofei** [Instagram/IGListKit#1204]
@rnystrom It looks like commit a1ee4c19f7a6cbd9899dba82deb5fb3ece669e9c add the test `test_withDuplicateDiffIdentifiers_thatDuplicatesAreRemoved` and it is failing.

**Comment by rnystrom** [comment]
@zhubofei thanks for flagging! We'll get this working ASAP.

**Comment by zhubofei** [comment]
@rnystrom Maybe we should reverse the commit entirely?  `objectsWithDuplicateIdentifiersRemoved` will always assert when there are duplicate ids.

**Comment by zhubofei** [comment]
Fixed bee2178443ffcaff1d9135c4e094f74240433a62
