### ISSUE TITLE
ListCollectionViewLayout Sizing for 2:1 Grid

### ISSUE THREAD

**Issue by antonioallen** [Instagram/IGListKit#1206]
Hi! First I would like to say thanks for this amazing library! It has truly made working with collection views fun again 😃! 

I'm trying to create a grid using IG's ListCollectionViewLayout where the first section controller (or cell) is twice the width of the normal cell. Similar to IGFeed. However, and this is probably due to my sizing (although I believe it is correct), I can't seem to get the third element to layout correctly. It always gets new-lined.  As a result, my grid looks like it is missing one cell. Please see the image below. Here is my layout class. Any help would be appreciated. 

I see in the docs that an item "newlines" when the `max-x position` for vertical scrolling, (and I'm guessing `max-y position` for horizontal) "extends beyond the width of the collection view". But I unsure when my position would be off.
https://instagram.github.io/IGListKit/Classes/IGListCollectionViewLayout.html

![igissue1](https://user-images.githubusercontent.com/11503003/42171451-2dad47e8-7dce-11e8-9965-b13a1f9f7456.png)
![igissue2](https://user-images.githubusercontent.com/11503003/42171461-32db300e-7dce-11e8-9a9b-27fa7b7f426e.png)
![igexample](https://user-images.githubusercontent.com/11503003/42171469-35cc5054-7dce-11e8-9ffe-86a623ce156d.png)

`
import BoltKit
import IGListKit

fileprivate typealias EPPCL = EditProfilePhotoCellLayout

class EditProfilePhotoCellLayout: ListCollectionViewLayout {
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    override init(stickyHeaders: Bool, scrollDirection: UICollectionViewScrollDirection, topContentInset: CGFloat, stretchToEdge: Bool) {
        super.init(stickyHeaders: false, scrollDirection: .horizontal, topContentInset: EPPCL.collectionContentInset.top, stretchToEdge: false)
    }
    
    private static var spacing:CGFloat = 25
    private static var numberItemsPerRow:CGFloat = 3
    
    static var primaryPhotoSize:CGSize {
        let screenWidth = Size.screen.width
        let width = floor(screenWidth / EPPCL.numberItemsPerRow) * 2
        return CGSize(width : width, height: width)
    }
    
    
    static var secondaryPhotoSize:CGSize {
        let screenWidth = Size.screen.width
        let width = floor(screenWidth / EPPCL.numberItemsPerRow)
        return CGSize(width: width, height: width)
    }
    
    static var collectionContentInset:UIEdgeInsets = .zero
    static var primarySectionInset:UIEdgeInsets = .zero
    static var secondarySectionInset:UIEdgeInsets = .zero
    
}`

## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by rnystrom** [comment]
@antonio081014 we actually use a specialized `UICollectionViewLayout` for that page. I don't think that this exact layout will work with `IGListCollectionViewLayout` 😢

**Comment by antonio081014** [comment]
@antonioallen , HAHA

**Comment by antonioallen** [comment]
Oh ok, would have been nice haha. Thanks anyways!
