### ISSUE TITLE
How to have a nested adapter inside a ListBindingSectionController cell?

### ISSUE THREAD

**Issue by yusuftor** [Instagram/IGListKit#1209]
This is related to #829, but the last comment suggesting an answer to the question didn't work for me. I'm trying to embed a horizontally scrolling `UICollectionView` inside a cell that belongs to a `ListBindingSectionController`. The problem is that the `UICollectionView` doesn't update the cells inside it after the data has been updated.

This is the way I'm doing it:

1. Add a `UICollectionView` inside a `UICollectionViewCell`
2. Initialise the adapter inside the `ListBindingSectionController`, setting the datasource to the section controller too.
3. Set up the datasource functions in the section controller, returning the necessary objects for the collection view as well as a new section controller to deal with those objects.
4. Inside `sectionController(_:cellForViewModel:at:)` I set the adapter's `collectionView` property as the cell's `collectionView`.
5. Make sure that the objects for the collection view are included in the `isEqual(toDiffableObject:)` function of the model of the ListBindingSectionController.

Unfortunately this seems to do everything except update the cells in the embedded collection view. It even creates the section controllers/removes the section controllers of the collection view but just doesn't change visually. The only thing I haven't done is use the `bindViewModel(_:)` function for the cell that contains the `UICollectionView` to do something to do with the collection view/adapter. What is the correct way to set this up? What am I missing? Thanks!

**Comment by yusuftor** [comment]
I fixed this by moving the update code for the event from the view controller to inside the `ListBindingSectionController`. All works as expected!

**Comment by CTres** [comment]
@yusuftor could you paste your successful update code?
