### ISSUE TITLE
Very low opening performance with huge amount of items

### ISSUE THREAD

**Issue by psi-gh** [Instagram/IGListKit#1212]
- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

- `IGListKit` version: Current
- iOS version(s): 11
- CocoaPods/Carthage version:
- Xcode version: 9
- Devices/Simulators affected: 5S
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

### Debug information

1. Download example project
2. Open `SingleSectionViewController.swift` and change data array from 20 items to 5000
3. Open it in app on old device; there will be a very noticeable lag during opening.

Also i have a problems with large navigation bar style (this one #1037), it seems like a UICollectionView issue, not IGListKit itself.

**Comment by rnystrom** [comment]
@psi-gh have you done any tracing? Where is the performance hit coming from?

**Comment by psi-gh** [comment]
On first screen launch layout acquires sizes for ALL items. You can see it if put logs in 
`- (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath`
method in `IGListAdapter+UICollectionView.m`

**Comment by jessesquires** [comment]
@psi-gh How expensive is your size calculation?

**Comment by psi-gh** [comment]
@jessesquires Even if i just `return CGSize(w, h)` it's takes some time to call `sizeForItemAtIndexPath` for each item.
But in most simple case, when you have dynamic size text label in your cell, size calculation will look like 
````
        let text = model.issueTitle
        let options: NSStringDrawingOptions = [.usesLineFragmentOrigin, .usesFontLeading]
        let font = UIFont(name: "Roboto-Bold", size: 20)
        let attrs: [NSAttributedStringKey : Any] = [NSAttributedStringKey.font: font as Any]
        let maxSize = CGSize(width: UIScreen.main.bounds.size.width - 16 - 76,
                             height: CGFloat.greatestFiniteMagnitude)
        let textRect = (text as NSString).boundingRect(with: maxSize,
                                                    options: options,
                                                    attributes:attrs,
                                                    context: nil)
        let textHeight = min(ceil(textRect.height), 48)
        return textHeight
````

**Comment by weyert** [comment]
I am wondering if using something like
https://github.com/GitHawkApp/StyledTextKit would improve the performance?

**Comment by rnystrom** [comment]
Yup this is just how `UICollectionView` works. The `UICollectionViewLayout` (no matter which type you're using) will need the layout attributes of _everything_ in order to find the [collectionViewContentSize](https://developer.apple.com/documentation/uikit/uicollectionviewlayout/1617796-collectionviewcontentsize?language=objc). We optimize this in Instagram a few ways:

1. Never initially load w/ this many objects. _Always_ page!
2. Keep size math as cheap as possible (namely: size text on background threads. See library @weyert linked)
3. Aggressively cache sizes and make invalidation smart (e.g. don't resize everything). We do this in `IGListCollectionViewLayout`

Closing since this isn't an issue w/ IGListKit.

**Comment by psi-gh** [comment]
@rnystrom Thanks! Does it mean that UICollectionView reduce its performance with increasing amounts of data? For example, if i scroll down history list and load more and more pages?

**Comment by rnystrom** [comment]
@psi-gh as long as you aren’t invalidating all layout data every time, it’ll be fine. This is part of the reason IGListKit exists: providing a better way to update rather than calling `reloadData` every time.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by psi-gh** [comment]
@rnystrom oh ok. now I have some more questions on collection view & instagram but don't want to offtop here. Where can i ask you, if you don't mind? :)

**Comment by rnystrom** [comment]
Another issue is fine if it’s a different topic 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
