### ISSUE TITLE
Add IGListSectionDelegate

### ISSUE THREAD

**Issue by zhubofei** [Instagram/IGListKit#1217]
Came across this answer today https://stackoverflow.com/a/39015025/2977647. I recalled the discussion we had on #168. I know no one wants to touch #168 again 😂, but I think this might be the better way to enforce compile-time safety.

**Comment by zhubofei** [comment]
Well, the answer is for swift, so I'm not sure if it applies to obj-c as well.

**Comment by rnystrom** [comment]
@zhubofei can you catch me up on what this would provide?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhubofei** [comment]
@rnystrom This can enforce abstract methods to be implemented. But at the cost of code redundancy. Well, I think I'm gonna close this. `delegate = self` looks silly.
