### ISSUE TITLE
Use dispatch_queue_get/set_specific instead of threadDictionary

### ISSUE THREAD

**Issue by zhubofei** [Instagram/IGListKit#1218]
https://github.com/Instagram/IGListKit/blob/bee2178443ffcaff1d9135c4e094f74240433a62/Source/IGListSectionController.m#L22-L45

Should we replace these `NSThread` code with GCD using  `dispatch_queue_get/set_specific`?

**Comment by rnystrom** [comment]
@zhubofei what would we gain?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhubofei** [comment]
@rnystrom I don't think there would be a performance gain here. But Apple does recommend [using GCD instead of NSThread](https://developer.apple.com/library/archive/documentation/General/Conceptual/ConcurrencyProgrammingGuide/ThreadMigration/ThreadMigration.html). And I remember reading this blog [GCD's Main Queue vs. Main Thread] (http://blog.benjamin-encz.de/post/main-queue-vs-main-thread/) earlier.

**Comment by rnystrom** [comment]
Unless we’re fixing/improving something, I’d err on leaving this alone. Not sure what the downsides of how we use `NSThread` here is.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
I think `NSThread` is technically incorrect, but not certain.
