### ISSUE TITLE
Missing documentation [IGListScrollDelegate listAdapter:didEndDraggingSectionController:willDecelerate:]

### ISSUE THREAD

**Issue by zhubofei** [Instagram/IGListKit#1220]
https://github.com/Instagram/IGListKit/blob/bee2178443ffcaff1d9135c4e094f74240433a62/Source/IGListScrollDelegate.h#L39-L45
Missing `@param decelerate`.

**Comment by Aviral190694** [comment]
Hi. Added the Pull Request for the starter bug. #1222 
Please let me know if this solves the issue.
