### ISSUE TITLE
Remove nibName argument from IGListReusableViewIdentifier

### ISSUE THREAD

**Issue by zhubofei** [Instagram/IGListKit#1223]
https://github.com/Instagram/IGListKit/blob/bee2178443ffcaff1d9135c4e094f74240433a62/Source/Internal/IGListAdapterInternal.h#L20-L23

`nibName` was never used and should not be used to generate identifiers.

**Comment by rnystrom** [comment]
Wait is that correct? Shouldn’t it have been used?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
