### ISSUE TITLE
prepareForReuse vs cellForItem

### ISSUE THREAD

**Issue by Recouse** [Instagram/IGListKit#1230]
Is it better to use `UICollectionView`'s `prepareForReuse` method or `ListSectionController`'s `cellForItem` method to reset some views state in cell?

**Comment by zhubofei** [comment]
If you are working with your model (item), `ListSectionController`'s `cellForItem` is probably the better choice.

**Comment by Recouse** [comment]
I want to manage the selection state of cells.

**Comment by rnystrom** [comment]
@Recouse can you give us an example of your setup and options? Either is probably ok. Typically for selection you’d set a property on the cell every time `cellForItem` is called, so that should take care of “resetting” the cells state.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Recouse** [comment]
Got it. Thank you for the answers.
