### ISSUE TITLE
ViewModel Dynamic height issue?

### ISSUE THREAD

**Issue by tasarimabi** [Instagram/IGListKit#1231]
How can i make vievModel height dynamic

switch viewModel {
        case is ImageViewModel: height = 375
        case is UserViewModel: height = 62
        case is ActionViewModel: height = 72

        case is CaptionViewModel: height = 48
//        case is Comment: height = 35
        default: height = 65

CaptionViewModel has a label and viewModel height has to change according to label height. I dont want to define a fix value. 

How can i do that?

## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by rnystrom** [comment]
@tasarimabi have you checked any of the examples in this project?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iperry90** [comment]
@tasarimabi`MonthSectionController.swift` in the examples of this project shows an example of what you are describing.
