### ISSUE TITLE
Question about logic of shouldInvalidateLayoutForBoundsChange in IGListCollectionViewLayout

### ISSUE THREAD

**Issue by allenhsu** [Instagram/IGListKit#1235]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.4.0
- iOS version(s): N/A
- CocoaPods/Carthage version: N/A
- Xcode version: N/A
- Devices/Simulators affected: N/A
- Reproducible in the demo project? (Yes/No): N/A
- Related issues: N/A

Actually it's not quite a bug but flaw in the logic.

When digging into implementation of IGListKit, I noticed in `shouldInvalidateLayoutForBoundsChange` of `IGListCollectionViewLayout`:

```
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds {
    const CGRect oldBounds = self.collectionView.bounds;

    // if the y origin has changed, only invalidate when using sticky headers
    if (CGRectGetMinInDirection(newBounds, self.scrollDirection) != CGRectGetMinInDirection(oldBounds, self.scrollDirection)) {
        return self.stickyHeaders;
    }

    // always invalidate for size changes
    return !CGSizeEqualToSize(oldBounds.size, newBounds.size);
}
```

It compares origin first, if origin changes, the value of `self.stickyHeaders` is returned. Otherwise, compare size of bounds.

The problem is, if there's some scenario when origin and size both changed, but `self.stickyHeaders` is NO, this method returns NO despite bounds' size changed.

It's not causing bugs, yet, but it's a bit inconsistent and not as the comment says, always invalidate for size changes.

The fix is actually easy, just move size comparison above origin comparison.

```
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds {
    const CGRect oldBounds = self.collectionView.bounds;
    // always invalidate for size changes
    if (!CGSizeEqualToSize(oldBounds.size, newBounds.size)) {
        return YES;
    }
    // if the y origin has changed, only invalidate when using sticky headers
    if (CGRectGetMinInDirection(newBounds, self.scrollDirection) != CGRectGetMinInDirection(oldBounds, self.scrollDirection)) {
        return self.stickyHeaders;
    }
    return NO;
}
```

I can open a PR if necessary.

**Comment by rnystrom** [comment]
Nice find!!
