### ISSUE TITLE
Non-class type `Tweet` cannot conform to protocol `ListDiffable`

### ISSUE THREAD

**Issue by BalestraPatrick** [Instagram/IGListKit#1243]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.4.0
- iOS version(s): 12.0
- CocoaPods/Carthage version: Carthage 0.30.1
- Xcode version: 10.0 beta 7
- Devices/Simulators affected: iPhone X
- Reproducible in the demo project? (Yes/No): N/A
- Related issues:

Hi there! It's my first experiment with `IGListKit` so sorry if this is a newbie question. I am trying to make my `Tweet` model conform to `ListDiffable` but the compiler in Xcode 10 beta 6 is throwing the following error: `Non-class type `Tweet` cannot conform to protocol `ListDiffable``

This is what my simple model looks like:

```swift
import Foundation
import IGListKit

public struct Tweet: Codable {
    public let idStr: String
    public let createdAt: Date
    public let favoriteCount: Int
    public let retweetCount: Int
    public let retweeted: Bool
    public let user: User
    public let text: String
}

extension Tweet: ListDiffable {

    public func diffIdentifier() -> NSObjectProtocol {
        return idStr as NSString
    }

    public func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
        guard let idStr2 = object?.diffIdentifier() as? String else { return false }
        return idStr == idStr2
    }
}

extension Tweet: CustomStringConvertible {

    public var description: String {
        return "\nTweet:\n\tidStr: \(idStr)\n\ttext: \(text)\n\tuser: \(user.description)"
    }
}
```

I found this pretty old related [pull request](https://github.com/Instagram/IGListKit/pull/203) which seems to have a similar scenario to mine and it actually compiles. Is this supposed to still compile and work as expected or is it mandatory to have all my models objects defines with `class`?

**Comment by davidseek** [comment]
Referring to the following [best practices doc](https://github.com/Instagram/IGListKit/blob/master/Guides/Best%20Practices%20and%20FAQ.md)  you can use [this snippet](https://github.com/Instagram/IGListKit/issues/35#issuecomment-277503724) to make your struct diffable.

**Comment by BalestraPatrick** [comment]
Oh, I missed that. I got confused by the example code in this [PR](https://github.com/Instagram/IGListKit/pull/203).
