### ISSUE TITLE
How does the diffIdentifier and isEqual values affects the detailed ui updates for a cell?

### ISSUE THREAD

**Issue by fans3210** [Instagram/IGListKit#1245]
## New issue checklist

- [ ✔️] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [✔️ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.4.0
- iOS version(s): ios 12 beta 10
- Xcode version: xcode 10 beta 6

I have read the documentation and saw a few samples about the detailed use case for the 'diffIdentifier' and 'isEqual' values. I understand from what you said that diffIdentifier works like a primary key and isEqual is as self described. But how do they affected the detailed ui update? Below is my use case:

I have a cell when two ui elements: a radio button image view(for selected status display) and a uitextfield. I'm using ListBindSectionsController. My view model is like below:

```
class RadioTitleWithTextFieldCellViewModel: ListDiffable {
    let selected: Bool
    let title: String
    let placeHolder: String
}
```
My expected behaviour is: when cell is selected, or when textfield begin editing, update the viewmodel to be 'selected' status, as shown below:

https://www.dropbox.com/s/vouvtd2t3wx5a2j/ScreenRecording_08-24-2018%2013-05-51.MP4?dl=0

At first, I used both 'title' and 'selected' and placeholder converted to string joined together to be the diffId and 'true' for the 'isEqual' value. But the ui looks a bit strange, when I tapped the textfield, the textfield begin editing at first but resignedfristresponder immediately. I have to tap textfield again to make the keyboard appear again, as shown below:

https://www.dropbox.com/s/nbvymbtfgn8p4nm/ScreenRecording_08-24-2018%2013-07-29.MP4?dl=0

To make ui to have  correct behaviour, I have to make the following chnages: 
1. for the diffIdentifier, I used only title as the diffIdentifier
2. implement the isEqual func instead of returning true. Like below:

```
selected == object.selected
        && title == object.title
        && text == object.text
        && phText == object.phText
```

My code just simply call the update function in the section controller. Although by making such changes above seems resolved the issue, but I still don't quite understand the causes. From the samples you provided, normally you just implement one of the two functions and leave the other identical. I never seen a sample from the doc the you implemented detailed logics for both method. I also reviewed other issues and you mentioned that you normally always put 'true' for the isEqual func for the instragram app for now.

From my understanding: Since you mentioned that diffId is just like a primary key, what I understand is: changes on diffid will cause a new viewmodel to fully overwrite the previous one for the cell, while changes on 'isEqual' doesn't actually change the viewmodel's primary key but changed its value. Both methods triggers the 'bindViewModel' function to update the cell. 

Now I'm getting confused:  
1. I implemented using two different approaches. First way changed the identifier of the viewmodel, while second way changed only the value. For both, 'bindViewModel' gets called.  Then how does the resignFristResponder happened only on the first case? Why the diffId change affects the editing status of a uitextfield. How does How does the diffIdentifier and isEqual values together affects the detailed ui updates for a cell?

2. what is an ideal solution for my case?

Appreciated if you could provide me some guidance.

**Comment by rnystrom** [comment]
This is an issue with cell reuse. Your cell is being reloaded. The original cell is removed from the window and it’s textview resigns. The same issue happens when you `reloadData` on a plain table or collection view.

Can you repro the issue and your setup in an example project? You’re using the binding SC so that should actually be reloading the cell if your identifier doesn’t change.

Also if the selected state powers your identifier, then that’s why the cell reloads. Maybe just use the title as the identifier?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fans3210** [comment]
working project:
https://www.dropbox.com/s/mhz3m31gvlqat5i/DemoIGIssue_work.zip?dl=0
demo video of working project:
https://www.dropbox.com/s/aq46v90v11gg2bz/work.MP4?dl=0

buggy project:
https://www.dropbox.com/s/5uej8q1i4oj2j1l/DemoIGIssue_buggy.zip?dl=0
demo video of buggy project:
https://www.dropbox.com/s/cfwhnnj2rtyeirw/buggy.MP4?dl=0

I have a number formatter in the textfield to force 2 digits, but there is no reload of the cell since the textfield doesn't resign. For the diffid, I didn't put the user's input text as the identifier since it will cause the cell to reload which is what I didn't want since I need the text field to always be first responder unless I manually resign.  For the buggy project, it won't format if I changed '0.00' to '000' since the isEqual returned me true which should be false, current solution is to force isEqual to force

Please check my viewmodel and my only change is the 'isEqual' function. 

```
class AmountInputCellViewModel: ListDiffable {
    
    let formattedAmountStr: String?
    let ph: String
    
    init(formattedAmountStr: String?, ph: String) {
        self.formattedAmountStr = formattedAmountStr
        self.ph = ph
    }
    
    func diffIdentifier() -> NSObjectProtocol {
        return (ph + (formattedAmountStr ?? "")) as NSObjectProtocol
    }
    
    func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
        guard let object = object as? AmountInputCellViewModel else { fatalError() }
                return formattedAmountStr == object.formattedAmountStr
                && ph == object.ph
        
//        return false //sol: force make difference to trigger the bindviewmodel??
    }
}
```

**Comment by fans3210** [comment]
@ryanolsonk pls check, tks

**Comment by rnystrom** [comment]
@fans3210 Did you update your model? Did anything get fixed? You might also want to keep your identifier constant or simple.

I tried using your example project and find it really hard to navigate. I'm not sure how this works.

**Comment by fans3210** [comment]
@rnystrom Sorry my example might not be that clear. For simplicity:

Update an identifier of a listdiffable will trigger cell reload, but not when we use constant identifier but overwrite 'isEqual' method.

You mentioned
`You’re using the binding SC so that should actually be reloading the cell if your identifier doesn’t change.`

But this might be the case in my example

**Comment by fans3210** [comment]
My original purpose is about asking the correct way to make a textfield with formatter(format text when resigned first responder) using listbindable datasource without reloading the cell. But since you mentioned that it should reload the cell when 'isEqual' is false which I think the existing behaviour shown in my example might be a bug?

**Comment by rnystrom** [comment]
For binding SC, you want equals to always return YES and instead diff the view models in the SC.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fans3210** [comment]
@rnystrom . I didn't see this in the documentation, but since you mentioned, I would like to confirm that: Is it the best practice to always return yes/true for isEqual for binding sc? If yes, I would follow this best practice and trying to achieve the same behaviour using some other ways such as what you mentioned: handle in sc

**Comment by fans3210** [comment]
@rnystrom 
From what I see from the documentation and my current usage, I think cell will only be reloaded when identifier changed, not for isEqual. But, both of them will trigger 'bindViewModel' which will update the ui of the cell.

**Comment by fans3210** [comment]
After checking the documentation again, noticed that have to follow some best practice for the listbindingsc, close this issue.
