### ISSUE TITLE
Changing cells background color affect other cells background colors

### ISSUE THREAD

**Issue by GitMAM** [Instagram/IGListKit#1246]
I have reviewed the 'README' File and docs
I have searched exsiting issues.

I have a EmbeddedSectionController and i wanted to change the color of the cell when pressed. But when i do so, some other cells i didn't click on change their color as well, not sure why. 

here is the code : 

`    override func didSelectItem(at index: Int) {
        guard let cell = collectionContext?.cellForItem(at: index, sectionController: self) as? TopicCell else {return}
        cell.label.backgroundColor = UIColor.black
        cell.label.textColor = UIColor.clear
    }
    `

Thanks

**Comment by rnystrom** [comment]
- Does the cell exist?
- Set the `contentView` background color instead
- What debugging have you done?
- Do you have an example project?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GitMAM** [comment]
Sorry it was my fault. i haven't set the color before changing it.
