### ISSUE TITLE
Prefetching Images in Section Controller (via WorkingRangeDelegate) cause memory problems?

### ISSUE THREAD

**Issue by siefix** [Instagram/IGListKit#1249]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

I'm looking to implement prefetching of images on cells. 

I noticed that in the Examples the [WorkingRangeSectionController](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/WorkingRangeSectionController.swift) is a perfect example of this.

However, I'm wondering **will this cause memory issues?**

According to the [Best Practices and FAQ Reference](https://instagram.github.io/IGListKit/best-practices-and-faq.html): 

> IGListKit does not reuse section controllers

So if I have a ton of cells, and therefore 1 Section Controller per cell, each with their own UIImage being **cached** at the SC level - would this eventually lead to a ton of memory being used if a user scrolls through a lot of cells?

**Comment by rnystrom** [comment]
Yes, you should be using a separate cache layer to efficiently cache image data instead of retaining the data on the SC. I’d recommend some of the memory/disk cache libraries like SDWebImage.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
