### ISSUE TITLE
Is there something similar for Android?

### ISSUE THREAD

**Issue by bschiranth** [Instagram/IGListKit#1258]
Any library for Android that generates UI forms from json?

**Comment by skyweb07** [comment]
like this https://github.com/pedrovgs/Renderers?

**Comment by rnystrom** [comment]
Unfortunately there's no IGListKit for Android

**Comment by rob-keepsafe** [comment]
https://medium.com/airbnb-engineering/epoxy-airbnbs-view-architecture-on-android-c3e1af150394#.9hno4vdc0
