### ISSUE TITLE
[Suggestion] IGListDisplayDelegate DidFinishDisplayingSectionController

### ISSUE THREAD

**Issue by kwstasna** [Instagram/IGListKit#1259]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.4.0
- iOS version(s): 12
- CocoaPods/Carthage version:
- Xcode version: 10

I think that `ListDisplayDelegate` should include a delegate method that will inform the viewController that hosts the listAdapter, for the sectionController that finish displaying.

**Comment by rnystrom** [comment]
@kwstasna are you saying a delegate to forward `viewDidAppear` and other such events? For what purpose?

**Comment by kwstasna** [comment]
@rnystrom Let's say that i want to subscribe to a certain websocket channel for a profile to get live data changes, but i want to subscribe when the view is loaded, and unsubscribe when the view disappears. 
Each view will know in which ID will subscribe and unsubscribe.

For example the UIPageViewController has the didFinishAnimating

https://developer.apple.com/documentation/uikit/uipageviewcontrollerdelegate/1614090-pageviewcontroller

We could build up something like this in IGListKit.

**Comment by rnystrom** [comment]
Ahh ok, cool! You could def wire up something in your VC to forward events to SCs confirming to a delegate. That’d be an easy example. 

Wiring this up in IGLK would still require manually forwarding the event unless we add swizzling.

Love the proposal, but think it won’t add a ton of value vs just doing it manually.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
