### ISSUE TITLE
Swift brach failing for swift 4.2 , Xcode 10.0 

### ISSUE THREAD

**Issue by kanumuri9593** [Instagram/IGListKit#1265]
## New issue checklist

![screen shot 2018-10-18 at 2 28 55 pm](https://user-images.githubusercontent.com/16531000/47175952-6bedf980-d2e2-11e8-9764-ad8b842240fe.png)

### General information

- `IGListKit` version: 3.3.0 swift branch
- iOS version(s): 11+
- CocoaPods/Carthage version:
- Xcode version: 10
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by rnystrom** [comment]
Let's keep this in #1081
