### ISSUE TITLE
Cell size calculation at Instagram

### ISSUE THREAD

**Issue by richardtop** [Instagram/IGListKit#1266]
Given how important the cell height is for making it with `IGListKit`, could you explain, how the cell sizing is implemented at Instagram?

What are the best practices for handling dynamic content with various heights without AutoLayout?

**Comment by jboo1212** [comment]
Do you mean text?

**Comment by yusuftor** [comment]
Check out the example project to see how sizing is implemented.

**Comment by rnystrom** [comment]
We don’t have anything fancy. Cell sizing is done by hand along with layout (just frame math). The examples in the repo are pretty close to how we do it at Instagram.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
