### ISSUE TITLE
NavigationBar Large Title and Scroll

### ISSUE THREAD

**Issue by brurend** [Instagram/IGListKit#1269]
## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.4.0
- iOS version(s): Latest
- CocoaPods/Carthage version: Latest
- Xcode version: Latest
- Devices/Simulators affected: Both
- Reproducible in the demo project? (Yes/No):
- Related issues: I believe I already seem similar issues before but I couldn't find it.

### Debug information

When using iOS 11 navigation bar large titles there a few issues, not entirely sure if its because of IGListKit or not.

If I have only a few cells, and the height isn't enough to go "out" of the screen, the scroll gets disabled. The main problem here is that I can't pull down to reveal the search bar in my navigation bar.

Other issue happens when there is enough cells to scroll with the large title, but when I scroll all the way to the top and the navigation bar goes to its regular size, the scroll gets disabled if the height of cells aren't enough to trigger the scroll with the new content size.

**Comment by rnystrom** [comment]
@brurend this doesn't sound like an issue with IGListKit since we don't do anything w/ nav bars. If you can show us an example we might be able to help, but I'm not sure there's much I can do here.

**Comment by brurend** [comment]
You are right, it is related to UICollectionView and actually isn't a bug at all.

Thanks for the reply and sorry for the unnecessary issue.
