### ISSUE TITLE
Dealing with `IGListAdapterProxy` in `UICollectionView` subclasses

### ISSUE THREAD

**Issue by attheodo** [Instagram/IGListKit#1280]
Hello,

I need to subclass `UICollectionView` to add some more methods to `UICollectionViewDelegate` protocol. The common pattern of course is to use an immediate, delegate proxy object similar to how IGListKit has `IGListAdapterProxy`. 

Here's my code:
```swift
import Foundation
import UIKit

import IGListKit

class CollectionViewDelegateProxy: NSObject, UICollectionViewDelegate {
    
    // MARK: - Public Properties
    
    public weak var delegate: CollectionViewDelegate?
    
    // MARK: - Public Methods
    
    override func responds(to aSelector: Selector!) -> Bool {
        return super.responds(to: aSelector) || delegate?.responds(to: aSelector) == true
    }
    
    override func forwardingTarget(for aSelector: Selector!) -> Any? {
        
        if delegate?.responds(to: aSelector) == true {
            return delegate
        } else {
            return super.forwardingTarget(for: aSelector)
        }
        
    }
    
    // MARK: - UICollectionViewDelegate
    
}

protocol CollectionViewDelegate: UICollectionViewDelegate {
    func collectionViewDidScrollUpwards(_ collectionView: CollectionView)
    func collectionViewDidScrollDownwards(_ collectionView: CollectionView)
}

extension CollectionViewDelegate {
    func collectionViewDidScrollUpwards(_ collectionView: CollectionView) {}
    func collectionViewDidScrollDownwards(_ collectionView: CollectionView) {}
}


class CollectionView: UICollectionView {
    
    // MARK: - Public Properties
    
    override var delegate: UICollectionViewDelegate? {
        set {
            delegateProxy.delegate = newValue as? CollectionViewDelegate
        }
        get {
            return delegateProxy.delegate
        }
    }
    
    // MARK: - Private Properties
    
    fileprivate var delegateProxy = CollectionViewDelegateProxy()
    
    // MARK: - Lifecycle
    
    override init(frame: CGRect, collectionViewLayout layout: UICollectionViewLayout) {
        super.init(frame: frame, collectionViewLayout: layout)
        super.delegate = delegateProxy
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        super.delegate = delegateProxy
        
    }
    
}

```

The problem is, where I am overriding `delegate` property on `CollectionView` and try to set the new external `newValue` delegate, the casting to `CollectionViewDelegate` always fails since the object is `IGListAdapterProxy: NSProxy` and cannot be casted ending up with a `nil` "external" delegate.

Are there any workarounds to that so I can keep my `CollectionView: UICollectionView` compatible for both IGLIistKit and non-IGListKit use-cases?

Thanks

**Comment by rnystrom** [comment]
Unfortunately I'm really not sure. I'd try at all costs to avoid subclassing `UICollectionView`. Is there maybe an alternative way to achieve what you're trying to do?

**Comment by attheodo** [comment]
@rnystrom copy paste code wherever its needed I guess 🤓

Why avoid subclassing at all costs?

**Comment by rnystrom** [comment]
Over time you may end up with multiple subclasses overriding and introspecting... gets yucky. I’ve seen decomposition almost always result in a more maintainable code base.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
