### ISSUE TITLE
Add shadows to section controller

### ISSUE THREAD

**Issue by russelltwarwick** [Instagram/IGListKit#1313]
Trying to add shadows to a section controller but having no luck finding a solution. Only way is to add shadows to the cells but this causes the shadows to overlap on to other cells. Anyone have any ideas?

**Comment by weyert** [comment]
Hmm, can't you use the decoration views for this?

**Comment by bdotdub** [comment]
@waruss321 did the decoration view work for you?

**Comment by abdela7ad** [comment]
Any one Figure out any solution

**Comment by Janscho** [comment]
Maybe this helps: https://github.com/Instagram/IGListKit/issues/805
Needed the same functionality, but still haven't tried it.

**Comment by waruss321** [comment]
Still no solution to this.

**Comment by yusuftor** [comment]
Has anyone got a working solution for this?

**Comment by lorixx** [comment]
I think the best approach is to model this into the view model, to have the cell respect the value for the rounder corner for that particular index path.  For example, if you have 5 view models in this section, and you want the top and bottom corner, then you should add that information into the view model itself, something like "cornerInfo":

[ viewModel with top corner, view model[with no corner], view model[with no corner], view model[with no corner], view model with bottom corner ]
