### ISSUE TITLE
RxIGListKit

### ISSUE THREAD

**Issue by Bruce-pac** [Instagram/IGListKit#1322]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```
IGListKit is a great framework that I used, but it isn't reactive enough.
I create [RxIGListKit](https://github.com/Bruce-pac/RxIGListKit) that can bring IGListKit into RxSwift world. The old one [RxIGListKit](https://github.com/Arlindog/RxIGListKit) is no longer maintained.
 May I open a PR and adding my project to IGListKit guide?

**Comment by lorixx** [comment]
Thanks Bruce for inspiring the IGListKit+RxSwift usage here! I think it's better to keep the RxIGListKit as one of the rule of thumb is that we dont want to couple too much dependencies in IGListKit. It's the same reason that we separate the diffing algorithm in IGListDiffing from IGListKit.
