### ISSUE TITLE
Catalyst (UIKit for Mac) support

### ISSUE THREAD

**Issue by ptmt** [Instagram/IGListKit#1328]
Probably will try to make a pull request, but got this in master:
![image](https://user-images.githubusercontent.com/1004115/59061746-db821a80-88ac-11e9-9e79-7c83a99966b9.png)

**Comment by Ziewvater** [comment]
@ptmt Can you give us a bit more context on this? Did you come across this issue just by trying to build the library for a macOS target?

**Comment by ptmt** [comment]
Sorry for such an unprofessional issue. I was building the default target but with the enabled option in Xcode 11: 

![image](https://user-images.githubusercontent.com/1004115/59325380-7afb3f00-8ceb-11e9-818b-b0a7bc528e36.png)

I managed to build it in the end by using many `#if TARGET_OS_UIKITFORMAC`, but not sure what's the right way here, I guess I need some time to experiment.

**Comment by lorixx** [comment]
Yea, that sounds like a cool experiment! As I understand it well, there is API differences between the iOS versions and the iPadOS/MacOS, hence the compiler complains. Let us know how it goes, for now, let's close this issue?

**Comment by ptmt** [comment]
Sure. Thanks!
