### ISSUE TITLE
Bug: Nested CollectionView

### ISSUE THREAD

**Issue by shuhrat10** [Instagram/IGListKit#133]
![2](https://cloud.githubusercontent.com/assets/62485/19826845/ce075366-9d63-11e6-95a4-f93537c41689.jpg)
If you add more nested CollectionView's to Nested Adapter example, you will notice that the horizontal scroll will be broken. Pod installed from master branch (https://github.com/Instagram/IGListKit). 
- Xcode 8.0

**Comment by jessesquires** [comment]
Thanks @shuhrat10 ! 😄 Can you provide more info or a link to the modified demo project?

cc @rnystrom

**Comment by shuhrat10** [comment]
Just replace data array in NestedAdapterViewController.swift file.

let data = [
        "Ridiculus Elit Tellus Purus Aenean",
        "Condimentum Sollicitudin Adipiscing",
        14,
        "Ligula Ipsum Tristique Parturient Euismod",
        "Purus Dapibus Vulputate",
        6,
        "Tellus Nibh Ipsum Inceptos",
        2,
        43,
        15,
        20,
        15,
        "a",
        "c",
        4
    ] as [Any]

Then run project and scroll a little to the left of the first collectionview and then scroll down.

**Comment by Sherlouk** [comment]
Tested on iPhone 7+ (iOS 10) and didn't do it, but tried on the same device as the screenshot iPhone 5s (iOS 9.3) and it does it (using the modified data type)

Looks to me like a simple case of when a UICollectionViewCell is reused then the scrollview is not reset. Adding in a `prepareForReuse` fixes this, PR open.

**Comment by shuhrat10** [comment]
@Sherlouk The fixes looks good until you do not need to keep contentOffset for previous collectionview. I think we need to store contentOffset in OrderedSet for existing collectionview, and pass this value to prepareForReuse if it exist.

**Comment by Sherlouk** [comment]
@shuhrat10 I already mentioned that in the PR, but not sure how deep we want to get with functionality based on what the example is trying to show (being that you can nest collection views)

Happy to leave this discussion open, and if we want to store offsets then that's a simple addition!

**Comment by shuhrat10** [comment]
Will be great if IGListKit will store offsets out-of-box. @Sherlouk cc @rnystrom

**Comment by rnystrom** [comment]
@shuhrat nice find! I think this also reinforces that we need to provide a stock embedded collection view section controller like we proposed in #13.

**Comment by jessesquires** [comment]
Looks like we can close this and follow-up in #31?

cc: @rnystrom
