### ISSUE TITLE
Docs broken for modeling and binding

### ISSUE THREAD

**Issue by danqing** [Instagram/IGListKit#1331]
Docs for modeling and binding is broken: https://instagram.github.io/IGListKit/modeling-and-binding.html

1. All images are broken
2. All expandable code snippets don't get rendered as code

**Comment by lorixx** [comment]
Thanks @danqing! I saw the images is broken, can you explain where 'all the expandable code snippets' dont get rendered? Thanks

**Comment by danqing** [comment]
<img width="738" alt="Screen Shot 2019-06-26 at 8 32 54 AM" src="https://user-images.githubusercontent.com/5134133/60142593-03e6a000-97ed-11e9-92b5-77a9b57cf5fe.png">

Sure - these expandable sections. They should probably be `<pre>` tags but are instead `<p>`.

**Comment by lorixx** [comment]
Nice catch, mind submit a PR to fix that? thanks! :)

**Comment by iperry90** [comment]
I noticed that the guide works fine from within the repo: https://github.com/Instagram/IGListKit/blob/master/Guides/Modeling%20and%20Binding.md

It seems like the guide is only broken when viewing the documentation on Github-Pages.

**Comment by lorixx** [comment]
This has been re-generated, closing now.

**Comment by danqing** [comment]
@iperry90 is right, and docs are still broken on GH Pages.
