### ISSUE TITLE
Are you planning to release anytime soon?

### ISSUE THREAD

**Issue by claudiogomezGL** [Instagram/IGListKit#1335]
I know this shouldn't be here, but I was wondering if is there a plan to release a new version soon? I've seen some issues have been resolved in master but hasn't been released. And I'd like to have those fixes included. 
Thanks in advance, and sorry to post this here.

**Comment by lorixx** [comment]
Thanks for asking! I think @Ziewvater and @bdotdub are planning a release coming out soon! So hang tight!

**Comment by PhilCai1993** [comment]
Sorry for commenting here, but can you have a look at issue #1341 ? I’m also expecting a release.
