### ISSUE TITLE
IGListStackedSectionController example

### ISSUE THREAD

**Issue by shuhrat10** [Instagram/IGListKit#134]
Can you add example how to use IGListStackedSectionController?

**Comment by Sherlouk** [comment]
Never knew this was even a thing, looking into the documentation for it now and will try to create a simple example! :)

**Comment by Sherlouk** [comment]
Started to make an example with this but reached a bit of a stumbling point with getting the correct object to the section controllers in the stack.

Will wait for someone with knowledge to respond on this!

**Comment by rnystrom** [comment]
Ah yes! We had an internal example that I forgot to port. Let me get that working.

**Comment by HumidBrains** [comment]
A IGListStackedSectionController example would be so helpful. Any progress on this?

**Comment by MMasterson** [comment]
+1 any update on this @rnyatrom @sherlouk

**Comment by MMasterson** [comment]
@rntatrom

**Comment by rnystrom** [comment]
Ack! Fell off my radar. Yes will update!

**Comment by MMasterson** [comment]
Thank you @rnystrom!
