### ISSUE TITLE
Crash when interative reordering and destroying a collectionview at the same time

### ISSUE THREAD

**Issue by PhilCai1993** [Instagram/IGListKit#1341]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version: 3.4.0
- iOS version(s): Found in iOS 12 device, guess it happens at all versions

For example, a collectionview is in a presented viewcontroller. When drag a cell, and dismiss the vc (the cell is still dragging) at the same time, it crash 100% at`-[UICollectionViewLayout+InteractiveReordering ig_cleanupInvalidationContext:]`. 

![image](https://user-images.githubusercontent.com/6828315/61277160-2b28ff80-a7e4-11e9-8ec8-6782642f92e1.png)

Because `UICollectionViewLayout` uses `OBJC_ASSOCIATION_ASSIGN` to hold `IGListAdapter`, and the real adapter is dealloced, EXC_BAD_ACCESS would happen.

One solution is using an intermediate object to hold the adapter, and `UICollectionViewLayout` hold a strong reference to the intermediate object.
![image](https://user-images.githubusercontent.com/6828315/61277520-ed78a680-a7e4-11e9-958f-c628f9869650.png)

![image](https://user-images.githubusercontent.com/6828315/61277508-e782c580-a7e4-11e9-985c-ed3adb2b2248.png)

**Comment by Ziewvater** [comment]
Can you repro this issue? Without more info about the crash we can't address it. I'm going to close for now, but feel free to reopen the issue when you have a demo app that reproduces this crash.

I haven't seen any other cases where this seems to be an issue, so it seems to me more like that something else in your app that is causing this crash. It seems like you could just prevent the crash by preventing the user from dismissing the view controller while they're reordering items in the collection view.

**Comment by PhilCai1993** [comment]
> Can you repro this issue? Without more info about the crash we can't address it. I'm going to close for now, but feel free to reopen the issue when you have a demo app that reproduces this crash.
> 
> I haven't seen any other cases where this seems to be an issue, so it seems to me more like that something else in your app that is causing this crash. It seems like you could just prevent the crash by preventing the user from dismissing the view controller while they're reordering items in the collection view.
@Ziewvater  Just open the iOS Example on device, open "Recorder Cell" example, then drag the cell, and press the back button on the navigation bar. It crashes.
