### ISSUE TITLE
Will there be more releases or should we use master?

### ISSUE THREAD

**Issue by danqing** [Instagram/IGListKit#1343]
I understand that Instagram uses master directly. There hasn't been a new release since over a year ago, so I want to ask if there's still plan to cut more releases or if we are expected to go with master. Thanks!

**Comment by claudiogomezGL** [comment]
Any news on here? Looking forward for a new version for some issues we have that already resolved in master? Is it safe to use master?

**Comment by claudiogomezGL** [comment]
@ryanolsonk @lorixx can we get an estimate for next release please?

**Comment by DimaVartanian** [comment]
Hey @danqing, @claudiogomezGL, thanks for writing. We're working on cutting a new release and will have one out soon.

**Comment by lorixx** [comment]
As dima said ^, pls feel free to use the master branch for the time being too!
