### ISSUE TITLE
Lot of ListSectionController and ListDiffable in memory after dismiss VC, Is this normal?

### ISSUE THREAD

**Issue by deshan** [Instagram/IGListKit#1356]
## New issue checklist

- [yes ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [yes ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version:3.4.0
- iOS version(s): 12
- CocoaPods/Carthage version:
- Xcode version: 10.2
- Devices/Simulators affected:iphone 6S
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```
I am using this in a VC and dismiss it when done. But when check the memory graph I see lot of ListSectionController and ListDiffable. Please see the attached image. Is this normal?

![Screen Shot 2019-08-13 at 1 49 25 AM](https://user-images.githubusercontent.com/234754/62896392-9aa3f780-bd6e-11e9-8b74-65481f395741.png)

**Comment by calimarkus** [comment]
This is not expected. It sounds like there is a retain cycle somewhere. Did you check the memory graph debugger to see what's still holding onto these objects?

**Comment by deshan** [comment]
Exactly, Thanks @calimarkus. Sorry for posting this here.
