### ISSUE TITLE
update data

### ISSUE THREAD

**Issue by adelbios** [Instagram/IGListKit#1361]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

i have 5 days ...  i was try every thing to implement pull to refresh but does not   work 
i got this error message 

<img width="703" alt="Screen Shot 2019-08-22 at 3 08 05 AM" src="https://user-images.githubusercontent.com/16545509/63476613-632dfd00-c48a-11e9-8096-0035d3aad5bc.png">

My model look like 
`
extension ExplorationItemModel : ListDiffable {
    
    func diffIdentifier() -> NSObjectProtocol {
        return id as NSObjectProtocol
    }
    
    func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
        guard self !== object else { return true }
        guard let object = object as? ExplorationItemModel else { return false }
        return id == object.id
    }
    
}

extension ExplorationItemModel : Equatable {
    
    static func == (lhs: ExplorationItemModel, rhs: ExplorationItemModel) -> Bool {
         return lhs.isEqual(toDiffableObject: rhs)
    }
}
`

**Comment by adelbios** [comment]
Anyone help me ?? 
Give me example or anything

**Comment by DimaVartanian** [comment]
Seems like the objects in your list are not unique (they have duplicate ids). One way around this as a start if there really is no data differentiating your objects is to return `self` as the `diffIdentifier`.
