### ISSUE TITLE
Update time relative label

### ISSUE THREAD

**Issue by ios4vn** [Instagram/IGListKit#1365]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

I used IGListKit to show contents from network API . Each row have one label display item created time such as:
- just now
- x minutes ago
- An hour ago

Items created time are fixed. I want the label will be update after each 30 seconds. ("Just now" after 60s will become "1 minute ago"). 
I looking for solution in couple hours.
So have you any suggestions for my case ?

**Comment by robertodias180** [comment]
You could use a `Timer` for that. When you update the cell you create a timer to run after X amount of seconds to update the view. and on `prepareForReuse` you stop the timer.

I went with this approach and it worked well for me 😀

**Comment by DimaVartanian** [comment]
Closing this out as it seems like you've got a good answer here.
