### ISSUE TITLE
Xcode 11 SPM Support/Release

### ISSUE THREAD

**Issue by RamblinWreck77** [Instagram/IGListKit#1368]
Hello! Now that the Xcode 11 GM is out, we're attempting to migrate from Cocoapods -> SwiftPM.

It looks like Package.swift is already on master, but there hasn't been a release that includes that commit yet. 

For now, simply switching SPM to "master" resolves the issue, but would you guys be interested in pushing out a release soon that officially supports SPM?

**Comment by DimaVartanian** [comment]
Hey @RamblinWreck77, thanks for the heads up! The team is working on cutting a new release.

**Comment by joeboyscout04** [comment]
How's it going with the release?  This is one of our last dependencies for our SPM conversion.

**Comment by Petteri78** [comment]
@RamblinWreck77 Did you manage to get it working with SPM from `master`? We get import errors when compiling.

**Comment by RamblinWreck77** [comment]
@Petteri78 I haven't tried master, though just looking at it I'm blown away that it has over a year of active development past the latest release. I usually shy away from using master since I don't want some stray commit causing instability and clear cut releases make testing easier, but if this is how they're doing things I might reconsider.

If they don't want to periodically cut releases once a quarter or so why bother supporting this (awesome) library in the first place?

**Comment by danqing** [comment]
I think the new IGListDiffKit change also needs to be added to SPM

**Comment by Ziewvater** [comment]
@danqing good call-out, this is something we'll need to make sure SPM can handle the changes with splitting IGListKit and IGListDiffKit

**Comment by nick-potts** [comment]
Now that 4.0 is out, can this be revisited? I had a crack at setting up the Package.swift but it was out of my depth.

**Comment by lorixx** [comment]
@nick-potts  Totally, we would prioritize to fix the SPM integration here, thanks for raising this!

**Comment by mohpor** [comment]
Any news?

**Comment by ivenprillwitz** [comment]
Any News?

**Comment by patch-benjamin** [comment]
The issue appears to be that the `package.swift` file doesn't include any dependency references. From my limited research on Swift PM I believe the package.swift file should include a dependency section that lists `IGListDiffKit` as a dependency and then make that framework also support Swift PM. Not sure if that would really fix it, but it seems like the right first step/direction. 
https://swift.org/package-manager/#importing-dependencies

**Comment by mohpor** [comment]
All that is needed to be done is to update the import declarations in some files. it's not that hard and I've already done it (contribute to) a few frameworks with C/C++ dependencies.

**Comment by RamblinWreck77** [comment]
Any news/progress?

**Comment by lorixx** [comment]
I have this draft SPM setting code WIP: https://github.com/lorixx/IGListKit/commit/81c90aee5c064bb57a72adf69e8cf4467b5f5244

However, I hit a road blocker for the "Internal header file not found error" error, ugrrr really hate Xcode project settings and I have no idea how to proceed here. If anyone want to continue to explore, feel free to take my draft code and send a PR!

**Comment by 3a4oT** [comment]
@lorixx please see #1465,  it took me some time to workaround bunch of limitations of SPM but I was able to make it work.

**Comment by RamblinWreck77** [comment]
Super exciting work @3a4oT, hope this ships soon!

**Comment by 3a4oT** [comment]
thanks, @RamblinWreck77, I think there is some workable solution now. Will appreciate any feedback from a real user :)

**Comment by BrentMifsud** [comment]
any updates on this?
