### ISSUE TITLE
 Scrolling programatically

### ISSUE THREAD

**Issue by Muki1992** [Instagram/IGListKit#1371]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version: 3.4.0
- Xcode version: 10.2
- Devices/Simulators affected: all

### Debug information

Dear IG team,

I'm happy to say that all of our app is build on IGListkit. Starting from the Login-Screen up to the Checkout - All views are flexible. And based on this I'm hoping to get one of our main problems finally solved: 

1. Having a starting scrolling section
2. Programatically scrolling to a section 

Considering 1:
So we have this dialog where our users may select a time range in which they will receive their delivery. When the user re-opens this dialog to edit the selection we'd like to have the horizontal-CollectionView position itself so the previously selected time range is centered. 

Having tried this is not solving the problem:

```bash

let adapter = ListAdapter(updater: ListAdapterUpdater(), viewController: nil)
adapter.collectionView = collectionView
adapter.dataSource = self
self.collectionView.scrollToItem(at: IndexPath(item: 0, section: selectedPosition), at: .left, animated: true)

```
Here we kinda know what the problem could be: When we're calling the collectionView to scroll the sections most probably "are not there yet". But what could be the solution? Some kind of callback indicating the complete loading of the section?

As mentioned in the beginning were building all are views with CollectionViews and IGListKit so what you see here is an embedded horizontal CollectionView inside a vertical one.

![image](https://user-images.githubusercontent.com/9077586/65834214-9d888680-e2e1-11e9-8151-ec9faeaf983e.png)

Considering 2: From time to time we want to focus certain sections: E.g. When the user selected a payment method and should now see the summary of his purchase. Unfortunately we were not able to have the collectionView scroll down after the user selected a payment method.

We tried following solution from another post

```bash

extension UICollectionView {
    func scrollToLast() {
        guard numberOfSections > 0 else {
            return
        }
        
        let lastSection = numberOfSections - 1
        
        guard numberOfItems(inSection: lastSection) > 0 else {
            return
        }
        
        let lastItemIndexPath = IndexPath(item: numberOfItems(inSection: lastSection) - 1,
                                          section: lastSection)
        scrollToItem(at: lastItemIndexPath, at: .bottom, animated: true)
    }
}
```
![image](https://user-images.githubusercontent.com/9077586/65834366-d543fe00-e2e2-11e9-8b5f-a90f41a01ca0.png)

Also bear with me for my "noobish" question here. Since we got a bit desperate on this problem I decided to post my first ever ticket on github 😄

**Comment by waruss321** [comment]
Is your collection view using a custom UICollectionViewFlowLayout? I had an issue when using an estimated size for the cells. Removed this and the issue went away. It's not ideal as it means you can't have dynamic heights for cells but it did solve the issue.

**Comment by Bruce-pac** [comment]
IGListAdapter->scrollToObject: supplementaryKinds: scrollDirection: scrollPosition:animated:

**Comment by Muki1992** [comment]
@Bruce-pac Thanks for the answer. Calling this method after adding all the models and waiting 0.5 seconds worked for us. 

The problem that we have now is that the wrong starting position shows up and after 0.5 secs the scrolling is performed. Do you have an idea on how to have the scrolling position set from the very beginning?

**Comment by Muki1992** [comment]
I think we got it solved by just doing the following:

(didMoveToSuperView)

collectionView.alpha = 0
scrollToObject (after delay 0.1 secs)
collectionView.alpha = 1

You really can't tell the difference. It looks as if it's there from the beginning on
