### ISSUE TITLE
ListBindingSectionController + Update Grid Cell via API

### ISSUE THREAD

**Issue by varyP** [Instagram/IGListKit#1372]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version: Latest Master
- iOS version(s): iOS 11+
- CocoaPods/Carthage version: 1.7.5
- Xcode version: 11
- Devices/Simulators affected: All

Hi, thanks for the fantastic framework, my whole app heavily uses IGListKit.

My setup is a Grid based Section Controller (using FlowLayout & ListBindingSectionController).
Model -> Has an objects array with some other flags.
In the section controller, i break the model into `4 cells` to be shown as a grid (2x2), so basically each section has 4 cells.

Upon tapping on one of the buttons in any cell, i delegate back to the ViewController(also where my adapter lives) & call an API, on receiving response of the api i want to update the cell which was tapped(just UI update)

Solution 1 : Update the Model such that the diff identifier changes, and delete & re-add the updated model, but this results in Section refresh, instead of the 1 cell, looks very weird.

Solution 2: Update that particular object in the model & call a public method on the section controller, calling the update(animated) method on the ListBindingSectionController. This although triggers `viewModelsFor` method, but cells don't get updated.

What is the correct way of handling such a scenario so as to only update the cell in the section controller.
<img width="232" alt="Screenshot 2019-10-01 at 11 50 47 PM" src="https://user-images.githubusercontent.com/8818244/65978639-a4acc180-e4a6-11e9-9c3b-8bd43dab8cae.png">

@rnystrom anything here?

**Comment by SnailLife** [comment]
How did you solve it?
