### ISSUE TITLE
Project fails to compile when included from podspec in a second-tier framework

### ISSUE THREAD

**Issue by joeboyscout04** [Instagram/IGListKit#1382]
I'm getting an issue with the latest `master` [specifically this commit](https://github.com/Instagram/IGListKit/commit/e4c60650f2953eb1adb258306ad5974b8e812eb3) where IGListKit fails to compile if it is included as a dependency from a pod which is also itself a dependency.  

<img width="1194" alt="Screen Shot 2019-11-04 at 21 05 43" src="https://user-images.githubusercontent.com/1489809/68154033-f386c480-ff46-11e9-8c6c-e8fae450ac9d.png">

I've attached the demo project below. Basically, the setup is as follows:

- OuterFramework
    - Inner Framework
        - IGListKit

The framework seems to link properly, but the imports to `IGListDiffKit` are broken 😢. 

I think this has something to do with how the imports are done in IGListKit (which is also is a problem with us using SPM, see #1368 ).   The `#import < >` syntax is assuming something about what's in the global header search paths, which breaks for the case here where the `InnerFramework`'s header search paths don't know about `IGListDiffKit`.  The `InnerFramework` compiles fine by itself.  I tried a few different attempts to fix this via the podspec, without success. 

## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [X] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version: `master`
- iOS version(s): iOS 13
- CocoaPods/Carthage version: 1.8.4
- Xcode version: 11.1
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No): Yes

Demo project:
[IGListKitFrameworkTester.zip](https://github.com/Instagram/IGListKit/files/3805856/IGListKitFrameworkTester.zip)

**Comment by natestedman** [comment]
Hey @joeboyscout04, this should be resolved in master now. You'll need to update your `Podfile` to also reference `IGListDiffKit` from master (same repo), this requirement should go away once we release 4.0.

**Comment by iperry90** [comment]
@joeboyscout04 closing this issue since it should now be resolved.
