### ISSUE TITLE
Specify end position for -scrollToObject

### ISSUE THREAD

**Issue by yusuftor** [Instagram/IGListKit#139]
The current implementation of -scrollToObject doesn't allow you to specify where you would like the section to be positioned at the end of the scroll. With Apple's implementation of -scrollToItem for a collectionView, they have a parameter called scrollPosition. This allows a user to specify whether the item should be positioned at the top, bottom, center etc. of the view.

It would be great if this feature could be implemented. For example, I want to be able to scroll to the very last cell, with the cell positioned at the bottom, when the keyboard is presented.
Thanks!

**Comment by rnystrom** [comment]
Absolutely. I've had this request internally too. We'll have to decide on whether or not this is a breaking change or not. Also we should get all the tests from #23 in place before doing this.

**Comment by zhubofei** [comment]
@rnystrom This may be a silly question. But what is the reason that we need to calculate the cell position manually inside `-scrollToObject` instead of calling 
`-scrollToItemAtIndexPath:atScrollPosition: animated;` directly?

**Comment by rnystrom** [comment]
@zhubofei in the case that you have a supplementary view at the beginning/end of your section and you want to scroll to the top of it. This happens in Instagram when we want to scroll to an item but align the top offset at the beginning of the supplementary view.

We could probably simplify a lot of this API though, or maybe split it out into other parts.

**Comment by zhubofei** [comment]
Still need unit test case for horizontal scrolling.

**Comment by jessesquires** [comment]
Done in #196. Closing.

Unit tests follow-up: #238
