### ISSUE TITLE
[Question] is it possible to disable cell selection of a section?

### ISSUE THREAD

**Issue by allenehuang** [Instagram/IGListKit#1402]
I have tried setting the ListAdapter collectionViewDelegate, but the shouldSelect and shouldHighlight methods are never called. (the didSelect hits just fine).

I've also tried just disabling userInteraction on the cells I don't want the user tapping, but that doesn't work.

**Comment by lorixx** [comment]
Look at "IGListAdapter+UICollectionView.m", you might need to add the missing delegate method if you want to disable the select or highlight state for UICollectionViewCell.
