### ISSUE TITLE
ListStackedSectionController 

### ISSUE THREAD

**Issue by adelbios** [Instagram/IGListKit#1403]
I update pod to use 4.0 version but I got issue  'Use of unresolved identifier 'ListStackedSectionController' 

and I check pod file this file doesn't exist

**Comment by iperry90** [comment]
Hi @adelbios, `IGListStackedSectionController` was removed in 4.0 ([1355](https://github.com/Instagram/IGListKit/pull/1355)).

**Comment by adelbios** [comment]
So how i can do something like this @iperry90 , because i have static Of stacked section with different data

**Comment by adelbios** [comment]
?? can you return this ?!

**Comment by iperry90** [comment]
@adelbios there are some suggestions and examples for replacing `IGListStackedSectionController` mentioned in https://github.com/Instagram/IGListKit/issues/1099.
