### ISSUE TITLE
Implicit declaration of function 'IGAssertNonnull' is invalid in C99

### ISSUE THREAD

**Issue by yusuftor** [Instagram/IGListKit#1419]
This is an error produced when building the latest version of IGListKit from the master branch. It occurs in `IGListBindingSingleSectionController.m` on the code `IGAssertNonnull(cell);`.

**Comment by qq432591** [comment]
same question

**Comment by Ziewvater** [comment]
Oh, looks like one of our assert macros that's not included in IGLK slipped through our internal diff process. Should be a simple fix, I'll get to that today.

**Comment by relsirc** [comment]
any update on this? @Ziewvater

**Comment by Ziewvater** [comment]
Sorry, this dropped off my radar. Should be resolved with @bdotdub's changes in https://github.com/Instagram/IGListKit/pull/1425
