### ISSUE TITLE
SelfSizing  change dataSource and reloadData contentoffset change

### ISSUE THREAD

**Issue by BestKai** [Instagram/IGListKit#1424]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version:4.0
- iOS version(s): 13.3.1
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

when i user selfSizing ，and i add some data to dataSources  then reloadData ，the collectionView will  shake 
<img width="647" alt="WeChate5710a68e09ba58702a015e3256aa4df" src="https://user-images.githubusercontent.com/8436462/73654022-975a4a80-46c5-11ea-97b1-77b5cf089b25.png">
![Untitled](https://user-images.githubusercontent.com/8436462/73654541-f4a2cb80-46c6-11ea-9dd9-6ad2f4262783.gif)

**Comment by bdotdub** [comment]
Hi @BestKai! Do you have a sample app I could take a look at?

**Comment by BestKai** [comment]
i use the IGListKit ios demo ,and change the  SelfSizingCellsViewController.swift  SelectionModel to all .fullWidth, when i add some datasouce to the data,the demo have the same problem.

**Comment by ahuinee** [comment]
@BestKai ，Me too！

**Comment by BestKai** [comment]
@ahuinee  I just changed to  UICollectionView  ，it appear also。so i think it is a bug of  UICOllectionView autolayout。

**Comment by ahuinee** [comment]
@BestKai  Thanks!  Please close this issues.
