### ISSUE TITLE
First item is overlapping with the last item

### ISSUE THREAD

**Issue by IPrototypeI** [Instagram/IGListKit#1434]
He guys I have following problem that the first item is always overlapping with the last item in the demos I try to modify the empty view demo and it is working but I don't understand that issue in my code

<img width="330" alt="Bildschirmfoto 2020-03-21 um 14 59 00" src="https://user-images.githubusercontent.com/11798225/77228128-7a9aa900-6b85-11ea-8b48-cf0d00837440.png">

Maybe I forgot something or you can help me:

`import Foundation
import Core
class FAQHeaderCell: UICollectionViewCell {

     public let HeadlineLabel : BoschLabel  = {
         var boschLabel = BoschLabel()
         boschLabel.category(.bigHeadline)
         boschLabel.translatesAutoresizingMaskIntoConstraints = false
         return boschLabel
     }()
     
    override init(frame: CGRect) {
        super.init(frame: frame)
        contentView.addSubview(HeadlineLabel)
/*
        NSLayoutConstraint.activate([
            HeadlineLabel.topAnchor.constraint(equalTo: topAnchor, constant: 10),
            HeadlineLabel.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 10)
        ])*/
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("has not been implemented")
    }
}
`
`//
//  FAQHeaderSectionController.swift
//  Alamofire
//
//  Created by Jeremy Teichmann on 21.03.20.
//

import Foundation
import IGListKit
import Core

class FAQHeaderSectionController: ListSectionController {
    var item: FAQHeader!
    override init() {
        super.init()
        inset = UIEdgeInsets(top: 0, left: 0, bottom: 10, right: 0)
    }
}
extension FAQHeaderSectionController {

    override func sizeForItem(at index: Int) -> CGSize {
        guard let context = collectionContext
        else {
            return .zero
        }
        
        let cell = cellForItem(at: index)
        
        
        var height : CGFloat = 0.0
        if let cell = cell as? FAQHeaderCell {
            let name : String = self.item.headline
            var FAQHeaderCellSize : CGFloat = TextSize.size(name, font: UIFont.boschSansRegular(ofSize: BoschUnits.TU*2.1), width: context.containerSize.width, insets: UIEdgeInsets(top: BoschUnits.GU, left: BoschUnits.GU, bottom: BoschUnits.GU, right: BoschUnits.GU)).height + 10.0
            
            height = FAQHeaderCellSize
        }
        
        
        let width = context.containerSize.width
        
    
        
        return CGSize(width: width, height: 55.0)
        

    }
      
    override func cellForItem(at index: Int) -> UICollectionViewCell {
        let cell : FAQHeaderCell = collectionContext!.dequeueReusableCell(of: FAQHeaderCell.self, for: self, at: index) as! FAQHeaderCell
        
        cell.HeadlineLabel.text = item.headline
        return cell

    }
      
    override func didUpdate(to object: Any) {
        item = object as? FAQHeader
    }
    
}
`

`//
//  UserFAQViewController.swift
//  Core
//
//  Created by Jeremy Teichmann on 28.02.20.
//

import Foundation
import Core
import UserLegalNetwork
import RxSwift
import IGListKit

class UserFAQViewController: UIViewController, StoryboardInstantiable {

    static weak var delegate: NavigationCoordinator?
    private(set) var viewModel: UserFAQViewModel!
    

    var filteredEntries: [Any] = [Any]()
    var faqEntries: [Any] = [Any]()
    let disposeBag = DisposeBag()

    override func viewDidLoad() {
        super.viewDidLoad()

        let tap: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(self.dismissKeyboard))
        view.addGestureRecognizer(tap)
        
         let text : String? = DocsDB.selectDoc(doc: Config.FAQIdentifier)
        self.faqEntries = viewModel.parseFAQString(data: text!)
        self.filteredEntries =  self.faqEntries
        
        viewModel.setView(controller: self)
        setupBody()
        
        //setupObservable()
        //setupData()
        
    }
    

    static func create(with viewModel: UserFAQViewModel, _ delegate : NavigationCoordinator) -> UserFAQViewController {
        let view = UserFAQViewController.instantiateViewController(Bundle(for: Self.self).resource)
        self.delegate = delegate
        view.viewModel = viewModel
        return view
    }
    
    func setupObservable() {
        viewModel.faqObservable.take(1).subscribe(onNext: { response in
            if(response.status == Resource.Status.SUCCESS) {

              DispatchQueue.main.async {

                  if(response.data?.data != nil) {
                      print("Hier99399: \(response)")
                      var decodedString : String?
                      var content = DocsDB.getContentOfDoc(docname : Config.FAQIdentifier, data: response.data!)
                      
                      /// decode string
                      do {
                          let decodedData = try Data(base64Encoded: content!)
                          decodedString = try String(data: decodedData!, encoding: .utf8)
                      } catch {
                          print(error)
                      }
                      if(decodedString != nil){
                        self.faqEntries = self.viewModel.parseFAQString(data: decodedString!)
                        
                        if(self.filteredEntries.count == self.faqEntries.count) {
                            self.filteredEntries =  self.faqEntries
                            self.listAdapter.performUpdates(animated: true, completion: nil)
         
                        }
                      }
                     // self.wrapper_container.activityIndicator.stopAnimating()
                  }
               }
            }
        }, onError: { error in
            print("Error: \(error)")
        }).disposed(by: self.disposeBag)
    }
      
    func setupData() {
        let text : String? = DocsDB.selectDoc(doc: Config.FAQIdentifier)
        print("Test \(text)")
        if(text != nil) {
            
            self.faqEntries = viewModel.parseFAQString(data: text!)
            self.filteredEntries =  self.faqEntries
            //self.listAdapter.performUpdates(animated: true, completion: nil)
        } else {
           // wrapper_container.activityIndicator.startAnimating()
        }
        viewModel.fetchFAQDocuments(docID : Config.FAQIdentifier)

        setupNavigationBar(headline: LanguageFile.Text(key: "AppTitle"))
    }
    func setupNavigationBar(headline : String) {
        title = headline
    }
    
    /*
    lazy var wrapper_container : UserFAQScreen = {
          let wrapper_container = UserFAQScreen()
          return wrapper_container
    }()*/
    
    lazy var listAdapter: ListAdapter = {
        return ListAdapter(
            updater: ListAdapterUpdater(),
            viewController: self)
    }()
    let collectionView: UICollectionView = {

        let view = UICollectionView(
            frame: .zero,
            collectionViewLayout: UICollectionViewFlowLayout())
        view.backgroundColor = .white
       // view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()

    func setupBody() {

        //self.view.addSubview(wrapper_container)
        
        self.view.addSubview(collectionView)
        
        
/*
        wrapper_container.anchor(top: view.safeAreaLayoutGuide.topAnchor, left: view.leftAnchor, bottom: view.safeAreaLayoutGuide.bottomAnchor, right: view.rightAnchor, paddingTop: 0, paddingLeft:0, paddingBottom: 0, paddingRight: 0, width: 0, height: 0)
        */
        
        self.listAdapter.collectionView = self.collectionView
        self.listAdapter.dataSource = self
        
       // self.wrapper_container.addActionToTextfield(target: self, action: #selector(self.textFieldDidChange))
        
        
    }
    
    @objc func dismissKeyboard() {
        view.endEditing(true)
    }
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        collectionView.frame = view.bounds
        
    }
    
    @objc func textFieldDidChange(_ textField: BoschTextField) {
        filterFAQ(text: textField.text)
    }
    func filterFAQ(text : String?) {
        if(text != "" && text != nil) {
            filteredEntries.removeAll()
            for item in self.faqEntries {
                if let item = item as? FAQItemData {
                    let filteredStrings = item.faq_text!.filter({(item: FAQAnswer) -> Bool in
                        return item.faq_answer!.lowercased().contains(text!.lowercased())
                    })
                    if(item.faq_question!.lowercased().contains(text!.lowercased()) || filteredStrings.count != 0) {
                    
                        var element =  FAQItemData(faq_question : item.faq_question!, faq_text : item.faq_text!)
                        element.status = true
                        filteredEntries.append(element)
                    }
                } else {
                    filteredEntries.append(item)
                }
            }
            
        } else {
            filteredEntries = self.faqEntries
        }
        listAdapter.performUpdates(animated: true, completion: nil)
    }
}
extension UserFAQViewController: ListAdapterDataSource {
    func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
        return filteredEntries as! [ListDiffable]
    }
    func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController {
        if object is FAQItemData {
            return FAQSectionController()
        } else {
            return FAQHeaderSectionController()
        }
        
    }
    func emptyView(for listAdapter: ListAdapter) -> UIView? {
        return UIView()
    }
}
`

**Comment by IPrototypeI** [comment]
I found the issue that if I am calling cellForItem(at: index) this problem will appears

**Comment by moosabaloch** [comment]
@IPrototypeI  I don't know if you're using the ListSupplementaryViewSource or not but from the screenshot I guess this overlapping view is the sticky header from ListSupplementaryViewSource, add the background to it to see the natural behavior.

**Comment by IPrototypeI** [comment]
I was using the ListSectionController but I switched to the supplementartyview source and it was using , thx for your support
