### ISSUE TITLE
How can I pass data or perform segue from sectionController ?

### ISSUE THREAD

**Issue by rupesh4545** [Instagram/IGListKit#1444]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by lorixx** [comment]
The SectionController has reference to the ViewModel, and whenever there is tap action happens in the SectionController's delegate, which came from the actual Cell. We can trigger/perform the segue to do navigation etc. All the necessary data should be either generated inside the SectionController or part of the View Model it owns. Hope this helps :)
