### ISSUE TITLE
swift packages error contains mixed language source files; feature not supported

### ISSUE THREAD

**Issue by baveku** [Instagram/IGListKit#1446]
## New issue checklist

- ✅ I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- ✅ I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- ✅ I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version: Latest from master
- iOS version(s): all version
- CocoaPods/Carthage version:
- Xcode version: 11.6
- Devices/Simulators affected: iphoen 8
- Reproducible in the demo project? (Yes/No): No

### Swift Packages Error
- Package.swift: target at 'IGListKit/Source' contains mixed language source files; feature not supported

**Comment by SebastianBO** [comment]
Any1 solved this? SPM works or not?

**Comment by Gutty1** [comment]
Still not working

**Comment by baveku** [comment]
I will close the issue because we don't have any solution to solved. So I suggest we still use cocoapods
