### ISSUE TITLE
Add -[IGListCollectionContext moveInSectionController:fromIndex:toIndex:] API

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#145]
We lack the ability to move cells in a section controller. Right now you could delete+insert but that's pretty lame since we support section moving via diff results.

Blocks #38

**Comment by rnystrom** [comment]
Blocks #31

**Comment by Sherlouk** [comment]
Does this relate to #291 at all?

**Comment by rnystrom** [comment]
@Sherlouk I'm not sure actually, I think the interactive move API is a little different. This API is for manually moving items.
