### ISSUE TITLE
Better Swift interop for -[IGListDiffable diffIdentifier]?

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#146]
B/c the return type of `diffIdentifier` is `id<NSObject>`, we end up with Swift that looks like this:

```swift
func diffIdentifier() -> NSObjectProtocol {
    return messageID
}
```

I'm not crazy about this. Could we change the method to `- (id)diffIdentifier`? I'd imagine we end up w/

```swift
func diffIdentifier() -> AnyObject {
    return messageID
}
```

Right? The `AnyObject` docs say:

> `AnyObject` can also be used as the concrete type for an instance of a type that bridges to an Objective-C class. Many value types in Swift bridge to Objective-C counterparts, like `String` and `Int`.

So if `AnyObject` is meant for interop w/ ObjC, and all ObjC objects respond to `hash` and `isEqual:` (which is [what the diffing algo uses](https://github.com/Instagram/IGListKit/blob/master/Source/IGListDiff.mm#L57-L67)).

cc @jessesquires for thoughts

**Comment by jessesquires** [comment]
Not quite: `id` now bridges to `Any` in Swift, so you would end up with

`func diffIdentifier() -> Any`

Then, I imagine you'd get `does not respond to selector` crashes.

Have you tried this yet?

**Comment by zhubofei** [comment]
Can we rewrite the objective-c++ in swift? Will there be a performance drop?

**Comment by rnystrom** [comment]
@zhubofei no, not for apps that don't want to bundle the Swift runtime (e.g. Instagram.app)

@jessesquires Ah, ok. I'll play around w/ this and see what happens. Really just anything bridgeable to an ObjC object is fine.

**Comment by rnystrom** [comment]
Adding to 2.0.0 milestone to make a decision. I think changing this to `id` will give us `Any` in Swift and that should be better to work w/ I think. As long as its an ObjC object that gets returned so we can call `hash` and `isEqual:` on it.

**Comment by jessesquires** [comment]
> I think changing this to `id` will give us `Any` in Swift 

Correct.

> As long as its an ObjC object that gets returned so we can call `hash` and `isEqual:` on it.

There's no way for us to guarantee this. `Any` in Swift means any *value or reference type*. If clients return a `struct` or `enum`, we'll crash when trying to message `hash` and `isEqual:`.

**Comment by jessesquires** [comment]
I think we're stuck with `id<NSObject>` (swift: `NSObjectProtocol`).

Alternative: introduce a new protocol that defines `hash` and `isEqual:`.

Then we can as for `id<IGListDiffIdentifying>` (swift: `IGListDiffIdentifying`). Swift clients could then return *any* type as long as it conforms to `IGListDiffIdentifying`.

**Comment by rnystrom** [comment]
Ugh. Dammit Swift. Sounds good then.
