### ISSUE TITLE
reagarding direct messages 

### ISSUE THREAD

**Issue by ruderumit** [Instagram/IGListKit#1502]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```
![bug](https://user-images.githubusercontent.com/80640657/111863819-b24c5480-8983-11eb-9bad-2e3fc19aa591.jpeg)

**Comment by ruderumit** [comment]
i am not able to see my direct messages

**Comment by Ziewvater** [comment]
Sorry, but we can't handle these kinds of issues here. This repo is strictly for issues with the IGListKit library. You can follow the instructions [here](https://help.instagram.com/381579045265733) to a report a problem you're having with the Instagram app.
