### ISSUE TITLE
adapter.scroll(to:supplementaryKinds:scrollDirection:scrollPosition:animated:) can not scroll to the specify item

### ISSUE THREAD

**Issue by MrKang** [Instagram/IGListKit#1504]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version: 4.0.0
- iOS version(s): iOS 14.4
- CocoaPods/Carthage version: 1.10
- Xcode version: 12.4
- Devices/Simulators affected: iPhone12(Simulators)
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

My page architecture is like this:

ViewController  with the collectionView and an adapter. There is a button in the view, tap it can scroll to the specify item in collectionView.
SectionViewController  manage the cells which have a collectionView that cannot scroll. The cells use autolayout to layout content.
ItemViewController manage the collectionView nested in cell.

My page have a lot of data. After the data loaded ,I tap the button to scroll to second last item in collectionView by `adapter.scroll(to:supplementaryKinds:scrollDirection:scrollPosition:animated:) `, the collectionView cannot scroll to correct position.

**Comment by Sheheryar-Ahmed** [comment]
did you found any solution?

**Comment by MrKang** [comment]
It seems to be caused by  main container collectionView doesn't know the accurate height of each cell at the begining. So I think the best way to solve this problem is to calculate the height of each cell(with a collectionView) first.Or you can let the main collectionView to scroll from top to bottom and scroll back to top, that can make it know size of each cell.

**Comment by Sheheryar-Ahmed** [comment]
i think this CollectionView does not have a method to scroll to a specific cell. It only allows to scroll to a specific Section only.

**Comment by MomenAShaheen** [comment]
I had the same problem but after i async with the main thread it worked .

```
DispatchQueue.main.async {
 self.adapter.scroll(to: self.scrollItem!, supplementaryKinds: nil, scrollDirection: .vertical, scrollPosition: .top, animated: false)
       }

```
