### ISSUE TITLE
How does Data updating work in IGListKit

### ISSUE THREAD

**Issue by sagarthecoder** [Instagram/IGListKit#1514]
- IGListKit version: 4.0.0
- iOS version(s): 12.0
- CocoaPods/Carthage version: 1.10.1
- Xcode version: 12.2
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:
 _______________________________________________________________________________________________________________________

Suppose you have a Horizontal collectionView ( Say **Child CollectionView**) inside a vertically scrolling CollectionView (Say **Parent CollectionView**). some items have been changed from the Child CollectionView cell but there is no change from the Parent CollectionView cell. In this case, will IGListKit update data immediately from the **Child CollectionView** cell?

**Comment by lorixx** [comment]
> will IGListKit update data immediately from the Child CollectionView cell?

Yes. Please refer to this example: https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/ViewControllers/NestedAdapterViewController.swift#L49 for more details, especially the https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/HorizontalSectionController.swift#L15 which has another ListAdapter inside the SectionController, which controls the child's item updates.
