### ISSUE TITLE
How to update all section's forcefully using IGListKit?

### ISSUE THREAD

**Issue by sagarthecoder** [Instagram/IGListKit#1516]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

- IGListKit version: 4.0.0
- iOS version(s): 12.0
- CocoaPods/Carthage version: 1.10.1
- Xcode version: 12.2
- Devices/Simulators affected: 
Reproducible in the demo project? (Yes/No):
Related issues:

...................................................................................................................................................................................................................................................

Is there any approach to update all sections forcefully?
As IGListKit is working with diff algorithm, that's why sections don't update if the identifier isn't changed.
But I locked some logos for premium. when users purchase my app, IGListKit didn't update the section instantly and didn't remove the lock icon from the Logo. Because I diff my model with Logo's name. As Logo's name isn't changed that's why sections are not automatically updated. So I need to update all sections forcefully when users purchase my app.
How can I do this?

**Comment by sagarthecoder** [comment]
edited

**Comment by DimaVartanian** [comment]
Hi! There are a couple of ways to make sure you get updates in your view.

First off, you probably wouldn't want the `diffIdentifier` to change as that indicates that this is an instance (whether updated or not) representing the same object. What you would want to change is what gets returned from `isEqualToDiffableObject`. In general, you'd want the view model (or model, if you don't have a view model) of your section to reflect its state. In this case, it sounds like you'll want to add a field to indicate whether it's locked or not in addition to the name. If your internal state is updated correctly, you should be able to call any of the existing update methods such as `performUpdatesAnimated` or `reloadObjects`.

Another alternative is to wipe out the whole collection and reload it which you can do by calling `reloadDataWithCompletion` (or `reloadData`), though this is more expensive and may not look as good.
