### ISSUE TITLE
Carthage 0.38.0 issue

### ISSUE THREAD

**Issue by dinesh547** [Instagram/IGListKit#1518]
IGListKit is not properly building on Carthage 0.38.0.
It builds the IGListKit.framework or xcframework. 
But failed to build the IGListDiffKit.framework or .xcframework.

affected version: 4.0.0

**Comment by LeXuanKhanh** [comment]
same here, can you check with carthage 0.37 ?
i found related issue in carthage too
https://github.com/Carthage/Carthage/issues/3218

**Comment by thephuongcqt** [comment]
The issue is Carthage choose the wrong workspace to build, you guys can correct that by deleting folder IGListKit/Examples before build carthage

```shell
carthage checkout "IGListKit"
rm -rf "Carthage/Checkouts/IGListKit/Examples"
carthage build "IGListKit"
```

**Comment by cntrump** [comment]
Fixed, https://github.com/Instagram/IGListKit/pull/1531
