### ISSUE TITLE
Issues in story and chats of Instagram

### ISSUE THREAD

**Issue by Jassi10000** [Instagram/IGListKit#1519]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues: I want to hightlight that in Instagram browser , am not able to use Stickers that are used to react to stories , neither am able to view the videos in the chats of a person . Are these functions only available in phone version , don't they work in browser version of Instagram

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by lorixx** [comment]
Thanks for sharing your feedback here for the IG web, we have story reactions on web but some features like stickers/video calls we don't have parity on. Please use the IG mobile app for those advanced features, by the way I had relayed your feedback to IG web team and they appreciate your feedback, please report feedback inside the mobile lab instead, let's keep the IGListKit issue tracking for the library issue only. Thanks! Closing now.
