### ISSUE TITLE
Podfile in Example is broken?

### ISSUE THREAD

**Issue by zhubofei** [Instagram/IGListKit#152]
When I try to do a `pod install ` in Example folder, I see this error message.
[!] Unable to integrate the following embedded targets with their respective host targets (a host target is a "parent" target which embeds a "child" target like a framework or extension):

- IGListKitExamples (iOS 8.0) and IGListKitMessageExample (iOS 10.0) do not use the same platform.
- IGListKitExamples (iOS 8.0) and IGListKitTodayExample (iOS 10.0) do not use the same platform.

**Comment by rnystrom** [comment]
@zhubofei are you using CocoaPods 1.1?

**Comment by zhubofei** [comment]
@rnystrom I've tried both 1.1 and 1.2beta. Neither worked.

**Comment by zhubofei** [comment]
@rnystrom #155 fixed this issue. And I do think we should add `@available(iOSApplicationExtension 10.0, *)` to Example/IGListKitTodayExample/TodayViewController.swift instead of having a different version of pod installed.
