### ISSUE TITLE
Example of using SupplementaryView

### ISSUE THREAD

**Issue by shuhrat10** [Instagram/IGListKit#153]
Can you provide example how to use SupplementaryView? Will be great if you could apply SupplementaryView to first item in Mixed data example. cc @rawlinxx, @Sherlouk

**Comment by Sherlouk** [comment]
Definitely think we need to get an example of some sort, been on my to-do list for a while
May take a look this weekend, just waiting for other pull requests to get feedback so I'm not doing  too much at once!

**Comment by shuhrat10** [comment]
I'm using IGListKit for one of my project and I need to use SupplementaryView. I will be happy see example how to use it.
