### ISSUE TITLE
Crash on iOS 15

### ISSUE THREAD

**Issue by aly-simplehabit** [Instagram/IGListKit#1530]
### General information

- `IGListKit` version: 4.0.0
- iOS version(s): iOS 15
- CocoaPods/Carthage version:
- Xcode version: 13 beta 5
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

I'm trying to run my project on iOS 15 but i have a crash in IGListKit despite it works well on the previous iOS version, do you have any update to support iOS 15 changes?
The error here:

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'the view returned from -collectionView:viewForSupplementaryElementOfKind:atIndexPath: does not match the element kind it is being used for. When asked for a view of element kind 'UICollectionElementKindSectionHeader' the data source dequeued a view registered for the element kind 'UICollectionElementKindSectionFooter'.'

**Comment by aguilarpgc** [comment]
Are you still getting this error or how did you fix it? @aly-simplehabit

**Comment by aly-simplehabit** [comment]
> Are you still getting this error or how did you fix it? @aly-simplehabit

@aguilarpgc I just registered the collectionViewCell with the Supplementary kind as below and works fine with me
collectionView.register(UICollectionViewCell.self, forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader, withReuseIdentifier: "identifier");

**Comment by aguilarpgc** [comment]
Thank you,
In my case I changed `dequeueReusableCell:` for `dequeueReusableSupplementaryView:` and it works for all `UICollectionReusableView`. Before iOS 15 was working fine
