### ISSUE TITLE
could not build Objective-C  module 'IGListKit'

### ISSUE THREAD

**Issue by dekelm8** [Instagram/IGListKit#154]
Hi 
I'm handling weird problem, i have started new project in xcode8 swift3, and in the beginning every thing works good, but after several pod installs (was need to add other pods) I'm getting the error 
**could not build Objective-C  module 'IGListKit'**
And also error:
**'IGListAdapter.h' file not found**
But after delete the **import IGListKit** line the errors disappear and project complied 

There's someone have any idea what could cause this problem?
I tried pod's version 1.0.0 & 1.1.0 xcode8 & xcode8.1 nothing help

**Comment by rnystrom** [comment]
Hey @dekelm8, bummer. I'm not totally sure what could be going wrong. Do you have an example project we could take a look at? What does your Podfile look like?

**Comment by jessesquires** [comment]
Latest CocoaPods is 1.1.1

**Comment by dekelm8** [comment]
pod file:
`platform :ios, '9.0'

target 'WallaHamal' do

  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'IGListKit'
  pod 'Alamofire', '~> 4.0'

end`

**Comment by dekelm8** [comment]
Ok so after install cocoapods 1.1.1 still not working, but after return back to 1.1.0 it's work weird (But at least its working now :) )
Thanks for the support

**Comment by rnystrom** [comment]
😕 weird. I'll go ahead and close this out for now and consider it an Xcode fluke. Will definitely keep an eye on these if they keep popping up.

**Comment by lutetium71** [comment]
Hi,
I had the same problem, weird. There's someone have any idea what could cause this problem?

Attach File is my project

[IGListDemoSwift.zip](https://github.com/Instagram/IGListKit/files/643615/IGListDemoSwift.zip)
