### ISSUE TITLE
Mark all example classes final

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#156]
We avoid subclassing on basically everything with IGListKit ([example](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.h#L36-L37)) and want to encourage good patterns in our examples too. We should use Swift's `final` on all of our example classes, I think.

**Comment by jessesquires** [comment]
👍 

lol, I've been meaning to do this

**Comment by Sherlouk** [comment]
Sorreh :(

**Comment by rnystrom** [comment]
@Sherlouk all good! I totally forgot that we can do `final` in Swift at all.
