### ISSUE TITLE
Setting content offset to hide top section (search bar)

### ISSUE THREAD

**Issue by ishabazz** [Instagram/IGListKit#158]
## New issue checklist

- [X ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 1.0.0
- iOS version(s):10.x
- CocoaPods/Carthage version:1.1.1
- Xcode version:8.1
- Devices/Simulators affected: 7Plus
- Reproducible in the demo project? (Yes/No):Yes
- Related issues: N/A

I'm trying to implement a list which initially has it's search bar hidden, which can then later be revealed by dragging down and dragging down further would implement pull-to-refresh.  How can I achieve this?

**Comment by rnystrom** [comment]
@ishabazz Couple ideas:

For the search bar, you can follow the setup we have in the [SearchViewController example](https://github.com/Instagram/IGListKit/blob/master/Example/IGListKitExamples/ViewControllers/SearchViewController.swift) with the token+section controller

For initializing the view w/ a shifted content offset, there's a couple things you could try. The simplest might be using the [scroll to item API](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.h#L179) to scroll to the _next_ item in the list. Something like this:

```swift

let adapter = // init IGListAdapter
let searchToken = NSObject()
let data: [IGListDiffable] = // array of some stuff

func objects(for listAdapter: IGListAdapter) -> [IGListDiffable] {
  return [searchToken] + data
}

func listAdapter(_ listAdapter: IGListAdapter, sectionControllerFor object: Any) -> IGListSectionController {
  // create/config section controllers and stuff
}

override func viewDidLoad() {
  super.viewDidLoad()
  adapter.scroll(to: data.first, supplementaryKinds: nil, scrollDirection: .vertical, animated: false)
}

```

There's also manually getting the cell for the search section controller (might be able to add a convenience method for this). Get the height of the cell and `collectionView.contentOffset = CGPoint(x: 0 y: -searchCell.frame.height)` or something.

**Comment by rnystrom** [comment]
@ishabazz any update here?

**Comment by jessesquires** [comment]
Going to close this due to inactivity. Feel free to re-open! 😄

**Comment by HumidBrains** [comment]
Sorry for digging up old stuff, but I just can't seem to get the hang of something closely related to this. I need to get the value of collectionView.contentOffset on an IGListCollectionView upon scrolling. I see the instructions in this issue, have checked out the SearchViewController among the IGListKit examples and the documentation points me to -listAdapter:didScrollSectionController:, but I still can't figure out how to access the contentOffset value. @rnystrom any idea? Maybe an example of how you'd access the value in the SearchViewController example?

**Comment by HumidBrains** [comment]
@rnystrom @jessesquires any input on this one?

**Comment by RishabhTayal** [comment]
Did anyone figure out how to do this?

**Comment by tamoyal** [comment]
I was debugging some pretty nasty stuff with regards to `iOS 11` and the `iPhone X` so I put together this project as a debug project. It hides a top section initially and you can pull down to reveal.

To do multiple levels, you basically need to manage the inset based on offset thresholds you set. I have this implemented but it's specific to my project so I'll just leave a few methods in the class as a teaser to get you started:

```
    private func reset() {
        currentLevel = 0
        UIView.animate(withDuration: 0.01, delay: 0.1, options: .curveEaseInOut, animations: {
            self.collectionView.contentInset.top = self.initialInset
        }, completion: nil)
    }

    private func bump() {
        UIView.animate(withDuration: 0.25, delay: 0.1, options: .curveEaseIn, animations: {
            self.collectionView.contentInset.top = self.collectionView.contentInset.top + self.levelHeights[self.currentLevel]
        }, completion: nil)
        currentLevel += 1
    }
    
    private func updateInsets() {
       initialInset = levelHeights.reduce(baseInset, -)   
        DispatchQueue.main.async {
            self.collectionView.contentInset.top = self.initialInset
        }
    }
```
