### ISSUE TITLE
Unable to install via Swift Package Manager

### ISSUE THREAD

**Issue by kartikthapar** [Instagram/IGListKit#1584]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/main/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version: 4.0.0
- iOS version(s): 16.2
- CocoaPods/Carthage version: N/A
- Xcode version: 14.3.1
- Devices/Simulators affected: 
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

Tried installing a few times and it fails with different files not being found. Examples include:

```
#import <IGListDiffKit/IGListMacros.h>
#import <IGListDiffKit/IGListDiffable.h>
```
<img width="1270" alt="Screenshot 2023-06-21 at 11 19 05 PM" src="https://github.com/Instagram/IGListKit/assets/810861/455f2333-6c4c-4bbf-ba07-09c4080cb1da">

**Comment by kartuzovmax** [comment]
I experience the same problem

**Comment by baveku** [comment]
You can use branch main for this issue. It still needs to be released.

**Comment by dmitrilosev** [comment]
Lets release it?

**Comment by VladimirAmiorkovFlutter** [comment]
Experiencing the same issue

**Comment by timisenman** [comment]
Experiencing this issue as well. Still persists.

**Comment by MehmetNuriAkyol** [comment]
Same issue here.

**Comment by TimOliver** [comment]
Hey folks! Now that v5.0 is out, SPM support should officially work now. Please try against that, and if it still occurs, please open a new issue. Thanks!
