### ISSUE TITLE
Unable to find a specification for `IGListSwiftKit`

### ISSUE THREAD

**Issue by wujingcheng7** [Instagram/IGListKit#1586]
```
  mypod.podspec
...
  s.dependency 'IGListKit'
  s.dependency 'IGListDiffKit'
  s.dependency 'IGListSwiftKit'
```

IGListKit & IGListDiffKit are both OK✅. 
But IGListSwiftKit always failed.❌

**Comment by cendolinside123** [comment]
it's look like IGListSwiftKit only available on latest version IGListkit.

actualy I need IGListSwiftKit too but I got problem when try to pod install from main branch

**Comment by TimOliver** [comment]
Hey folks! With v5.0 released, `IGListSwiftKit` is now on CocoaPods as well, so this issue should be resolved.

Please let me know if you have any more issues! Thanks!
