### ISSUE TITLE
conversion of 'long' to 'NSString * _Nullable' is disallowed with ARC

### ISSUE THREAD

**Issue by shayanaghajan** [Instagram/IGListKit#1588]
### Debug information

I'm using SPM and the main branch as it's told in the documentation but it seems like there is an issue in IGListBatchUpdateTransaction.m and the issue is `implicit conversion of 'long' to 'NSString * _Nullable' is disallowed with ARC`

**Comment by mohpor** [comment]
@shayanaghajan You should use this revision for now: `ffd51e6235c761b14c52ac657c69dd52ee7b321f`

**Comment by TimOliver** [comment]
Hey folks! Now that v5.0 is out, this hopefully should be resolved. Please let me know if it's still happening. Thanks!
