### ISSUE TITLE
Display Delegate Example

### ISSUE THREAD

**Issue by yusuftor** [Instagram/IGListKit#159]
It would be great to have an example that shows how to use the displayDelegate. This would be particularly useful for (like in Instagram) playing and stopping videos within cells. 

I also noticed you have to implement both `-listAdapter:willDisplaySectionController:`and `-listAdapter:willDisplaySectionController:cell:atIndex:` (and the same for didEndDisplaying). Both versions of the functions get called at the same time. What's the reasoning behind that?

**Comment by jessesquires** [comment]
Thanks @yusuftor ! 😄 

Agreed, we should add an example. Even if it just logs the method calls.

@rnystrom -- This is a good point. Do we need `*displaySectionController:` **and** `*displaySectionController: cell:` ?

**Comment by jessesquires** [comment]
Oh nevermind.

@yusuftor 

1. `*displaySectionController:` -- these methods provide *section*-level notifications
2. `*displaySectionController: cell:` -- these methods provide *item*-level notifications

**Comment by rnystrom** [comment]
But +1 on the display delegate example. I've got a queue of examples to get up! All very useful though.

**Comment by yusuftor** [comment]
Ahh yes, that makes sense! Thanks.

**Comment by zhubofei** [comment]
@rnystrom @jessesquires Shall we add a `@optional` directive to this protocol?

**Comment by yusuftor** [comment]
@zhubofei I also think it would be good to go through all the protocols and add `@optional` to all methods that aren't required, would save a lot of space taken up by blank functions! However, this has already been mentioned in #62.

**Comment by rnystrom** [comment]
Ya we have a pretty firm anti-`@optional` stance here in favor of the compiler catching our bugs for us.
