### ISSUE TITLE
Unable to build project using Xcode 15: Undefined symbols

### ISSUE THREAD

**Issue by jurex** [Instagram/IGListKit#1592]
## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/main/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version: This commit from main branch `ebbc90961b8162079039eaf869ed447033375a29`
- iOS version(s): 17.0
- CocoaPods/Carthage version: None
- Xcode version: 15.0
- Devices/Simulators affected: iOS 17 simulator and devices
- Reproducible in the demo project? (Yes/No): Haven't tried
- Related issues:

Hey guys, just wanted to let you know that I'm no longer able to build my project when using `IGListKit` from main branch (SPM, commit: ebbc90961b8162079039eaf869ed447033375a29), Xcode 15. Got a weird linking error with no additional information:

```
Undefined symbols:
Linker command failed with exit code 1 (use -v to see invocation)
```

After setting `-ld_classic` in `Other Linking flags` parameter in the Linking section I got this:

```
Undefined symbol: _objectsWithDuplicateIdentifiersRemoved
Linker command failed with exit code 1 (use -v to see invocation)
```

Took me several hours to track it down to this library, and after using some older commit everything start to work again. I suspect it's probably related to this commit 51a3cb140e3cbf3b9577683ffdfbf3bfc9644c8b

Cheers.

**Comment by TimOliver** [comment]
Thanks @jurex! This should have been fixed in #1591. Please let me know if you find anything else!
