### ISSUE TITLE
XCode 15 Debug iOS 14.3 iphone will crash, how to solution it ? 

### ISSUE THREAD

**Issue by esonwork** [Instagram/IGListKit#1594]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/main/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version: 4.0.0
- iOS version(s): 14.3
- CocoaPods/Carthage version: 1.14.2
- Xcode version: 15.0.0
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): No
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by TimOliver** [comment]
Hi @esonwork! Sorry about the delay.

Unfortunately, there's not a lot we can do if you don't fill out the issue with the information we need.

Version 15.0 of IGListKit is out now. I'd encourage you to try that one out and see how you go. If you're still experiencing any issues, please open up a new issue and provide us with a stack trace of the crash.

Thanks so much!
