### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by sashabaranov** [Instagram/IGListKit#1596]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/main/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

From [Apple docs](https://developer.apple.com/support/third-party-SDK-requirements/):

> Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update. Signatures are also required in these cases where the listed SDKs are used as binary dependencies.

Could you please add a privacy manifest for this library?

**Comment by cendolinside123** [comment]
> ## New issue checklist
> * [x]  I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/main/README.md) and [documentation](http://instagram.github.io/IGListKit)
> * [x]  I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
> * [x]  I have attempted to reproduce the issue and include an example project.
> 
> ### General information
> From [Apple docs](https://developer.apple.com/support/third-party-SDK-requirements/):
> 
> > Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update. Signatures are also required in these cases where the listed SDKs are used as binary dependencies.
> 
> Could you please add a privacy manifest for this library?

hello, if you on urgent need it you can pull from mine or use


```
pod 'IGListDiffKit', :git => 'https://github.com/cendolinside123/IGListKit', :branch => 'Jan/Privacy-Manifest-Support'
pod 'IGListKit', :git => 'https://github.com/cendolinside123/IGListKit', :branch => 'Jan/Privacy-Manifest-Support'

```

**Comment by cendolinside123** [comment]
https://github.com/cendolinside123/IGListKit/tree/Jan/Privacy-Manifest-Support-Main-Branch

I create it from main branch

**Comment by TimOliver** [comment]
Thanks folks! I just landed a PR that adds the privacy manifest to the project and all subsequent dependency managers!

**Comment by jiasongs** [comment]
> Thanks folks! I just landed a PR that adds the privacy manifest to the project and all subsequent dependency managers!

<img width="383" alt="图片" src="https://github.com/Instagram/IGListKit/assets/22904757/b06afc24-bd57-409e-8b6a-3346ec822ccb">

Hello, this will cause duplication of "PrivacyInfo.xcprivacy"，它应该像这样：
`s.resource_bundles = { "#{s.name}_Privacy" => ['Source/PrivacyInfo.xcprivacy'] }`
