### ISSUE TITLE
Issue with changed message and pop up notification

### ISSUE THREAD

**Issue by mefistaa** [Instagram/IGListKit#1601]
When user change some message and after that another user in chat gives reaction on this message ( that had been changed ) Pop up notification on Apple iOS 17.2.1 shows the state of the previous text(not updated with new modified message) that was before.

**Comment by TimOliver** [comment]
Hi @mefistaa! Please report issues with the Instagram app in the app itself. It'll get routed to the right team that way. Thanks!
