### ISSUE TITLE
not support indexTitle?

### ISSUE THREAD

**Issue by OtsoTieto** [Instagram/IGListKit#1603]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/main/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by TimOliver** [comment]
Hi @OtsoTieto!

I'm afraid we don't have enough information to help here. Please make sure to fill out the issue with as much information as you can.

I'll close this for now, but once you've updated the issue, please feel free to re-open. Thanks!
