### ISSUE TITLE
PrivacyInfo

### ISSUE THREAD

**Issue by snailSmile** [Instagram/IGListKit#1604]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/main/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version:4.0.0
- iOS version(s):16
- CocoaPods version:1.15.2
- Xcode version:15.1

### Debug information
The current available version 4.0.0 of Pod does not have a PrivacyInfo.list file, but the main branch does. How should we solve this problem

Looking forward to your reply

**Comment by TimOliver** [comment]
Hi @snailSmile! I'm still working out of the privacy manifest is good to go so we haven't shipped a new release yet.

If you're using CocoaPods, please use the configuration to point directly at the main branch.

```
pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git'
```

**Comment by snailSmile** [comment]
Although I am eager to obtain a new version, I fully support your decision to prioritize the integrity of your privacy list. Looking forward to a new release version.
