### ISSUE TITLE
Auto like

### ISSUE THREAD

**Issue by Yoosafalii** [Instagram/IGListKit#1606]
# New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/main/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by Yoosafalii** [comment]
I want Instagram likes

**Comment by Hackaswan** [comment]
Fager

**Comment by TimOliver** [comment]
Let's keep the issues in here on track with IGListKit. Thanks folks. :)

**Comment by isaac26347** [comment]
https://www.instagram.com/reel/DGSXdyHOKYx/?igsh=MWkxbHZzdHh4cWV2dQ==

**Comment by isaac26347** [comment]
Jxjjxxjx
