### ISSUE TITLE
UICollectionElementKindSectionHeader

### ISSUE THREAD

**Issue by shuhrat10** [Instagram/IGListKit#163]
I need to add CollectionView to UICollectionElementKindSectionHeader. How can I pass object and then control it from there? I can't make it sticky header if I'm putting this CollectionView to the cell.

**Comment by rnystrom** [comment]
This might be more helpful once we push an example for #153, I think it'll make more sense. Maybe we should move this there?

It sounds like you're trying to configure a supplementary view based on the `object`, right?

**Comment by shuhrat10** [comment]
yes, and I want to pass array object with items and then render cells in
UICollectionView located in UICollectionElementKindSectionHeader.

**Comment by rnystrom** [comment]
Take a look at #169 for an example of using header supplementary views. Will be merged soon!

**Comment by shuhrat10** [comment]
Great example, I did the same way a few days ago.
I think I will share my example later this month.

Thank you for providing this example in a short time.

**Comment by jessesquires** [comment]
Sounds like we're good here 👍

**Comment by shuhrat10** [comment]
Yep
