### ISSUE TITLE
Add a -[IGListAdapter visibleObjects] API

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#164]
It's easy to get the visible objects, but a little cumbersome. Would be a nice convenience API to be able to see what all items are currently visible.

**Comment by rnystrom** [comment]
Removed starter, adding this internally

**Comment by jessesquires** [comment]
@rnystrom - don't forget a changelog

**Comment by rnystrom** [comment]
@jessesquires whoops good call
