### ISSUE TITLE
Can't make space between section and cells

### ISSUE THREAD

**Issue by dekelm8** [Instagram/IGListKit#166]
Hi 
How i can make spaces between sections?
i'm using collectionview on storyboard, but inset parameters not working, there's special way to do it with IGListKit?

**Comment by rnystrom** [comment]
Hey @dekelm8, try changing the `inset` of your section controller, like:

```swift
class MySectionController: IGListSectionController, IGListSectionType {
  override init() {
    super.init()
    inset = UIEdgeInsets(top: 0, left: 0, bottom: 15, right: 0)
  }
}
```

Are you setting the insets on `UICollectionViewFlowLayout`? We had a suggestion to get global section insets working once, maybe we should revisit that.

**Comment by dekelm8** [comment]
Thanks that's work.
Really want to say thanks for the great support guys, It's really feel like IG team are full committed for this amazing framework
Thanks Again
