### ISSUE TITLE
Apple LLVM 8.0 error

### ISSUE THREAD

**Issue by TongBig** [Instagram/IGListKit#170]
clang: error: no such file or directory: '/Volumes/T/swift3.0/IGListKit/Source/Internal/NSIndexSet+PrettyDescription.m'
clang: error: no input files

**Comment by rnystrom** [comment]
@TongBig can you provide a little more detail here? Is this the sample app? Are you importing master to a project?

**Comment by TongBig** [comment]
Run the demo (IGListKitExamples) error, prompt can not find "NSIndexSet + PrettyDescription. M" file

**Comment by zhubofei** [comment]
@rnystrom The last commit removed "NSIndexSet + PrettyDescription.m" from source. Might need to `pod install` again in the Example folder to remove the reference.

**Comment by rnystrom** [comment]
@zhubofei ah yup! Looks like Travis runs `pod install` each time so the build wont fail. I might tweak that a little bit. Got it covered in #169. Looks like we have the answer so I'm going to close this.
