### ISSUE TITLE
Issue  with UICollectionReusableView

### ISSUE THREAD

**Issue by shuhrat10** [Instagram/IGListKit#180]
I noticed, when I'm using UICollectionReusableView from storyboard I'm getting additional view on top of mine. This second UICollectionReusableView is not allowing me to use gesture correctly.

![1](https://cloud.githubusercontent.com/assets/62485/20164436/eb4375d6-a6d2-11e6-96ba-4df81fd662b9.jpg)

**Comment by rnystrom** [comment]
@shuhrat10 What is the `UICollectionReusableView` for? A supplementary header view? Your storyboard looks like there's an extra view put in the collection view. Is that a prototype cell or an actual view?

**Comment by shuhrat10** [comment]
Header and Footer is UICollectionReusableView. I noticed when you added header or footer to CollectionView via storyboard and then debug this ViewController via "Debug view hierarchy" you will see addition UICollectionReusableView. I don't figured out yet why is it happening. It's not issue in IGListKit. @rnystrom

**Comment by rnystrom** [comment]
Hmm, ya if its not a prototype cell I bet the view is actually being created and inserted into the collection view's hierarchy. You probably want to create a prototype cell (it'll be `UICollectionViewCell`) and then use that cell class+identifier for your supplementary views.

If this isn't an issue w/ IGListKit, can we close this issue?

**Comment by jessesquires** [comment]
👍

**Comment by shuhrat10** [comment]
When you start using SupplementaryView for header or footer, xCode will added one more to the view hierarchy. I think it's a bug in xCode.

![bug](https://cloud.githubusercontent.com/assets/62485/20186313/78f51302-a73d-11e6-9215-9ef9d8078810.jpg)

So if you want change zIndex SupplementaryView in order to hide behind the cell, don't do it. Instead, change zIndex for the cell.

Yes, you can close this ticket.
