### ISSUE TITLE
Regen documentation before 2.0.0 cut

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#181]
Creating a reminder issue to regen docs before cutting 2.0.0.

@jessesquires do we want to change the style? Or are we happy w/ current: https://instagram.github.io/IGListKit/

**Comment by jessesquires** [comment]
What do you mean, style? The theme?

I think it's good for now. 👍 We can always update visuals later.

Let's get this to 100% too. Currently at 79%. Actually, I wanted to take a full pass at docs to review before `2.0.0`. Will try to do that soon.

Also be sure to get the latest version of `jazzy`.

**Comment by jessesquires** [comment]
Mind if I steal this issue?

**Comment by rnystrom** [comment]
Yup theme, that's what I meant. Other option is the "full width" which is kind of nice http://reduxkit.github.io/ReduxKit/master/

++ doc coverage to 100%. Let's do it. If you want to knock some out go for it, happy to help too, and we can `starter-task` parts.

**Comment by zhubofei** [comment]
Have to say Full Width looks great!

**Comment by zhubofei** [comment]
@jessesquires Shall we tweak the CSS a little bit? The sidebar cuts off the class name like this on my screen. <img width="235" alt="screen shot 2016-11-21 at 7 35 53 pm" src="https://cloud.githubusercontent.com/assets/770482/20506396/c05a8776-b021-11e6-865b-05d39e81c0f8.png">

**Comment by jessesquires** [comment]
@zhubofei -- we'll probably keep the jazzy defaults for now 😄 

i'd be open to suggestions after 2.0 ships though 👍
