### ISSUE TITLE
Refactor unit test helper macros and functions into single file

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#183]
Lots of stuff that we use in multiple places that I think should be cleaned up throughout the test suite

- https://github.com/Instagram/IGListKit/blob/master/Tests/IGListAdapterE2ETests.m#L22-L25
- https://github.com/Instagram/IGListKit/blob/master/Tests/IGListBatchUpdateDataTests.m#L25-L39
- https://github.com/Instagram/IGListKit/blob/master/Tests/IGListDiffTests.m#L25-L28

We also have a similar pattern throughout our tests:

- Create window, adapter, collection view
- Setup data source before testing
  - https://github.com/Instagram/IGListKit/blob/master/Tests/IGListAdapterE2ETests.m#L64-L69

Do we create our own testing suite class? Or maybe just a bunch of setup helper functions? Or not worry about it?

**Comment by jessesquires** [comment]
> Do we create our own testing suite class?

:100: Yes, we should. Lowers barrier for writing tests. Less boilerplate == more likely to write tests. :smile:
