### ISSUE TITLE
Multi-selection

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#184]
Been asked this quiet a lot internally. It's easy to do but different than traditional `UICollectionView`. The whole "deselect" API is _not_ what we want to be using for this.

**Comment by cdoncarroll** [comment]
I obviously don't have the proper context into why we don't want to use `UICollectionView`'s deselection API. Can you elaborate?

**Comment by rnystrom** [comment]
@cdoncarroll It's not a bad API, but `UICollectionView` does a lot of (private) state preservation for you, and all the state it saves revolves around "index paths". 

I whipped up a sample project illustrating a few of these ideas: [UICollectionViewDeselection.zip](https://github.com/Instagram/IGListKit/files/586510/UICollectionViewDeselection.zip)

Where you have `-[UICollectionViewCell selected]`, we could have `-[IGListSectionController selected]` but what if only 1 of 2 cells in the section controller were actually selected? There's also `-[UICollectionView indexPathsForSelectedItems]`. Again we could do `[IGListAdapter selectedObjects]` but we have the same "1 of 2 cells in the section selected" problem.

Then there's `reloadData` which nukes selection state. I'm not sure what we do there. Maybe we internally track cell selection and restore it when cells are used? Possible. However if we do that, now we're out of sync w/ `-[UICollectionView indexPathsForSelectedItems]`, so we replace that w/ our own tracking.

Also you have to override `-[UICollectionViewCell setSelected:]` to change a cell's appearance to use custom hide/show selectors. You can use `-[UICollectionView selectedBackgroundView]` but I don't imagine that'll be super useful.

Putting this all together, we end up reimplementing the selection API and introduce some weird `UICollectionView` behavior (e.g. in the example, select a cell, tap "Reload", now try deselecting the cell. No select or deselect methods are called. Dunno why.).

In the end we do a lot of complicated things and possibly introduce some weird behavior all to save clients tracking state themselves, which shouldn't be hard.

**Comment by kronik** [comment]
@rnystrom so what's the right way of managing selected cells (setting a state, getting a list of selected) for IGListCollectionView?

**Comment by rnystrom** [comment]
@kronik I'll make sure to get an example up, but for now probably manually tracking selection in the section controllers. The trickier part is then getting a list of selected stuff. There are two options that I've seen work:

- At the VC level, iterate all of your section controllers. Check for your selectable SC type, then check if the SC is marked as selected (again using your custom property)
- Create a delegate on the section controller that forwards select/deselect events up to the VC
  - IMO this is more tedious

I'd probably go w/ the first option.

However @cdoncarroll and I were chatting a lot last week about this and we might try to find a way to bake support into IGListKit, but to fully support selection it'll be a bigger change, so nothing concrete planned.

**Comment by kronik** [comment]
@rnystrom Got it. Thanks.
