### ISSUE TITLE
Unit test IGListReloadDataUpdater

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#185]
https://coveralls.io/builds/8776307/source?filename=Source%2FIGListReloadDataUpdater.m#L41

We probably just need to use this in a few more `IGListAdapterTests` tests, I think? This updater does everything synchronously w/ `reloadData`, so covering the remaining areas should be simple.

**Comment by zhubofei** [comment]
@rnystrom Any suggestions on how to do this one?
