### ISSUE TITLE
Test -[IGListAdapter sectionForObject:]

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#190]
https://coveralls.io/builds/8776307/source?filename=Source%2FIGListAdapter.m#L313

The underlying call to the map is tested, but we need this method covered so the public API does not regressed if changed.

**Comment by zhubofei** [comment]
@rnystrom Also may need to change return type from NSUInteger to NSInteger for swift.

**Comment by rnystrom** [comment]
I'm putting up a PR for this test right now, I'll include that!
