### ISSUE TITLE
Unit test scroll events forwarding

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#193]
https://coveralls.io/builds/8776307/source?filename=Source%2FIGListAdapter.m#L640

We also don't have any tests around scrolling events forwarded to:

- Section controllers
- The `scrollViewDelegate`

**Comment by zhubofei** [comment]
@rnystrom We have to use UI Testing for this, right?

**Comment by rnystrom** [comment]
@zhubofei shouldn't have to, we should be able to mock the protocol and verify that it receives events. Also have to confirm that the section controllers (that are "on screen") receive the events.
