### ISSUE TITLE
Travis bug

### ISSUE THREAD

**Issue by zhubofei** [Instagram/IGListKit#195]
Each time Travis finishes his work, Coverall posts a message. So we always end up with two same messages from Coverall 😂. Something wrong with the setup maybe?

**Comment by rnystrom** [comment]
@zhubofei The settings are basically "post" or "don't post" when things change. We can disable posting entirely but then we have to manually check when coverage increases/drops.

Each commit/push triggers a build. I've found that if I just push once w/ each change it's not as noisy, vs pushing often will trigger a build-per-push (which results in Coveralls posting for each build).
