### ISSUE TITLE
Change NSUInteger to NSInteger in public API

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#200]
This makes interop w/ Swift tricky. Let's audit and swap all `NSUInteger` to `NSInteger` in the public headers.

e.g. https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.h#L160

**Comment by jessesquires** [comment]
fixed in e2fbb6867056cbaab07acd076a995ad95c5b1dbc
