### ISSUE TITLE
Write a migration guide for 1.0 to 2.0

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#221]
Add:

`/Guides/migration.md`

**Comment by rnystrom** [comment]
I should add a "writing good diff identifier + equality" guide

**Comment by jessesquires** [comment]
Ooohhhh 😍  👍

**Comment by jessesquires** [comment]
Another idea:

Extract the `README` tutorial stuff into `/Guides/getting_started.md` and link to that in the `README`.

With all of this, we can then pass `/Guides/` to `jazzy` and have everything show up in the sidebar docs. 🎉
