### ISSUE TITLE
isEqual function different on simulator vs on device

### ISSUE THREAD

**Issue by yusuftor** [Instagram/IGListKit#226]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 1.0 master branch
- iOS version(s): 10
- CocoaPods/Carthage version: latest
- Xcode version: 8
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No): No
- Related issues:

Since the change of the `-isEqual:` function to `-isEqualToDiffableObject:`, I'm having a problem running on the device vs running on the simulator. The simulator correctly uses the new `-isEqualToDiffableObject:` function. However, running the exact same code and switching to a device produces the following error:

`Method 'isEqual(toDiffableObject:)' has different argument names from those required by protocol 'IGListDiffable' ('isEqual')`

If I change back to the old `-isEqual:` method, then it's completely fine... Until I run again on the simulator as it wants me to use the new method.

Is this an issue with IGListKit or is there something wrong with my project?

**Comment by jessesquires** [comment]
Hey @yusuftor 😄 

Sounds like you probably need to clean and re-build?

**Comment by rnystrom** [comment]
Looks like this might be a Swift bug. Agree cleaning should help

https://bugs.swift.org/browse/SR-1208

https://github.com/apple/swift/commit/e003e5e099b9cf79b581560ff9d494a7722fc465

**Comment by jessesquires** [comment]
Ugh. 

Are there more bridging features we can use? I vaguely remember some kind of "refined for Swift" ObjC macro or something...

**Comment by jessesquires** [comment]
Oh also -- can we repro in the demo projects?

**Comment by rnystrom** [comment]
> can we repro in the demo projects

I never ran into this, but I didn't run on device after refactoring. I still have the demo on my phone I'll run and see what happens.

Just ran it: no repro. Hopefully a one-off?

**Comment by yusuftor** [comment]
Solved it. I cleaned the build folder, but then that gave me a lot of other issues to do with Cocoapods. After disintegrating/installing cocoapods a few times it seemed to disappear. Weird, but I can close this issue now!

**Comment by jessesquires** [comment]
Thanks @yusuftor !
