### ISSUE TITLE
Unit test -[IGListAdapter scrollToItem:...]

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#23]
This method is only tested manually and not backed by any type of automation. We should get a test up to make sure that all conditions pass:
- Vertical/horizontal scrolling
- No supplementary view
- Single supplementary view
- Multiple supplementary views
- Empty feed
- Item not in feed

(flagging as a bug since unit test coverage should be a requirement)

**Comment by yusuftor** [comment]
I'm trying to use this -[IGListAdapter scrollToObject:...] function (I assume it's the same one you're talking about?). I'm testing it in my view and it just doesn't scroll to any item at all. My code is:

`adapter.scroll(to: model.content.last, supplementaryKinds: nil, scrollDirection: .vertical, animated: true)`

Where model.content.last is an object being displayed in a section.

**Comment by zhubofei** [comment]
@rnystrom Can you change the bulleted list into a task list 🤔. So that we can work these out in separate PRs.

**Comment by rnystrom** [comment]
@yusuftor could you create a new issue for this with an example?

@zhubofei sure thing! That will make it way easier to track.

**Comment by yusuftor** [comment]
@rnystrom False alarm! I realised that I needed to unwrap model.content.last and then it worked. However, I have noticed that it scrolls the item to the top of the view, with no option to specify whether you want it at the top or at the bottom. I'll create a new issue with that as a suggestion.

**Comment by zhubofei** [comment]
@rnystrom @jessesquires We can close this one 😏.
