### ISSUE TITLE
RFC: Support NSCollectionView

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#25]
Suggestion from an attendee of [iOSDevUK](http://iosdevuk.com/) where we announced the project. Wanted to record it.

I've never done any macOS work before, so I'm not sure how difficult this would be. But I know that `NSCollectionView` was modernized recently to mimic `UICollectionView`.

Open for discussion.

**Comment by zhubofei** [comment]
Seems doable if we only support macOS 10.11+

**Comment by zhubofei** [comment]
@rnystrom Since there is no `typealias` in obj-c (we can use it in swift to switch type between different OS, I think it is a very elegant way to do cross-platform support), I think we will need a lot of
```
#if TARGET_OS_IOS
      xxxx
#elif TARGET_OS_MAC
      xxxx
#endif 
```
To switch between NSClasses and UIClasses. I'm not sure if you want this in the source code.

**Comment by zhubofei** [comment]
If you are OK with it, I think I can go on and work on this one.

**Comment by rnystrom** [comment]
@zhubofei let's hold on this for now, not sure its something we want to fully support yet. Issue is open as a discussion point more now than anything.

**Comment by jessesquires** [comment]
Relevant to this issue: #235

**Comment by insidegui** [comment]
Just FYI: I tried doing what @zhubofei suggested but there are some very significant differences between `NSCollectionView` and `UICollectionView`. On macOS, collection view items are view controllers, not views, just to name one.

There are also major differences regarding view controllers, views and layouts on macOS which make porting the UI part of the project kind of hard. It is definitely doable, but will take a lot of work.

**Comment by zhubofei** [comment]
@insidegui I would say maybe it's better to build a side project specifically for macOS and keep this repo just for iOS&tvOS.

**Comment by zhubofei** [comment]
@insidegui Wow, I just found out that you're the author of this awesome [article](https://medium.com/@guilhermerambo/why-uikit-for-macos-is-important-ff4e74a82cf0#.92xuy9g2j). If UXKit is to be release in the near future, it will definitely be a good choice for this.

**Comment by rnystrom** [comment]
@insidegui awesome info, ya I have 0 experience w/ `NSCollectionView`. I'm going to close this out then since it sounds like this is would be pretty out of scope of what we want to achieve. +1 @zhubofei on someone spinning up a new project to do this maybe.
