### ISSUE TITLE
Create new IGListDiffable + isEqual guide

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#253]
Copy @rnystrom's internal post on *"IGListDiffable and good -isEqual: methods"* into a new guide.

https://fb.facebook.com/groups/505465172835436/permalink/1208294839219129/

**Comment by jessesquires** [comment]
How about

`/Guides/Conforming to  IGListDiffable.md`

(note: unfortunately we need spaces in the filename for jazzy to list it correctly in the sidebar)

**Comment by HowardCsie** [comment]
Could you please briefly explain the guide? Though reading the comment, i felt a little bit confused.
Or I just wait for 2.0 ?

**Comment by jessesquires** [comment]
@HowardCsie -- we'll be posting this soon!
