### ISSUE TITLE
Different with ReactJS's diff algorithm

### ISSUE THREAD

**Issue by keywind** [Instagram/IGListKit#255]
This is a wonderful library, I just want to know what's the difference of the diff algorithm between IGListKit and ReactJS's virtual dom.

I use Componentkit for one of my apps, so I imagine if I could apply this diff algorithm to ComponentKit and make it automatically change just using reload.

**Comment by rnystrom** [comment]
First off, thanks for the compliment! We worked and continue to work really hard on this. Really appreciate it.

Regarding the ReactJS diff algo, you know I'm not actually sure. I should reach out to whoever maintains is here and do some idea sharing.

I think the ComponentKit reloading is really interesting too. I'm only barely familiar w/ the table/collection infra. On the main Facebook app we have our own abstractions for handling data source changes, but I think we have to take those changesets and tell ComponentKit to apply the changes (vs the infra finding the changes itself).

cc @ocrickard (who worked on IGListKit and maintains ComponentKit)

**Comment by keywind** [comment]
> but I think we have to take those changesets and tell ComponentKit to apply the changes (vs the infra finding the changes itself)

Yes you get the point, this is why I want to apply the diff algo to ComponentKit
