### ISSUE TITLE
Getting started page not found

### ISSUE THREAD

**Issue by pableiros** [Instagram/IGListKit#256]
I tried to find some documentation to getting started and the Getting Started page returns me a http 404 error.

<img width="785" alt="captura de pantalla 2016-11-24 a la s 10 02 33" src="https://cloud.githubusercontent.com/assets/5769029/20606290/2d9bacae-b22d-11e6-85be-de791e0bde50.png">

Link:
https://instagram.github.io/IGListKit/Guides/Getting%20Started.md

**Comment by zhubofei** [comment]
https://instagram.github.io/IGListKit/getting-started.html

**Comment by pableiros** [comment]
This is how I get that link.
First I click here in the release page:

<img width="786" alt="captura de pantalla 2016-11-24 a la s 10 14 34" src="https://cloud.githubusercontent.com/assets/5769029/20606566/08c96acc-b22f-11e6-95c8-b7a03a922d99.png">

Then I click on the documentation page the Getting Started link:

<img width="707" alt="captura de pantalla 2016-11-24 a la s 10 14 47" src="https://cloud.githubusercontent.com/assets/5769029/20606580/1e08ea66-b22f-11e6-870c-188dafa7009a.png">

And finally I get the http 404 error

**Comment by rnystrom** [comment]
🤔 I wonder if this is a Jazzy issue? The sidebar has the correct link

`https://instagram.github.io/IGListKit/getting-started.html` vs the link in the readme that 404s which is `https://instagram.github.io/IGListKit/Guides/Getting%20Started.md`

+ @jessesquires

**Comment by jessesquires** [comment]
lol

The README link is relative, so it works when clicked from the README.

jazzy generates the html docs, so then that relative link is broken. will fix.
