### ISSUE TITLE
Center aligned flow layout

### ISSUE THREAD

**Issue by MarvinNazari** [Instagram/IGListKit#263]
Hi thanks for this amazing library! loving it so far, the only issue that i have right now is that i need a center aligned collection view layout, is there any way we could add some sort of alignment to the new `IGListGridCollectionViewLayout` so that we could have both left and center alignment?

**Comment by zhubofei** [comment]
@jessesquires I can take on this, if you guys approve this api.

**Comment by Sherlouk** [comment]
@zhubofei Are you still interested in working on the extra alignment ability of your grid layout?

**Comment by zhubofei** [comment]
@Sherlouk Yes, I'm gonna post a PR by the end of this week 😊.

**Comment by rnystrom** [comment]
Closing since we have a new layout inbound in #450. Once that's landed we can revisit if this is still needed.
