### ISSUE TITLE
Create private IGListStackedSectionController method to get relative index

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#272]
There are so many calls where we get the child section controller offset and add the index:

https://github.com/Instagram/IGListKit/blob/master/Source/IGListStackedSectionController.m#L164-L165

There should be a method opposite of [localIndexForSectionController:index:](https://github.com/Instagram/IGListKit/blob/master/Source/IGListStackedSectionController.m#L106-L110) that _adds_ the offset and index.

Need to refactor all places we do `index + offset` to use this method instead.

**Comment by bmeverett** [comment]
Can I try this?

Do you have a name for the method? `localPlusOffsetForSectionController:index`

So [this](https://github.com/Instagram/IGListKit/blob/master/Source/IGListStackedSectionController.m#L196)
would become `atIndex:[self localPlusOffsetForSectionController:sectionController index:index]`

**Comment by jessesquires** [comment]
@bmeverett - Definitely! 🙌 

Let's name it `offsetIndexForSectionController: localIndex:` ?

@rnystrom - Not really sure. What does "localIndex" mean anyway?

**Comment by jessesquires** [comment]
Err, maybe :`relativeIndexForSectionController: fromLocalIndex:`

@bmeverett

**Comment by rnystrom** [comment]
+1 to @jessesquires latter naming suggestion

@bmeverett all you!

**Comment by bmeverett** [comment]
@rnystrom will I have to do a force push after rebase then? Here's what the log and status look like
<img width="727" alt="screen shot 2016-12-02 at 6 31 15 am" src="https://cloud.githubusercontent.com/assets/3941006/20832621/30d9ea2a-b859-11e6-9ae4-95b753f9f3fc.png">


@jessesquires I pushed another branch [t2](https://github.com/bmeverett/IGListKit/tree/t2) and it looks like it stills has your commit in it.

Sorry guys, but what should I do?
