### ISSUE TITLE
Unblock Travis

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#276]
Something is going on with Travis as of yesterday. Doesn't seem like any builds are passing, lots of hanging.

https://travis-ci.org/Instagram/IGListKit/builds/180498817 is taking over 3 hours with about half of the builds succeeding in around a minute.

**Comment by jessesquires** [comment]
Yep -- known issue. Travis is having some problems:

https://www.traviscistatus.com/incidents/nq0sf0srvx8s
