### ISSUE TITLE
Init overrides storyboard settings in IGListCollectionView. Should -[IGListCollectionView commonInit] be removed?

### ISSUE THREAD

**Issue by dcaunt** [Instagram/IGListKit#277]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 1.0.0
- iOS version(s): 10.1
- CocoaPods/Carthage version:
- Xcode version: 8.1
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues: #92 

The next release of IGListKit will support storyboards, but at present [-[IGListCollectionView commonInit]](https://github.com/Instagram/IGListKit/blob/f2a9d93be84e7ea23ec85dddbb3e2421215a6eec/Source/IGListCollectionView.m#L15-L16) sets a couple of options which override those provided by the storyboard.

I can open a PR to remove these if appropriate. The IB default appears to be white, but the example ViewControllers would need updating to explicitly set a background color in code.

**Comment by jessesquires** [comment]
Ah, good find @dcaunt ! 💯 

Yeah, let's do that and remove `initWithCoder:`
