### ISSUE TITLE
Fix "tbd" revisions in changelog just before 2.0

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#278]
Reminder for myself

**Comment by jessesquires** [comment]
fixed in #292

**Comment by Sherlouk** [comment]
@jessesquires @rnystrom 

Few other things in changelog that don't have links! :)

> Added -isFirstSection and -isLastSection APIs to IGListSectionController

https://github.com/Instagram/IGListKit/commit/394760081c7c2daa5ae6c18e00cdeaf2b67e22c1

> Added an additional initializer for IGListSingleSectionController to be able to support single sections created from nibs. An example can be found here.

https://github.com/Instagram/IGListKit/pull/56
https://github.com/Instagram/IGListKit/commit/ce4b851da343940513a074342fab6f5a7e67125d

> The default NSObject<IGListDiffable> category was removed and replaced with NSString<IGListDiffable> and NSNumber<IGListDiffable> categories. All other models will need to conform to IGListDiffable.

https://github.com/Instagram/IGListKit/commit/316fbe2b8b2508b58a0f38387c3a343b9c37e282
