### ISSUE TITLE
IGListStackedSectionController deselectItemAtIndex:sectionController:animated bug

### ISSUE THREAD

**Issue by jeffbailey** [Instagram/IGListKit#279]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: Current master
- iOS version(s): 10.1
- CocoaPods/Carthage version:
- Xcode version:8.1
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):No
- Related issues:

The current implementation is this:
```
- (void)deselectItemAtIndex:(NSInteger)index sectionController:(IGListSectionController<IGListSectionType> *)sectionController animated:(BOOL)animated {
    const NSUInteger localIndex = [self localIndexForSectionController:sectionController index:index];
    [self.collectionContext deselectItemAtIndex:localIndex sectionController:self animated:animated];
}
```

 But I believe the correct implementation is:
```
- (void)deselectItemAtIndex:(NSInteger)index sectionController:(IGListSectionController<IGListSectionType> *)sectionController animated:(BOOL)animated {    
    const NSUInteger relativeIndex = [self relativeIndexForSectionController:sectionController fromLocalIndex:index];
    [self.collectionContext deselectItemAtIndex:relativeIndex sectionController:self animated:animated];
}
```

The index being passed to this method is already a local index, so it needs to be converted to an index relative to the Stacked Section Controller.

**Comment by rnystrom** [comment]
Yikes, yup! Spot on. Definitely a bug w/ stacked section controller.

**Comment by jeffbailey** [comment]
Great. IGListKit is brilliant BTW.  Thanks for make it open source.

**Comment by rnystrom** [comment]
@jeffbailey that means the world to me
