### ISSUE TITLE
Jazzy Guide Formatting

### ISSUE THREAD

**Issue by Sherlouk** [Instagram/IGListKit#280]
Super minor but for some reason the formatting isn't working on the migration guide when viewed via Jazzy (it's fine when viewed via GitHub)
Picture of what I'm seeing: [image](https://cloud.githubusercontent.com/assets/15193942/20867194/8be47de8-ba36-11e6-858e-a04d61347e0b.png)

The IGListDiffable guide looks fine, and has similar code formatting?

## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

**Comment by rnystrom** [comment]
Good eye, I bet there is supposed to be a newline between the header and ```
