### ISSUE TITLE
[Example] Horizontal scrolling Issue

### ISSUE THREAD

**Issue by mobilinked** [Instagram/IGListKit#284]
### Steps
- Adding `layout.scrollDirection = .horizontal` below line 24 in the SelfSizingCellsViewController.swift 

### Issue
- When testing Self-sizing feature
- Scroll to end of right, you will find the scrollbar flashed and the scroll bar position is not continous.

**Comment by rnystrom** [comment]
@mobilinked this is almost certainly an issue with self-sizing cells and `UICollectionView`, not IGListKit. Our goal is to be compatible with all types of layout and sizing strategies, but we aren't in the business of supplying them. Not sure we can do much about this 😞
