### ISSUE TITLE
Unit test background color on IGListCollectionView

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#299]
We landed a couple commits to avoid changing the background to white when using storyboards or `UIAppearance`:

- https://github.com/Instagram/IGListKit/commit/80916636eca9472ed1b3c3129cee07028f36ca5d
- https://github.com/Instagram/IGListKit/commit/394e6c827bf382723057de42e2296af595ce30e3

However they are only tested w/ eyeballs. We should add unit tests to prevent regressions.

**Comment by rnystrom** [comment]
@jessesquires think this needs to be part of 2.0.0? Or since 2.0.0 is stable w/ this feature we just add the tests in whenever we can get to it.

cc original authors @jeffbailey and @dcaunt

**Comment by jessesquires** [comment]
+1 for doing tests now.

also, need to update CHANGELOG?

**Comment by jeffbailey** [comment]
I'll write the tests.  I've got dinner plans tonight, but can get it done by Thursday night if that works.

**Comment by rnystrom** [comment]
@jessesquires not sure if we should update the changelog since this fixed a feature we added in 2.0.

**Comment by jessesquires** [comment]
done in b9ede32f5be71bed87b0d82c3cb7e50daa6444ea
