### ISSUE TITLE
Add a UICollectionViewLayout similar to flow layout that doesn't newline sections, a section-based grid layout

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#3]
If you use `UICollectionViewFlowLayout` and your item controllers return individual cells that should be in a grid (see Instagram Explore tab), they will stick vertically in new rows instead of fitting into rows/columns as if they were all in the same section.

We have this internally for our Explore product (which uses `IGListKit`) but the layout is pretty specific for that instance. It'd be amazing to have a general layout as part of the framework.

**Comment by zhubofei** [comment]
@rnystrom Do you mean we should let cells from different sections be in the same row if width permitted?

**Comment by jessesquires** [comment]
@zhubofei - this would be a "section-based" grid layout.

If you have square thumbnail cells with 1 item per section and use `FlowLayout`, each cell will be in its own section. (So you would have a lot of whitespace on the right.)

This layout would allow you to have a grid like Photos.app, except instead of 1 section with many items, it would be many sections with 1 item.

**Comment by jessesquires** [comment]
I think "row" implies "full-width" -- these cells would **not** be full-width, but a grid like Photos.app with 1 cell in each section 😊

**Comment by rnystrom** [comment]
@zhubofei yup what @jessesquires. Think a grid layout where each column is a different section. We might be able to cleanup and open one of our layouts but they are all pretty specific. I've seen some other open source layouts that do this, but haven't taken the time to find "the one".

If there's a great layout out there we could just link to and recommend they use it, but bundling one w/ `IGListKit` would def be nice.

**Comment by Sherlouk** [comment]
For what it's worth I've previously used this:
https://github.com/rhodgkins/RDHCollectionViewGridLayout

Been a while since I looked but it used to work very well!

**Comment by zhubofei** [comment]
@rnystrom @jessesquires  I created a half-baked flow layout. Posted a PR just want to make sure that I am on the right track.

**Comment by zhubofei** [comment]
@Sherlouk Unfortunately, RDHCollectionViewGridLayout seems only support fixed width & height.

**Comment by zhubofei** [comment]
@jessesquires For this layout, can I assume that each section only has one item?

**Comment by jessesquires** [comment]
> For this layout, can I assume that each section only has one item?

Yes. In fact, one thing we want here is a "Grid Layout" specifically.

@rnystrom -- was your intent here for a grid, or just a "no newline", section-based layout.. ?

in any case, it would probably be simpler to start with a grid (cells fixed width/height)

**Comment by zhubofei** [comment]
<img width="618" alt="screen shot 2016-10-31 at 4 38 08 pm" src="https://cloud.githubusercontent.com/assets/770482/19870792/810d14c0-9f88-11e6-8d19-05bcf5a6b1e3.png">
@jessesquires The layout I wrote dose something like this. It is too much?

**Comment by jessesquires** [comment]
@zhubofei 😍 💯
