### ISSUE TITLE
Move emptyView API to a property on IGListAdapter

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#30]
There's really no need for this to be a required method on `IGListAdapterDataSource`. It could simply be a property, defaulted to `nil`. When you set the property we use it when the adapter is empty.

Not sure if we need to bother what happens if you set the property _after_ everything has been updated.

**Comment by tunidev** [comment]
@rnystrom The empty view in conflict when you using something like this: 
https://github.com/aschuch/StatefulViewController

so I hope that wether you provide a "Loading", "Error" and "Empty" views or just remove "emptyView" or keep it optional

**Comment by weyert** [comment]
How would it conflict with it? I thought `StatefulViewController` doesn't mess around with the `UICollectionView`?

**Comment by tunidev** [comment]
@weyert sorry for not being clear, I mean when I will use `StatefulViewController` I will not need the `emptyView` of `IGListKit`

**Comment by weyert** [comment]
Yes, so you can just return `nil` there?

**Comment by tunidev** [comment]
@weyert  sure, but it will be confusing to have two different logic to handle empty state, hence the suggestion to make it optional like suggested in the initial issue

**Comment by weyert** [comment]
I think the idea is to switch away from optional's in the code base (@rnystrom correct?) so maybe it's better to have a default implementation which returns nil
