### ISSUE TITLE
IGListDisplayDelegate methods are not called when section controller displays only supplementary views without cells.

### ISSUE THREAD

**Issue by almas73** [Instagram/IGListKit#300]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: latest on master
- iOS version(s): 10.1
- Reproducible in the demo project? : [yes with minor modifications](https://github.com/almas73/IGListKit/commit/3478c9d094868c0047495f1df05ae4f0b8596806)

With the current implementation non of the display delegates are called when number of items is equal to 0. It makes sense that these two methods are not called:

```
- (void)listAdapter:(IGListAdapter *)listAdapter willDisplaySectionController:(IGListSectionController <IGListSectionType> *)sectionController
               cell:(UICollectionViewCell *)cell
            atIndex:(NSInteger)index;
- (void)listAdapter:(IGListAdapter *)listAdapter didEndDisplayingSectionController:(IGListSectionController <IGListSectionType> *)sectionController
               cell:(UICollectionViewCell *)cell
            atIndex:(NSInteger)index;
```

but I think the other two must be called since the section is displayed and has content (supplementary views):

```
- (void)listAdapter:(IGListAdapter *)listAdapter willDisplaySectionController:(IGListSectionController <IGListSectionType> *)sectionController;
- (void)listAdapter:(IGListAdapter *)listAdapter didEndDisplayingSectionController:(IGListSectionController <IGListSectionType> *)sectionController;
```

**Comment by rnystrom** [comment]
Very interesting. This could actually improve display event notifications sent when a supplementary view is about to appear but the cells haven't yet.

Since we support iOS 8+ this should be easy. We can tap into:

```
- (void)collectionView:(UICollectionView *)collectionView willDisplaySupplementaryView:(UICollectionReusableView *)view forElementKind:(NSString *)elementKind atIndexPath:(NSIndexPath *)indexPath;

- (void)collectionView:(UICollectionView *)collectionView didEndDisplayingSupplementaryView:(UICollectionReusableView *)view forElementOfKind:(NSString *)elementKind atIndexPath:(NSIndexPath *)indexPath;
```

To give us display start/end events and use the display handler. Great find @almas73!
