### ISSUE TITLE
Link to media in README.md

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#309]
Two things that come to mind:

- [Realm talk and transcription](https://realm.io/news/tryswift-ryan-nystrom-refactoring-at-scale-lessons-learned-rewriting-instagram-feed/)
  - Tho some of the naming is out of date (e.g. "item controller" is now "section controller")
  - Could link to the iOS singapore video but its not transcribed
- Ray Wenderlich tutorial (not yet published)

Would be happy to add external blog posts if they come up.

**Comment by jessesquires** [comment]
Let's list these under "Getting Started"

**Comment by jessesquires** [comment]
this is done
