### ISSUE TITLE
Provide IGListCollectionSectionController [inception]

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#31]
Create a stock horizontal or vertical scrolling item controller. This is a pretty loaded RFC b/c the API would have to be _really_ thought out. Some questions come to mind:
### Subclassing?

Since the infra requires subclassing `IGListItemController` and conforming to `IGListItemType`, if we provide a new item controller for this it would have to follow the same pattern as the stacked or single item controller:

``` obj
@interface IGListCollectionItemController : IGListItemController <IGListItemType>
@end
```

Question is: do we have clients _subclass_ this object or do we stick `SUBCLASSING_RESTRICTED` on it and provide some hooks?

Another idea is that we don't conform to `IGListItemType` but add hooks to properly setup/configure/reload the embedded item controller.
### UICollectionView config
- Should we have an enum for h/v scrolling?
- What layout object would we use?
  - Maybe we keep the stock version of this to using `UICollectionViewFlowLayout`
# 

I'm sure there will be more questions that come up. Open to suggestions.

**Comment by jessesquires** [comment]
To clarify a bit: 

What we want to achieve is to have multiple sections with horizontal scrolling that together scroll vertical. Essentially, a ListKit version of https://github.com/ashfurrow/AFTabledCollectionView.

Correct, @rnystrom ? (At least, that's *part* of this proposal)

**Comment by zhubofei** [comment]
@rnystrom IGListItemController was renamed to IGListSectionController right?

**Comment by jessesquires** [comment]
@zhubofei - correct 😄 We should update the initial comment

**Comment by rnystrom** [comment]
Noting from #133 that we want to store and reset the content offset of the collection view when it is reused.

**Comment by jessesquires** [comment]
@rnystrom - can this be deferred from 3.0 to a later release?

**Comment by rnystrom** [comment]
@jessesquires we could sneak it in, honestly, now that #517 and #503 are under wraps. Probably ok to punt tho since there's enough documentation right now.

**Comment by jessesquires** [comment]
@rnystrom - Cool let's push this to 3.1.0

**Comment by tunidev** [comment]
any news about that

**Comment by jessesquires** [comment]
Clearing the milestone here since this seems like it's still in the pretty early stages of design, etc

**Comment by Ziewvater** [comment]
There isn't much call for something like this internally, so we're not going to invest effort in building it out.
