### ISSUE TITLE
Markdown Link Verification

### ISSUE THREAD

**Issue by Sherlouk** [Instagram/IGListKit#312]
Since v1.0 a lot of files have moved around to make place for new functionality for example extra example packs or simply neatening up the file structure and this causes links to break.

While it seems the structure is a bit more stable now and links should continue to work I was wondering if we should consider some sort of check in travis?

By no means am I saying use this, but [this CLI tool](https://www.npmjs.com/package/markdown-link-check) could work by just checking each of the our MD files causing builds to fail if they produce broken links catching them before they get merged!

**Comment by jessesquires** [comment]
I'd be ok with using `markdown-link-check` if we can keep it contained to travis-ci. Is that possible?

**Comment by Sherlouk** [comment]
Well at it's core we just need the command line extract from it. Travis runs shell scripts, so we really only need it to run `cat *.md | markdown-link-check` right at the beginning/end.

I'm not very familiar with travis, but assuming we can add a more generic step to the build matrix (rather than all the SDK/destination gubbins, we just specify "CHECK_MARKDOWN" or something) then run the shell script I don't see it being too difficult

**Comment by jessesquires** [comment]
> I'm not very familiar with travis, but assuming we can add a more generic step to the build matrix (rather than all the SDK/destination gubbins, we just specify "CHECK_MARKDOWN" or something) then run the shell script I don't see it being too difficult

Yep! 😊  That's basically what our current `POD_LINT` check is doing. We can do the same with `CHECK_MARKDOWN`

**Comment by Sherlouk** [comment]
I'm happy to pick this up and see if I can get it working?
