### ISSUE TITLE
Could not build Objective-C module 'IGListKit'

### ISSUE THREAD

**Issue by lutetium71** [Instagram/IGListKit#316]
Hi
I'm handling weird problem. "Could not build Objective-C module 'IGListKit'"
There's someone have any idea what could cause this problem?
Attach File is my project.
Cocoapods version is 1.1.1
Xcode 8.1
OS 10.11.6.

Another question, can I use IGListKit in a Objective-C project? How to user it? Thanks.

[IGListDemoSwift.zip](https://github.com/Instagram/IGListKit/files/645111/IGListDemoSwift.zip)

**Comment by rnystrom** [comment]
@lutetium71 Thanks for providing a sample project! However it looks like its 404ing. We're using the same version of CocoaPods. I wonder if Xcode is breaking, make sure you try:

- Cleaning (command-shift-K)
- Cleaning build folder (command-shift-option-K)
- Removing derived data (`$ rm -rf ~/Library/Developer/Xcode/DerivedData`)

> can I use IGListKit in a Objective-C project

Definitely! The whole framework is written in Objective-C (with a sprinkle of C++). It should work just fine. You can use CocoaPods, Carthage, or just drag and drop the files into your Objective-C project. You just need to:

```objc
#import <IGListKit/IGListKit.h>
```

And you're good to go!

**Comment by lutetium71** [comment]
Thanks! It works!
