### ISSUE TITLE
Disable prefetchEnabled by default on IGListCollectionView

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#318]
Our experiments find that disabling this feature that IGListKit does not uses yields ~5% increase to scroll performance. `-[UICollectionView prefetchEnabled]` defaults to `YES` with the iOS 10 SDK.

**Comment by svenbacia** [comment]
I started working on this [here](https://github.com/svenbacia/IGListKit/commit/54ae08cb005365bdf1cdbfd6f79fab759095911c). Currently the default value is only applied for collectionViews which are created from the `initWithFrame:collectionViewLayout:` initializer. Should the default value also be applied for collectionViews created from Storyboard for example by overriding `initWithCoder:`?

**Comment by rnystrom** [comment]
@svenbacia yes definitely! We should make sure _every_ `IGListCollectionView` has the same behavior.

**Comment by rnystrom** [comment]
nit on the branch before its PR'd:

Instead of checking OS version we can just check `[self respondsToSelector:@selector(setPrefetchingEnabled:)]`.

**Comment by jessesquires** [comment]
Fixed in #323
