### ISSUE TITLE
Update travis-ci to Xcode8.2

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#334]
Travis has Xcode 8.2 GM now.
https://blog.travis-ci.com/2016-12-13-xcode-82-ga-is-here

Apparently 8.2 is supposed to be more reliable on CI. Let's see. 👀

**Comment by heshamsalman** [comment]
@jessesquires I've found that it's more reliable and a touch faster, so long as you continue using the iOS 10.1 image. Stubs and mocks of `MFMailComposeViewController` crash under 10.2. Might take on this task.
