### ISSUE TITLE
how to set background color separately by each section when a section's numberOfItems greater than 1

### ISSUE THREAD

**Issue by walkerwzy** [Instagram/IGListKit#338]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information
to illustrate my question: 
<img width="723" alt="e4f00cd3-d9ff-4a91-8bff-c4887b67b7d5" src="https://cloud.githubusercontent.com/assets/1918101/21258333/6a014122-c3b7-11e6-8235-97b2832f93a3.png">

how to set section3's background color to gray?

I have three sections, and judge [this issue](https://github.com/Instagram/IGListKit/issues/335),  I use a `inset` to demonstrate a `line spacing`, so I set the mainivew's background color to `black`, and it will shown like this.
each section have a standalone background color, use the standard `cellForItemAtIndex:(NSInteger)index`,  I dequeue q `UICollectionViewCell` and set it's background color to what I want. 

so far so good .

but the third section I have 4 items, the cell's background color set to items itself rather than the whole section!!!

is IGListKit support this?

=====
For now, I can only use a nested adapter in section3, and set the child view's collection view's background color to blue.
but if I use this way , the items in the nested view can only scroll vertical or horizontal, can't act like my picture (flow), so I have to wrap the four item into a array again:
`[1,2,3,4] -> [[1,2,3,4]]`
do I miss something?

**Comment by rnystrom** [comment]
@walkerwzy IGListKit supports basic section+item setups like normal `UICollectionView`. We proposed the idea of a section background view in #142 but dropped it b/c of the complexity.

Section background colors isn't something that IGListKit supports out of the box. There are ways to do this with custom `UICollectionViewLayout`s, but that's beyond the scope of IGListKit.

[This resource](http://strawberrycode.com/blog/how-to-create-a-section-background-in-a-uicollectionview-in-ios-swift/) looks like a great place to start!

**Comment by gannasong** [comment]
@walkerwzy Does this problem have been solved? I have similar problems.

**Comment by walkerwzy** [comment]
@gannasong it's been a long time and I forgot how to do it finally. but according to my question, perhaps I used NestedAdapter, so the child section can have it's own background color rather than set to the cell's.
