### ISSUE TITLE
Diffing inside nested section not working

### ISSUE THREAD

**Issue by MarvinNazari** [Instagram/IGListKit#340]
Hi, i have an issue appending data inside an section, the `adapter.performUpdates(animated: true)` dosen't do anything. i made an sample project [here](https://github.com/MarvinNazari/IGListKitIssue)
you see that when i press `Add more` dosen't append more data.

### General information

- `IGListKit` version: 2
- Reproducible in the demo project? (Yes/No): Yes

**Comment by rnystrom** [comment]
@MarvinNazari thanks for providing the sample project! I did a little digging and found a couple issues that are causing this:

- I see you added the [NSObject+IGListDiffable extension](https://github.com/MarvinNazari/IGListKitIssue/blob/master/IGListKitIssue/ViewController.swift#L93-L100) which works, but `self.items` never changes, it is [only mutated](https://github.com/MarvinNazari/IGListKitIssue/blob/master/IGListKitIssue/ViewController.swift#L54). That means that the pointer will never change, and wont ever trigger an update, b/c pointers are always equal to themselves (identity comparison). 
  - You probably want to build new objects and set them on `items` whenever something changes. You'll also end up w/ immutable models then too, which is a safer architecture.
- Along w/ immutable models, your section controller only [updates its items](https://github.com/MarvinNazari/IGListKitIssue/blob/master/IGListKitIssue/PostSectionController.swift#L41) when the top-level model changes. As stated above, the `SFDiscoveryPostSectionItem` pointer never changes to the section controller doesn't get a chance to receive new objects and rebuild `self.posts`.

An easy way to start would be setting a new model on `self.items` on the VC each time "Add More" is tapped.

**Comment by MarvinNazari** [comment]
@rnystrom thanks for answer! the problem is that when i replace the item with a new item, all the cells flashes, and even duplicates items, i pushed a new commit to the sample code so you can see it

**Comment by rnystrom** [comment]
@MarvinNazari ya, that's because its reloading the entire section. To avoid the flashing you can do `animated: false`, but to really do this right it probably requires a little rearchitecting.

I wonder if adding new items to append to the `items` array on the VC level, instead of appending to a sub-array to update a single section? That's really how IGListKit was designed: to have a top-level array of items.

Are you trying to use flow layout to have a grid/column layout?

**Comment by MarvinNazari** [comment]
@rnystrom i thought about that, but we have a similar layout like explore page in Instagram app (Stories, Video, Grid of posts), so i have multiple section type , but when i add them to the top level, the every grid section takes the whole width, even though the size item is right

**Comment by shuhrat10** [comment]
@MarvinNazari you are right. You have to apply custom layout IGListGridCollectionViewLayout to your CollectionView.

**Comment by shuhrat10** [comment]
I'm trying to solve the similar problem like you #290

**Comment by rnystrom** [comment]
@MarvinNazari +1 to @shuhrat10's suggestion of using `IGListGridCollectionViewLayout`. It's pretty basic right now. We're going to try to get it more robust with more advanced layout features that we use within Instagram eventually. There are other open source layouts out there too that do this as well that might be helpful.
