### ISSUE TITLE
Question about iOS 7 support

### ISSUE THREAD

**Issue by PhilCai1993** [Instagram/IGListKit#347]
I have reviewed the [`Merge Request`](https://github.com/Instagram/IGListKit/commit/9e8ad9626ab91326b6bbb75cb6927f8dbe134896).

Even there are few users are still using iOS 7 devices, I couldn't abandon iOS 7 support in our app immediately. But IGListKit is really helpful for data driven applications so I still want to take it into use.

So could you please tell me are there any other points that I should be careful with when using IGListKit? (I have made a copy on our private gitlab so I can make some changes to meet our temporary requirements)

Thank you!

**Comment by jessesquires** [comment]
Hey @PhilCai1993 ! 

You're definitely free to do whatever you want. 😄 However, we can't (and won't) be able to support any questions/bugs/etc. regarding iOS 7.

Personally, I would consider dropping iOS 7. Apple recommends only supporting the 2 most recent OSes. At Instagram (and Facebook), all apps are iOS 8+.

**Comment by rnystrom** [comment]
@PhilCai1993 that's pretty much the only issue with iOS 7. If you add that back on your own fork you'll be good to support iOS 7. We were using IGListKit before we dropped iOS 7 support in the fall.

**Comment by PhilCai1993** [comment]
@jessesquires @rnystrom Thanks a lot!
