### ISSUE TITLE
IGListDiffable protocol does not inherit from NSObject

### ISSUE THREAD

**Issue by iostriz** [Instagram/IGListKit#349]
I cannot check if object isKindOfClass:
```objective-c
- (BOOL)isEqualToDiffableObject:(id<IGListDiffable>)object
{
   if(![object isKindOfClass:[SectionItemWide class]]) // <- error
     ;
   }
}
```

I have to ugly-cast first:
```objective-c
- (BOOL)isEqualToDiffableObject:(id<IGListDiffable>)object
{
    NSObject<IGListDiffable> *o = (NSObject<IGListDiffable> *)object;    
    if ([o isKindOfClass:[SectionItemWide class]]) {
     ;
    }
}
```

Is this intentional?

## New issue checklist

- [TRUE] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [TRUE] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: HEAD
- iOS version(s):10+
- CocoaPods/Carthage version: latest
- Xcode version: 8.2.1
- Devices/Simulators affected: all
- Reproducible in the demo project? (Yes/No): YES
- Related issues: -

**Comment by rnystrom** [comment]
We removed `<NSObject>` b/c of Swift interop issues. If `IGListDiffable` inherits from the `NSObject` then all swift classes must conform to `NSObjectProtocol`, which is unnecessary.

It does make this a little annoying though, I agree. In Instagram we just make the parameter `id` (not `id<IGListDiffable>`) to make the class checks easy. Not sure if there's a better solution out there.

**Comment by jessesquires** [comment]
That doesn't make sense. `id` is just syntactic sugar for `NSObject *`. You shouldn't need any casting.

Sounds like `SectionItemWide` is forward-declared instead of imported... ?

**Comment by iostriz** [comment]
@rnystrom Yes, thanks, it is the simplest. I'll do that... (remove conformance to the IGListDiffable). Language purists may drop dead now, but, oh, well... :-)

@jessesquires It all happens _in_ SectionItemWide:
```obj-c
@implementation SectionItemWide

- (id<NSObject>)diffIdentifier
{
    return self;
}

- (instancetype)initWithIndex:(NSUInteger)index
{
    self = [super init];
    return self;
}

// change to:
//- (BOOL)isEqualToDiffableObject:(id)object
- (BOOL)isEqualToDiffableObject:(id<IGListDiffable>)object
{
    if ([self isEqual:object])
        return YES;

    NSObject<IGListDiffable> *o = (NSObject<IGListDiffable> *)object;
    if ([o isKindOfClass:[SectionItemWide class]]) {
        /// ...
    }
    // something something in the month of May
    return NO;
}
@end
```

**Comment by jessesquires** [comment]
oh my bad. just checked this.

bizarre.

**Comment by rnystrom** [comment]
@jessesquires ya it's a PITA, not really sure why `id<Something>` wouldn't conform to `NSObject` since its still an `id`...
