### ISSUE TITLE
[Swift] reference type and value type conformances to IGListDiffable

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#35]
The handy `NSObject+IGListDiffable` category doesn't really help with Swift objects like `String` and `Int`. This seems a little tricky because `String` is a `struct` but is convertible to an `NSString`. Doing that conversion gives us the `NSObject<IGListDiffable>` conformance, but that's kind of lame. I wonder if there's a way we can get this to work a little better?

For example, the Swift 3.0 compiler wont allow this:

``` swift
let letters: [IGListDiffable] = ["a", "b", "c"]
```

But you can get this to work a few ways:

``` swift
let strings: [NSString]  = ["a", "b", "c"]
let letters = strings as [IGListDiffable]
// or
let letters = ["a" as IGListDiffable, "b" as IGListDiffable, "c" as IGListDiffable]
// or
let letters: [IGListDiffable] = ["a" as NSString, "b" as NSString, "c" as NSString]
```

Also adding an extension to `String` isn't easy either, since `String` is a struct and `IGListDiffable` is an Objective-C protocol...

> Note that this also stunts using `IGListDiffable` with Swift structs

**Comment by matthewcheok** [comment]
Is there still no way we have a swift struct conform to `IGListDiffable`?

**Comment by rnystrom** [comment]
@matthewcheok nope 😕  when using Swift objects have to be a `class`. I'm sure there's a good pattern by boxing with something like `Box<StructType>` where `Box` is a `class` conforming to `IGListDiffable`.

**Comment by jessesquires** [comment]
Going to close this since there's nothing actionable right now (and for the foreseeable future)

**Comment by danielgalasko** [comment]
Inspired by @jessesquires I will put my solution in here for enabling swift value types to conform to Diffable. I ended up with a new Swift protocol `ItemDiffable` and used `Equatable` as the means for exposing `isEqual(toDiffableObject object)` from IGListKit.

I then wrap diff'ing around a struct called `DiffUtility`

```swift
/**
 A diffable value type that can be used in conjunction with
 `DiffUtility` to perform a diff between two result sets.
 */
public protocol ItemDiffable: Equatable {
    
    /**
     Returns a key that uniquely identifies the object.
     
     - returns: A key that can be used to uniquely identify the object.
     
     - note: Two objects may share the same identifier, but are not equal.
     
     - warning: This value should never be mutated.
     */
    var diffIdentifier: String { get }
}

/**
 Performs a diff operation between two sets of `ItemDiffable` results.
 */
public struct DiffUtility {
    
    public struct DiffResult {
        public typealias Move = (from: Int, to: Int)
        public let inserts: [Int]
        public let deletions: [Int]
        public let updates: [Int]
        public let moves: [Move]
        
        public let oldIndexForID: (_ id: String) -> Int
        public let newIndexForID: (_ id: String) -> Int
    }
    
    public static func diff<T: ItemDiffable>(originalItems: [T], newItems: [T]) -> DiffResult {
        let old = originalItems.map({ DiffableBox(value: $0, identifier: $0.diffIdentifier as NSObjectProtocol, equal: ==) })
        let new = newItems.map({ DiffableBox(value: $0, identifier: $0.diffIdentifier as NSObjectProtocol, equal: ==) })
        let result = IGListDiff(old, new, .equality)
        
        let inserts = Array(result.inserts)
        let deletions = Array(result.deletes)
        let updates = Array(result.updates)
        
        let moves: [DiffResult.Move] = result.moves.map({ (from: $0.from, to: $0.to) })
        
        let oldIndexForID: (_ id: String) -> Int = { id in
            return result.oldIndex(forIdentifier: NSString(string: id))
        }
        let newIndexForID: (_ id: String) -> Int = { id in
            return result.newIndex(forIdentifier: NSString(string: id))
        }
        return DiffResult(inserts: inserts, deletions: deletions, updates: updates, moves: moves, oldIndexForID: oldIndexForID, newIndexForID: newIndexForID)
    }
}

private final class DiffableBox<T: ItemDiffable>: IGListDiffable {
    
    let value: T
    let identifier: NSObjectProtocol
    let equal: (T, T) -> Bool
    
    init(value: T, identifier: NSObjectProtocol, equal: @escaping(T, T) -> Bool) {
        self.value = value
        self.identifier = identifier
        self.equal = equal
    }
    
    // IGListDiffable
    
    public func diffIdentifier() -> NSObjectProtocol {
        return identifier
    }
    
    public func isEqual(toDiffableObject object: IGListDiffable?) -> Bool {
        if let other = object as? DiffableBox<T> {
            return equal(value, other.value)
        }
        return false
    }
}
```

**Comment by rnystrom** [comment]
@danielgalasko 😲 this is super cool! cc @jessesquires

**Comment by CurlyHeir** [comment]
@jessesquires reading this took me some time, before i understood it. Could you put here small example of usage?

**Comment by danielgalasko** [comment]
sure thing @CurlyHeir but its very similar to how you would use IGListKit normally. So lets start with a struct:

```swift
fileprivate struct TestDiff: Diffable {
    var name: String
    let id: String

    var diffIdentifier: String {
        return id
    }

    static func ==(lhs: TestDiff, rhs: TestDiff) -> Bool {
        return lhs.name == rhs.name
    }
}
```

```swift
        let bob = TestDiff(name: "Bob", id: "1")
        let tigger = TestDiff(name: "tigger", id: "2")
        let initial = [bob]
        let new = [bob, tigger]
        let diff = DiffUtility.diff(originalItems: initial, newItems: new)
        //diff.inserts == 1
```

Not sure if thats what you were asking but thats how I use it

**Comment by Eke** [comment]
Hello @danielgalasko ! How do you use `Diffable` objects in `public func objects(for listAdapter: IGListAdapter) -> [IGListDiffable]` ?

**Comment by danielgalasko** [comment]
@Eke you will see I created `DiffableBox` that takes a `Diffable` object and transforms it into `IGListDiffable`.

```swift
diffableItems.map({ DiffableBox(value: $0, identifier: $0.diffIdentifier as NSObjectProtocol, equal: ==) })
```

Kinda like that :)

**Comment by vibrazy** [comment]
Just created an extension to `Sequence` to wrap `DiffableBox`. 
```
extension String: Diffable {
	public var diffIdentifier: String { return self }
}

extension Int: Diffable {
	public var diffIdentifier: String { return String(self) }
}

extension Sequence where Iterator.Element: Diffable {
	func diffable() -> [ListDiffable] {
		let toListDiffable: [ListDiffable] = map{ DiffableBox(value: $0, identifier: $0.diffIdentifier as NSObjectProtocol, equal: ==) }
		return toListDiffable
	}
}

// usage
func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
	return ["Daniel", "Hollis", "Tavares"].diffable()
}
```

**Comment by tunidev** [comment]
is this still the way to go ? any full example please ?

**Comment by levi** [comment]
Chiming in here. Would be fantastic to simply use `Hashable` conformance on the Swift side in place of `ListDiffable`, since it provides both identity and equality comparison. Much easier said than done, however, since `ListDiffable` a core type of the diffing algorithm. Not much flexibility off the top of my head without either constructing a DiffableBox like @jessesquires above or maintaining a completely separate Swift adapter implementation. I'm going to do some more independent thinking/research and see what could be realized. 

Instagram looking to adopt Swift anytime soon? 😂

**Comment by tunidev** [comment]
@levi that would be awesome, any progress ? the  `DiffableBox` works but it adds unnecessary code to the project. I hope that we can use `Hashable` soon 🥇

**Comment by rnystrom** [comment]
Just letting you all know that I have a Swift bridge layer idea in progress that will handle all of this under the hood, letting you use Swift structs with IGListKit!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by levi** [comment]
Thanks for the update, Ryan!

**Comment by JUSTINMKAUFMAN** [comment]
@rnystrom First off, this is such a killer library you've built! 

I'm just wondering if there's been any movement on the Swift bridge layer mentioned above for enabling the use of Swift structs? Thanks!

**Comment by Arcovv** [comment]
@vibrazy HI @danielgalasko 
I really love your solution, but met some problems.

Seems `func diffable() -> [ListDiffable]` tries to map the value using `DiffableBox`. 

When I want to use them in a `ListAdapterDataSource`, in `func objects(for listAdapter: ListAdapter) -> [ListDiffable]`  using your extension is really awesome. 

But when I try to use in `func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController`, the `object` actually the type of `DiffableBox<T>`, the typecast process will crash my code.

And `DiffableBox<T>` is private so can't access the real value.

Should you think make `DiffableBox<T>` as public or something to solve this problem?

Thanks for your help!

**Comment by staticdreams** [comment]
Any progress officially supporting this? @rnystrom

**Comment by claudiogomezGL** [comment]
@rnystrom Any progress supporting this?

**Comment by fenixsolorzano** [comment]
2019 Already, is this still a WIP?

**Comment by rob-keepsafe** [comment]
I would just look into using [`DifferenceKit`](https://github.com/ra1028/DifferenceKit) or the [new iOS 13 api's](https://developer.apple.com/videos/play/wwdc2019/220/) for this instead

**Comment by wonder2011** [comment]
2022. Nothing yet ?
