### ISSUE TITLE
how to have an grid layout with dynamic items per row

### ISSUE THREAD

**Issue by gvlachos** [Instagram/IGListKit#351]
I'd like to have a layout where the number of items per row varies depending on the width of the device (e.g. iPhone vs iPad or during an orientation change) and the items are equally spaced in the view i.e. margins around as well as between them are equal

at the moment the way I am doing this is

- in my UIViewController I define an IGListAdapter and assign to it a IGListCollectionView and an IGListAdapterDataSource

- in my IGListAdapterDataSource in the listAdapter I return a custom IGListSectionController which I use to set the data to be displayed in each item

- in my IGListCollectionView I use a IGListGridCollectionViewLayout where I calculate the width (a fixed width) and height of each item (all items have the same dimensions) and set the itemSize, minimumInteritemSpacing and minimumLineSpacing attributes of the layout

At first this seemed to have worked: I got 1 item on the iPhone 5s simulator and 2 on portrait orientation of the iPad Air simulator which when I rotate to landscape became 3.  However the items were not centered on the display, though the spacing between the items seems equal.

Is this the correct approach ?

(I am very new to Swift and iOS so I greatly appreciate your help)

**Comment by rnystrom** [comment]
@gvlachos are you trying to space the items across the width of the collection view? Sometimes called [justified](https://css-tricks.com/almanac/properties/j/justify-content/) (see the "space between"). Or are you trying to get them centered?

That might require updating the `IGListGridCollectionViewLayout` to be more flexible in its layout. Atm its pretty locked down.

Your setup looks right though!

**Comment by gvlachos** [comment]
@rnystrom oh ok, my description was a bit off. I am trying to have them justified with space-around, so all white space (around the items) in a row  is equal.

**Comment by rnystrom** [comment]
Ahh, so centered w/ the same interitem spacing between them. Have you tried setting `minimumInteritemSpacing` on the layout itself and not using the API on the section controller?

**Comment by gvlachos** [comment]
yes I set layout.minimumInteritemSpacing to a fixed value (CGFloat(10.0)) and I do get equal spacing between the items, so that works.

However I am trying to figure a way to get the same amount of spacing on the left and the right of the items as well as between them.

Actually I start to think that I might need to do something on the outside view (the one containing the IGListCollectionView).

**Comment by MarvinNazari** [comment]
@rnystrom @gvlachos `minimumInteritemSpacing` on `IGListGridCollectionViewLayout` dosent work properly, if the section width is equal to collectionview width (full width), and the `minimumInteritemSpacing` is > 0, it crashes.
i should make an issue about that

**Comment by zhubofei** [comment]
@rnystrom I think we can add an alignment style enum to the grid layout.

**Comment by AbeiOS** [comment]
> I think we can add an alignment style enum to the grid l

did add an alignment style ?
