### ISSUE TITLE
better to generate identifier with a custom identifier or prefix/suffix

### ISSUE THREAD

**Issue by walkerwzy** [Instagram/IGListKit#362]
now the IGListKit have generate reusable views mainly by class_name:
```
NSString *identifier = IGListReusableViewIdentifier(cellClass, nil, nil);
NSString *identifier = IGListReusableViewIdentifier(viewClass, nil, elementKind);
```

I make a page which have many different section each have unique layout, but it's all very simple , so I use `UICollectionViewCell` for most of it, but since the class name determine the identifier, those cell can be used by other section's cell.

so I need to create my own `UICollectionViewCell`'s subclass and do nothing just to get a unique identifier.

it's not a bug, and it's recommend to subclass every cell, but it could be more convenient  if the kit can support this feature which we can custom identifier of a simple reusable view.

**Comment by rnystrom** [comment]
@walkerwzy 🤔 really interesting. You're right that we could really easily add this API now that we've done the legwork for storyboards and nibs. Basically a "dequeue with identifier", skipping [this step](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L794).

Haven't had the need for it, but there's no reason we couldn't.

Agree w/ you tho, want to encourage making cell subclasses since the stock `UICollectionViewCell` is basically nothing.

**Comment by jessesquires** [comment]
I'm not really sure why you would be using `UICollectionViewCell` *without* subclassing...

**Comment by walkerwzy** [comment]
@jessesquires 
![7a788683-8e92-46c8-af3e-6dd1f6a1d49b](https://cloud.githubusercontent.com/assets/1918101/21465549/00d56322-c9e3-11e6-8a7f-f98f1daab153.png)
sometimes you just want to write code quickly, i dequeue a cell, configure it the first time, and reset the biz data every showing time.

**Comment by jessesquires** [comment]
Hm... this is really bad practice. 😅 

A couple notes:

1. You're killing performance by doing this. You have to alloc/init and add subviews **every single time**. That's expensive. This is what cell reuse + dequeuing is intended to address. You really should be subclassing and using your subclass.
2. This is also a really bad usage of `view.tag` -- this is a rather regrettable API and its usage is highly discouraged by Apple.

😄 

-----------------

@rnystrom For these reasons, I would be against adding support for custom identifiers -- seems like it would only encourage bad behaviors / misuse of UIKit APIs.

**Comment by rnystrom** [comment]
@walkerwzy oh ya you should _absolutely_ be making your own subclass for that. Using tags and adding subviews in `cellForItemAtIndex:` is really really fragile and wont scale as you add more cell types. Using a subclass would make things crystal clear, simple, and extendable.
