### ISSUE TITLE
The platform of the target .... (OS X 10.8) is not compatible with `IGListKit (2.0.0)`, which does # not support `osx`.

### ISSUE THREAD

**Issue by yakushevichsv** [Instagram/IGListKit#370]
### General information
- `IGListKit` version: 2.0.0
- CocoaPods/Carthage version: 1.1.1/ 0.15.2
- Xcode version: 8.2
- Language: ObjC

Hello guys,
I wanted to make more advanced sample for MacOS using Objective-C.
I included into my project the framework by cocoa pods: 
I got the following error:
 
**The platform of the target .... (OS X 10.8) is not compatible with `IGListKit (2.0.0)`, which does # not support `osx`.**

After that I used  `Carthage` but there is no target for MacOS, just iOS, tvOS.
Therefore I included the framework as a submodul;  checkout command contains MacOS target.

Please add support of MacOS target via cocoapods & carthage.

`Cartfile` has only one command `github "Instagram/IGListKit" ~> 2.0.0`
`Podfile` contains(not formatted here): `platform :osx, '10.7'  .... pod 'IGListKit' `

**Comment by Sherlouk** [comment]
MacOS support is coming in the 2.1.0 release of IGListKit which is yet to be released

In the time being if you would like the absolute latest changes (including macOS support, using CocoaPods) then you can use `pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'`

There is currently not an ETA for the release of 2.1.0

**Comment by jessesquires** [comment]
you can track progress on 2.1.0 here:

https://github.com/Instagram/IGListKit/milestone/2
