### ISSUE TITLE
Steps

### ISSUE THREAD

**Issue by Alfonso69** [Instagram/IGListKit#372]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

**Comment by rnystrom** [comment]
@Alfonso69 looks like the issue submitted before filling in info. Mind updating?
