### ISSUE TITLE
Fix build docs script

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#373]
Because of `macOS` support and adding a `Common/` sub-directory, the `jazzy` build script is broken again.

Same problem as #55 (i.e. https://github.com/realm/jazzy/issues/667). We'll need another workaround, similiar to https://github.com/Instagram/IGListKit/commit/7163cf8868bf8d79e1768f9a7442a8d4346f889f. 

However, this workaround will be significantly more complicated. We need to move the `Common/` files to the tmp dir `IGListKit/`, then we need to move **only those files** back.

Relevant issues: #235, #328, #270, #53, #368, #365

**Comment by Sherlouk** [comment]
Can we rely on git? 🤔 Merge all the directories then `git reset` the source directory leaving just updated docs.

Alternative being we iterate the files, add to an array, move, run jazzy, then move back.

**Comment by jessesquires** [comment]
> Alternative being we iterate the files, add to an array, move, run jazzy, then move back.

We'll have to do this. IG uses mercurial internally.
