### ISSUE TITLE
emptyView Not Updated In Response to Item Updates

### ISSUE THREAD

**Issue by Adlai-Holler** [Instagram/IGListKit#378]
Love the framework! I have a simple test app with a section controller that initially has 0 items, and after it loads content it calls `insertInSectionController:atIndexes:` to add some items. However, the list adapter never updates `emptyView.hidden` so there's a spinner behind the content!

In terms of a workaround, I can cast the collection context to `IGListAdapter` and call `performUpdatesAnimated:completion:` from inside the section controller. That'll trigger the empty view to update even though it's not beautiful.

Tested on a748e6f6c7e957dd68fb611fc95e608db877f4a5

**Comment by jessesquires** [comment]
Thanks @Adlai-Holler ! 👍 

Sounds like an edge-case that we've overlooked

**Comment by rnystrom** [comment]
Eek ya, good find. This should definitely be fixed and should be pretty easy to add a unit test for.

**Comment by edmonston** [comment]
I'd love to take a crack at writing a fix & test(s) for this one over the weekend if no one is on it already...

**Comment by rnystrom** [comment]
@edmonston all yours!
