### ISSUE TITLE
RFC: View-model, auto diffing section controller

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#38]
We generate view models to drive all of the cells in a particular section controller on Instagram. These models are derived from a top-level model that is created from server data. The view models are then used to configure things like image and text cells within a section controller. 

We can represent this transformation:

``` swift
protocol ViewModel: IGListDiffable {...}

func map(object: Any) -> [ViewModel] {...}
```

We could create a section controller that diffs its own array of `ViewModel` objects, then apply those diffs at the _item_ (e.g. "cell") level.

There are a few gotchas to doing this, that's why I think a built-in and tested version of this would be valuable (similar to the embedded adapter idea in #31).

You end up with diffing of sections/section-controllers _and_ the items/cells within them. It totally converts your setup to being data-driven all the way down to the cell level.

**Comment by rnystrom** [comment]
This would really be _one-way data flow_ once built:

1. Top-level data in `IGListAdapterDataSource`
2. Section controller transforms data into an array of view models
3. View-model to cell class
4. "Bind" view model to cell (e.g. config)

Don't want to lock down the API too much though, for instance cell selection should still be handled manually I think.

**Comment by jessesquires** [comment]
> Section controller transforms data into an array of view models

This is "too late" in the flow.

Where we use view models, we're returning them in `-itemsFromListAdapter:`. The view models need to be **the items** that are diff'd.

**Comment by rnystrom** [comment]
@jessesquires I mean use a top-level array of objects to drive sections, then a view-model array to drive `numberOfItems`. Then the section controller does diffing for its view models when the top-level model changes.

Not sure if that makes sense.

(basically what we do for feed items tho)

**Comment by rnystrom** [comment]
Had some ideas this morning. Need to write them down so they aren't lost.

- Instead of calling reload in the infra, if we have a cell bind/configure architecture, we can actually reconfigure the cell instead of calling reload (which does delete+insert internally). This unlocks moving and reloading the cell at the same time!!
- Have to take special care not to call reloadSection when diffing the top-level object. If that happens the item-level updates are lost.
- Need to avoid over-diffing the view models. Just like the top-level arrays, this should only happen once when the update is performed.
- Should the transform be a SC subclass override? a block passed on init? custom object w/ protocol passed on init? Still 🤔 on this
- Does #392 need to be done first? I don't think so.
- I like the sound of `IGListBindable` for the cells. Thoughts?

**Comment by jessesquires** [comment]
💯

**Comment by heumn** [comment]
![thumbs-up-good-job-ali-larter-3o6Ztlpl0ntHo3wmWI](https://media.giphy.com/media/k39w535jFPYrK/giphy.gif)
