### ISSUE TITLE
Refactor macOS example to use NSCollectionView

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#381]
As evidenced in #342 and #337, the changeset produced by the diffing algorithm is not compatible with `NSTableView` since it expects its batch updates to be made incrementally (even when using [batch updates](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-macOS/IGListKitExamples/ViewControllers/UsersViewController.swift#L62-L69)).

So that we don't lead anyone astray, we should refactor the example to use an `NSCollectionView` that should work the same as `UICollectionView` when batch updating.

**Comment by heshamsalman** [comment]
I'm down to jump in on this one when i get back from traveling.

**Comment by Sherlouk** [comment]
@heshamsalman Quick ping! -- when are you back from travelling?

**Comment by heshamsalman** [comment]
@Sherlouk just made it back last night!

**Comment by MoralAlberto** [comment]
Hi @heshamsalman, any news about the example with NSCollectionView? thanks!

**Comment by Sherlouk** [comment]
@heshamsalman Still intending on doing this one or would you like someone else to pick it up?

Don't mind having a look!

**Comment by heshamsalman** [comment]
@sherlouk ah, this totally slipped through the cracks 😔

The night owl in me says to do it, but the realist in me is looking at the sprint I have ahead of me. If you wanna pick it up, go for it.

**Comment by weyert** [comment]
I am working on this now. I just wished Xcode wouldn't crash each time I drag in a Collection View 😅

**Comment by weyert** [comment]
Phew, quite a pain to get the NSCollectionView in the storyboard so I ended up copy-pasting it from Ray Wenderlich tutorial. For some reason when you drag a NSCollectionView into the view controller (after removing the table view bits) it crashes Xcode 8 and 9.

I have made the necessary changes to make it work with the NSCollectionView as this class doesn't support row actions I have added a button instead.

@rnystrom @jessesquires

**Comment by weyert** [comment]
I have also fixed the issue that you couldn't see the collection view animations. The backing view had to Core Animation enabled so I did this in IB and made a comment in the code. 

Looking forward to hear from you, what you think of this PR. Thanks!
