### ISSUE TITLE
Update [IGListSectionType didSelectItemAtIndex:] to pass back the cell

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#382]
We have a situation where we want to animate cell subviews when tapped.

The hook for this is `-[IGListSectionType didSelectItemAtIndex:]`, however it doesn't pass back the cell. 

It would be nice to do:

```objc
- (void)didSelectItemAtIndex:(NSInteger)index cell:(UICollectionViewCell *)cell {
     [cell animateSubview];
}
```

Current possible workarounds:

- Reload the section from the section controller (this updates the cell, but no animations)
- Delegate up the chain to do it

We can't do this:

```objc
- (void)didSelectItemAtIndex:(NSInteger)index {
    MyCell *cell = [self cellForItemAtIndex:index];
    // do stuff with cell
}
```

Because `cellForItemAtIndex:` will dequeue a new cell.

**Comment by jessesquires** [comment]
Actually, a better spelling for this would be:

`didSelectCell:(__kindof UICollectionViewCell *)cell atIndex:(NSInteger)index`

**Comment by mattyohe** [comment]
> Because cellForItemAtIndex: will dequeue a new cell.

`cellForRowAtIndexPath` will not dequeue a new cell.

**Comment by rnystrom** [comment]
@mattyohe `UICollectionView` [docs](https://developer.apple.com/reference/uikit/uicollectionview/1618088-cellforitem) say the same

> The cell object at the corresponding index path or nil if the cell is not visible or indexPath is out of range.

@jessesquires actually we can probably close this. The `UICollectionViewDelegate` API is

```objc
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath;
```

So we'd still have to use `-[UICollectionView cellForItemAtIndexPath:]` to get the cell 😄

**Comment by jessesquires** [comment]
Oops 😳 derp.

Yep, we can use the existing method:
https://github.com/Instagram/IGListKit/blob/master/Source/IGListCollectionContext.h#L49-L50
