### ISSUE TITLE
Clean internal NSArray copying

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#384]
After reading some internal threads, I realized we are calling `copy` on internal arrays too much. This is wasteful. Some examples:

- https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L495
- https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L544
- https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L376

There are many others. It'd be worth doing a full audit of our copy calls to remove waste.

Note that there _are_ valid uses of `copy`, e.g.

- https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L259
- https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L294

**Comment by AdamRobertsEF** [comment]
Done, see Pull request #403
