### ISSUE TITLE
Storyboard support

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#39]
I thought that storyboards would work out-of-the-box, but they don't. The adapter will attempt to register the cells, which probably writes over the cell registered as a prototype in the storyboard.

I think all we need to do is provide a dequeue method specifically for storyboards. This would skip checking and registering the cells. Something like:

```objc
- (__kindof UICollectionViewCell *)dequeueReusableCellFromStoryboardWithIdentifier:(NSString *)identifier forIndexPath:(NSIndexPath *)indexPath;
```

Note that we don't need to provide a cell class, unlike the current dequeue method, because the identifier is set in the storyboard.

**Comment by zhubofei** [comment]
@rnystrom Shall we close this issue?
