### ISSUE TITLE
IGListSingleSectionControllerDelegate selection function should include object

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#396]
Right now to get the object from the `selectionDelegate`, you have to:

```swift
func didSelect(_ sectionController: IGListSingleSectionController) {
  let object = adapter.object(for: sectionController)
  // do something
}
```

When `IGListSingleSectionController` already has [the object](https://github.com/Instagram/IGListKit/blob/master/Source/IGListSingleSectionController.m#L23), this lookup is wasteful.

I propose we change the delegate method to:

```objc
- (void)didSelectSingleSectionController:(IGListSingleSectionController *)sectionController 
  withObject:(id)object;
```

- What do you think about the naming? "withObject" or maybe just "object"?
- Should we shorten the method to just `didSelectSectionController`?

**Comment by Sherlouk** [comment]
For the Swift interop it would be nice for something like `didSelect(_ sectionController: .. with object: ..)`

If no one else takes it, I may give this a try?
