### ISSUE TITLE
Permanently disable the "Merge" PR button

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#399]
Talking w/ @orta this weekend we had an idea:

Since we want to disable _anyone_ from _ever_ clicking the merge button, how about we setup a simple service and use the [GH status API](https://developer.github.com/v3/repos/statuses/) to return `state: failure` for every single PR? No logic, no nothing, just fail every PR. That way we can stick to using our internal tools and add collaborators w/out having to warn ppl (sorry @Sherlouk @zhubofei 😅 ).

W/ the setup we have, I don't think there is ever a need to click that button.

**Comment by Sherlouk** [comment]
Don't have write access anyway, so can't press it even if I wanted to!

Sounds like an easy solution to the problem though

**Comment by rnystrom** [comment]
@Sherlouk 🤔  you should have write-access

**Comment by Sherlouk** [comment]
@rnystrom I just see this: http://prntscr.com/dth4xm (Buttons are disabled)

**Comment by rnystrom** [comment]
Hm interesting. I wonder if our tooling messed something up. Going to check internal settings and see what's up there.

**Comment by Sherlouk** [comment]
Assumed it was intentional to stop me pressing it!

**Comment by zhubofei** [comment]
I can confirm that the Merge Button was clickable to me for a really short period two days ago and then went grey.

**Comment by Sherlouk** [comment]
@rnystrom We have #394 which is to use Danger for automated PR verification, could we just add a fail clause for every pull request which is "Merges must be done internally"?

Saves having *another* service bound to the repo?

**Comment by rnystrom** [comment]
@Sherlouk totally agree
