### ISSUE TITLE
SizeForItem with custom layout

### ISSUE THREAD

**Issue by risp** [Instagram/IGListKit#400]
Hi, I was wondering how IGListKit works with a custom UICollectionViewLayout. I've a `CollectionViewHorizontalLayout` that asks the CollectionView for the size using this protocol:

```swift
protocol CollectionViewHorizontalLayoutDelegate { 
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, referenceSizeForHeaderInSection section: Int) -> CGSize
}
```
Before using IGListKit I returned the GCSize in the CollectionView. But with IGListKit the `IGListSectionController` controller should return the size. I'm not really sure how to do this. Especially since I'm using multiple IGListSectionControllers? 

And how does the size of an item and the UICollectionViewLayout relate to 
``` swift
public func sizeForItem(at index: Int) -> CGSize
```

I also searched in the examples but couldn't find anything related to customlayouts and dynamic sizes.

**Comment by rnystrom** [comment]
@risp we've added an API on `IGListAdapter` to do just that! [Here's the header docs](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.h#L212-L230).

So your setup should probably be something like:

```swift
class ViewController: UIViewController, MyLayoutDelegate {

  let adapter = IGListAdapter(...)	

  // MARK: MyLayoutDelegate

  func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
    return adapter.sizeForItem(at: indexPath)
  }

  func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, referenceSizeForHeaderInSection section: Int) -> CGSize {
    return adapter.sizeForSupplementaryView(ofKind: "header_kind_string", at: IndexPath(item: 0, section: section))
  }

}
```

**Comment by risp** [comment]
Thanks a lot, it's all clear now and works great!

**Comment by HumidBrains** [comment]
@rnystrom It would be so helpful with an example project using custom UICollectionViewLayout. Is it possible to dig one out? Thanks :)

**Comment by rnystrom** [comment]
@HumidBrains possibly! We're [in the middle](https://github.com/Instagram/IGListKit/pull/423#issuecomment-275225162) of adding one of our layouts, but it piggybacks off of `UICollectionViewDelegateFlowLayout`'s architecture (where the collection view data source is also the layout delegate).

W/out a custom layout that has this setup it's kind of tough to demonstrate, but there might be something we can do.

**Comment by HumidBrains** [comment]
@rnystrom Thank you so much, looking forward!
