### ISSUE TITLE
`-[IGListIndexSetResult hasChanges]` should instead be a readonly property

### ISSUE THREAD

**Issue by mdznr** [Instagram/IGListKit#402]
`-[IGListIndexSetResult hasChanges]` should instead be a readonly property.

IGListIndexSetResult.h:46 is currently:
```objc
- (BOOL)hasChanges;
```

it should instead be:
```objc
@property (nonatomic, assign, readonly) BOOL hasChanges;
```

**Comment by rnystrom** [comment]
I'm down with this. Not breaking for ObjC, breaking for Swift tho. But I think it makes more sense as a computed variable for Swift rather than a method. @jessesquires on board?

**Comment by jessesquires** [comment]
@rnystrom - Sounds good.

We have other breaking changes coming for 3.0.

**Comment by mdznr** [comment]
Thanks for the quick response!
