### ISSUE TITLE
Documentation Outdated

### ISSUE THREAD

**Issue by Sherlouk** [Instagram/IGListKit#406]
Not a biggie, but as of 279f348 the documentation is slightly [incorrect](https://instagram.github.io/IGListKit/Protocols/IGListSingleSectionControllerDelegate.html#/c:objc(pl)IGListSingleSectionControllerDelegate(im)didSelectSingleSectionController:)

cc: @jessesquires @rnystrom

**Comment by rnystrom** [comment]
I think that's fine. We're trying to only regen docs on `master` when we cut releases

**Comment by jessesquires** [comment]
Yep! especially with the new branching workflow, we should only re-gen docs when tagging releases.
