### ISSUE TITLE
Can IGListKit be used with Core Data and NSFetchedResultsController?

### ISSUE THREAD

**Issue by ybabenko** [Instagram/IGListKit#407]
Can IGListKit be used with Core Data and NSFetchedResultsController?

**Comment by rnystrom** [comment]
@ybabenko Core Data: yes! `NSFetchedResultsController`: probably not.

`NSFetchedResultsController` is really designed to be a `UITableView`'s data source with a few other bells & whistles. The majority of NSFRC setups I've seen us it for its animated updates, which IGListKit was built to solve.

IGListKit is really designed to be data-architecture-agnostic. Just feed the adapter some models, provide section controllers for them, and your collection view "just works".

The only thing you have to do with Core Data is make your models conform to `IGListDiffable` and you're good to go!

NSFRC also wasn't really designed with `UICollectionView` in mind. @jessesquires actually has a [library](https://github.com/jessesquires/JSQDataSourcesKit)) that makes it work tho.

**Comment by ybabenko** [comment]
@rnystrom Thank you.
