### ISSUE TITLE
Remove workingRangeSize from initializer

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#414]
Talked w/ @ocrickard, probably default disabled and allow setting the size (which would internally create and update the WR state) after initing the `IGListAdapter`.

Incredibly useful feature, but:

- Other apps have their own implementation
- We should investigate how well the `UICollectionView` prefetch API works
- Since this is a more advanced feature, most implementations don't need to think about it at init time

Options:

- 2 initializers (`initWithUpdater:viewController:` and `initWithUpdater:viewController:workingRangeSize:`
  - Makes transition easier
  - Maybe add `__attribute__ ((deprecated))` to the old init?
- `@property NSUInteger workingRangeSize`
  - Have to worry about setting after feed created and used. Means we have to find what the range is and what's in it so once scrolling starts we're g2g.

**Comment by BasThomas** [comment]
Which of the two options would you prefer and why?

**Comment by rnystrom** [comment]
@BasThomas let's do the first! I agree, easier for everyone.

**Comment by jessesquires** [comment]
@BasThomas if you want to / have time to do this within the next week or so, we can include in the 3.0 release 😄

**Comment by BasThomas** [comment]
So I was looking at this - do we want to deprecate and remove the option to provide a working range size completely? Or should we still provide the init for advanced usage?

**Comment by rnystrom** [comment]
@BasThomas let's leave the current init as the designated initializer still, but provide an initializer that internally does `workingRangeSize: 0`.

Also would you mind double-checking what work [IGListWorkingRangeHandler](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L47) does when the size is 0? I think it basically no-ops, but we _might_ want to wrap [initializing the handler](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L47) with something like:

```objc
if (workingRangeSize > 0) {
  _workingRangeHandler = // ...
}
```

Might want to sync w/ @ocrickard really quick too to see if that's the best course of action.

**Comment by BasThomas** [comment]
When we do a no-op (not initializing the `workingRangeHandler`), `test_whenDisplayingItemAtPath_withWorkingRangeSizeZero_thatItemEntersWorkingRange` and `test_whenDisplayingItemAtPath_withWorkingRangeSizeZero_thenHidingThatItem_thatItemLeavesWorkingRange` fail, as they seem to rely / test the rangeHandlers without them being present.

**Comment by rnystrom** [comment]
Hmmm. We can followup w/ another issue on that. We might want to consider removing those tests and not using the working range when size = 0.
