### ISSUE TITLE
Header/.m/.mm order clean up

### ISSUE THREAD

**Issue by AdamRobertsEF** [Instagram/IGListKit#416]
Suggestion to move .m and .mm files directly below header file for easier project navigation.

See screenshot below for before and after example.

![screen shot 2017-01-13 at 19 49 37](https://cloud.githubusercontent.com/assets/1706109/21943587/c28cb6be-d9c9-11e6-9075-dc00e456ad80.png)

![screen shot 2017-01-13 at 19 55 43](https://cloud.githubusercontent.com/assets/1706109/21943691/4e87b132-d9ca-11e6-96c6-5f2e7a57f287.png)

Thanks
Adam

**Comment by jessesquires** [comment]
yeah we just need to right-click -> "sort by name"

**Comment by rnystrom** [comment]
@AdamRobertsEF wanna PR it?

**Comment by AdamRobertsEF** [comment]
@rnystrom yes :-)
