### ISSUE TITLE
Add a method on diff results that is "safe for batch updates"

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#42]
New method should:
- Convert reloads+moves to insert+deletes
- Convert reloads to insert+deletes
  - This is proven to not be safe for `performBatchUpdates:completion:`

**Comment by jessesquires** [comment]
not needed anymore?

**Comment by rnystrom** [comment]
@jessesquires added in b5aa5e39002854c947e777c11ae241f67f24d19c forgot to ref this issue
