### ISSUE TITLE
Question about -[IGListAdapter performUpdatesAnimated:completion:]

### ISSUE THREAD

**Issue by PhilCai1993** [Instagram/IGListKit#420]
According to the doc, the animated parameter indicates whether transition is animated.
What does `transition` mean?

If I set animated to NO, the collectionview still performs an animated transition when it comes to `-[UICollectionView ig_applyBatchUpdateData:]`, where `deleteItemsAtIndexPaths:` and other updating methods are animated automatically.

Does that mean if I want a non-animated update, I should use the `IGListReloadDataUpdater` rather than `IGListAdapterUpdater`? Or call `reloadDataWithCompletion:` ?

Thanks a lot.

**Comment by rnystrom** [comment]
@PhilCai1993 it'll still use `-[UICollectionView performBatchUpdates:completion:]` under the hood, but [wrapped in a block](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L214-L216) that disables animations. If you're using `animated: NO` and its still animating the UI, could you file an issue w/ an example?

**Comment by PhilCai1993** [comment]
Oh, I'm sorry, it's totally my fault. Everything is OK😂
