### ISSUE TITLE
is performUpdatesAnimated always necessary when data changes?

### ISSUE THREAD

**Issue by danywarner** [Instagram/IGListKit#421]
I've been implementing IGListKit on my current project but I read that:

> IGListKit automatically diffs your objects and performs animated batch updates on the UICollectionView for whatever changed.

However, I set the collectionView array but whenever it changes, the collectionView is not automatically updated unless I call performUpdatesAnimated

Am I missing something? because the idea I got was that IGListKit automatically performed all the updates for me.

**Comment by rnystrom** [comment]
@danywarner can you point out where that copy is? I remember seeing it before, its not in our repo but I might be able to clean that up.

For clarification, IGListKit doesn't observe changes in your data source. That'd require us use some KVO or ReactiveCocoa mechanism. It's totally doable, but we don't want to dictate how your stuff gets updated.

Your'e spot on though, whenever your data changes you need to call `performUpdatesAnimated:completion:` to update the actual view state.

**Comment by Sherlouk** [comment]
@rnystrom Possibly referring to the paragraph in this tutorial: https://www.raywenderlich.com/147162/iglistkit-tutorial-better-uicollectionviews

(Under "Introducing IGListKit")
