### ISSUE TITLE
Is it right to use OBJC_ASSOCIATION_ASSIGN?

### ISSUE THREAD

**Issue by PhilCai1993** [Instagram/IGListKit#424]
I've updated pod to 2.1.0, and when I am applying it to my project, I found [this](https://github.com/Instagram/IGListKit/blob/master/Source/IGListStackedSectionController.m#L36) a little strange:

```
- (void)ig_setStackedSectionControllerIndex:(NSInteger)stackedSectionControllerIndex {
    objc_setAssociatedObject(self, kStackedSectionControllerIndexKey, @(stackedSectionControllerIndex), OBJC_ASSOCIATION_ASSIGN);
}
```

Since it's assigning an NSNumber to `UICollectionViewCell `, should it be `OBJC_ASSOCIATION_COPY_NONATOMIC` instead?

Thanks.

**Comment by rnystrom** [comment]
@PhilCai1993 yup good catch!

**Comment by PhilCai1993** [comment]
I've created a merge request [here](https://github.com/Instagram/IGListKit/pull/426).
