### ISSUE TITLE
Any examples of basic IGListKit in Objective-C?

### ISSUE THREAD

**Issue by farhansyed9** [Instagram/IGListKit#425]
Wondering if theres any basic examples of working IGListKit in Objective-C.

**Comment by rnystrom** [comment]
@farhansyed9 there aren't, but I've gotten this question so many times that I think there needs to be. Let's add a new example VC, section controllers, and cells using ObJC!

**Comment by liuxz656** [comment]
Wondering too...

**Comment by charles0126dev** [comment]
@farhansyed9 @liuxz656 @rnystrom 
I have just uploaded  [an ObjC demo](https://github.com/charles0126dev/IGListObjcDemo) to my repository.  Maybe it is helpful.

**Comment by Sherlouk** [comment]
@rnystrom Did we want to have a single project (Examples-iOS) with both ObjC and Swift, or to create a new pack (Examples-iOS-ObjC) to keep them separate?

**Comment by rnystrom** [comment]
@Sherlouk nah single ObjC VC+SC+cell in the current `Examples-iOS` is fine I think. Don't want to make the examples too complicated. Thoughts?

**Comment by charles0126dev** [comment]
@rnystrom   Actually, it's totally identical. 😀  And I will PR it ASAP.

**Comment by jessesquires** [comment]
fixed in #446
