### ISSUE TITLE
IGListExperiment is not used anywhere?

### ISSUE THREAD

**Issue by PhilCai1993** [Instagram/IGListKit#427]
I'm wondering what is `IGListExperiment` and since it exists, what is it designed for?

**Comment by rnystrom** [comment]
@PhilCai1993 its not right now, ya. We use this to inject different types of experiments/tests into the framework. e.g. we added [background reloading](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L157-L166) but wanted to confirm that it worked as intended. We use A/B testing at Instagram to confirm hypothesis on experimental changes/features.
