### ISSUE TITLE
Sporadic build/test failures

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#428]
I keep seeing build errors. Not totally sure what this is. @jessesquires any ideas?

e.g. https://travis-ci.org/Instagram/IGListKit/jobs/192983683

> Error Domain=IDETestOperationsObserverErrorDomain Code=12 "Failed to background test runner. If you believe this error represents a bug, please attach the log file at ..."

Here's the raw error:

```
2017-01-18 12:35:22.720 xcodebuild[1964:6537] Error Domain=IDETestOperationsObserverErrorDomain Code=12 "Failed to background test runner. If you believe this error represents a bug, please attach the log file at /Users/travis/Library/Developer/Xcode/DerivedData/IGListKitExamples-cfbxdbnpimeeplcoaiqrlyrrqjxn/Logs/Test/C85E98F2-F395-4148-A47F-4DFF374A3349/Session-IGListKitExamples-UITests-2017-01-18_123106-QT629f.log" UserInfo={NSLocalizedDescription=Failed to background test runner. If you believe this error represents a bug, please attach the log file at /Users/travis/Library/Developer/Xcode/DerivedData/IGListKitExamples-cfbxdbnpimeeplcoaiqrlyrrqjxn/Logs/Test/C85E98F2-F395-4148-A47F-4DFF374A3349/Session-IGListKitExamples-UITests-2017-01-18_123106-QT629f.log}
Testing failed:
	Test target IGListKitExamples-UITests encountered an error (Failed to background test runner. If you believe this error represents a bug, please attach the log file at /Users/travis/Library/Developer/Xcode/DerivedData/IGListKitExamples-cfbxdbnpimeeplcoaiqrlyrrqjxn/Logs/Test/C85E98F2-F395-4148-A47F-4DFF374A3349/Session-IGListKitExamples-UITests-2017-01-18_123106-QT629f.log)
** TEST FAILED **
The command "if [ $RUN_UI_TESTS == "YES" ] && [ $SDK == $IOS_SDK ]; then xcodebuild build test -workspace "$IOS_EXAMPLE_WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c; fi" exited with 65.
```

**Comment by jessesquires** [comment]
Hm... looks like flaky UI tests.

Everything runs ok locally?

**Comment by rnystrom** [comment]
> Everything runs ok locally?

brb

**Comment by rnystrom** [comment]
@jessesquires ya it works. It's using [iPhone 6s and iOS 10.1](https://github.com/Instagram/IGListKit/blob/master/.travis.yml#L38). Do we need to bump to 10.2?

**Comment by rnystrom** [comment]
Another random failure:

https://travis-ci.org/Instagram/IGListKit/jobs/191790549

> Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7f882e329ba0>
> Error Domain=IDETestOperationsObserverErrorDomain Code=3 "The operation couldn’t be completed. (DTXProxyChannel error 1.) If you believe this error represents a bug, please attach the log file at

**Comment by jessesquires** [comment]
yeah we can see if 10.2 is more reliable

**Comment by zhubofei** [comment]
@rnystrom @jessesquires  #432 failed on both 10.1 & 10.2
https://travis-ci.org/Instagram/IGListKit/jobs/194536882
https://travis-ci.org/Instagram/IGListKit/jobs/194536883

**Comment by jessesquires** [comment]
meh. i think this is as good as it's going to get

**Comment by Sherlouk** [comment]
Unless there genuinely is a test fail, there's not much we can do with inconsistent test results besides using the latest SDKs and hoping it gets improved upon

**Comment by jessesquires** [comment]
btw, we can always re-start the specific builds that fail in the travis-ci UI

(maybe only @rnystrom and i have permissions though)

**Comment by Sherlouk** [comment]
@jessesquires Just checked, can restart builds -- must be part of collaborator status!
