### ISSUE TITLE
Remove reloadIndexPaths: from IGListBatchUpdateData

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#429]
~~Blocked by #418~~

We should remove the ability to call `-[UICollectionView reloadIndexPaths:]` completely since we are trying to force everything to go through `performBatchUpdates:`

https://github.com/Instagram/IGListKit/blob/master/Source/Internal/UICollectionView%2BIGListBatchUpdateData.m#L19

**Comment by jessesquires** [comment]
is this a breaking change?

**Comment by rnystrom** [comment]
@jessesquires I don't think so, only breaking internally

**Comment by rnystrom** [comment]
Will also happen when #392 lands
