### ISSUE TITLE
Coveralls reporting "Change unknown"

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#434]
Something is broken. While we're at it let's also kill posting. We can just keep an eye on the badge.

**Comment by jessesquires** [comment]
are there settings to limit the posting?

**Comment by rnystrom** [comment]
@jessesquires there aren't, its all or nothing

**Comment by Sherlouk** [comment]
As mentioned previously on Twitter, we can probably get away with turning the comments off and just relying on GitHub status at the bottom of PRs

![image](https://cloud.githubusercontent.com/assets/15193942/22153384/05056ba8-df1f-11e6-99df-4c8c7a44c75e.png)

It'll show the last comment that Coveralls would've said, whether that's an increase, decrease or the same.

**Comment by rnystrom** [comment]
@Sherlouk yup spot on

**Comment by rnystrom** [comment]
Reported to OSS oncall internally, they will turn off commenting
