### ISSUE TITLE
Get cell indexPath and data via CGPoint location

### ISSUE THREAD

**Issue by shuhrat10** [Instagram/IGListKit#439]
Hi, 

I have IGListKit with multiple sections which contain embedded IGCollectionView. I wonder how can I get master and child IndexPath from UIViewController and then get data for each IndexPath.

Thanks!

**Comment by rnystrom** [comment]
@shuhrat10 sure thing, should be really easy! And you don't have to use any IGListKit stuff in fact:

```swift
let path = collectionView.indexPathForItem(at: point)
let object = adapter.object(atSection: path.section)
```

I wonder if this would be a good API on `IGListAdapter` @jessesquires?

**Comment by shuhrat10** [comment]
@rnystrom I did that, but I'm getting only section. I think once I get section cell, I need to convertPoint to get IndexPath from child IGCollectionView.

**Comment by rnystrom** [comment]
Ooooh, _embedded_ collection view. I skipped over that. Here's a quick thought that might get you on the right path:

```swift
let path = collectionView.indexPathForItem(at: point)
let object = adapter.object(atSection: path.section)
if let cell = collectionView.cellForItem(at: path) as? EmbeddedCollectionViewCell,
    let sectionController = adapter.sectionController(for: object) as? NestedAdapterViewController {
    let subPoint = cell.collectionView.convert(point, from: collectionView)
    let subPath = cell.collectionView.indexPathForItem(at: subPoint)
    let subObject = sectionController.adapter.object(atSection: subPath.section)
}
```

I'm using classes in our example project, assuming your setup is similar.

**Comment by shuhrat10** [comment]
@rnystrom thank you very much! It's working as expected
