### ISSUE TITLE
[enhancement] Capability of applying different inset or item/line spacing to every section controller of IGListStackedSectionController.

### ISSUE THREAD

**Issue by ShaneQi** [Instagram/IGListKit#448]
## New issue checklist

- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): 10.2
- CocoaPods/Carthage version: 1.1.1
- Xcode version: 8.2
- Devices/Simulators affected: both
- Reproducible in the demo project?: Yes
- Related issues: None

===============

Let's say I have a stackedSectionController managing three section controllers:

```swift
...
let stackedSectionController = IGListStackedSectionController(sectionControllers: [
	SectionControllerAAA(),
	SectionControllerBBB(),
	SectionControllerCCC(),
	])
...
```

If I want to only give inset and line spacing to `SectionControllerAAA`.  
The problem is: setting inset and line spacing in `SectionControllerAAA`'s initializer does't work. Because it is managed by `stackedSectionController` (__I assumed all cells of all three sub section controllers are combined into a single section controller__).

So I set inset and line spacing to the `stackedSectionController`:

```swift
...
stackedSectionController?.inset = UIEdgeInsets(top: 5, left: 5, bottom: 5, right: 5)
stackedSectionController?.minimumLineSpacing = 5
...
```

But another problem would be:  
Setting inset and line spacing on `stackedSectionController` would effects all the three section controllers (and top/bottom inset doesn't apply between different sub section controllers) which is obviously not what I want in this case.

So I suggest to enhance IGListKit with the capability of applying different inset or item/line spacing to every section controller of IGListStackedSectionController.

I haven't got a chance look into it yet, so that I don't have the idea how complicated this enhancement would be. If this suggestion makes sense to you guys, I will go ahead try to do this.

**Comment by rnystrom** [comment]
I love this idea, but I think that w/out a heavily customized `UICollectionViewLayout` that is designed specifically to integrate w/ IGListKit, it'll be almost impossible. `UICollectionViewFlowLayout` only applies insets to the entire section. The new layout we're introducing in #449 also uses that logic.

We could look into extending the new layout w/ this, but atm I think it's going to be too complicated.

IMO if the sections need to behave that differently, I wonder if they belong in the stack in the first place?

@ShaneQi mind if we close this?

**Comment by ShaneQi** [comment]
@rnystrom 
I looked into source code a little bit earlier today, seems too complicated, not worthy.
Also, my model is too complicated which makes layout complicated. I may need to simplify my model in the first place.  

I agree we close this issue.  
Thanks for the time!

**Comment by denisenkoaj** [comment]
Hello guys. Want to up this topic.
Is there any way to make space between SectionControllers inside IGListStackedSectionController ?

**Comment by rnystrom** [comment]
Unfortunately we're planning on deprecating `IGListStackedSectionController` (see #1099), but even if we weren't this would require a custom `UICollectionViewLayout`.
