### ISSUE TITLE
`estimatedItemSize` causes crash because collectionView asks for size of non-existing cells.

### ISSUE THREAD

**Issue by ShaneQi** [Instagram/IGListKit#452]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): 10.2
- CocoaPods version: 1.1.1
- Xcode version: 8.2
- Devices/Simulators affected: Both affected.
- Reproducible in the demo project? (Yes/No): __Yes ([IGListKitCellSizeCrashing](https://github.com/ShaneQi/IGListKitCellSizeCrashing/blob/master/Podfile.lock))__
- Related issues: None.

---

The pre-condition is that `estimatedItemSize` is set on collectionVIew's layout:

```swift
let layout = UICollectionViewFlowLayout()
layout.estimatedItemSize = CGSize(width: 100, height: 40)
collectionView.setCollectionViewLayout(layout, animated: false)
```

Then the problem is that:  
When I use `adapter.reloadData()`, the collectionView will ask size of cells in __old indices__ on __new sectionController__.  
For example, before `adapter.reloadData()`, the collectionView has 10 cells, after `adapter.reloadData()` called, the collectionView will have 5 cells. But after `adapter.reloadData()` called, the collectionView will ask for sizes of the 10 cells firstly then ask sizes of the 5 new cells.

In most cases, this doesn't cause crash. But:

- If in the size delegate of `IGListSectionType`, size is related to the index, it may cause crash because __old indices__ are passed in. (demonstrated in [IGListKitCellSizeCrashing](https://github.com/ShaneQi/IGListKitCellSizeCrashing/blob/master/Podfile.lock))
- If the new sectionController is a stackedSectionController, when __old indices__ are passed in, the stackedSectionController will not be able to find the sectionController of the incorrect indices. (will add this case later into [IGListKitCellSizeCrashing](https://github.com/ShaneQi/IGListKitCellSizeCrashing/blob/master/Podfile.lock))

Crash can be reproduced very easily in this demo project:  
([IGListKitCellSizeCrashing](https://github.com/ShaneQi/IGListKitCellSizeCrashing/blob/master/Podfile.lock))

**Comment by rnystrom** [comment]
:heart for providing a demo project! Will dive into this. I know we added a [layout invalidation](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L85) to reloading, but that's after data source changes are applied.

Estimated cell sizing is the bane of my existence, but I want to make sure we support as many `UICollectionView` features as possible.

**Comment by jessesquires** [comment]
Closing in favor of #516
