### ISSUE TITLE
IGListStackedSectionController to respect children insets

### ISSUE THREAD

**Issue by ninokierulf** [Instagram/IGListKit#467]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- tvos version(s): 10.1
- CocoaPods/Carthage version: 1.2.0
- Xcode version: 8.2.1

#### Issue
IGListStackedSectionController encapsulates child section controllers.
If insets were set for each separate child section controllers,
insets of the child section controllers are not applied.
Instead, the set inset of IGListStackedSectionController is the only visible change.
Child section controller's insets are not changed, so layout is not desirable.

**Comment by zhubofei** [comment]
@ninokierulf Dup with #448
