### ISSUE TITLE
Disable Wiki

### ISSUE THREAD

**Issue by KrauseFx** [Instagram/IGListKit#47]
Similar to https://github.com/KrauseFx/xcode-install/issues/118, according to @jhersh, all internet tubes are clogged 👍

**Comment by rnystrom** [comment]
Proposal tag just for you @KrauseFx

**Comment by KrauseFx** [comment]
Haha, the downvote is just by the troll @neonichu, and as long as there is no content in the Wiki, we can disable it 👍

**Comment by jessesquires** [comment]
+1

**Comment by rnystrom** [comment]
done!

**Comment by KrauseFx** [comment]
Thanks, finally! Feels much faster again 🚀
