### ISSUE TITLE
Update CONTRIUBUTING.md

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#473]
https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md

Let's add:

- How we do major and minor releases:
  - https://github.com/Instagram/IGListKit/issues/471#issuecomment-278161714
- A "launch checklist" template (e.g. #471)
- Testing philosophy (total coverage)
- Update coding style
  - Restrict subclassing (objc macro, `final` in examples)
  - ivars v props
  - local vars instead of `self.prop` over & over

Anything I'm missing?

**Comment by jessesquires** [comment]
https://github.com/Instagram/IGListKit/blob/master/.github/RELEASE_CHECKLIST.md

😄

**Comment by rnystrom** [comment]
Good point I should have documented that:

Basically we want 99% test coverage at all times. So if you're adding new stuff, get it tested.

When fixing bugs, try your hardest to recreate the bug in a unit test, then fix the test. This sets us up to never regress that issue again.

**Comment by agisilaos** [comment]
Ok, gonna add that with the Title: **Testing philosophy** and the points  you mentioned :)

**Comment by agisilaos** [comment]
Ok here's the Pull request I just made: https://github.com/Instagram/IGListKit/pull/558
