### ISSUE TITLE
Migration guide for 2.x to 3.x breaking changes

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#475]
We'll need to add a new section to the migration guide for the 3.0 release.

https://github.com/Instagram/IGListKit/blob/master/Guides/Migration.md

Maybe we can keep a running list on this thread?

**Comment by agisilaos** [comment]
Hey @jessesquires! Gonna start diving around to help you with this task! :)

**Comment by jessesquires** [comment]
Hey @agisilaos ! 💯 Awesome 🎉 

So:

- there's one guide example already (1.x to 2.x) -- let's follow that format.
- all changes are in the `CHANGELOG`

The migration guide should focus on the big changes and how to adopt them. We don't need to discuss small things, like method/class renaming — the `CHANGELOG` is sufficient for that.

**Comment by rnystrom** [comment]
Super important are the [breaking changes](https://github.com/Instagram/IGListKit/blob/master/CHANGELOG.md#breaking-changes) for 3.0.0. I don't think there's anything too crazy in there.

Thanks @agisilaos for taking this on!! This will help us release 3.0 even faster.

**Comment by rnystrom** [comment]
Also we should detail how to migrate from the old grid layout to the new one. See #559
