### ISSUE TITLE
Support for NIB Cells?

### ISSUE THREAD

**Issue by talkaboutdesign** [Instagram/IGListKit#481]
Does IGListKit support NIBs or Storyboards for Cells?

**Comment by rnystrom** [comment]
Yup! We have APIs [like this](https://github.com/Instagram/IGListKit/blob/master/Source/IGListCollectionContext.h#L96-L124) to dequeue cells and supplementary views from nibs + storyboards. There are also [some examples](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/ViewControllers/StoryboardViewController.swift) of this in use.
