### ISSUE TITLE
IGListCollectionViewLayout line spacing not working

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#485]
The check for `if (item > 0)` is outdated now. If it is newlining it should always add the line spacing to the Y offset.

**Comment by rnystrom** [comment]
Nevermind, line spacing should only affect spacing **between items in the same section**.

https://developer.apple.com/library/content/documentation/WindowsViews/Conceptual/CollectionViewPGforIOS/UsingtheFlowLayout/UsingtheFlowLayout.html

**Comment by HowardCsie** [comment]
How can i make line spacing  between sections?

**Comment by rnystrom** [comment]
@HowardCsie you should be able to use the [inset](https://github.com/Instagram/IGListKit/blob/master/Source/IGListSectionController.h#L55) in your section controller which will add spacing to the top/left/right/bottom between sections. If you want spacing between items use [minimumLineSpacing](https://github.com/Instagram/IGListKit/blob/master/Source/IGListSectionController.h#L62) or [minimumInteritemSpacing](https://github.com/Instagram/IGListKit/blob/master/Source/IGListSectionController.h#L69).

There's a few [docs](https://github.com/Instagram/IGListKit/blob/master/Source/IGListCollectionViewLayout.h#L56-L66) on how this works, but the [tests](https://github.com/Instagram/IGListKit/blob/master/Tests/IGListCollectionViewLayoutTests.m) have more explicit examples on how it should all work.

**Comment by RuofeiLv** [comment]
@rnystrom  So in order to achive the **same** effect like instagram grid, we should set the 
 self.minimumInteritemSpacing=1.0;
 self.inset=UIEdgeInsetsMake(0.5, 0, 0.5, 0);
to make each section have 1 px padding around.

Though it works, but it's looks strange. I think use minimumLineSpacing and minimumInteritemSpacing to make it happen seems more comfortable.
