### ISSUE TITLE
Automatic Cell Size with UITextView

### ISSUE THREAD

**Issue by dennisgec** [Instagram/IGListKit#487]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): 9.0 - 10.0
- CocoaPods/Carthage version: 1.1.1
- Xcode version: 8.2.1
- Devices/Simulators affected: iPhone 7
- Reproducible in the demo project? (Yes/No): No
- Related issues: --

![img_1024](https://cloud.githubusercontent.com/assets/15718311/22880399/49dacd10-f1e2-11e6-8069-3e8ec03d84d2.PNG)

I am using IGListKit extensively in my entire iOS App. What I would want to achieve is a Text View inside a CollectionCell and have it auto size, by the dynamic text contained in that Text View. I saw in the Instagram app, that you have this feature built in, are you using IGListKit in the Edit Porfile Screen. If yes I would really appreciate, how you pulled it off.

Thank in advance.

**Comment by rnystrom** [comment]
@dennisgec we aren't using IGListKit to size our editable cells yet, this is a good question though! We probably need to get #459 working for this to work really well since reloading the cell will recycle the view.

Going to get a PR up for that very soon!

**Comment by dennisgec** [comment]
@rnystrom Good to know, thanks already for getting back that quickly.

**Comment by jessesquires** [comment]
Closing to track at #516
