### ISSUE TITLE
Dynamic section height while keeping image aspect ratio

### ISSUE THREAD

**Issue by joecarey81** [Instagram/IGListKit#489]
How would I size a full screen width section's height for a downloaded image and keep its aspect ratio correct?

**Comment by rnystrom** [comment]
@joecarey81 in Instagram the server sends the aspect ratio of the media as part of the JSON response. The we take the `collectionContext.containerSize.width * aspectRatio` to find the appropriate height. This makes calculating the size super cheap/efficient.
