### ISSUE TITLE
Initialize containers with capacity

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#492]
This is a mostly negligible perf gain for modern devices, but its a measurable improvement (less resizes, etc). Might as well opt in.

Should be doable for:

- `NSMutableDictionary`
- `NSMutable(Ordered)Set`
- `NSMutableArray`

Reading:

- http://ridiculousfish.com/blog/posts/array.html
- http://www.cocoawithlove.com/2008/08/nsarray-or-nsset-nsdictionary-or.html

But does [this article](http://ciechanowski.me/blog/2014/03/05/exposing-nsmutablearray/) debunk the value in this? Looks like the initial size is always 16?

(note: I know this is just bikeshedding, but its a fun topic nonetheless)

**Comment by jessesquires** [comment]
lol

**Comment by rnystrom** [comment]
Doesn't matter

**Comment by jessesquires** [comment]
lol
