### ISSUE TITLE
How to make dynamic height and fix width equal to collection view frame width

### ISSUE THREAD

**Issue by alexwillrock** [Instagram/IGListKit#497]
## New issue checklist

- [ OK] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ OK] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.2.0
- iOS version(s): 10+
- CocoaPods/Carthage version: 
- Xcode version: 8+
- Devices/Simulators affected: Simulators
- Reproducible in the demo project? (Yes/No): NO
- Related issues:

how to make dynamic height and fix width in cell ?
in controller my code is:
` UICollectionViewFlowLayout *layout = [[UICollectionViewFlowLayout alloc] init];
    layout.estimatedItemSize = CGSizeMake(self.collectionView.frame.size.width, 137);
    self.collectionView.collectionViewLayout = layout;`

is section controller my code is:

```
- (CGSize)sizeForItemAtIndex:(NSInteger)index {

    CGFloat width = self.collectionContext.containerSize.width;
    CGFloat height = 137;

    CGSize result = CGSizeMake(width, height);
    return result;
}
```

and in collection cell:

```
-(UICollectionViewLayoutAttributes *)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes *)layoutAttributes{
    
    if (_isCalculate == false) {
        
       // [super preferredLayoutAttributesFittingAttributes:layoutAttributes];
        
        [self setNeedsLayout];
        [self layoutIfNeeded];
        
        CGSize size = [self.contentView systemLayoutSizeFittingSize:layoutAttributes.size];
        
        CGRect newFrame = layoutAttributes.frame;
        newFrame.size.width = (CGFloat)ceilf(size.width);
        
        NSLog(@"%@", newFrame);
        
        layoutAttributes.frame = newFrame;
        _isCalculate = true;
        
        
    }  
    return layoutAttributes;
}
```

And my cell is not fill width equal to collection view width, can you help me ?

**Comment by edwinkcw** [comment]
I think you shouldn't change the width of the newFrame, you should just change the height only. As in the sample code 
https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/Views/FullWidthSelfSizingCell.swift#L44

```
    override func preferredLayoutAttributesFitting(_ layoutAttributes: UICollectionViewLayoutAttributes) -> UICollectionViewLayoutAttributes {
        setNeedsLayout()
        layoutIfNeeded()
        let size = contentView.systemLayoutSizeFitting(layoutAttributes.size)
        var newFrame = layoutAttributes.frame
        // note: don't change the width
        newFrame.size.height = ceil(size.height)
        layoutAttributes.frame = newFrame
        return layoutAttributes
    }
```

**Comment by alexwillrock** [comment]
> edwinkcw

Thanks, you saved my day, it's work perfectly ))

**Comment by damian-rzeszot** [comment]
@edwinkcw any idea why `setNeedsLayout` and `layoutIfNeeded` are obligatory for valid size?
