### ISSUE TITLE
"Claimed" label for issues

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#504]
Thoughts? Some people want to grab a starter-task, but then see there's already a PR or someone working on it. I don't think we can assign stuff to people that aren't collabs.

How do other projects handle people working async?

**Comment by jessesquires** [comment]
We could try using GH projects: 

- https://help.github.com/articles/about-projects/
- https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features

With projects, issues can have an explicit state ("ready", "in-progress", etc.)

**Comment by jessesquires** [comment]
good to close this?

**Comment by rnystrom** [comment]
@jessesquires ya, don't think this has caused much churn, don't think it matters atm
