### ISSUE TITLE
Is `isEqualToDiffableObject:` necessary

### ISSUE THREAD

**Issue by PhilCai1993** [Instagram/IGListKit#509]
`IGListDiffable` protocol requires `isEqualToDiffableObject:` and `diffIdentifier`.

But I think `diffIdentifier` is enough to do the diff.

Why do I think `isEqualToDiffableObject:` is not necessary?

Sometimes it's possible that the implementation of `diffIdentifier` and `isEqualToDiffableObject:` is not consistent.

The simplest way is just return "`self `" for diffIdentifier.

```
@interface ClassA ()<IGListDiffable>
@interface ClassB ()<IGListDiffable>
...
- (nonnull id<NSObject>)diffIdentifier {
   return self;
}
```

And both `ClassA` and `ClassB` could optionally implement their own `-isEqual:` and `-hash`, according to their needs.

As a result, `[id<IGListDiffable>instance1.diffIdentifier isEqual:id<IGListDiffable>instance2.diffIdentifier]` becomes `[instance1 isEqual:instance2]`.

**Comment by rnystrom** [comment]
Good question! So we actually didn't use to have `isEqualToDiffableObject:` at all! We just used `isEqual:`.

The point of having the two methods has to do with **identity** and **equality**, where the diff identifier uniquely identifies data (common scenario is primary key in databases). Equality comes into play when comparing the **values** of two uniquely identical objects (driving reloading).

> For even more history, we originally set out to just use `hash` and `isEqual:`, but after @ryanolsonk and I filled up too many whiteboards, we settled on having an object-based identifier.

**Comment by PhilCai1993** [comment]
I thought about this because of #503 
I guess that crash lies in the inconsistence of the two methods.

**Comment by jessesquires** [comment]
@rnystrom - should we update the diffable guide with this discussion?

https://instagram.github.io/IGListKit/iglistdiffable-and-equality.html

**Comment by rnystrom** [comment]
@jessesquires ya lets

**Comment by jessesquires** [comment]
closing as resolved
