### ISSUE TITLE
When use `estimatedItemSize` and there is only one cell in the section: the cell is center aligned (should be aligned left).

### ISSUE THREAD

**Issue by ShaneQi** [Instagram/IGListKit#520]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): 10.2
- CocoaPods/Carthage version: 1.2.0
- Xcode version: 8.2.1
- Devices/Simulators affected: both
- Reproducible in the demo project? (Yes): Details described below.
- Related issues: maybe #516 

This issue is totally reproducible in demo project with two simple steps:

1. In file [MixedDataViewController.swift](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/ViewControllers/MixedDataViewController.swift#L27):  
Change the `itemCount` to `1`.

2. In viewDidLoad function of file [MixedDataViewController.swift](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/ViewControllers/MixedDataViewController.swift#L58):  
Add this snippet of code to set estimated cell size:  
```swift
let layout = UICollectionViewFlowLayout()
layout.estimatedItemSize = CGSize(width: 50, height: 50)
collectionView.setCollectionViewLayout(layout, animated: false)
```

Then when run the project and goto Mixed Data view, it will turn out to be like:
__(The single cell section center aligns the cell, which should be aligned left.)__

<img width="423" alt="screen shot 2017-02-28 at 6 16 05 pm" src="https://cloud.githubusercontent.com/assets/7324708/23440525/ff7799a4-fde1-11e6-845c-efd52e1d9eb9.png">

**Comment by jessesquires** [comment]
Probably just as to do with item spacing or other flow layout settings?

**Comment by ShaneQi** [comment]
I tried the same without IGListKit, the issue still exists. It turned out not a issue of IGListKit.

Sorry for mis-reporting. I will close this issue.

**Comment by filippkos** [comment]
Did you manage to find a solution to this problem?

**Comment by heykomikmi** [comment]
Hacked

iPhone’umdan gönderildi

Filipp Kosenko ***@***.***> şunları yazdı (14 May 2023 ÖS 12:19):

﻿

Did you manage to find a solution to this problem?

**Comment by ShaneQi** [comment]
@filippkos @heykomikmi 

TBH I don't remember how I worked around it. I think I customized the collectionview flowlayout for the cell to be where I wanted it to be at.
