### ISSUE TITLE
3D Touch peek and pop

### ISSUE THREAD

**Issue by HarshilShah** [Instagram/IGListKit#523]
## New issue checklist

- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)

### General information

- `IGListKit` version: 2.1.0

I’m curious if there are any plans for implementing 3D Touch peek and pop / preview and commit within IGListKit. Being able to set up actions within sections, with say `didPeekItem` and `didPopItem` similar to the existing `didSelectItem` would be great.

**Comment by rnystrom** [comment]
Hey @HarshilShah, good question! No plans to support anything with 3D touch at the moment, mostly b/c its outside of the scope of what IGListKit set out to do. In Instagram, we have our own 3D touch handling that works alongside IGListKit (and IGListKit makes getting data from UI state hella easy) but its not a first-class feature.

**Comment by HarshilShah** [comment]
Fair enough. Would love to read more about your implementation, if possible.

**Comment by heumn** [comment]
> Fair enough. Would love to read more about your implementation, if possible.

Me too :)

> outside of the scope of what IGListKit set out to do

👌  💯

**Comment by davidseek** [comment]
1+ on a little doc about your version.
as i have tried to implement peek & pop and i'm getting incorrect indexPath values for the location

any chance to get some code snippets on your version? @rnystrom

**Comment by JackIrish** [comment]
> 1+ on a little doc about your version.
> as i have tried to implement peek & pop and i'm getting incorrect indexPath values for the location
> 
> any chance to get some code snippets on your version? @rnystrom

I'm getting an incorrect indexPath value for the location as well. Did you manage to figure this out?
