### ISSUE TITLE
Cell preselection

### ISSUE THREAD

**Issue by pharosproduction** [Instagram/IGListKit#524]
I'm trying to preselect a cell in `cellForItem(at index: Int) -> UICollectionViewCell` by `cell.isSelected = true` in section controller.
It works fine and cell becomes selected. When I try to deselect a cell by tapping it cell doesn't react at all. Tap triggers `isHighlighted` method but doesn't want to trigger neither `isSelected` in cell nor `didDeselectItemAt` delegate method.
This issue is related only to preselected cells. All other cells work fine in the same collection.

**Comment by rnystrom** [comment]
@pharosproduction can you describe a bit what you're trying to do? `UICollectionViewCell` selection APIs aren't really supposed to be changed manually, you're supposed to let the `UICollectionView` internals handle all of that for you.

The [docs](https://developer.apple.com/reference/uikit/uicollectionviewcell/1620130-isselected) say:

> You typically do not set the value of this property directly. Changing the value of this property programmatically does not change the appearance of the cell. The preferred way to select the cell and highlight it is to use the selection methods of the collection view object.

If you're trying to do custom selection state, we recommend making your own properties and settings.

**Comment by pharosproduction** [comment]
There is a `Set` of groups displayed as a two column list, one section with one row for each group. Some of them should be selected when list appears. Each group contains a selection state(bool). Groups amount is a variable(pagination load). What is the best way to select marked for selection cells and where?
I have tried already different approaches including `selectItem(at: IndexPath?, animated: Bool, scrollPosition: UICollectionViewScrollPosition)` but no luck to find the best way to do this. The goal is just to select a cell without triggering any delegate methods so user can deselect it or proceed with a default selection set(fetched by `indexPathForSelectedItems`)

**Comment by rnystrom** [comment]
@pharosproduction at Instagram we use custom properties to represent selected state in our UI instead of relying on the `UICollectionView` built-in stuff. We would do something like:

- Add a custom `@property BOOL checkmarkDisplayed;` to our cell subclass
- In the `setCheckmarkDisplayed:(BOOL)checkmarkDisplayed` setter, set the state and call `[self setNeedsLayout]` and set `hidden` on our checkmark image view
- Position the view in `layoutSubviews`

Then in `cellForItemAtIndex:` we can manually set the state w/out worrying about `UICollectionView` internals.

Then in `didSelectItemAtIndex:` you can flip the selection state, both in the cell and wherever you're tracking it.

**Comment by pharosproduction** [comment]
Got it. Thanks.
BTW, `collectionView` doesn't trigger `didSelectItemAtIndex:`, only `deselect`. Is it possible to switch from `didSelectItem(at index: Int)` in section to `collectionView` delegate without loosing all other `IGListSectionController` functionality?

**Comment by rnystrom** [comment]
@pharosproduction you mean to use the `UICollectionViewDelegate` APIs alongside `IGListSectionController`? It's possible, but not at the section-controller level. You can attach a [collectionViewDelegate](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.h#L69) to the adapter to get all the normal delegate events.

**Comment by pharosproduction** [comment]
No, on ViewController level. `didDeselectItemAtIndex` works fine, but `didSelectItemAtIndex` doesn't work, instead IGListKit triggers `didSelectItem` at section level. Is it possible to trigger both of them(`didSelectItemAtIndex` and `didSelectItem`)?

Actually I understand it's possible by digging inside IGListKit and changing current code, but maybe I'm wrong and I have missed something in docs.

**Comment by rnystrom** [comment]
@pharosproduction it should be totally possible. That `collectionViewDelegate` should just forward events to the delegate while also notifying the section controller. [Here's the source](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L697-L706).

**Comment by pharosproduction** [comment]
I have updated IGListKit to the latest master. It works, thank you.

**Comment by jessesquires** [comment]
💯

**Comment by mohpor** [comment]
I know it might be a little late to solve this issue, but for those who still need to resolve this issue without too much hassle, you just need to call the `selectItem(at: IndexPath?, animated: Bool, scrollPosition: UICollectionViewScrollPosition)` inside ` cellForItem(at index: Int) -> UICollectionViewCell`:

```swift
override func cellForItem(at index: Int) -> UICollectionViewCell {
    reusableCell(at: index, isNib: false) {
      let item = self.item?.items[safe: index]
      $0.item = item
      $0.isSelected = item?.isSelected ?? false
      if item?.isSelected == true {
        self.collectionContext.selectItem(at: index,
                                          sectionController: self,
                                          animated: false,
                                          scrollPosition: [])
      }
    } as Cell
  }
```

Then the `didSelect` and `didDeselect` delegates will be called.

**Comment by mohpor** [comment]
Here is the syntactic sugar I used for the previous comment:

```swift

extension ListSectionController {
  
  public func reusableCell<T: UICollectionViewCell>(at index: Int, isNib: Bool, configCell: ((T) -> Void)? = nil) -> T {
    
    if isNib {
      guard let cell = collectionContext?.dequeueReusableCell(withNibName: String(describing: T.self), bundle: nil, for: self, at: index) as? T else {
        fatalError("Could not dequeeu nib cell of type: {\(type(of: T.self))}")
      }
      configCell?(cell)
      return cell
    } else {
      guard let cell = collectionContext?.dequeueReusableCell(of: T.self, for: self, at: index) as? T else {
        fatalError("Could not dequeeu class cell of type: {\(type(of: T.self))}")
      }
      configCell?(cell)
      return cell
    }
    
  }
}
```
