### ISSUE TITLE
New guide for UICollectionView (follow-up to #409)

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#527]
In light of #409, we should publish updates to the Guides, or maybe a new guide?

Proposal, new guide:

> ### Working with `UICollectionView`
>
> - details the history (legacy) of `IGListCollectionView`
> - links to #409 
> - lists the methods **you should never call** on `UICollectionView` when using ListKit

Thoughts?

**Comment by jessesquires** [comment]
cc @rnystrom

**Comment by rnystrom** [comment]
Also `prefetchingEnabled = NO`, using `UIAppearance` trick is cool too

**Comment by weyert** [comment]
Sorry, why is `prefetchingEnabled = NO` wasn't this one of the hot new features of iOS 10 announce last year at WWDC?

**Comment by rnystrom** [comment]
@weyert yup, it was. However we've run some testing and show that by simply being enabled this feature causes a significant scroll performance regression. That is, if `prefetchingEnabled = YES` and you don't even have a `prefetchDataSource` set.

IGListKit doesn't use this feature (we have our own "working range" implementation that is similar), so recommend always disabling it.

**Comment by weyert** [comment]
Ah, makes sense. Thanks for clarifying it, @rnystrom

**Comment by jessesquires** [comment]
PR up
