### ISSUE TITLE
Make diff code available as a separate component

### ISSUE THREAD

**Issue by insidegui** [Instagram/IGListKit#53]
It would be useful to have just the diff algorithm implementation and related protocol used in IGListKit available as a separate component to be used for other purposes (i.e. table views, existing apps that don't want to migrate to IGListKit but want the diffing).

**Comment by rnystrom** [comment]
@insidegui you're in luck, it already is!

If you add IGListKit to your app you can use the diffing by itself. There's an example [in the readme](https://github.com/Instagram/IGListKit#diffing) for this, but basically:

```objc
NSArray *oldStuff = @[...];
NSArray *newStuff = @[...];
IGListIndexSetResult *result = IGListDiff(oldStuff, newStuff, IGListDiffEquality);
// or if you want index paths, where the first two ints are the from/to sections
IGListIndexPathResult *result = IGListDiffPaths(0, 0, oldStuff, newStuff, IGListDiffEquality);
```

Then you can use the result objects to update the `UICollectionView` or `UITableView`.

Now if you want to use the diffing w/out importing the rest of IGListKit (which is arguably not a big framework to add), we might be able to add another Cocoapods spec for that, but I'm not sure its worth the effort of maintaining a separate workspace/tests/etc for that yet.

**Comment by insidegui** [comment]
Awesome! I think it would be useful to have a separate spec, especially since the framework doesn't support macOS yet but the diff code does.

**Comment by rnystrom** [comment]
Good point re: macOS

**Comment by laptobbe** [comment]
@rnystrom Would having it as a subspec in CocoaPods require it to be a separate workspace? If not, maybe that could be solution?

**Comment by rnystrom** [comment]
@laptobbe I'm not sure tbh, I'll have to do a little research to see what options we have. The most important things for this will be:

- Not interfering w/ existing IGListKit installations
  - Should stay as simple as `pod IGListKit` or dropping in `IGListKit.xcodeproj`
- Compatible w/ internal setup
  - We use [buck](https://buckbuild.com/) for Facebook dependency management and already _do_ separate the diffing and main lib, so we can't break that

**Comment by jessesquires** [comment]
> Would having it as a subspec in CocoaPods require it to be a separate workspace? If not, maybe that could be solution?

CocoaPods subspec should do the trick, without requiring any major changes. The subspec could specify macOS target compatibility too. (As far as I know.) 

I think a subspec gets us 90% of the way there. The problem is that this forces clients to use CocoaPods. (But I like CocoaPods, so `¯\_(ツ)_/¯`)

> Also, importing the entire IGListKit lib isn't that much of a binary size hit, and you can use the diffing algo by itself still. 

Right, but not on macOS or watchOS. (Because of `UICollectionView`)

**Comment by insidegui** [comment]
I actually made a little [repo](https://github.com/insidegui/IGListDiff) for myself with the diffing part isolated, the only source changes I had to make involved adding `#if TARGET_OS_OSX` checks to the umbrella header and `IGListDiffCore.mm` to import `Cocoa` on macOS and `UIKit` on iOS. I am using Carthage so I didn't make a podspec for it.

**Comment by jessesquires** [comment]
@insidegui -- It is possible to create cross-platform frameworks. Would you want to submit a PR to do this? 

Actually -- we should be able to add a macOS target, guard necessary areas with `#if TARGET_OS_OSX`, and only include the diffing files in the macOS target.

**Comment by jessesquires** [comment]
An example of a cross-platform ObjC framework:
https://github.com/jessesquires/JSQSystemSoundPlayer

(Slightly different, because this doesn't use UIKit or any iOS specific APIs. But, the general idea is the same.)

**Comment by insidegui** [comment]
> Would you want to submit a PR to do this?

I am working on this, will open the PR soon ;)

**Comment by insidegui** [comment]
There you go: https://github.com/Instagram/IGListKit/pull/235

**Comment by Sherlouk** [comment]
@jessesquires Flagging for closure

**Comment by jessesquires** [comment]
Done in #368
