### ISSUE TITLE
Question about supplementaryView and Make a decision for me.

### ISSUE THREAD

**Issue by RuofeiLv** [Instagram/IGListKit#531]
## New issue checklist

- [ yes] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ yes] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

Hi, First of all, thanks for this awesome project.
My question is that I have a headerView in collectionView(Same design like instagram, put a userHeaderView in collection in user profile page), I usually make a supplementary as a placeholder view and add my headerView on this collectionView.

But when I use this project, I think I can just set the contentInset of collectionView, and the top of contentInset is jus same the headerView's height. I am wondering if this is a good design or the first one, have a supplementaryView in the first section and put my headerView onto it.

**Comment by jessesquires** [comment]
Discussion at #329 might help

**Comment by RuofeiLv** [comment]
@jessesquires thanks for this link, and that issue mainly is about insets in sectionController.
But I think it's just about the insets of collectionView. 


I am wondering how Instagram implement.


I am trying to use the insets of collectionView and the below is how I do it for your references. I use reactive-cocoa to observe the frame of headerView and adjust the contentInsets of collectionView and the position of refreshControl.
`    [RACObserve(self.userHeaderView, frame) subscribeNext:^(NSNumber* rect) {
        CGFloat headerViewHeight=rect.CGRectValue.size.height;
        weakSelf.collectionView.contentInset=UIEdgeInsetsMake(headerViewHeight, 0, 0, 0);
        weakSelf.refreshControl.bounds = CGRectMake(weakSelf.refreshControl.bounds.origin.x,headerViewHeight,weakSelf.refreshControl.bounds.size.width,weakSelf.refreshControl.bounds.size.height);
    }];`

**Comment by rnystrom** [comment]
@RuofeiLv good timing, as I'm in the middle of some big rewrites within Instagram and have been dealing with exactly this problem. I also wrote our custom refresh control, so I have some knowledge about how that works.

For starters, our "headers" are just plain-ol section controllers. Nothing too fancy. They are different from other section controllers within the list (photos and stuff), but its the same concept. We use the various [reload](https://github.com/Instagram/IGListKit/blob/master/Source/IGListCollectionContext.h#L184-L191) and [invalidate](https://github.com/Instagram/IGListKit/blob/master/Source/IGListCollectionContext.h#L229-L240) methods to dynamically resize (expand, etc).

Our refresh control is totally separated from all of this. It knows about IGListKit or `UICollectionView`. It listens for `UIScrollViewDelegate` events and adjusts its frame and animation based on a threshold using a combination of `contentInset.top` and `contentOffset.y`.

**Comment by RuofeiLv** [comment]
@rnystrom  Thanks for this reply. I think it's good design to think header as sectionController too. I will probably adopt this design. And then the position of refresh control do not need to change anymore.
