### ISSUE TITLE
Master branch not building

### ISSUE THREAD

**Issue by MultX** [Instagram/IGListKit#537]
Hello. IGListKit is a great solution, like it, but have some troubles - master not compiling.

/.../Source/Internal/IGListAdapterUpdaterInternal.h:16:9: 'IGListBatchUpdateState.h' file not found

/.../Source/IGListAdapterUpdater.m:11:9: In file included from
/.../Source/IGListAdapterUpdater.m:11:

IGListBatchUpdates.h not found too

**Comment by rnystrom** [comment]
@MultX are you building the project workspace? Or is this after updating to the master branch via Cocoapods? I might have missed a step when I landed #525.

**Comment by MultX** [comment]
I am building the workspace. Before this [https://github.com/Instagram/IGListKit/commit/3f9dea21e0aaa30329bd36a20edb61e364ab33dd] commit building from workspace working

**Comment by rnystrom** [comment]
Bah I broke it then. Will patch immediately.
