### ISSUE TITLE
Updating IGListAdapter when new object has same pointer

### ISSUE THREAD

**Issue by christianselig** [Instagram/IGListKit#547]

**Comment by rnystrom** [comment]
@christianselig 🤔 missing some details?

If the pointer doesn't change, you can:

- Send change `NSNotification`s that section controllers subscribe to
- Call `-[IGListAdapter reloadObjects:]` with w/e needs updated
- Use `-[IGListAdapter reloadDataWithCompletion:]` instead

**Comment by christianselig** [comment]
Argh, sorry, I believe I hit enter before fully composing the post. 😰 #548 

Not sure if you can nuke this from orbit, but feel free to!
