### ISSUE TITLE
Updating IGListAdapter with new objects when "new" object has same pointer as old

### ISSUE THREAD

**Issue by christianselig** [Instagram/IGListKit#548]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): iOS 10.2
- CocoaPods/Carthage version: CocoaPods 1.2.0
- Xcode version: 8.2
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: N/A

---

Hey, big fan of the project, and I use it in conjunction with AsyncDisplayKit. It's delightful, really appreciate the work done.

I have a list of objects I'm returning to the adapter's `objects(for:)` method. Specifically, a list of `Comment` objects. Which for all intents and purposes just looks like this:

````swift
class Comment {
    let identifier: String
    let body: String
    var collapsed = false

    init(identifier: String, body: String) {
        self.identifier = identifier
        self.body = body
    }
}
````

A `Comment` object can be collapsed, in which case its child comments won't be returned when the adapter asks. So say you have a root comment with 4 children, originally the adapter will receive 5 `Comment` objects, but when the user taps on the root comment, it will collapse, and the adapter will only receive 1 `Comment`: the root comment in a "collapsed" state.

My issue is that when I effectively do (oversimplification for illustrative purposes):

````swift
rootComment.collapsed = true
return [rootComment]
````

The root comment is never deemed "different" as it never receives `isEqualToDiffableObject` as in `IGListDiff.mm` the line `if (n != o && ![n isEqualToDiffableObject:o]) {` (line 139) the `n != o` condition always fails, as the pointers are indeed the same.

How should I handle this? From my perspective it's expected behaviour that the "old" comment object has the same pointer as the new, because that's not what defines "new" vs "old" in this case (I thought the definition would be given in `isEqualToDiffableObject`).

**Comment by rnystrom** [comment]
@christianselig originally we did always call `isEqualToDiffableObject`, but you'll essentially still be calling `self.body == self.body` which will always be true.

- Can your models be immutable? That would make this easy (regen the models)
- What about copying the models returned in `objects(for:)`?

If none of that works, you can try some of the options I mentioned in #547 or take a look at how my [weather app](https://github.com/rnystrom/SimpleWeather/blob/master/SimpleWeather/Classes/SectionControllers/ConditionsSectionController.swift#L16) stores expanded state on the section controller itself (not the model).

**Comment by christianselig** [comment]
@rnystrom I've been meaning to change to immutable objects for awhile now, that's probably the right way to go, thanks for the suggestion. :) The other options would work well too if I kept it mutable, so that covers it really well! 

I'll close this, thank you again. 👍
