### ISSUE TITLE
Error when running ./build_docs.sh

### ISSUE THREAD

**Issue by svenbacia** [Instagram/IGListKit#55]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information
I just tried to build a new version of the documentation but I ran into the following issue:

> .../IGListKit/Source/IGListKit.h:18:9: fatal error: 'IGListKit/IGListAssert.h' file not found

I am using Jazzy version 0.7.2

**Comment by rnystrom** [comment]
Ya, this is a known issue. realm/jazzy#667 is tracking the bug for jazzy docs.

We can get it to work by doing:

```bash
$ mv Source IGListKit
$ ./build_docs.sh
$ mv IGListKit/Source
```

Pretty hacky though. If the issue w/ jazzy isn't addressed maybe we can just add the swap/restore to the script?

@jessesquires whatcha think?

**Comment by jessesquires** [comment]
👍 Yeah, let's just add this to the script with a comment and link to this issue
