### ISSUE TITLE
Invaild reload one sectionController after adapter  performUpdatesAnimated(true)

### ISSUE THREAD

**Issue by FengDeng** [Instagram/IGListKit#550]
## invalid - (void)reloadSectionController:(IGListSectionController<IGListSectionType> *)sectionController  after called - (void)performUpdatesAnimated:(BOOL)animated completion:(nullable IGListUpdaterCompletion)completion.

I guess because performUpdatesAnimated is not finished.

sorry for poor english!

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:2.2.1
- iOS version(s):8.4
- CocoaPods/Carthage version:
- Xcode version:8.2.1
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

**Comment by rnystrom** [comment]
Hey @FengDeng! Could you provide a stack trace or example project reproducing this issue? We're going to need a little bit more information to look into this.

**Comment by FengDeng** [comment]
sample description:
I have a webview in one sectionController. And need reload height after webview load finished.
Adapter called performUpdatesAnimated(true),if webview load finished soon and reload it's sectioncontroller,it's invaild.webview sectionController height not changed.

> in webview sectionController

`func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        webView.evaluateJavaScript("document.body.offsetHeight") { (height, err) in
            guard let height = height as? NSNumber else{return}
            self.height = CGFloat(height.floatValue) + 15
            self.data?._height = self.height
            print(self.height)
            self.data?.reloadData()
            print("reloadData begin")
            /*
            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 1.0, execute: {
                self.data?.reloadData()
                print("因为html：\(self.data?.sectionViewController?.viewController)")
            })*/

        }
    }
`
`func reloadData(){
        self.sectionViewController?.collectionContext?.reload(self.sectionViewController!)
    }
`
if delay 1.0 second,and webview sectionController height changed!

**Comment by rnystrom** [comment]
@FengDeng oh nice, I think @ocrickard had some similar experiences too when he was doing some prototyping.

Instead of just reloading, could you try wrapping it in a batch update and see if that works?

Something like:

```swift
collectionContext?.performBatch(animated: true, updates: {
  self.collectionContext?.reload(self)
})
```

**Comment by jessesquires** [comment]
That should work, we use this workaround as well.

**Comment by FengDeng** [comment]
@jessesquires  @rnystrom  Thanks,it works!

**Comment by frenkelor** [comment]
Hi @FengDeng can you elaborate more about your solution I'm trying to implement something similar but the app crashes.
`libc++abi.dylib: terminating with uncaught exception of type NSException`
Removing the WKWebView delegate from the sell solves the crash but I'm not sure why.

Are you using self-sizing cells?

initializing the webview
```
lazy public var webView: WKWebView = {
        let webView: WKWebView = WKWebView(frame: .zero)
        webView.translatesAutoresizingMaskIntoConstraints = false
        webView.scrollView.isScrollEnabled = false;
        webView.allowsBackForwardNavigationGestures = false
        return webView
    }()

///....
func bindViewModel(_ viewModel: Any) {
            guard let vm = viewModel as? WebViewContentModel else { return }
            let urlPath = URL(fileURLWithPath: Bundle.main.bundlePath)
            webView.navigationDelegate = self
            webView.stopLoading()
            webView.loadHTMLString(vm.htmlTemplate, baseURL: urlPath)
}
```
