### ISSUE TITLE
Where do you put exactly your networking code when using IGLikstKit?

### ISSUE THREAD

**Issue by Ricardo1980** [Instagram/IGListKit#551]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: Any
- iOS version(s): iOS9 and 10
- CocoaPods/Carthage version: Lastest
- Xcode version: Version 8.2.1 (8C1002)
- Devices/Simulators affected: None
- Reproducible in the demo project? (Yes/No): N/A
- Related issues: None

Hello,

I would like to know your opinion about this:

Lets say one of your cells is a toolbar with a Like button, that sends a network request when pressed (basically like Facebook, but without optimistic UI, so I wait for response)
You reuse that cell in several section controllers, some of them, not all.
My question is: Where do you write that networking logic? I guess writing this in the section controller is not a good idea, because in that case, then we are repeating a lot of logic that is different. If we are using MVC or MVVM or similar, does this mean we have to use delegates to connect the cell, passing through the section controller, collection view and view controller, to use something like NetworkServiceProvider? And when we have the response, then the opposite path.

Just wanted to know your suggestions about how you architect your app for this.
Thanks a lot.

**Comment by heumn** [comment]
This is a really good question and a well discussed topic. Straight to the point @rnystrom has begun making a nice weather app using IGListKit over here: https://github.com/rnystrom/SimpleWeather

Maybe something like that is what you would like to dig into? It shows a nice separation of concerns and where one `could` put networking logic. I learned a lot about IGListKit by reading his code.

And you are absolutely right. Putting network logic directly in a Section Controller / View Controller is something you should avoid.

> "If we are using MVC or MVVM or similar, does this mean we have to use delegates to connect the cell, passing through the section controller, collection view and view controller, to use something like NetworkServiceProvider?" 

Not entirely sure I understood your suggestion here but yes. Using something like a NetworkServiceProvider sounds like a good idea 👌 

To give you another suggestion I would read more about the different options
I think this medium post summarizes the different options well 
https://medium.com/ios-os-x-development/ios-architecture-patterns-ecba4c38de52#.iab7e9hh2

Do not be overvelmed by all the suggestions. There are no silver bullets. Everything has drawbacks and there is no such thing as a perfect architecture. The fact that you are asking these questions is a great start.

**Comment by Ricardo1980** [comment]
Thanks a lot for your response.
You are not going to believe this, but I already have FeedViewController, FeedViewModel and buildSections in my code. Are you in London? ;)

**Comment by heumn** [comment]
> Thanks a lot for your response.

My pleasure!

> You are not going to believe this, but I already have FeedViewController, FeedViewModel and buildSections in my code. Are you in London? ;)

Hehe.. No I am located in Oslo, Norway :)

**Comment by jessesquires** [comment]
Thanks @heumn ! 💯 🥇
