### ISSUE TITLE
Example-iOS Obj-C lose image when calling performUpdatesAnimated method

### ISSUE THREAD

**Issue by damthieuquang** [Instagram/IGListKit#552]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): 10.2
- Xcode version: 8.2.1
- Devices/Simulators affected: iphone SE

Hi @rnystrom,

I have a problem when try to load more with Example-iOS Obj-C.

```
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    if (!self.isLoadingMore) {
        CGFloat _offsetY = scrollView.contentOffset.y;
        CGFloat _height = scrollView.frame.size.height;
        CGFloat _curOffsetY = _offsetY + _height;
        CGFloat _contentSizeH = scrollView.contentSize.height;
        CGFloat _percentContentSize = (_curOffsetY / _contentSizeH) * 100;
        
        if (_percentContentSize >= 80 && _offsetY >= 0) {
            self.isLoadingMore = YES;

                UserInfo *userE = [[UserInfo alloc] initWithName:@"userE"];
                [self.data addObjectsFromArray:@[ userE,
                                                  @"Image-Placeholder-String",
                                                  @"",
                                                  @"hope she might like it.",
                                                  @"I love it."]];
                [self.adapter performUpdatesAnimated:YES completion:nil];
//                [self.adapter reloadDataWithCompletion:nil];
        }
    }
}
```
 I implement this code for loading more when the user scroll down of collection view, but all of images disappear when I call this method `[self.adapter performUpdatesAnimated:YES completion:nil];`. Otherwise, everything works well when using ` [self.adapter reloadDataWithCompletion:nil];`

I don't know why so can you help me to understand this

[IGListKit-master.zip](https://github.com/Instagram/IGListKit/files/841750/IGListKit-master.zip) (demo)

**Comment by rnystrom** [comment]
Hey @damthieuquang! We should probably update the ObjC demo to use more concrete models. What's happening is the diffing algorithm seems duplicated objects and [trims them](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L122) from its objects array. It doesn't do this when the demo first launches because it hasn't diffed anything yet.

We'll update this example ASAP. Thanks for flagging!
