### ISSUE TITLE
numberOfItems results in the same item appearing multiple times in the section

### ISSUE THREAD

**Issue by eyzuky** [Instagram/IGListKit#553]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): 10.0
- Xcode version: 8.2.1

Hi again! :)
I am trying to have a section that has 2 items one next to each other. At the moment I get both items in each section as a duplicate of one of them. This does not surprise me since I have not done anything special to make it happen, but what would be the best practice?
I have the main ViewController that has this implementation:
![screen shot 2017-03-15 at 14 50 57](https://cloud.githubusercontent.com/assets/19775989/23949159/d9b20bc4-098e-11e7-98ab-c1549b782783.png)

**Comment by rnystrom** [comment]
Hey again @eyzuky 😄 

I'd honestly go w/ another wrapper object solution since the section is supposed to represent **two people**, it'd be fine to have a `TuplePerson` or something object that has a left/right `Person`.

**Comment by eyzuky** [comment]
great :) thanks!

**Comment by eyzuky** [comment]
would you prefer having 5 instances of TuplePerson rather than an array of 10 people? Assuming you have 10 people to show, where each row contains 2 people..

**Comment by rnystrom** [comment]
@eyzuky one idea, if your concern is mostly about the UI (being in the same row) and _not_ that the section only functions/exists w/ 2 `Person` objects, then I'd recommend sticking with 1 `Person` per section controller but using our `IGListCollectionViewLayout` so that you can have sections on the same row (flow layout doesn't let you do this).

**Comment by eyzuky** [comment]
Exactly the piece I had missing in this puzzle. Thanks a lot.

**Comment by eyzuky** [comment]
By the way, for some reason the file  'IGListCollectionViewLayout' is not in the API, and I do not have it in my files after installing the pod. It does appear in your example project, any ideas?

**Comment by jessesquires** [comment]
@eyzuky you can use `master` if you need this now. see our installation guide for details
