### ISSUE TITLE
layoutSubviews crashes on scroll 

### ISSUE THREAD

**Issue by rotemdoron** [Instagram/IGListKit#554]
cant really tell why this is happening but when i scroll up by tapping on the status bar i get this crash (as in the picture) anyone know's how to deal with this? 

## New issue checklist
![screen shot 2017-03-15 at 17 35 06](https://cloud.githubusercontent.com/assets/3501076/23957265/a0b1145a-09a7-11e7-9cc8-4f9de385c851.png)

- [*] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ *] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s): 10.1
- CocoaPods/Carthage version: 1.1.1
- Xcode version: 8.2
- Devices/Simulators affected: Device
- Reproducible in the demo project? (Yes/No): Not sure 
- Related issues:

**Comment by heumn** [comment]
At minimum I think anyone would need a stacktrace or (much better) an example project to understand what is going on. A crash happens because something _critically wrong_ so my best guess is that you have configured something out of the ordinary that IGListKit does not support or you got confused about how to do XYZ correct :)

**Comment by kleiberjp** [comment]
i have the same issue, but i don´t know if are in the same cases that @rotemdoron, but i have an stack trace, and is relationated to another isses
[Stack trace crash layoutsubview](https://github.com/Instagram/IGListKit/files/845371/com.grability.rappi_issue_3651_crash_ef71721a93a043adb713b53662230c97_f13bb580a6044fe7ad023a2f85dca61f_0_v1.txt)

**Comment by heumn** [comment]
I replied in your issue @kleiberjp :) Thanks for the stacktrace and the example project! Those help a a lot

**Comment by rotemdoron** [comment]
hi @heumn  thanks for replying, the only stack trace i get is this : 
`libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

![screen shot 2017-03-16 at 09 18 06](https://cloud.githubusercontent.com/assets/3501076/23985768/886e8cf6-0a29-11e7-8d57-0dfc88d23534.png)

it happens always when i scroll up by clicking on the status bar

**Comment by heumn** [comment]
Thanks for the screenshot :) This is only "half" of the crash information. You are not printing / showing the exception thrown when it crashes

Would it be possible with an example project?

**Comment by rotemdoron** [comment]
ok so this is the exception im getting : 
`negative sizes are not supported in the flow layout`
but there is no place in the sizeForItem that i give a negative size

**Comment by rnystrom** [comment]
@rotemdoron can you post some of the code for your section controllers? Are you doing any form of subtraction in there? Also you're using `UICollectionViewFlowLayout` right?

**Comment by rotemdoron** [comment]
yeap my collectionview is in storyboard together with the flowlayout, not using the flow layout in code though.
code example : 
` func cellWidth() -> CGFloat {
        return collectionContext!.containerSize.width - inset.left - inset.right
    }
    
    func sizeForItem(at index: Int) -> CGSize {
        
        let cellType = self.object?.articleSectionList[index]
        var size : CGSize = CGSize(width: cellWidth(), height: 0)
        
        switch cellType! {
        case .stamp:
            size.height = WHStampLabelCollectionCell.getCellHeight()
            break
        case .writer:
            let height = WHWriterCollectionViewCell.textHeight((object?.writer?.fullNameAndCredit)!, width: cellWidth())
            size.height = height
            break
        case .date:
            size.height = WHDateCollectionViewCell.getDateCellHeight()
            break
        
        case .content:
            let height = WHContentLabelCollectionCell.textHeight((object?.content)!, width: cellWidth())
            size.height = height
            break
        case .media:
            size.height = (object?.mediaSize.value)!
            break
        case .hashTag:
            size.height = calculateHashTagsHeight()
            break
        case .embed:
            size.height = (object?.embededSize.value)!
            break
        }
        
        print("size -- \(size) and Type -- \(cellType!)")
            return size
    }
    
    func cellForItem(at index: Int) -> UICollectionViewCell {
        
        let cellType = self.object?.articleSectionList[index]
        
        switch cellType!
        {
        case .stamp:
            let cell = self.collectionContext!.dequeueReusableCell(withNibName: WHStampLabelCollectionCell.nibName, bundle: nil, for: self, at: index) as! WHStampLabelCollectionCell
            cell.configureCellWith(article: object!)
            return cell
            
        case .writer:
            let cell = self.collectionContext!.dequeueReusableCell(withNibName: WHWriterCollectionViewCell.nibName, bundle: nil, for: self, at: index) as! WHWriterCollectionViewCell
            cell.configureCellWith(article: object!)
            cell.delegate = self
            
            return cell
            
        case .date:
            let cell = self.collectionContext!.dequeueReusableCell(withNibName: WHDateCollectionViewCell.nibName, bundle: nil, for: self, at: index) as! WHDateCollectionViewCell
            cell.configureCellWith(article: object!)
            return cell
            
        case .content:
            let cell = self.collectionContext!.dequeueReusableCell(withNibName: WHContentLabelCollectionCell.nibName, bundle: nil, for: self, at: index) as! WHContentLabelCollectionCell
            cell.textLabel.text = object?.content
            
            return cell
            
        case .media:
            let cell = collectionContext!.dequeueReusableCell(withNibName: MediaTypesCollectionCell.nibName, bundle: nil, for: self, at: index) as! MediaTypesCollectionCell
            adapter.collectionView = cell.collectionView
            
            return cell
            
        case .embed:
            let cell = configureEmbedCell(index: index)
            return cell
            
        case .hashTag:
            let cell = collectionContext!.dequeueReusableCell(withNibName: WHHashtagsCollectionCell.className, bundle: nil, for: self, at: index) as! WHHashtagsCollectionCell
            cell.configureCell(hashtags: object?.hashtag, cellTappedBlock: {(hashTag) in
                _ = self.viewController?.navigationController?.wh_PushViewController(type: .hashTags, presentType: .push , animated: true, userInfo: hashTag)
                AnalyticsManager.instance.trackAction(event: .hashtag, info: nil)
            })
            
            return cell
        }
    }
`

you can see im printing the sizes, none of them is negative size or zero.

**Comment by rnystrom** [comment]
@rotemdoron Hmm the `return collectionContext!.containerSize.width - inset.left - inset.right` looks suspect.  Could you add an assert that checks if the container width is 0? I'm going to open another issue to track possibly fixing making this mistake.

**Comment by rotemdoron** [comment]
@rnystrom thanks for the feedback, i tried assert seems the container size is correct im also printing it and the size is right even right before the crash.
