### ISSUE TITLE
Fix calendar example layout bug

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#557]
I think [this](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/MonthSectionController.swift#L72) needs to be `floor`ed.

**Comment by jessesquires** [comment]
lol

does this use the listkit layout?

shiyi submitted a diff internal to floor/round/ceil something there

**Comment by rnystrom** [comment]
Oh sweet, that might be the problem. Yup demo uses our layout. Will hold on this and close if that fixes it.

**Comment by Sherlouk** [comment]
@rnystrom Did this get fixed?

**Comment by rnystrom** [comment]
Oh yup, thanks for cleaning things up @Sherlouk!
