### ISSUE TITLE
IGListGridCollectionViewLayout is not available on branch master

### ISSUE THREAD

**Issue by kleiberjp** [Instagram/IGListKit#559]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): 10.2
- CocoaPods/Carthage version: 1.0
- Xcode version: 8.3
- Devices/Simulators affected:None
- Reproducible in the demo project? (Yes/No): no
- Related issues: None

I´m using IGListGridCollectionViewLayout from the version on release, but when update the pod to the master branch the class is not available more ☹️.. there is some reason? or is another class that replace it?

**Comment by jessesquires** [comment]
Thanks @kleiberjp ! 

Sorry about that. `master` **is stable and reliable** but it does have breaking changes. 😄 

Checkout the `CHANGELOG` for details! 👍 

https://github.com/Instagram/IGListKit/blob/master/CHANGELOG.md
