### ISSUE TITLE
Setting contentInset of IGListCollectionView, causes bug on scroll method from IGListCollectionContext

### ISSUE THREAD

**Issue by aleufms** [Instagram/IGListKit#563]
- `IGListKit` version: 2.1
- iOS version(s): All
- CocoaPods/Carthage version:
- Xcode version: 8.2.1
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No):
- Related issues:

If we put a contentInset (on my case, I have a header view above the collection view.) on a IGLIstCollectionView, the scroll method from IGListCollectionContext bugs. Is the scroll method aware of custom contentInset? If I return the contentInset to 0 it works well.

**Comment by heumn** [comment]
I use contentInset on the collectionView without any troubles. It would help a lot if you attached an example project that reproduces your problem. Would be great if you could extend on what you mean by "cause bug on scroll method" :)

**Comment by aleufms** [comment]
Ow,sorry guys. I found out that the "issue" is on uicollectionview, because the same happens with it. It is because the viewcontroller add contentinsets by itself. I have to disable it, because I manage it manually. Closing.
