### ISSUE TITLE
Don't allow returning negative sizes for cells and supplementary views

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#566]
Even though this is user-error, IGListKit could ease the pain here.

Callsites:

- [Cell size](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L461)
- [Supplementary size](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L468)

Options:

1. Assert when < 0. This points out the error to the user
2. Print when < 0, just point out the mistake but not actually fatal
3. Gracefully handle < 0

I'm leaning towards 3 b/c this mistake can probably creep up w/ different layout implementations. Thoughts?

Inspired by #554

**Comment by rnystrom** [comment]
@jessesquires `UICollectionViewFlowLayout` throws (see #554). We hit this internally once too.

**Comment by jessesquires** [comment]
Ah... 👍

**Comment by rnystrom** [comment]
t16455632 for instance
