### ISSUE TITLE
Github topics

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#568]
Just realized these are a thing. Will get them enabled. Suggestions?

**Comment by viktorgardart** [comment]
iOS :neckbeard:

**Comment by heumn** [comment]
Objective-C :trollface:

**Comment by jessesquires** [comment]
github :trollface:

**Comment by zhubofei** [comment]
UICollectionView:trollface:

**Comment by Sherlouk** [comment]
Closing this as we now have some topics on the repo!
