### ISSUE TITLE
IGListBindingSectionController object property should probably be public

### ISSUE THREAD

**Issue by heumn** [Instagram/IGListKit#572]
I want my `IGListBindingSectionController` subclass to be able to implement `IGListSupplementaryViewSource`. To do that I need access to the section object. Given the fact that the `object` (the section model in my case) is a private property on `IGListBindingSectionController`, it can not contain this type of information any more (not accessible) 

An option is to represent the supplementary view (a header in my case) as a cell with its own viewModel (what I am doing now) but I would still think this should be available. Thoughts?

`IGListBindingSectionController` implementation file:

![skjermbilde 2017-03-21 kl 20 25 41](https://cloud.githubusercontent.com/assets/1769314/24166737/94630cd6-0e74-11e7-90f5-ed1f4c067c63.png)

**Comment by rnystrom** [comment]
Good point, it probably should.

Are we ok with it being `id object` (which will be `Any` in Swift) and letting callers check/cast the object? Not sure if we should try any fancy ObjC generics here.

**Comment by heumn** [comment]
> Are we ok with it being id object (which will be Any in Swift) and letting callers check/cast the object? Not sure if we should try any fancy ObjC generics here.

No need for generics here in my eyes, but now that you mentioned it 🤔  It would be neat

Other than that, `IGListBindingSectionController` is sweeet :)

Maybe I can open a PR tomorrow?

**Comment by rnystrom** [comment]
@heumn all you!

**Comment by jessesquires** [comment]
If possible, lightweight ObjC generics would probably be nice
