### ISSUE TITLE
Supplementary view strange behavior

### ISSUE THREAD

**Issue by mzds** [Instagram/IGListKit#574]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

Thanks for this great project.
I find a problem while studying example code. In ObjcDemoViewController.m, I want to add a supplement footer view in ImageSectionController, i expected each section has a yellow footer view, but when i do that, only the last section display footer view, the other missed footer view(maybe hidden?)

here is my code:
![2017-03-22 10 47 58](https://cloud.githubusercontent.com/assets/3622493/24204293/f45fdc3e-0f52-11e7-97cd-fd34e0becbbc.png)

And i also checked the debug view hierarchy:
![2017-03-22 10 58 49](https://cloud.githubusercontent.com/assets/3622493/24204344/261a10be-0f53-11e7-92c5-8311e13680d2.png)

It seems two footer view overlap？any help? thanks! 
@rnystrom @jessesquires

**Comment by rnystrom** [comment]
This is actually an error in the demo. I have a reminder to clean this demo up quite a bit. The issue is that the same string is in the objects array multiple times, so a single section controller ends up being used for image sections. Will clean up this demo.
