### ISSUE TITLE
Grid Layout

### ISSUE THREAD

**Issue by thedevme** [Instagram/IGListKit#579]
I have not been able to find a solution for this as all the examples have the grid flowing to the left.  I need to get my grid to be centered.  Currently it is floating to the left:

![img_1909](https://cloud.githubusercontent.com/assets/1933678/24251286/067bd8ca-0fb0-11e7-9c66-755c954b30b5.JPG)

I am not sure why my values for inset are not working but they are not in the SectionController.  Any advice? Thanks

**Comment by zhubofei** [comment]
@thedevme The grid layout only supports left alignment at the time. For your use case, I think `UICollectionViewFlowLayout` might be more suitable (if you only have one Section Controller per line).

**Comment by thedevme** [comment]
I am not sure what you mean - so are you saying use reg collection view for this?  I will need it to be centered.

**Comment by zhubofei** [comment]
I mean use `UICollectionViewFlowLayout` instead of `IGListCollectionViewLayout`.

**Comment by thedevme** [comment]
Ahh ok thank you very much for the quick response

**Comment by thedevme** [comment]
@zhubofei does this also apply to a grid?
<img width="578" alt="screen shot 2017-03-23 at 10 35 29 am" src="https://cloud.githubusercontent.com/assets/1933678/24263971/300f4508-0fd5-11e7-9cf1-9eff51e4d62d.png">

I tried using UICollectionViewFlowLayout but it won't show up in a grid - when I use IGListCollectionViewLayout I get the following.

**Comment by zhubofei** [comment]
@thedevme No. UICollectionViewFlowLayout newlines section controllers. If you want grid layout and center alignment at the same time. We have to do the math yourself. Setup the right width and spacing.

**Comment by thedevme** [comment]
I have tried with both ways doing it with math and setting the width and it still doesn't thought it might be a bug.  Thanks

**Comment by rnystrom** [comment]
@thedevme can you use `IGListCollectionViewLayout` and set the `contentInset` of the collection view itself to something to "center" the content?

**Comment by D-Link13** [comment]
Same thing here.. If I am using Flow layout, insets works like a charm.. but when using Grid, settings the insets has no effect. Here is my code:
```
import UIKit
import IGListKit

class InviteFriendsSectionController: IGListSectionController {

    var item: String!
    let spacing = CGFloat(20)
    
    override init() {
        super.init()
        inset = UIEdgeInsets(top: spacing, left: spacing, bottom: spacing, right: spacing)
    }
}

extension InviteFriendsSectionController: IGListSectionType {
    
    func numberOfItems() -> Int {
        return 1
    }
    
    func sizeForItem(at index: Int) -> CGSize {
        
        guard let context = collectionContext else { return .zero }
        let width = context.containerSize.width / 2 - spacing * 2
        
        return CGSize(width: width, height: width)
    }
    
    func cellForItem(at index: Int) -> UICollectionViewCell {
        
        let cell = collectionContext?.dequeueReusableCellFromStoryboard(withIdentifier: "InviteFriendCell", for: self, at: index) as! InviteFriendCell
        cell.imageView.image = UIImage(named: item)
        return cell
    }
    
    func didUpdate(to object: Any) {
        item = object as? String
    }
    
    func didSelectItem(at index: Int) {
        
    }
}
```

Help me please!

**Comment by rnystrom** [comment]
@D-Link13 can you try using the master branch and our `IGListCollectionViewLayout` layout instead? We've deprecated the grid layout in favor of an upgraded one that better supports insets and inline sections/items.
