### ISSUE TITLE
How to insert new section controller within the visible section controllers

### ISSUE THREAD

**Issue by yusuftor** [Instagram/IGListKit#581]
I have a trigger that needs to insert a section controller somewhere in between the currently visible section controllers on screen. I can get the visible section controllers and their objects, however, I am unable to find their indices.

I'm trying something like this:

```
//model.content is [IGListDiffable]
let visibleControllers = adapter.visibleSectionControllers()
if let firstController = visibleControllers.first {
    let section = adapter.section(for: firstController)
    if let object = adapter.object(atSection: section) as? IGListDiffable,
        let index = model.content.index(of: object) { // Doesn't work
        ...
    }
}
```

But you can't use index(of:) with an IGListDiffable array. How can I do this? Thanks!

**Comment by rnystrom** [comment]
@yusuftor you already have the indices by getting the `section` of the section controller 😉 

```swift
let section = adapter.section(for: controller)
let object = adapter.object(at: section)
// or
let object = adapter.objects()[section]
```

**Comment by yusuftor** [comment]
Oops 😬 Thanks!
