### ISSUE TITLE
IGListKit compatible with LinkedIn's LayoutKit?

### ISSUE THREAD

**Issue by coreywiley** [Instagram/IGListKit#585]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### 
 I reviewed [Best Practices and FAQ](https://github.com/Instagram/IGListKit/blob/master/Guides/Best%20Practices%20and%20FAQ.md) and was wondering if ListKit will also work with LinkedIn's LayoutKit?

**Comment by rnystrom** [comment]
Hey @coreywiley! I assume it would work, but I haven't used that framework at all before. Would love to see someone take this up and try it!
