### ISSUE TITLE
Document the need for model objects to be immutable

### ISSUE THREAD

**Issue by robertjpayne** [Instagram/IGListKit#587]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: `master`
- iOS version(s): not applicable
- CocoaPods/Carthage version: not applicable
- Xcode version: 8.3
- Devices/Simulators affected: not applicable
- Reproducible in the demo project? (Yes/No): not applicable
- Related issues: #407 #460  #461 

This caught me out a bit, but IGListKit currently requires that an object's pointer personality changes for any type of reload action to occur.

Even if `diffIdentifier` changes and the isEqual value returns false if the object's pointer is the same the diff algorithm ignores it.

I understand why this is difficult to achieve but I feel like it's sort of a hidden implementation detail and there is little documentation stating that object pointer's *must* change for reloads to occur.

**Comment by robertjpayne** [comment]
Gah I totally missed the Diff and Equality document. Sorry

**Comment by jessesquires** [comment]
No worries! Thanks @robertjpayne ! 👍
