### ISSUE TITLE
Self-sizing cells in demo project crashes the app in iOS 9.3

### ISSUE THREAD

**Issue by Ricardo1980** [Instagram/IGListKit#588]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: Last one
- iOS version(s): iOS 9.3 (It works fine under iOS 10)
- CocoaPods/Carthage version: Last one.
- Xcode version: 8.2.1
- Devices/Simulators affected: iPhone 6s  iOS 93.
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

Hello,

My app works perfectly under iOS 10, but crashes in iOS 9.3.

I realised we have the same problem in the demo project.

Just open IGListKitExamples and select "Self-sizing cells" under any iOS 9.3 simulator.
The app will crash (the other demos work perfectly).

So, it seems we cannot have variable height cells in iOS 9.3.

![screen shot 2017-03-27 at 11 54 56](https://cloud.githubusercontent.com/assets/738681/24353321/eee6ad06-12e4-11e7-978c-0b9d77d81042.png)

**Comment by Nonepse** [comment]
Also tested with:
> pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit', :commit => '5eca718ea7df02bc091dc65bfe1d452c486b3ba9'

**Comment by jessesquires** [comment]
Thanks @Ricardo1980  !

We're tracking this at #516 😄
