### ISSUE TITLE
[Question]: Best practice for using IGListKit with cells that require auxiliary inputs

### ISSUE THREAD

**Issue by robertjpayne** [Instagram/IGListKit#589]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

IGListKit is absolutely fantastic and thank you to the whole team that created it. I'm curious as to what the Instagram team would recommend as best practice for handling auxiliary inputs like extra buttons, segmented controls, text fields etc…

If you have a recommendation I'd love to write an example and a PR with it so others can leverage the same knowledge.

**Comment by jessesquires** [comment]
Hey @robertjpayne -- you mean for these elements inside a cell?

The common pattern is usually:

1. Hook up those `UIControl`s in the cell
2. Provide a `delegate` on the cell
3. Have your section controller conform to the delegate protocol and assign itself as the cell's delegate `cell.delegate = self`

**Comment by robertjpayne** [comment]
@jessesquires yea I was curious what Instagram does since there are a various patterns, sounds like the delegate pattern works best for IGListKit and in my practice it seems that way too since the model has to be immutable so the view can't ask it to update itself…

**Comment by robertjpayne** [comment]
Closing this -- maybe will try and find time to add to examples 👍
