### ISSUE TITLE
Crash on iOS 9.2.1

### ISSUE THREAD

**Issue by CurlyHeir** [Instagram/IGListKit#591]
### General information
- `IGListKit` version: 2.1
- iOS version(s): 9.2.1
- Xcode version: 8.3
- Devices/Simulators affected: iPad 3  (MD368PL/A)

### log: 
http://crashes.to/s/664d621d31b

i have no access to device, and I can't reproduce this on other devices and iOS versions

**Comment by MarvinNazari** [comment]
related to #554

**Comment by jessesquires** [comment]
Going to close as a duplicate of #554
