### ISSUE TITLE
Does IGListSectionController has an underlying view component?

### ISSUE THREAD

**Issue by staticdreams** [Instagram/IGListKit#598]
I'm trying to implement 2 section view controller (they are the same and inherit from the same model) and place multiple items (simple UICollectionView cells) inside each. I managed to do that, but my problem is styling...
Basically I'm trying to access each section to apply background color, rounded corners, add headers with titles and separate them a little etc..

It should look something like image below (mockup, not a real app :-))
Is this at all possible?

![app](https://cloud.githubusercontent.com/assets/988705/24539800/7370d750-15f0-11e7-86b6-e75b0078b582.jpg)

## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- iOS version(s): 10.3
- Xcode version: 8.3

**Comment by PhilCai1993** [comment]
I made this using decoration view, with customized layout

**Comment by staticdreams** [comment]
@PhilCai1993 thanks for your reply. Is there an example I can take a look at?

**Comment by PhilCai1993** [comment]
@staticdreams http://stackoverflow.com/questions/22955413/ios-separate-section-background-colors-on-uicollectionview

**Comment by staticdreams** [comment]
@PhilCai1993 I'm not sure how to apply all of the this to list adapter.
I found a [great example of decoration views + header + footer ](https://github.com/SebastienMichoy/CollectionViewsDemo) in Swift which looks like this

![simulator_screen_shot_1_apr_2017__10_48_00](https://cloud.githubusercontent.com/assets/988705/24577200/a48d4402-16c9-11e7-8ece-1db29479520d.jpg)

Apart from the spacing and rounded corners it is exactly what I need, but how to attach it to existing listAdapter? Since it does not expose the same methods as classic collectionView.

I wish the link was helpful, but not really..

**Comment by staticdreams** [comment]
Anyway, after much research, trial and error I managed to do exactly what I wanted.
[This article](http://strawberrycode.com/blog/how-to-create-a-section-background-in-a-uicollectionview-in-ios-swift/) has been of huge help to me for those who are interested.
