### ISSUE TITLE
Replacement for  reloadSectionController(_ sectionController: Any!)

### ISSUE THREAD

**Issue by nikitaame** [Instagram/IGListKit#601]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1

This function seems to have been taken out. Is there a replacement for `func reloadSectionController(_ sectionController: Any!)` ?? If so what is it?

**Comment by jessesquires** [comment]
https://github.com/Instagram/IGListKit/blob/master/CHANGELOG.md

**Comment by rnystrom** [comment]
Still exists, just moved to a context object to enforce calling in an update block.
