### ISSUE TITLE
SectionController Animation

### ISSUE THREAD

**Issue by vcepeda858** [Instagram/IGListKit#603]
Is it possible to animate sectionControllers as they initially load in.  I've tried editing the frame of a section controller in `listAdapter(_: willDisplay: cell: at:) `with no luck.  Also looked into subclassing `IGListGridCollectionViewLayout` to override `initialLayoutAttributesForAppearingItem` yet that only gets called upon insert and not the initial load or `performUpdatesAnimated(_:completion:)`.

**Comment by rnystrom** [comment]
@vcepeda858 I think the only way to do an initial load animation would be to start with an empty (`[]`) objects array for your data source and then call `adapter.performUpdate(animated: true)` on it.

**Comment by vcepeda858** [comment]
@rnystrom Thank you, thats a route I was going to head next.  I was just hoping there was something out of the box from IGListKit.  Thanks again.
