### ISSUE TITLE
Possible a mistake in IGListDisplayHandlerTests

### ISSUE THREAD

**Issue by PhilCai1993** [Instagram/IGListKit#604]
[Here](https://github.com/Instagram/IGListKit/blob/2284ce389708f62d99f48ff2ec15644f1ec59537/Tests/IGListDisplayHandlerTests.m#L218
) is where I find might be wrong.
```ObjC
[[self.mockAdapterDelegate reject] listAdapter:self.adapter   willDisplayObject:self.list  atIndex:path.item];
```

Because I forked to our private repo, and replace `IGListAdapterDelegate` as follows:
```ObjC
- (void)listAdapter:(IGListAdapter *)listAdapter 
  willDisplayObject:(id<IGListDiffable>)object atIndex:(NSInteger)index;
```
Then a compile error occurs.

Should it be `[[self.mockAdapterDelegate reject] listAdapter:self.adapter willDisplayObject:self.object atIndex:path.item];` ?

**Comment by PhilCai1993** [comment]
#605

**Comment by jessesquires** [comment]
looks like a bug to me 👍
