### ISSUE TITLE
IGListDiffable and Non-class type

### ISSUE THREAD

**Issue by pgherveou** [Instagram/IGListKit#61]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information
Is there any reason IGListDiffable could not be implemented on Struct? 
the following code returns this error:
`Non-class type 'Foo' cannot conform to class protocol 'IGListDiffable'`

```swift
struct Foo: IGListDiffable {
  let id: String

  func diffIdentifier() -> NSObjectProtocol {
    return id as NSObjectProtocol
  }

  func isEqual(object: Any?) -> Bool {
    return false
  }
}
```

- Library version(s): 1.0.0
- iOS version(s): 10.0

**Comment by jessesquires** [comment]
Thanks @pgherveou !

See the discussion in #35. 

In short, this is a limitation in the Swift compiler when bridging *from* Objective-C *to* Swift. It's difficult (or impossible) to determine if reference semantics are required, or not. Thus, protocols are imported as `@objc` which requires a reference (`class`) type.
