### ISSUE TITLE
Could IGListBindingSectionControllerDataSource also use a covariant?

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#611]
Now that `IGListBindingSectionController` has covariant types, could the data source also use it so that we get types for its object params?

Also change `MonthSectionController` to use `Month`, would be cleaner.

Follow up from #608

**Comment by Adlai-Holler** [comment]
@rnystrom Unfortunately Objective-C doesn't support generics on protocols.

**Comment by rnystrom** [comment]
Bummer
