### ISSUE TITLE
Grid layout for IGListSectionController with multiple cells

### ISSUE THREAD

**Issue by sleepyUdon** [Instagram/IGListKit#613]
## New issue checklist

- [v] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [v] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.0.0
- iOS version(s): 10.2.1
- Xcode version: 8.2.1
- Devices/Simulators affected: all
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

I would like to create a collection view with IGListKit to be displayed in a grid layout. In the example file, in the MixedDataViewController, the GridSectionController displays the items in a grid layout. This IGListSectionController only contains one single cell.

![simulator screen shot apr 3 2017 10 15 22 am](https://cloud.githubusercontent.com/assets/18637330/24613506/82deac90-1856-11e7-8621-70398bf0341d.png)

I would like to know if a IGListSectionController with multiple cells (instead of a single cell) can be displayed in a grid layout as well. I have experimented with a collection flow layout for IGListSectionController with multiple cells but the cells do not stay grouped together. See screenshot.

![simulator screen shot mar 31 2017 8 43 52 am](https://cloud.githubusercontent.com/assets/18637330/24613560/a50d36f6-1856-11e7-93c0-64db0da86bbf.png)

Is there a way to have the cells grouped the same way they are in a full width layout (see screenshot below), but in a grid layout?

![simulator screen shot mar 31 2017 8 45 10 am](https://cloud.githubusercontent.com/assets/18637330/24613372/216c9152-1856-11e7-88d4-0f9302b81055.png)

Thank you

**Comment by rnystrom** [comment]
Hey @sleepyUdon! This should _totally_ be doable. If you return the container width for each cell, then everything should stack on top of each other. Take a look at how I do this in my [weather app](https://github.com/rnystrom/SimpleWeather/blob/master/SimpleWeather/Classes/SectionControllers/ConditionsSectionController.swift#L38). Also our [working range demo](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/WorkingRangeSectionController.swift#L45-L47) does this as well.

If that answers your question feel free to close this issue! 😄

**Comment by sleepyUdon** [comment]
Thanks Ryan,

I changed the width of the item in WorkingRangeSectionController to see if I can have 3 items per row instead of stacked together:
   ```
 func sizeForItem(at index: Int) -> CGSize {
        let width: CGFloat = (collectionContext?.containerSize.width)!/3 ?? 0
        let height: CGFloat = CGFloat(index == 0 ? 55 : (self.height ?? 0))
        return CGSize(width: width, height: height)
    }
```
I am having the same problem as the items do not stay grouped: 
![img_0048](https://cloud.githubusercontent.com/assets/18637330/24627542/3ba92bd4-1883-11e7-8f28-4d2fc22e3b72.PNG)

**Comment by rnystrom** [comment]
@sleepyUdon oh maybe I'm misunderstanding the problem. Can you explain what you mean a little more about how they should "stay grouped"? Some questions:

- Which collection view layout are you using?
- Do you have a quick mockup of what you're trying to achieve?
- Which part of the example in `GridSectionController` doesn't work as desired?
  - The grid items are all individual cells, they aren't contained in a parent cell. Not sure if I'm understanding that correctly.

**Comment by sleepyUdon** [comment]
Hi @rnystrom, 

Thanks for the quick response. What I am trying to achieve is a collection view like this: 
<img width="542" alt="collectionview" src="https://cloud.githubusercontent.com/assets/18637330/24638775/3c994976-18b9-11e7-9ecc-c40c422c2dd9.png">

In this instance, I would like to structure each "card" as a section controller made of a collectionviewCell for the picture and another collectionviewCell containing the profile pic, name and likes.

**Comment by otymartin** [comment]
@sleepyUdon  I managed to create a grid finally. Perhaps my issue #632 can help you out?

**Comment by jessesquires** [comment]
Thanks @sleepyUdon -- looks like #632 might help. If not, let us know 😄

**Comment by ryancstack** [comment]
@sleepyUdon I edited their layout to stack cells in a section instead of placing them horizontally next to each other. Here's my gist: https://gist.github.com/ryancstack/10dce72fb5671b6301859a374d7597e3

I haven't tested it in all situations (headers and such), but it's been working well for me so far.
