### ISSUE TITLE
Scope example variables (fileprivate, etc)

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#618]
In an effort to promote architecture and design best-practices, we should recommend people scope their variables appropriately.

e.g. [this variable](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/LabelSectionController.swift#L20)

Should do for all

- Section controllers
- Cells
- View controllers
- Models

Followup from #612

**Comment by heshamsalman** [comment]
Functions as well?
