### ISSUE TITLE
IGListKit with Rx

### ISSUE THREAD

**Issue by kleiberjp** [Instagram/IGListKit#619]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): 10.3
- CocoaPods/Carthage version: 1.0
- Xcode version: 8.3
- Devices/Simulators affected: none
- Reproducible in the demo project? (Yes/No): no
- Related issues: none

Hi, guys, just a question...will exist a remotelly posibility that could exist a example where has the combination of this library with Rx? o just a giudeline for implement Rx properly with the library.

**Comment by jessesquires** [comment]
We're definitely open to PRs or will gladly link to a project from our README and other docs.

Core contributors don't have time for this right now. Going to close.

**Comment by yuzushioh** [comment]
@kleiberjp I created [sample project](https://github.com/yuzushioh/RxIGListKit) that uses IGListKit with RxSwift for fun! Hope it helps.  Sorry for commenting closed issue

**Comment by jessesquires** [comment]
Thanks @yuzushioh ! 🥇 

Would you might opening a PR and adding your project to this guide:
https://github.com/Instagram/IGListKit/blob/master/Guides/Best%20Practices%20and%20FAQ.md#does-iglistkit-work-with

under the "Does IGListKit work with..." section ?
