### ISSUE TITLE
Should IGListSectionController Be Generic on Object Type?

### ISSUE THREAD

**Issue by Adlai-Holler** [Instagram/IGListKit#622]
I added the generic to IGListBindingSectionController because it's the only section controller that currently exposes its object type publicly. But the more I think about it, the more I think we should elevate that generic up to IGListSectionController itself – even if the API doesn't currently expose that Object Type through any of its API, it's true that most section controllers expect an object of a certain kind.

In practice, the cost of this change is, it would force developers to establish and handle generics for their section controllers. The benefit is, it might serve as in-source-code documentation and it might make migration easier if, in the future, IGListSectionController ever exposes any API that deals with its object (such as if we implemented #168 ).

**Comment by jessesquires** [comment]
cc @rnystrom

**Comment by Adlai-Holler** [comment]
Ah if only this were doable. Maybe in Swift 6.0.1 😛
