### ISSUE TITLE
Visible sectionController's layout not updated after performUpdates()

### ISSUE THREAD

**Issue by maxim04** [Instagram/IGListKit#629]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: Master
- iOS version(s): 10
- CocoaPods/Carthage version: 1.2.0
- Xcode version: 8.3
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

Hi all, i am getting data from a rest api, after getting the data i append it to the data array and call adapter.performUpdates(). I apply a transform to the cells in the sectionController, but the visible sectionController's layout is not updated until the state of the section changes from offScreen -> onScreen.

This can be reproduced in the example project in the `Tail Loading` example by applying `cell.transform = CGAffineTransform(a: 1, b: 0, c: 0, d: -1, tx: 0, ty: 0)` in the `LabelSectionController`, newly added visible cell's will not have the correct transform until they go offScreen -> onScreen.

Can anybody guide me in the correct direction here, much appreciated.

**Comment by ryancstack** [comment]
`adapter.performUpdates()` looks at the the `diffIdentifier` and the `isEqualTo:diffableObject` methods to identify if a section controller needs reloading. You can include your transform in the `isEqualTo:diffableObject` method to determine if the view model has changed.

**Comment by rnystrom** [comment]
@maxim04 to apply transforms to the cells, you might want to use `IGListDisplayDelegate` and apply your transform in `willDisplay` [like this](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/DisplaySectionController.swift#L47-L50).

It also might be more technically correct to do this sort of stuff in a `UICollectionViewLayout`.

**Comment by maxim04** [comment]
@rnystrom tried to apply the transform in `listAdapter(_ listAdapter: IGListAdapter, willDisplay sectionController: IGListSectionController, cell: UICollectionViewCell, at index: Int)` and still the same thing happening, the transform is only applied when the cell comes from offscreen to onscreen, the already onscreen sections don't have the correct transform. 
I'm using IGListKit in conjunction with SlackTextViewController if that gives more context, hence why i'm trying to apply the inverted transform.

**Comment by rnystrom** [comment]
Oh, I've actually never gotten the inverted transform to work with UICollectionView. I believe if you want that to work you'll have to do it all through the layout.

**Comment by ryancstack** [comment]
In the `cellForItem:atIndex` method, add your transform: `cell.transform = cell.transform.scaledBy(x: 1, y: -1)`. I've also added my collection view as the "arbitrary scroll view managed by SlackTextViewController" in the `init(scrollView:)` initializer for the SlackTextViewController

**Comment by maxim04** [comment]
After a lot of trial and error i managed to get the inverted UICollectionView to work. The trick was to apply the transform to `cell.contentView` instead of the `cell`. Now the already on screen sections have the correct transform, as well as the offscreen ones.
