### ISSUE TITLE
Unable to run pod install for iOS example project

### ISSUE THREAD

**Issue by runmad** [Instagram/IGListKit#630]
Running `pod install` in `/Examples-IOS/` or `pod_setup.sh` fails to install the pods:

```ruby
Nanaimo::Reader::ParseError - [!] Array missing ',' in between objects
   #  -------------------------------------------
   #  				2942FF911D9F39E00015D24B /* LabelSectionController.swift in Sources */,
   #  				295D8A9D1E92ECDE001F7C06 /* Post.m in Sources */
830>  				29F7E2AD1E92843A00197586 /* IncrementAnnouncer.swift in Sources */,
      				^
   #  				2981BA391DB874BB00A987F9 /* WorkingRangeViewController.swift in Sources */,
   #  				29C629831DCFDB57004A5BB1 /* UserHeaderView.swift in Sources */,
   #  -------------------------------------------
```

## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): N/A
- CocoaPods/Carthage version: 1.2.0
- Xcode version: Xcode 8.3.1
- Devices/Simulators affected: N/A
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: N/A

**Comment by namsoila** [comment]
Same issue.

**Comment by ludoded** [comment]
@runmad 
there's is a missing coma after 

> 295D8A9D1E92ECDE001F7C06 /* Post.m in Sources */

So open `IGListKitExamples.xcodeproj` via any text editor and add missing coma (line 829) and save it. 
Try again and it should work

**Comment by runmad** [comment]
I know, I've opened a PR.
