### ISSUE TITLE
When you publish new release?

### ISSUE THREAD

**Issue by chapayGhub** [Instagram/IGListKit#633]
## New issue checklist

Hey guys

Perfect job! 
I found a small problem for me
I started using library in my project and can't use code from your examples. Examples uses library with new changes and they are not compatible with current library version.

Could you please make some notes in readme to save time for other developers?

As example I can't use *HorizontalSectionController* + *EmbeddedCollectionViewCell* as is from examples with 2.1.0 library version

<img width="1088" alt="screen shot 2017-04-10 at 10 36 02" src="https://cloud.githubusercontent.com/assets/878464/24851638/16d260a0-1ddd-11e7-94e5-b38216ffb6e6.png">

- [+] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [+] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version: 8.3
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

**Comment by Sherlouk** [comment]
I recall Jesse & Ryan saying a new version would be "soon", but I can't expand on that.

In the time being, as per the instructions on [the installation guide](https://github.com/Instagram/IGListKit/blob/master/Guides/Installation.md) you can install the `master` branch as a pod using the following in your `Podfile` which will give you access to all the recent changes! (It's used at Instagram, so fairly safe)

```ruby
pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'
```

**Comment by jessesquires** [comment]
Thanks @Sherlouk ! 💯 

@chapayGhub As @Sherlouk notes, `master` is stable so feel free to upgrade -- although a few more breaking changes are coming.

Alternatively, you can download the 2.1.0 release directly and run the examples there:
https://github.com/Instagram/IGListKit/releases/tag/2.1.0

**Comment by chapayGhub** [comment]
Thanks guys!

**Comment by rnystrom** [comment]
@chapayGhub and I've got a 2.1 -> 3.0 migration guide drafted right now! Trying to batch as many breaking changes into one major release so we don't cause too much churn on everyone.
