### ISSUE TITLE
"visible" section controllers

### ISSUE THREAD

**Issue by PhilCai1993** [Instagram/IGListKit#643]
`- (NSArray<IGListSectionController<IGListSectionType> *> *)visibleSectionControllers;` in IGListAdapter is not **all visible section controllers** sometimes.

For example, in a list, there is a section controller, with **zero** cell, but there's a header, footer or other supplementary view. So the section controller is still "visible".

**Comment by rnystrom** [comment]
Ah ya, we're only using `-[UICollectionView visibleCells]` atm, but absolutely not perfect. Tracking visible supplementary views is much more complicated b/c

- `visibleSupplementaryViewsOfKind:` is iOS 9+
- Requires knowing element kinds ahead of time

Maybe instead we should query `-[UICollectionViewLayout layoutAttributesForElementsInRect:]` w/ `collectionView.bounds` and just nab `-[UICollectionViewLayoutAttributes indexPath]` to build a set of section controllers?

Should be easy to unit test too.

**Comment by Sherlouk** [comment]
@rnystrom Want to card that up separately? Seems like a nice starter task!

**Comment by manicakes** [comment]
@rnystrom I took a stab at implementing your fix idea + added a unit test!
