### ISSUE TITLE
"Delete twice" test flaky because of bug in UICollectionView

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#651]
Woot, we found another bug in `UICollectionView`! It looks like UICV has no problem handling multiple inserts at the same index path (e.g section = 0, item = 0) within the same batch update. 

However if you try to delete from the same index path twice in a single batch update, things will _eventually_ break.

This bug was exposed when we landed a415ef5552cbfbf2d3884a705241973f4ea72dde #483.

Here's a sample project demonstrating the issue. Radar time!

[UICollectionViewMultipleDeletesSameIndex.zip](https://github.com/Instagram/IGListKit/files/925777/UICollectionViewMultipleDeletesSameIndex.zip)

**Comment by rnystrom** [comment]
cc @amonshiz @jessesquires this explains some of the test flakiness (t17306420)

**Comment by jessesquires** [comment]
@rnystrom Nice find!

Somebody call Steve 😄
