### ISSUE TITLE
IGListAdapterProxy needs init/new marked unavailable and designated initializer

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#654]
[IGListAdapterProxy](https://github.com/Instagram/IGListKit/blob/master/Source/Internal/IGListAdapterProxy.h) header is missing some of the annotations that we use elsewhere, gets this class consistent.

**Comment by jessesquires** [comment]
need:

- designated init
- `init` unavailable
- `new` unavailable

cc @Sherlouk who might want to do this 😄
