### ISSUE TITLE
Remove all @param alignment style in header docs

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#655]
Keeping param descriptions aligned (adding whitespace) is too difficult to maintain and we end up in weird states [like this](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.h#L89-L91) over time. We need to do a pass over all headers and clean this up.

**Comment by heshamsalman** [comment]
Might be a good opportunity to explore Orta's suggestion of including [SpaceCommander](https://github.com/square/spacecommander) to handle this for us in the future.
