### ISSUE TITLE
Conversion from value of type NSIndexPath* to incompatible type IGListMoveIndexPath*

### ISSUE THREAD

**Issue by valeriyvan** [Instagram/IGListKit#68]
XCode's static analyser shows issue:
/Users/someuser/somepath/IGListKit/Source/IGListDiff.mm:179:13: Conversion from value of type 'NSIndexPath *' to incompatible type 'IGListMoveIndexPath *'
## New issue checklist

- [*] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [*] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- Library version(s):
1.0.0
- iOS version(s):
Not relevant
- Devices/Simulators affected:
Not relevant
- Reproducible in the demo project? (Yes/No):
Not relevant
- Related issues:
None

**Comment by rnystrom** [comment]
Interesting, I think this is a false-positive from the static analyzer.

- A move is generated (for an index _or_ index path) [here](https://github.com/Instagram/IGListKit/blob/master/Source/IGListDiff.mm#L245)
- There is a value for param `obj`, so it adds the object to the collection [here](https://github.com/Instagram/IGListKit/blob/master/Source/IGListDiff.mm#L175-L176)

It looks like we need to address the static analyzer though so we can have a clean analysis.

**Comment by rnystrom** [comment]
Closed as of #69
