### ISSUE TITLE
Empty space in CollectionView during fast scrolling

### ISSUE THREAD

**Issue by madmag77** [Instagram/IGListKit#680]
## New issue checklist
Bug with empty cells [Bug description on stackoverflow](http://stackoverflow.com/a/13389461/377384). In certain conditions (when section insets, lineSpacing and interItemSpacing are set) when one scrolls fast then blocks of cells are disappearing from _collectionView_.
I change Demo here: https://github.com/madmag77/IGListKit/tree/demo-with-emty-cells in order to reproduce this bug. 
One needs just run "Display delegate" on iPad Pro 12.9 and scroll fast. Empty space will occur then.
ScreenShot: <img width="795" alt="screen shot 2017-04-20 at 07 37 53" src="https://cloud.githubusercontent.com/assets/5850849/25208061/614338dc-259c-11e7-9308-c561a566809a.png">
PR that fixes it: https://github.com/Instagram/IGListKit/pull/674

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0 (Current master)
- iOS version(s): 10.3
- CocoaPods/Carthage version: 1.1.1
- Xcode version: 8.3
- Devices/Simulators affected: Simulator iPad Pro 12.9 inch
- Reproducible in the demo project? (Yes/No): Yes (Display delegate demo)
- Related issues:

**Comment by rnystrom** [comment]
@madmag77 amazing! Will dig into this, thank you SO MUCH for providing an example!

**Comment by PhilCai1993** [comment]
I dont know if it is correct. But after replacing `sizeForItem` in `DisplaySectionController.swift`. It does not happen again. 

```Swift
 func sizeForItem(at index: Int) -> CGSize {
        var width = collectionContext!.containerSize.width
        if collectionContext!.containerSize.width > 600 {
            width = collectionContext!.containerSize.width * 0.4
        } else if collectionContext!.containerSize.width > 1200  {
            width = collectionContext!.containerSize.width * 0.2
        }
//        return CGSize(width: width, height: CGFloat(arc4random_uniform(100) + 50))
        return CGSize(width: width, height: CGFloat(50))
    }

```

**Comment by rnystrom** [comment]
@PhilCai1993 ya the error happens randomly when an item on the same row is a lot smaller than the proceeding one. Check out [this explanation of the problem](https://github.com/Instagram/IGListKit/pull/674#issuecomment-295821009).

**Comment by iOSUser110** [comment]
Hi,  I am facing same issue , even with the latest version of IGListKit 3.4.0 , with using IGListKitCollectionViewLayout or using CollectionViewFlowLayout for layouting ,  I tried all the way but not getting the solution for this . like bunch of 4 to 5 cell with empty data on fast scrolling , its looking like very irritating , if somebody have solution for this
