### ISSUE TITLE
Assert generic type in IGListGenericSectionController

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#682]
https://github.com/apple/swift-evolution/blob/master/proposals/0057-importing-objc-generics.md#opting-in-to-type-argument-discovery

In our [new IGListGenericSectionController](https://github.com/Instagram/IGListKit/blob/master/Source/IGListGenericSectionController.h#L18-L28), you can define a section controller with a generic type which saves a little bit of setup:

```objc
@interface StringSectionController: IGListGenericSectionController<NSString *>
@end

@implementation
- (void)didSelectItemAtIndex:(NSInteger)index {
  NSLog(self.object); // compiler knows its an NSString
}
@end
```

While great, implementations can still screw it up:

```objc
- (IGListSectionController *)listAdapter:(IGListAdapter *)listAdapter sectionControllerForObject:(id)object {
  if ([object isKindOfClass:[NSNumber class]]) {
    return [StringSectionController new];
  }
  // ...
}
```

One way to avoid that would be to assert in [-[IGListGenericSectionController didUpdateToObject:]](https://github.com/Instagram/IGListKit/blob/master/Source/IGListGenericSectionController.h#L18-L28).

However, it doesn't look like there is any way at runtime to introspect the generic type that your section controller uses.

I tried using [objc runtime hacks](https://github.com/AlanQuatermain/aqtoolkit/blob/367b73a47e1a459a3758e138024d68dd92c7f33b/Extensions/NSObject%2BProperties.m#L216-L232), but the generic type isn't there. Just `id`.

@jckarter sent [this original proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0057-importing-objc-generics.md#opting-in-to-type-argument-discovery) which is pretty interesting, but would require more work on clients.

Anyone have any ideas? Would love to get some extra runtime safeguards, and also just picking at my curiosity.

**Comment by mattrobmattrob** [comment]
[This SO post](http://stackoverflow.com/a/30866503/856336) makes me think it's not possible. Mainly:

>So the entire lightweight generics feature is based on a [type erasure model](https://en.wikipedia.org/wiki/Type_erasure). Which means that the compiler has all of this rich static type information but it erases that information when generating code.

**Comment by jessesquires** [comment]
As far as I know, this type information simply doesn't exist in the ObjC runtime.

**Comment by rnystrom** [comment]
Had an extensive convo w/ @jckarter on Twitter, not possible in the slightest w/ ObjC generics. We could _maybe_ use some C++ stuff to get this working, but probably not worth the effort. Going to close out.

**Comment by jessesquires** [comment]
@rnystrom -- link to twitter?
