### ISSUE TITLE
When i switch the tab more than one time , somehow cell 's contentView will change it's height

### ISSUE THREAD

**Issue by icefox57** [Instagram/IGListKit#685]
When i switch the tab more than one time , somehow cell 's contentView will change it's height.
Also happen in device

I reload data at viewWillAppear, so every time  switch back will load same local json file and call
adapter.performUpdates(animated: true) 
 
And i remove the cell initialize code to make sure it's maybe the problem from IGListKit
and change contentView color to Teal 

so here is some shoot screen , i print height , you can see it's same value
when the third time i switch back , contentView changed.
![image](https://cloud.githubusercontent.com/assets/1716737/25259990/f3756ede-267b-11e7-88b6-910956353f03.png)
![image](https://cloud.githubusercontent.com/assets/1716737/25260013/12b8258e-267c-11e7-9aa3-3b99b24ec1a1.png)

it's happend randomly. 
I tried many different way , but  i can't find why? and how to solve this.
(If every cell has some height it will not happen)

please help me

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): 10.2.1
- CocoaPods/Carthage version: 1.0
- Xcode version: 8.2.1
- Devices/Simulators affected: Devices & Simulators
- Reproducible in the demo project? (Yes/No):
- Related issues:

**Comment by icefox57** [comment]
after i change object to NSNumber which is same value from my Card object.
and set it at sizeForItem

this problem happen rarely, but still will happen randomly
still have no idea why....

![image](https://cloud.githubusercontent.com/assets/1716737/25270836/90a01ed8-26b4-11e7-800c-b5371bdb4722.png)

**Comment by rnystrom** [comment]
@icefox57 do you have an example project reproducing this issue that we could take a look at? In the meantime, some questions:

- What `UICollectionViewLayout` are you using?
- What happens if you use `adapter.reloadData()` instead?

Also, you probably don't need to update in `viewWillAppear:`, instead just update when data actually changes.

**Comment by icefox57** [comment]
UICollectionViewFlowLayout
adapter.reloadData()  is my first try ,  still will happen this problem, but a little less

And i will make a example project .

**Comment by jessesquires** [comment]
Going to close due to inactivity. 😄  Also, doesn't seem like an IGListKit-specific bug...
