### ISSUE TITLE
[AppleBug] Deleting the same index path twice crashes in batch updates

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#689]
We disabled [this test](https://github.com/Instagram/IGListKit/blob/master/Tests/IGListAdapterE2ETests.m#L1442-L1461) due to flakiness. It turns out that `UICollectionView` can't handle deleting from the same `NSIndexPath` twice in the same `performBatchUpdates:completion:` phase. (though it'll handle 2x inserts just fine...)

This really only manifests when a client deletes the head, e.g. {section = 0, item = 0}, and the updates are coalesced in the same runloop.

Discovered in https://github.com/Instagram/IGListKit/commit/a415ef5552cbfbf2d3884a705241973f4ea72dde and workarounds attempted in #657.

**Comment by jessesquires** [comment]
should file a radar

**Comment by rnystrom** [comment]
Going to punt this for next release, no reports about it and we don't run into this at all, more of a known bug that we might eventually find but is too rare to make hi pri.

**Comment by rnystrom** [comment]
Area:
UIKit

Summary:
If the same NSIndexPath is included in the array provided to `-[UICollectionView deleteItemsAtIndexPaths:]` more than once, eventually there will be an EXC_BAD_ACCESS in `-[UICollectionViewData layoutAttributesForItemAtIndexPath:]`.

Say I have an `NSMutableArray` of data powering the data source of my `UICollectionView`, if I wanted to delete the head element twice, I might do something like:

```objc
[self.collectionView performBatchUpdates:^{
  NSArray *paths = @[
    [NSIndexPath indexPathForItem:0 inSection:0],
    [NSIndexPath indexPathForItem:0 inSection:0]
  ];
  [self.data removeObjectAtIndex:0];
  [self.data removeObjectAtIndex:0];
  [self.collectionView deleteItemsAtIndexPaths:paths];
} completion:nil];
```

If I repeat this action, or do other batch updates, eventually it will crash.

Steps to Reproduce:
1. Open sample app provided
2. Tap "Play" nav bar item a few times
3. Observe crash

Expected Results:
Delete the first two elements each time, don't crash.

Actual Results:
It will delete the first two elements, but after a few times tapping the "Play" item, it will crash.

Version:
10.3.1 (14E304)

Notes:


Configuration:
7 simulator, iPhone 7+

----

[UICollectionViewMultipleDeletesSameIndex.zip](https://github.com/Instagram/IGListKit/files/951875/UICollectionViewMultipleDeletesSameIndex.zip)

----

Please dupe:

https://openradar.appspot.com/radar?id=5021459084738560

**Comment by rnystrom** [comment]
Got a response from the big fruit. This is considered a bad update and crash is ok. 🤷‍♀️

**Comment by jessesquires** [comment]
Weird 🤷‍♂️
