### ISSUE TITLE
Audit+optimize IGListDiffing(...) retain/release

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#695]
ARC obviously makes things safe, but it can tend to be overly protective of memory by retaining/releasing stuff that we know wont/can't be released. We should do our homework and find ways to `__unsafe_unretained`/etc our [diffing algorithm](https://github.com/Instagram/IGListKit/blob/master/Source/Common/IGListDiff.mm#L68).

Also would be interesting to use a benchmark test to see if there is a measurable difference.

**Comment by jessesquires** [comment]
> Also would be interesting to use a benchmark test to see if there is a measurable difference.

I would only support this if there's a significant perf gain

**Comment by rnystrom** [comment]
Not worth it atm

**Comment by rnystrom** [comment]
Wait there are obvious wins here, doing this

**Comment by jessesquires** [comment]
lol

**Comment by rnystrom** [comment]
Looked again, already optimized. I was looking at the blocks within `IGListDiffing(...)`. They already don't retain anything. Good to go.
