### ISSUE TITLE
Prevent keyboard overlapping with scrollToItem

### ISSUE THREAD

**Issue by D-Link13** [Instagram/IGListKit#703]
I have an IGList with textFields in each cell, so I am trying to use `scrollToItem(at: IndexPath, at: UICollectionViewScrollPosition, animated: Bool)` to prevent keyboard overlapping when it appears. This approach requires calling scrollToItem from textFieldDidBeginEditing. How can I pass IndexPath to this method in this case?
Maybe you can advise me some better technique to achieve this goal?

**Comment by D-Link13** [comment]
I've tied to send a cell from section controller to my view controller with delegate like this:
```
func textFieldDidBeginEditing(_ textField: UITextField) {
        let cell = textField.superview?.superview as! MyCell
        delegate?.scrollTo(cell)
    }
```
than in my view controller I've implemented delegate method like this:
```
func scrollTo(_ cell: MyCell) {
        if let indexPath = collectionView.indexPath(for: cell) {
            collectionView.scrollToItem(at: indexPath, at: .top, animated: true)
        }
    }
```
Unfortunately, this doesn't helped me =(

Than I decided to try using observers for keyboard (show, hide). Here is a code from my view controller:
```
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillShow), name: .UIKeyboardWillShow, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillHide), name: .UIKeyboardWillHide, object: nil)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        NotificationCenter.default.removeObserver(self, name: .UIKeyboardWillShow, object: nil)
        NotificationCenter.default.removeObserver(self, name: .UIKeyboardWillHide, object: nil)
    }
func keyboardWillShow(notification: Notification) {
        adjustingHeight(show: true, notification: notification)
    }
    
    func keyboardWillHide(notification: Notification) {
        adjustingHeight(show: false, notification: notification)
    }
    
    func adjustingHeight(show:Bool, notification:Notification) {
        var userInfo = notification.userInfo!
        
        let keyboardFrame = (userInfo[UIKeyboardFrameEndUserInfoKey] as! NSValue).cgRectValue
        
        let animationDurarion = userInfo[UIKeyboardAnimationDurationUserInfoKey] as! TimeInterval
        
        if show {
            collectionView.contentInset = UIEdgeInsetsMake(0, 0, keyboardFrame.height, 0)
        } else {
            UIView.animate(withDuration: animationDurarion) {
                self.collectionView.contentInset = UIEdgeInsetsMake(0, 0, 0, 0)
            }
        }
    }
```
Well, this approach gives me some result.. It scrolls well when keyboard appears, but for some reason it breaks my layout after keyboard hides. 

Can anyone help me with this issue, please?

**Comment by rnystrom** [comment]
@D-Link13 what's the behavior when you use `collectionView.scrollToItem(at: indexPath, at: .top, animated: true)`? It might not work b/c the cell isn't visible. The docs say:

> Scrolls the collection view contents **until the specified item is visible**.

You can also try getting the associated object for that cell (cell -> index path -> [objectAtSection:](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.h#L177-L184)) and then call [this method](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.h#L225-L238) to scroll to the object. That will use the cell's frame and position the content offset of the view.

**Comment by jessesquires** [comment]
Going to close due to inactivity 😄
