### ISSUE TITLE
IGListCollectionViewLayout release

### ISSUE THREAD

**Issue by nikitaame** [Instagram/IGListKit#704]
Hey All!

I was wondering if you had an estimate on the next stable release for IGListCollectionViewLayout. Really hoping to use BOOL stickyHeaders but don't want to use master.

Thanks!
Nikita

**Comment by jessesquires** [comment]
Hey @nikitaame ! 😄 

We are aiming to get this out within 1-2 weeks. There are only a few things left to finish.

We actually recommend using `master` — this is what the Instagram iOS app uses and ships weekly to the app store. 😄 It's stable, though there is *some* churn — however, you can pin to a specific commit to avoid that.
