### ISSUE TITLE
cellForItem dequeing cell with IBOutlets == nil

### ISSUE THREAD

**Issue by xiaosongshu** [Instagram/IGListKit#706]
Could there be any reason why my cell is dequeing with all IBOutlets being nil? Trying to literally load a basic cell but crashing on:

        cell.messageLabel.text = message?.text

with ```fatal error: unexpectedly found nil while unwrapping an Optional value```

and Variables View / Console showing all other IBOutlets are nil (ie `messageLabel` = `(UILabel!) nil` hence my belief the reason for the crash. Here's the Section Controller:

```
class MessageSectionController: IGListSectionController {
    var message: Message?
}

extension MessageSectionController: IGListSectionType {
    func numberOfItems() -> Int {
        return 1
    }
    
    func sizeForItem(at index: Int) -> CGSize {
        guard let context = collectionContext, let message = message else {
            return .zero
        }
        
        return MessageCollectionViewCell.size(for: context.containerSize.width, message: message)
    }
    
 func cellForItem(at index: Int) -> UICollectionViewCell {

        let cell = collectionContext!.dequeueReusableCell(of: MessageCollectionViewCell.self, for: self, at: index) as! MessageCollectionViewCell

        cell.messageLabel.text = message?.text // crashes HERE

        // all other assignments here, commented out during testing and removed for simplicity

        return cell
    }
    
    func didUpdate(to object: Any) {
        self.message = object as? Message
    }
    
    func didSelectItem(at index: Int) {
    }
}
```

And here's the AdapterDataSource

```
extension MessagesViewController: IGListAdapterDataSource {
    func objects(for listAdapter: IGListAdapter) -> [IGListDiffable] {
        return returnDisplayedMessages()
    }
    
    func listAdapter(_ listAdapter: IGListAdapter, sectionControllerFor object: Any) -> IGListSectionController {
        
            return MessageSectionController()

    }
    
    func emptyView(for listAdapter: IGListAdapter) -> UIView? {
        return nil
    }
}
```

With adapter assigned in MessagesViewController

```
// ...
    @IBOutlet weak var collectionView: IGListCollectionView! // connected via storyboard

//...
    lazy var adapter: IGListAdapter = {
        return IGListAdapter(updater: IGListAdapterUpdater(), viewController: self, workingRangeSize: 0)
    }()

//...
        self.adapter.collectionView = self.collectionView
        self.adapter.dataSource = self

```

And to add, not sure if it makes a difference but my Message model is a Realm `Object`

**Comment by rnystrom** [comment]
@xiaosongshu it looks like you're dequeuing your cells with the class API. You need to use [this method for XIBs](https://github.com/Instagram/IGListKit/blob/master/Source/IGListCollectionContext.h#L127-L142) or [this method for storyboards](https://github.com/Instagram/IGListKit/blob/master/Source/IGListCollectionContext.h#L144-L155).

Let us know if that works!

**Comment by xiaosongshu** [comment]
Ah that fixed it! Thanks Ryan (@rnystrom), and also great talk at try! Swift. Came across the video on Realm's site and it's what convinced me to give this a shot. 

Now that I had a chance to test out IGListKit, had one follow-up question was hoping you could help with (apologies in advance, it's a big long)..

[Background]
I saw your comment in #629 where you mentioned cell transforms could be applied in IGListDisplayDelegate's `willDisplay` method. I'm also trying to apply cell transforms, but my use case is slightly different, as I have two arrays, one being messages already displayed to the user, and one for new messages that haven't been seen yet. For each new message that hasn't been seen yet, I want to animate each one in with a scale transform, one after the other with a slight delay. Eventually the messages will be removed from the new message array, and will each be appended to the existing messages array.

I got this working previously by using a pretty complicated array of "pendingMessages", where one message would be animated at a time via `performBatchUpdates`, and in the completion block, I would call an `animate` method on the cell to perform the transforms, then recursively call `performBatchUpdates` to animate in the next "pendingMessage." This gave me plenty of headaches, which lead to me discovering IGListKit :)

```
// animatePendingMessages() {
// ...
//    self.collectionView.performBatchUpdates({ () -> Void in
// ...
        }, completion: { finish in
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                if finish {
                    self.collectionView.scrollToItem(at: IndexPath(row: self.returnDisplayedMessages().count - 1, section: 0), at: .top, animated: true)
                    if let cell = (self.collectionView.cellForItem(at: IndexPath(row: self.returnDisplayedMessages().count - 1, section: 0)) as? MessageCollectionViewCell) {
                        cell.animate { // perform the transforms
                            animateNext() // animate the next message in "pendingMessages" array
                        }
                    } else {
                        animateNext()
                    }
                }
            }
```

You can see what the animate method inside the MessageCollectionViewCell looks like here:

```
func animate(completion: (() -> Void)?) {
        topView.isHidden = true
        let resizeAnimation = CABasicAnimation(keyPath: "transform.scale")
        resizeAnimation.fromValue = 0.0
        resizeAnimation.toValue = 1.0
        resizeAnimation.duration = 0.4
        resizeAnimation.beginTime = CACurrentMediaTime()
        resizeAnimation.fillMode = kCAFillModeBackwards
        messageLabel.layer.add(resizeAnimation, forKey: "scale")
        containerView.layer.add(resizeAnimation, forKey: "scale")
        coverView.layer.add(resizeAnimation, forKey: "scale")
        
        let startY = dateLabel.layer.position.y - 150
        let startTransform: CATransform3D = CATransform3DMakeTranslation(0, startY, 0)
        let endTransform: CATransform3D = CATransform3DIdentity
        
        let transformAnimation = CABasicAnimation(keyPath: "transform")
        transformAnimation.fromValue = NSValue(caTransform3D:startTransform)
        transformAnimation.toValue = NSValue(caTransform3D:endTransform)
        transformAnimation.duration = 0.4
        
        transformAnimation.beginTime = CACurrentMediaTime() + 0.4
        transformAnimation.fillMode = kCAFillModeBackwards
        
        dateLabel.layer.add(transformAnimation, forKey: "position")
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.4) {
            completion?()
        }
    }
```

The problem I'm having is adding back this `cell.animate` method in IGListDisplayDelegate methods. Adding it to `willDisplay` animates the cell every time you scroll which I don't want (since I only want to animate in the new messages once), whereas calling it in `didEndDisplaying` never actually shows the animations.

```
    func listAdapter(_ listAdapter: IGListAdapter, didEndDisplaying sectionController: IGListSectionController, cell: UICollectionViewCell, at index: Int) {
        print("~ willDisplay cell")
        if let cell = cell as? MessageCollectionViewCell {
            cell.animate(completion: nil)
        }
    }
```

[Question]
Do you have any idea how I can go about reusing my `cell.animate` method call, to animate in only the new messages, one after each other (cascading / delayed)? So effectively you can imagine the collectionView first scrolls to the bottom of the screen, then one new message animates in after each other (think similar to the Qu@rtz news app).

**Comment by rnystrom** [comment]
@xiaosongshu good question, but do you mind copy/pasting that into a new issue so we can track separately? That way if someone else runs into the same problem, it'll be much easier for them to find vs being buried in an unrelated issue.
