### ISSUE TITLE
Infinite horizontal scrolling in embedded CollectionView

### ISSUE THREAD

**Issue by swissdev** [Instagram/IGListKit#710]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): 10.3
- CocoaPods/Carthage version: 
- Xcode version: 8.3.2
- Devices/Simulators affected: 
- Reproducible in the demo project? (Yes/No): no
- Related issues:

### Debug information

Hi, very great Kit! It made the whole development of one of our projects much easier and simpler. Thanks. We are using embedded horizontal collection views in some sections for sliding views. Is there a way to do infinite scrolling like a carousel?

**Comment by rnystrom** [comment]
@swissdev interesting question! The best way to do infinite scrolling is actually a `UIScrollView` trick where you adjust the `contentOffset` in `UIScrollViewDelegate` methods. Check out [this 2011 WWDC video](https://developer.apple.com/videos/play/wwdc2011/104/), they discuss techniques around 4:25.

To hook into those methods with IGListKit, just attach an object as the [scrollViewDelegate](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.h#L70-L73) on an `IGListAdapter`.

**Comment by swissdev** [comment]
Many thanks. Very great! Thanks for sharing. We didn't know about this technique.
