### ISSUE TITLE
Best practice to expand a cell animated in a section?

### ISSUE THREAD

**Issue by PhilCai1993** [Instagram/IGListKit#711]
I've read #499 and #459 , But still quite confused.

![image](https://cloud.githubusercontent.com/assets/6828315/25624221/520582be-2f8b-11e7-97ed-ef4eb75c60b2.png)

The image above is a section controller, "cell2" is expanded when some extra data is received from HTTP request. The single section is composed of a red header and serval cells(I didn't make each cell a section because the whole list is rather complicated, there are a lot of other kind of sections). 

The section controller has a "model", naming "SectionObject" for example.
```ObjC
@interface SectionObject : NSObject <IGListDiffable>
@property (nonatomic, copy) NSArray *datas;//(each data represent a cell, there are 4 in the pic above)
@end
```

If I want to expand the "cell2", I found the index of data which represent "cell2", modify that data, then call ```reloadInSectionController:atIndexes:``` in ```IGListBatchContext```. The cell did expand with a default animation.  But if I want to take advantage of the invalid layout API to make spring animations, I didn't find a good practice.

And in the example of #499 , the height of the cell is bind to a property `height` in section controller, the "data" is not modified. And in my example, the data for the cell is modified(add some extra info from server then update the cell).

**Comment by rnystrom** [comment]
@PhilCai1993 what determines the height of cell2? Is it the data itself? A member/property of the data?

Can you not just call `invalidateLayoutForSectionController: self` like in [the example](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/ExpandableSectionController.swift#L47)?

**Comment by PhilCai1993** [comment]
one property of the data

**Comment by rnystrom** [comment]
@PhilCai1993 As long as the data makes its way to the section controller, the invalidate API should work exactly the same as `reloadInSectionController:`. Just call invalidate _after_ the data has changed.

**Comment by PhilCai1993** [comment]
I'll post some examples later at the weekend.

**Comment by jessesquires** [comment]
Going to close as resolved. 😄

**Comment by PhilCai1993** [comment]
@jessesquires 😄 OK, I did post any example because I'm busy with my work😂. Could I reopen it when examples are post?
