### ISSUE TITLE
sizeForSupplementaryViewOfKind is called always for index=0

### ISSUE THREAD

**Issue by gobetti** [Instagram/IGListKit#714]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): Any
- CocoaPods version: 1.2.1
- Xcode version: 8.3.2
- Devices/Simulators affected: Any
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: -

No matter which is the actual section index, the delegate method `-[IGListSupplementaryViewSource sizeForSupplementaryViewOfKind:atIndex:]` is always called for an index=0. The bug comes from the fact that an `indexPath` is calculated by `-[UICollectionViewDelegateFlowLayout collectionView:layout:referenceSizeForHeaderInSection:]` and `-[UICollectionViewDelegateFlowLayout collectionView:layout:referenceSizeForFooterInSection:]` like this:
`NSIndexPath *indexPath = [NSIndexPath indexPathForItem:0 inSection:section];`
however in the defective method mentioned above, the `index` that is passed is extracted from the `NSIndexPath` like this:
`const CGSize size = [supplementaryViewSource sizeForSupplementaryViewOfKind:elementKind atIndex:indexPath.item];`
(notice that the `item` is taken instead of the `section`, thus always resulting 0)

**Comment by jessesquires** [comment]
Thanks @gobetti !

**Comment by rnystrom** [comment]
@gobetti thanks for looking into this! I'm not sure I understand what the bug is though. Supplementary views are meant to be used with index paths when used beyond `UICollectionViewFlowLayout`. Notice how the [UICollectionViewLayout supplementary attributes API](https://developer.apple.com/reference/uikit/uicollectionviewlayout/1617792-layoutattributesforsupplementary?language=objc) asks for an index path (meaning you can have more than one, thus needing the `item`).

We designed the `IGListSupplementaryViewSource` API with this in mind.

Do you have an example of how this breaks? With the change in #715, implementations with more than one supplementary view will break (b/c they receive the section and not the index of the view).

**Comment by gobetti** [comment]
Hi @rnystrom, maybe the issue wasn't noticeable so far because 1) usually people use IGListKit with single cell section controllers and 2) usually people want the same size for a section header/footer, regardless of its index. The issue is easily noticeable though by setting a breakpoint in an IGListSupplementaryViewSource method implementation when under a multiple section collection view. The method will be called multiple times, always with the index 0. After fixing it, the indexes are correctly called for each section.
Notice that "item" is always 0, since this is the value that is being passed to the NSIndexPath constructor.

I noticed you guys are using the master branch for the upcoming release, however it would be interesting if it was possible to have a non-major release where this bugfix (or others) are present since major changes have occurred since 2.x. If you have any plan on continuous stable releases for 2.x, let me know how to open a PR targeting that codebase (a cherry-pick from my commit into 2.1.0 won't work, the files are different).

Thanks!

**Comment by gobetti** [comment]
@rnystrom , considering this part of your comment:

> With the change in #715, implementations with more than one supplementary view will break

My code in #715 does only affect the size that is being returned for a supplementary view. You can still have multiple, but now you can return different sizes for them according to their section index, which today isn't possible due to the index always being equal to 0.

**Comment by rnystrom** [comment]
@gobetti 

> You can still have multiple, but now you can return different sizes for them according to their section index, which today isn't possible due to the index always being equal to 0.

That would be the responsibility of different section controllers implementing their sizes differently, right?

W/ your solution, how would you size two different supplementary views within the same section? They would both have the same section value.

Can you give a little more detail about your setup? The API is designed to return the `item` index, not the section (same as the `cellForItemAtIndex:` API).

**Comment by MarvinNazari** [comment]
@rnystrom: but isn't `elementKind` there for that same reason? so u return different size depending on `elementKind` but still same index?

**Comment by gobetti** [comment]
@rnystrom I think some part of my explanation and my unit test failed to be clear, I'm sorry for that. Could you try again to run the unit test before and after my modification? You'll see that an object implementing the `IGListSupplementaryViewSource` will never be able to receive any index other than 0. This value 0 is hardcoded at the moment that you create an NSIndexPath with item=0 and section=sectionIndex (the only variable part here is the sectionIndex). You need to know the section index in order to return different sizes for different sections, but currently you're passing the item, which is always 0 and thus you won't be able to return different sizes.

**Comment by gobetti** [comment]
And continuing @MarvinNazari 's reasoning, if we assume that what you said about the API is correct, then what is the index parameter for if it will always be 0?

**Comment by rnystrom** [comment]
@gobetti it will always be 0 if you use 'UICollectionViewFlowLayout', but if you build your own layout with arbitrary supplementary views you may need the index for each supplementary view. 

You're right that you can use different element kinds to distinguish between different types, but just as you can have multiple cells of the same type, you can do the same with supplementaries.

I'm still curious, hiw does this not work in your implementation? Are you using a single 'IGListSupplementaryViewSource' shared with all section controllers? Why do you need the section?

Sorry I'm having trouble understanding! 🤕

**Comment by gobetti** [comment]
Let's say I implemented the UICollectionFlowDelegate on my own, i.e. without IGListKit. Then I'd be able to specify a size for each section, based on their index. IGListKit implements that protocol for me, converting that sectionIndex into an index path (with item = 0), Passing this index path to another method and finally calling back the IGListSupplementaryViewSource method by passing the item instead of the section. The result is that this final method is being provided with something that is not what was provided in the original protocol - and which is always the same value.

This doesn't work for me because I have multiple sections in the same collection view, each one of them containing multiple cells. I want to have the same header for every section, so it's natural that I'm using the same supplementary view source for them. This scenario is probably the most common, when you want all the sections in a collection view to have the same UIView header. The only difference though is their size, but then I can't differ them for the reasons above.

**Comment by gobetti** [comment]
I wasn't clear that the same supplementary view source is used multiple times, but that's because we have multiple sections. It's always the same section controller class, but multiple instances of it.
