### ISSUE TITLE
Rename new sectionIndex API to "section"?

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#720]
I should have caught this earlier, but for consistent naming alongside [these APIs](https://github.com/Instagram/IGListKit/blob/master/Source/IGListSectionController.h#L105-L113), we should probably name `sectionIndex` to just `section`.

Thoughts @jessesquires @amonshiz? I'm happy to peel this off really quick before 3.0.0

**Comment by amonshiz** [comment]
yeah, that is fine by me. no one said anything so i stuck with `sectionIndex`.

**Comment by jessesquires** [comment]
completely agree that `section` is bettur

**Comment by jessesquires** [comment]
also +1 for `3.0` 😄

**Comment by BasThomas** [comment]
Lmk if I can help out with this one, @rnystrom :)

**Comment by rnystrom** [comment]
Thanks @BasThomas! It's landing internally right now
