### ISSUE TITLE
Collection view debug dump script empty

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#722]
[This code](https://github.com/Instagram/IGListKit/blob/master/Source/Internal/UICollectionView%2BDebugDescription.m#L14-L41) is showing up empty when used [here](https://github.com/Instagram/IGListKit/blob/master/Source/Internal/IGListAdapter%2BDebugDescription.m#L70).

[Example](https://github.com/Instagram/IGListKit/issues/699#issuecomment-297151847)

**Comment by jessesquires** [comment]
🤔  so what's happening here?
