### ISSUE TITLE
Compile Error In Examples

### ISSUE THREAD

**Issue by namsoila** [Instagram/IGListKit#73]
Error in SpinnerCell.swift

```
IGListKit-master/Example/IGListKitExamples/Views/SpinnerCell.swift:25:53: Cannot convert value of type '(IGListCollectionContext) -> CGSize' to expected argument type 'IGListSingleSectionCellSizeBlock' (aka '(Optional<IGListCollectionContext>) -> CGSize')
```

Error in SingleSectionViewController.swift

```
IGListKit-master/Example/IGListKitExamples/ViewControllers/SingleSectionViewController.swift:65:74: Cannot convert value of type '(IGListCollectionContext) -> CGSize' to expected argument type 'IGListSingleSectionCellSizeBlock' (aka '(Optional<IGListCollectionContext>) -> CGSize')
```

Xcode suggests fix using casting that allows project to build so that line goes from:

```
return IGListSingleSectionController(cellClass: SpinnerCell.self,
                                         `configureBlock:` configureBlock,
                                         sizeBlock: sizeBlock)
```

To:

```
return IGListSingleSectionController(cellClass: SpinnerCell.self,
                                         configureBlock: configureBlock,
                                         sizeBlock: sizeBlock as! IGListSingleSectionCellSizeBlock)
```

and from:

```
let sectionController = IGListSingleSectionController(nibName: NibCell.nibName,
                                                              bundle: nil,
                                                              configureBlock: configureBlock,
                                                              sizeBlock: sizeBlock)
```

To:

```
let sectionController = IGListSingleSectionController(nibName: NibCell.nibName,
                                                              bundle: nil,
                                                              configureBlock: configureBlock,
                                                              sizeBlock: sizeBlock as! IGListSingleSectionCellSizeBlock)
```

However, this causes crash once the Single Section Controller or Tail Loading sections are accessed.

## New issue checklist

- [+ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [+ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- Library version(s): 1.0.0 and master
- iOS version(s): 10.0.2 and 9.3.5
- Devices/Simulators affected: se/6
- Reproducible in the demo project? (Yes/No): yes
- Related issues:

**Comment by rnystrom** [comment]
Hey @namsoila I'm not able to reproduce any compilation errors on `master` or `stable`. Can you try pulling `master` and building again? Also make sure you're opening `Example/IGListKitExamples.xcworkspace`.

**Comment by namsoila** [comment]
Thanks @rnystrom ! Pulled current master with addition of single section controller using alerts and is fine.
