### ISSUE TITLE
[AppleBug] UICollectionView crashes when changing contentInset before changing its dataSource

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#732]
Summary:
When using "embedded" `UICollectionViews` and `UICollectionViewFlowLayout` (e.g. a vertical, full-width collection view that has cells with horizontal `UICollectionView`s in them), if you change the `contentInset` property of one of the embedded collection views **before** changing the `dataSource` (changed because the cells are reused), `UICollectionView` will throw when validating layout attributes.

This seems to be because changing the `contentInset` triggers an invalidation pass, setting some internal state that disallows another invalidation after changing the dataSource (which _should_ trigger an internal `reloadData` and invalidation).

This issue can be avoided by using a custom `UICollectionViewFlowLayout` subclass and overriding:

```objc
- (BOOL)invalidateFlowLayoutDelegateMetrics {
  return YES;
}
```

But that is both undocumented and unexpected behavior.

This also only occurs when changing the contentInset.top between reused collection views.

Steps to Reproduce:
1. Open uploaded example app.
2. Scroll to bottom.
3. Crash (100% of the time)

Expected Results:
`UICollectionView` shouldn't throw an exception, the views should be laid out with the correct `contentInset`, and the dataSource change should result in a `reloadData` call that invalidates on layoutSubviews.

Actual Results:
`UICollectionView` crashes, throwing an exception like:

```
'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist:
```

Version:
iOS 10.3.2

Notes:

Configuration:
iPhone 7+, iPhone 7 Simulator

Attachments:
[UICollectionViewContentInsetCrash.zip](https://github.com/Instagram/IGListKit/files/991042/UICollectionViewContentInsetCrash.zip)

**Comment by rnystrom** [comment]
Please dupe

https://openradar.appspot.com/radar?id=5041489335812096

**Comment by jessesquires** [comment]
> 3. Crash (100% of the time)

😆

**Comment by bdotdub** [comment]
Just ran the project and confirmed it no longer happens. Closing this out!
