### ISSUE TITLE
Carthage 0.22.0 -  No available version 3.0.0 for github "Instagram/IGListKit"

### ISSUE THREAD

**Issue by tuanvo** [Instagram/IGListKit#736]
## New issue checklist

- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version: carthage 0.22.0
- Xcode version: 
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by jessesquires** [comment]
Thanks @tuanvo ! We haven't tagged the 3.0 release yet but will be doing so soon!

**Comment by jessesquires** [comment]
@tuanvo this should work now!
