### ISSUE TITLE
Binding section controller resizes self-sizing cells on calling performUpdates

### ISSUE THREAD

**Issue by HarshilShah** [Instagram/IGListKit#739]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0.0
- iOS version(s): 10.3.1
- CocoaPods/Carthage version: NA
- Xcode version: 8.3
- Devices/Simulators affected: Yes; both
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: NA

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

<details>

```
IGListAdapter 0x608000151f60:
  Updater type: IGListAdapterUpdater
  Data source: <IGListKit_SelfSizingBinding.BindingSelfSizingViewController: 0x7fbb0c4057e0>
  Collection view delegate: (null)
  Scroll view delegate: (null)
  Is in update block: No
  View controller: <IGListKit_SelfSizingBinding.BindingSelfSizingViewController: 0x7fbb0c4057e0>
  Is prefetching enabled: Yes
  Registered cell classes:
  {(
    IGListKit_SelfSizingBinding.FullWidthSelfSizingCell
)}
  IGListAdapterUpdater instance 0x6080000d2910:
    Moves as deletes+inserts: No
    Allows background reloading: Yes
    Has queued reload data: No
    Queued update is animated: Yes
    State: Idle
  Section map details:
    Object and section controller at section: 0:
      <IGListKit_SelfSizingBinding.LabelSectionModel: 0x618000031fc0>
      <IGListKit_SelfSizingBinding.LabelModelSectionController: 0x60000012be00>
  Collection view details:
    Class: UICollectionView, instance: 0x7fbb0c827200
    Data source: <IGListAdapter: 0x608000151f60>
    Delegate: <IGListAdapter: 0x608000151f60>
    Layout: <UICollectionViewFlowLayout: 0x7fbb0c405cb0>
    Frame: {{0, 0}, {414, 736}}, bounds: {{0, -64}, {414, 736}}
    Number of sections: 1
      3 items in section 0
    Visible cell details:
      Visible cell at section 0, item 0:
      <IGListKit_SelfSizingBinding.FullWidthSelfSizingCell: 0x7fbb0c50ef30; baseClass = UICollectionViewCell; frame = (0 0; 414 132); text = 'Aenean lacinia bibendum n...'; layer = <CALayer: 0x600000036840>>
      Visible cell at section 0, item 1:
      <IGListKit_SelfSizingBinding.FullWidthSelfSizingCell: 0x7fbb0c512ab0; baseClass = UICollectionViewCell; frame = (0 132; 414 132); text = 'Donec sed odio dui. Donec...'; layer = <CALayer: 0x600000038360>>
      Visible cell at section 0, item 2:
      <IGListKit_SelfSizingBinding.FullWidthSelfSizingCell: 0x7fbb0c514ab0; baseClass = UICollectionViewCell; frame = (0 264; 414 193); text = ‘Sed posuere consectetur e...’; layer = <CALayer: 0x6000000394a0>>
```
</details>

When using the new `ListBindingSectionController` with self-sizing cells, the cells are resized to their default size as defined in `sectionController(_ sectionController: ListBindingSectionController<ListDiffable>, sizeForViewModel viewModel: Any, at index: Int)`, and then resized back to the correct size whenever `performUpdates` is called.

Resizing cells when `performUpdates` is called makes sense, but the intermediate change to the default size doesn’t quite make sense (especially given how at least for me the cell size remains unchanged at the end 90% of the time), and produces some janky animations/lag.

The debug information is a bit hard to capture since the change is just momentary, but I have created a simple [demo project](https://github.com/HarshilShah/IGListKit-SelfSizingBinding), using some components already found in the provided examples, to demonstrate this behaviour.

Btw, congrats on shipping 3.0! 🎉

**Comment by rnystrom** [comment]
Adding this to #516.

Thanks for the sample! Going to poke around at it. Hard to prioritize estimated size stuff right now, but I'd definitely like to get this working since its a new feature and will probably be pretty common.

I'd guess this has something to do with how we are [manually configuring](https://github.com/Instagram/IGListKit/blob/master/Source/IGListBindingSectionController.m#L64-L72) cells that are reloaded (instead of actually reloading them).

**Comment by HarshilShah** [comment]
Hmm, my expectation was that it should manually configure cells, as that would enable animating changes in `bindViewModel`, as discussed in #451

**Comment by jessesquires** [comment]
closing this in favor of tracking at #516

**Comment by HarshilShah** [comment]
Hey folks, I’m wondering has there been any progress on this? The source file in question hasn’t changed on public branches, but I don’t know if any progress has been made in private, hence the question.

I don’t, uh, know Objective-C, but I’d be happy to take a stab at it if you folks could point me in the right direction as to what might fix this.

Thanks!

**Comment by rnystrom** [comment]
Hey @HarshilShah! We're moving all the self-sizing stuff to #516. We honestly don't really prioritize self-sizing cells or Auto Layout b/c we don't use it at all internally (and have a **lot** of reasons not to). 

I overlooked your demo project tho. Going to download that and give it a spin, see if anything sticks out.

**Comment by HarshilShah** [comment]
Yeah I figured, but was curious if anything had changed given changes in iOS 11.

**Comment by HarshilShah** [comment]
An update on this: Manually fetching visible cells and binding new view models seems to work with no resizing involved. I've updated my demo project for this: https://github.com/HarshilShah/IGListKit-SelfSizingBinding

This skips over the diffing step, but the result should be the same regardless: There's only one root model and binding section controller, so diffing should be no issue there. For the individual view models, since the identifiers (text) remain the same and the colours change, the result of the diff should be to apply the 3 new view models to the 3 existing cells
