### ISSUE TITLE
Help with scroll(to:..)

### ISSUE THREAD

**Issue by folexz** [Instagram/IGListKit#743]
## New issue checklist

- [+] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [+] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: last
- iOS version(s): 9.1-now
- CocoaPods/Carthage version: last
- Xcode version: last
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

So I have a IGListCollectionView that looks like UIPageViewController (horizontal scroll, paging enabled), I need to show the last cell when app loads. How can I do that?

**Comment by Sherlouk** [comment]
You state that you're using the "last" (assuming latest) version of IGListKit, but as per the discussion [here](https://github.com/Instagram/IGListKit/issues/409) the `IGListCollectionView` has been removed in version 3.0!

Regardless `IGListCollectionView` was just a small wrapper of `UICollectionView` providing some warnings/errors when you tried to use certain methods. You should be able to scroll the same way you would if it was just a `UICollectionView` using the scrollToItem(at: indexPath) method like:

```swift
collectionView.scrollToItem(at: IndexPathOfLastItem, at: .centeredHorizontally, animated: false)
```

Does this help?

**Comment by folexz** [comment]
Thanks @Sherlouk, one more question, how do I find an IndexPath for last item? I've tried few methods, but nothing has helped me :(

**Comment by Sherlouk** [comment]
Well that will depend on your exact setup, but you just need to construct an IndexPath based on the size of your collection view.

Assuming you follow IGListKit recommendations and have many sections, then you _could_ do something like this:

```swift
IndexPath(item: 0, section: collectionView.numberOfSections)
```

**Comment by folexz** [comment]
@Sherlouk Thanks a lot!

**Comment by Sherlouk** [comment]
We good to close this issue @folexz?

**Comment by folexz** [comment]
Yes, we are. Thanks a lot.


От 16 May 2017 в 18:13:38, James Sherlock (notifications@github.com)
написал:

You state that you're using the "last" (assuming latest) version of
IGListKit, but as per the discussion here
<https://github.com/Instagram/IGListKit/issues/409> the IGListCollectionView
has been removed in version 3.0!

Regardless IGListCollectionView was just a small wrapper of UICollectionView
providing some warnings/errors when you tried to use certain methods. You
should be able to scroll the same way you would if it was just a
UICollectionView using the scrollToItem(at: indexPath) method like:

collectionView.scrollToItem(at: IndexPathOfLastItem, at:
.centeredHorizontally, animated: false)

Does this help?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Instagram/IGListKit/issues/743#issuecomment-301762978>,
or mute the thread

**Comment by jessesquires** [comment]
Thanks @Sherlouk !
