### ISSUE TITLE
Show Jazzy installation instructions when not installed locally

### ISSUE THREAD

**Issue by BasThomas** [Instagram/IGListKit#744]
This came up in #681:

> I could alternatively change the SwiftLint script to rely on a user's `HomeBrew` installed copy of SwiftLint (instead of a locally referenced binary), and echo installation instructions if they don't have it installed?

> That's how we handle `jazzy`. User must have it installed. (Though we don't provide a helpful message about how to install. that would be nice)

**Comment by Sherlouk** [comment]
I'll pick this up
