### ISSUE TITLE
[Question] How to implement grid layout like Instagram's photo lists

### ISSUE THREAD

**Issue by yuzushioh** [Instagram/IGListKit#746]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0
- iOS version(s): all

### Question
I was able to implement a grid layout using `IGListGridCollectionViewLayout` (codes below) in version 2.2.0, but after updating it to version 3.0.0 I am not sure how I should implement the same feature since `IGListGridCollectionViewLayout` was replaced by `IGListCollectionViewLayout` which is not `UICollectionViewFlowLayout` and is restricted to inherit.

This is the layout I want to implement.
![img_2263](https://cloud.githubusercontent.com/assets/12425729/26140035/8a232f40-3b0f-11e7-8143-f9e82016d80b.PNG)

I was able to do the layout with the piece of code below, but in version 3.0.0 I can't do the same thing by using `UICollectionViewFlowLayout` instead of `IGListGridCollectionViewLayout`.

In `ViewController` inherited from `IGListAdapterDataSource`
```swift
    let layout: IGListGridCollectionViewLayout = {
        let layout = IGListGridCollectionViewLayout()
        layout.minimumInteritemSpacing = 1
        layout.minimumLineSpacing = 1
        return layout
    }()

    let collectionView = IGListCollectionView(frame: .zero, collectionViewLayout: layout)
    view.addSubview(collectionView)
    adapter.collectionView = collectionView
```

In `SectionController`
```swift
     override init() {
        super.init()
        minimumInteritemSpacing = 1
        minimumLineSpacing = 1
    }

    func sizeForItem(at index: Int) -> CGSize {
        let rowCount = photo.rowCount
        let containerWidth = collectionContext?.containerSize.width ?? 0
        let width = (containerWidth - (minimumLineSpacing * rowCount)) / rowCount
        return CGSize(width: width, height: width)
    }
```

It would be really great if someone from Instagram team tells me how you guys do that. 
Thank you!

**Comment by jessesquires** [comment]
Thanks @yuzushioh ! 😄 

It should work the same way. Our storyboard example uses the new layout:

https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/ViewControllers/StoryboardViewController.swift

**Comment by michaeldong** [comment]
hi @jessesquires , I see your link, I try it! ,and on purpose, I set "3" height larger; But I want "5","6" below near "1","2"（now this was Occupy by spaces),  I guess I'm not use the correct Layout ? Hope for your help, What I should do or a demo for this. Thanks.
![image](https://user-images.githubusercontent.com/1925773/34461805-cbf95868-ee6f-11e7-8019-1a358c3bd6e1.png)

**Comment by wang9262** [comment]
Run into the same issue,is there any solutions? only writing a specific layout makes sense?

**Comment by zhubofei** [comment]
@michaeldong @wang9262 Yes, you have to write a specific layout for this case.
