### ISSUE TITLE
Issues updating collectionView with new sections

### ISSUE THREAD

**Issue by jonauz** [Instagram/IGListKit#747]
## Issues updating collectionView with new sections

Instantly saying sorry for little info for starting, so please let me know what's not clear and what info in addition I need to provide.

I'm building a page of two columns using two `Diffable` objects and two `section controllers`.
Left is kind of menu with embedded collection view.
Right side - content, made of embedded collection view.

Now i call one API to get menu, and then I call second API to get content part for selected menu item.
Menu part loads nice, but content section seems to never appear, even that Diffable objects for the top collection view is increased by adding Content Diffable object.
I try many different reloading functions, but non of them seems to update UI with Content section part.
And I tested, main collection view `sections` array count does have 2 objects, even return appropriate Content section controller.

Some how I do miss a good example how to use IGListKit with dynamically changing content list, or I'm missing something useful.

Can some one please help me to get on track?
And it's a bit urgent, as I started to implement some new pages, schedule is tight.

### General information

- `IGListKit` version: 3.0.0
- iOS version(s): 10.3
- Xcode version: 8.3.2
- Reproducible in the demo project? (Yes/No): No

**Comment by BasThomas** [comment]
Is it possible to post the code you are referencing, or a project which shows the issue?

**Comment by jonauz** [comment]
I would need to rewrite it into separate project, which I could just need time a bit more spare time, still need to deliver page on time 🤔 Will try, but in the mean time if any one can propose some ideas, really will appreciate.
Also on small side project had similar issue with inserting, loading and scrolling to new cell using default methods.
Eventually made it work with some ugly hacks.
Maybe will include both examples.

#### Thoughts:
So far have concern that either I'm using IGListKit not as it was intended, or there some very specific use case which is not clear.

**Comment by jonauz** [comment]
#### Short update:
After adding `adapter.reloadData(completion: nil)` in `viewDidAppear(_ animated: Bool)` the missing Content SectionController view appears in the screen. Though, I'm calling this same method in completion handler after API request and data parsing to add new content to main data model.
It's weird why same method in completion handler is not making collection views to load properly.
It's still not done.. keep on testing more.

**Comment by jessesquires** [comment]
hey @jonauz ! 😄 

thanks for the update!

sounds like maybe you aren't calling that completion handler code on the main thread?

**Comment by jonauz** [comment]
@jessesquires no.. completion hangler is being executed on the main thread, tested. Will update when i have some more details.
Do we have any examples with such dynamic loading cells.. i.e. Fetch new objects, append to secions data source and reload collection view?

**Comment by rnystrom** [comment]
@jonauz we have an example of "tail loading" more data [here](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/ViewControllers/LoadMoreViewController.swift), hope that's useful!
