### ISSUE TITLE
[Q] Responding on scroll

### ISSUE THREAD

**Issue by krysztalzg** [Instagram/IGListKit#748]
### General information

- `IGListKit` version: 2.0
- iOS version(s): 10.3
- CocoaPods/Carthage version:  1.2
- Xcode version: 8.3.2

I managed to attach my view controller as delegate to scroll of IGCollection from other view, but now I'm struggling to get the information about scrolling direction (calculated with content offset for normal scroll views). Can anyone give me some tip how to get data about how collection content got scrolled?

**Comment by jessesquires** [comment]
Thanks @krysztalzg !

You can set the `scrollViewDelegate` on your list adapter to get these events, then everything is the same as if you were listening for events on any scroll view or collection view.

https://instagram.github.io/IGListKit/Classes/IGListAdapter.html#/c:objc(cs)IGListAdapter(py)scrollViewDelegate

**Comment by jessesquires** [comment]
Oh also, we released `3.0`. I'd definitely recommend upgrading 😄

**Comment by krysztalzg** [comment]
I don't think this responded to my question. I said I managed to get delegate working, but don't know how to read content offset values to determine scrolling direction.

**Comment by krysztalzg** [comment]
Okay, after updating I managed to get content offset value, but now I have other problem. 
My view contains three vertically align stackviews and when collection gets scrolled down I hide top and bottom stacks. With UIScrollView it works, but with ListCollection when middle stack resized (after other two disappear) it scrolls up which makes those two other stacks to appear again when they aren't supposed to.
