### ISSUE TITLE
Is it possible to set Gradient background for several cells

### ISSUE THREAD

**Issue by chapayGhub** [Instagram/IGListKit#749]
For example we have vertical feed like next:
[header 1]
[cell 1.0]
[cell 1.1]
[cell 1.2]

[header 2]
[cell 2.0]
[cell 2.1]
[cell 2.2]
..............
Is it possible to set gradient background only for cell 1.0, cell 1.1, cell 1.2?

**Comment by rnystrom** [comment]
@chapayGhub You might have to use a custom decoration view as a "background" for each section. Check out [this guide](http://strawberrycode.com/blog/how-to-create-a-section-background-in-a-uicollectionview-in-ios-swift/) for some tips.

Another trick might be to use a `CAGradientLayer` between all of your cells, and dynamically set the stops in each cell so it looks like a gradient spreads between all of the cells.

**Comment by chapayGhub** [comment]
Thank you
