### ISSUE TITLE
Convert reloadIndexPath when inside batch updates to delete+insert

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#75]
Calling `reloadSections:` and `reloadIndexPaths:` on a `UICollectionView` while executing the update block in `-[UICollectionView performBatchUpdates:completion:]` is proven to be dangerous. Instead, we should **always** delete+insert. We converted this for sections already, but its still around for index paths.
- Remove the `reloadIndexPaths` mutable container from `IGListAdapterUpdater`
- Add index paths to `deleteIndexPaths` and `insertIndexPaths` [when batch updating in progress](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L484)
- Remove `reloadIndexPaths` from [IGListBatchUpdateData](https://github.com/Instagram/IGListKit/blob/master/Source/IGListBatchUpdateData.h#L52)

**Comment by jessesquires** [comment]
@rnystrom what's the status here?

**Comment by jessesquires** [comment]
ping

**Comment by rnystrom** [comment]
Forgot this issue existed, fixed in 169c0d6c5480a885b66e9d04dc584473e538d2a4
