### ISSUE TITLE
Horizontal scroll with UICollectionViewFlowLayout

### ISSUE THREAD

**Issue by foulkesjohn** [Instagram/IGListKit#750]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s): 10
- CocoaPods/Carthage version:
- Xcode version: 8
- Devices/Simulators affected: iPad
- Reproducible in the demo project? (Yes/No):
- Related issues:

Hi, i'm having issues with asyncdisplaykit and IGListKit, although I do think it is mainly an issue with IGListKit....

When using it with a standard `UICollectionViewFlowLayout`, on iPad, with scroll direction set to horizontal. The collection view doesn't wrap items onto new lines.

The size of cell is calculated to be `width / 3`, `height / 3`, so a 3x3 grid. The line spacing, insets and minimum interim spacing is all 0 for my section controller. The section controller is returns 1 item.

When scroll direction is horizontal the cells layout one after another on 1 single line instead of putting 3 items in columns.

I'm looking to achieve: 

![image](https://cloud.githubusercontent.com/assets/984496/26250541/3b864162-3ca2-11e7-9740-4972fcfbc77e.png)

**Comment by rnystrom** [comment]
@foulkesjohn what does your setup look like? Are all of your cells part of a single section controller? Or are they all section controllers with 1 cell?

**Comment by foulkesjohn** [comment]
@rnystrom Setup is a section controller with 1 cell. I couldn't see a way of using AsyncDisplayKit with the single section controller so haven't tried that

**Comment by rnystrom** [comment]
@foulkesjohn ya I don't know how well that works yet (not super familiar w/ the ASDK integration), but I think this is actually a limitation of `UICollectionViewFlowLayout`... I'll get an issue open to work on horizontal support for `IGListCollectionViewLayout` but it's not super high priority internally. Would be an **amazing** contribution if you're interested! I'd be very happy to help you along.

**Comment by rnystrom** [comment]
Horizontal support working!
