### ISSUE TITLE
Horizontal list support in IGListCollectionViewLayout

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#752]
Inspired by #750. If you wanted to have a horizontally scrolling list that put sections on the "same line" (which would actually be a column), this wont work with IGListKit since `UICollectionViewFlowLayout` doesn't support this.

**Comment by jessesquires** [comment]
@rnystrom Isn't this "collection view inside a collection cell" ?

**Comment by rnystrom** [comment]
@jessesquires it's actually making `IGListCollectionViewLayout` work w/ horizontal scrolling (its fixed to vertical using height/y atm).

**Comment by edmonston** [comment]
So I was going to take a crack at this one, if no one is working on it... If we generalize `IGListCollectionViewLayout`, what's the desired behavior for section headers when scrolling horizontally -- always fill vertically (minus insets) and, if sticky, pin to the left (offset by `stickyHeaderOriginAdjustment`)?

**Comment by zhubofei** [comment]
@rnystrom @jessesquires @edmonston With UICollectionViewFlowLayout, supplementary views are placed on the left/right side of each section. But that's kind of lame... If you take a look at built-in emoji keyboard, each section has a sticky header on top. It looks nice but might not be easy to copy? (For example, headers have to have same height?)

**Comment by edmonston** [comment]
Yeah I agree @zhubofei that `UICollectionViewFlowLayout`'s way of handling horizontal scrolling with supplementary views is not super useful from UI perspecive (see video). But as you point out, keeping the headers horizontal would need them to be the same height (and could be strange with short/narrow sections)... I have a local branch that generalizes `IGListCollectionViewLayout` to behave more like `UICollectionViewFlowLayout` in the horizontal axis. @rnystrom was that what you had in mind with this enhancement? If so I can work it into a PR...
![horizontal](https://user-images.githubusercontent.com/885428/27566879-038b930c-5ab6-11e7-83e5-00660a2cf27f.gif)
