### ISSUE TITLE
Cache gems in Travis CI builds

### ISSUE THREAD

**Issue by heshamsalman** [Instagram/IGListKit#757]
We should cache gems in Travis CI to speed up builds & improve build reliability. May involve moving to a Gemfile and caching bundler.

**Comment by rnystrom** [comment]
I think we used to have this but removed b/c I was fighting caches while adding more stuff. Maybe, can't remember.

Either way 👍 from me if it helps Travis, lil fella needs all it can get!

**Comment by jessesquires** [comment]
for anyone looking to do this:

https://github.com/Instagram/IGListKit/blob/master/.travis.yml#L4
