### ISSUE TITLE
Grammar improvement: "long term" in README

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#760]
⚠️ Open Source Workshop ⚠️

Should be "long-term"

edit: Also occurs in the VISION guide

**Comment by heshamsalman** [comment]
@rnystrom what is oss-workshop?

**Comment by rnystrom** [comment]
@heshamsalman Facebook is putting on an intro to open source, teaching some folks how to start contributing to big projects. Special issues for the event (sorry for the notification spam).

**Comment by rnystrom** [comment]
Another "long term" that needs corrected in the VISION guide

**Comment by rnystrom** [comment]
@heshamsalman 😂 your "grammer" correction. TIL I don't word good.

**Comment by BasThomas** [comment]
Seems like a really cool idea, @rnystrom!

**Comment by danalamo** [comment]
This should be g2g 👍
