### ISSUE TITLE
Spelling: "datasource" should be IGListAdapterDataSource in Core Data guide

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#769]
⚠️ Open Source Workshop ⚠️

The line

> The main difference will be in the setup of the model in the datasource.

Should be

> The main difference will be in the setup of the model used in the `IGListAdapterDataSource`.

**Comment by manvsmachine** [comment]
I'll take this.

**Comment by rnystrom** [comment]
Thanks @manvsmachine! Still planning on this?
