### ISSUE TITLE
Remove extra whitespace in IGListCollectionContext.h

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#770]
⚠️ Open Source Workshop ⚠️

There is too much whitespace in the header, just needs to be consistent w/ other headers and have one line of whitespace (instead of 3).

https://github.com/Instagram/IGListKit/blob/master/Source/IGListCollectionContext.h#L17-L19

edit: more here:

https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterDataSource.h#L16-L18

**Comment by joseph-ortiz** [comment]
I can work on this one!

**Comment by rnystrom** [comment]
Thanks @joseph-ortiz! 🎉
