### ISSUE TITLE
[Danger] Don't warn if less than 10 loc

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#792]
Need to update the [Dangerfile](https://github.com/Instagram/IGListKit/blob/master/Dangerfile) to be less noisy for tiny changes. Will require manually scanning the PR in case it fixes a bug or something (tho a bug fix should be paired w/ a test, thus boosting the LOC count).

**Comment by BasThomas** [comment]
What warning would you like to skip in this case?

**Comment by rnystrom** [comment]
The changelog one:

https://github.com/Instagram/IGListKit/blob/master/Dangerfile#L13
