### ISSUE TITLE
[Danger] Don't warn when changing docs

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#793]
Doc/guide changes don't need a pairing changelog or "big PR" warning. Not sure how tough this would be. Maybe we can only scan changes in the `Source` dir?

https://github.com/Instagram/IGListKit/blob/master/Dangerfile

**Comment by BasThomas** [comment]
Yep, we have a `has_app_changes` over at Moya: https://github.com/Moya/Moya/blob/master/Dangerfile

**Comment by rnystrom** [comment]
Actually this should be fine, forgot we added this

https://github.com/Instagram/IGListKit/blob/master/Dangerfile#L2
