### ISSUE TITLE
Does not work with collection view self-sizing cells (.estimatedItemSize)

### ISSUE THREAD

**Issue by sunbohong** [Instagram/IGListKit#80]
- [✅ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [✅ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate
- Library version(s):1.0.0
- Xcode Version(s):8.0
- iOS version(s):10.0
- Devices/Simulators affected:Simulators
- Reproducible in the demo project? (Yes/No):Yes
- Related issues:

I was trying to remove layout logic from view to SectionController,
and i add some layoutConstraints to cell's subviews and `estimatedItemSize` to  `UICollectionViewFlowLayout`

But IGListKit does not work on auto-size.iOS will log craze.

```
    static var flowLayout = { () -> UICollectionViewFlowLayout in
        var layout = UICollectionViewFlowLayout()
            layout.estimatedItemSize = CGSize(width: 300, height: 300)
        return layout
    }()
```

**Comment by sunbohong** [comment]
You can see this when you select `Mixed Data` cell.

**Comment by jessesquires** [comment]
Thanks @sunbohong ! 😄 

It's hard to say if this is actually a ListKit bug or not. 

1. What errors do you see? What happens?
2. Can you reproduce this in the sample projects?

**Comment by rnystrom** [comment]
Sample project would be helpful. We don't use the estimated sizing methods at all, and `IGListAdapter` implements the `UICollectionViewFlowLayoutDelegate` methods for sizing. I'm not sure how all those play together.

**Comment by sunbohong** [comment]
@jessesquires  @rnystrom  

https://github.com/sunbohong/IGListKit/commit/4cf113c39ef5f1ffd75a570cf86716c8efc79db0

this commit is the sample project.

**Comment by rnystrom** [comment]
@sunbohong ok I think I figured out what is going wrong here, to use estimated sizing cells you need to implement `preferredLayoutAttributesFitting(...)` in your custom cell when not using auto layout to do the sizing. I added this line to `CollectionCell.swift` and it works:

```swift
override func preferredLayoutAttributesFitting(_ layoutAttributes: UICollectionViewLayoutAttributes) 
    -> UICollectionViewLayoutAttributes {
  return layoutAttributes
}
```

Can you give this a try? If this works for you, can you close this issue. I'll open a new issue on how to use `IGListKit` with estimated sizing cells.

**Comment by sunbohong** [comment]
@rnystrom


  if we return layoutAttributes directyly,the crazy log will disappear;but,the layout will **incorrect**.

```
    override func preferredLayoutAttributesFitting(_ layoutAttributes: UICollectionViewLayoutAttributes) -> UICollectionViewLayoutAttributes {
        return layoutAttributes;
    }

```

  if we use super's preferredLayoutAttributesFitting method,the crazy log will **not disappear**.

```
    override func preferredLayoutAttributesFitting(_ layoutAttributes: UICollectionViewLayoutAttributes) -> UICollectionViewLayoutAttributes {
        let attributes = super.preferredLayoutAttributesFitting(layoutAttributes);
        return attributes;
    }

```

**Comment by sunbohong** [comment]
@rnystrom  i add one unsafe Constraint to cell.contentView,the crazy log will disappear;but,the layout will **incorrect** when we select the `CollectionCell`.


            cell.contentView.snp.makeConstraints({ (make) in
                make.width.lessThanOrEqualTo(collectionContext!.containerSize.width)
            })

**Comment by rnystrom** [comment]
@sunbohong I think we need to find an example of a project using:

- `UICollectionViewFlowLayoutDelegate` and returning actual sizes from the delegate method
- Setting `estimatedSizes` on the layout
- Not using storyboards or nibs

I'm honestly just not all that familiar w/ the estimated cell sizing and how the `estimatedSize` property plays with the layout delegate values. As I understand it the value returned by the delegate should be the true value (fully sized).

Have you used this API before? Do you have an example of how this is supposed to work when setting up a `UICollectionView` from scratch?

**Comment by sunbohong** [comment]
@rnystrom 
 
I have upload a new demo.

https://github.com/sunbohong/Demo-Collection/commit/e2273de157e45d9d05250390b95b34cce52b3a17

**Comment by saucym** [comment]
@rnystrom

**Comment by saucym** [comment]
@rnystrom 
if we use self-sizing and call performUpdates  the Animation is not perfect.
this function is not Optional. -> public func sizeForItem(at index: Int) -> CGSize
Is there any way to perfect support self-sizing?  Especially the animation.

**Comment by rnystrom** [comment]
@saucym so to use `estimatedSize` cells we can't implement `collectionView:layout: sizeForItemAtIndexPath:`?

**Comment by jessesquires** [comment]
@rnystrom - that doesn't sound correct. Layout should still query this method to get the final, actual size... (i think) 

Or maybe is does just use `preferredLayoutAttributesFitting:...` 🤔

**Comment by zhubofei** [comment]
I found this http://stackoverflow.com/a/25896386/2977647. Hope it helps.

**Comment by zhubofei** [comment]
@sunbohong To use` estimatedSize` you need to override the `frame` size  in `preferredLayoutAttributesFittingAttributes`, like this post http://stackoverflow.com/a/25896386/2977647 did.

**Comment by zhubofei** [comment]
@jessesquires After reading https://developer.apple.com/reference/uikit/uicollectionviewflowlayout/1617709-estimateditemsize?language=objc, I think if we set `estimatedSize` to a non-zero value, the layout will only ask `preferredLayoutAttributesFittingAttributes` for item size.
