### ISSUE TITLE
Inset is not working for SupplementaryView 

### ISSUE THREAD

**Issue by Shivaprasad2452** [Instagram/IGListKit#800]
I used         self.inset = UIEdgeInsetsMake(0.0, 25.0f, 0.0f, 25.0f);
and 
- (CGSize)sizeForSupplementaryViewOfKind:(NSString *)elementKind
                                 atIndex:(NSInteger)index
{
    return CGSizeMake(self.collectionContext.containerSize.width-50, 50);

}
<img width="281" alt="screen shot 2017-05-28 at 8 55 03 pm" src="https://cloud.githubusercontent.com/assets/1208524/26529923/f7abadfe-43e7-11e7-9635-d1ac41acc8e6.png">

Thanks in advance

**Comment by rnystrom** [comment]
@Shivaprasad2452 what `UICollectionViewLayout` subclass are you using?

**Comment by Shivaprasad2452** [comment]
I am using UICollectionViewFlowLayout 

below is the code snippet
 
- (UICollectionView *)collectionView {
    if (!_collectionView) {
        UICollectionViewLayout *layout = [[UICollectionViewFlowLayout alloc] init];
        _collectionView = [[UICollectionView alloc] initWithFrame:CGRectZero collectionViewLayout:layout];
        _collectionView.backgroundColor = [UIColor whiteColor];
    }
    return _collectionView;
}

**Comment by ninokierulf** [comment]
+1

**Comment by flybrotherlixiang** [comment]
@Shivaprasad2452 @ninokierulf 

Section insets are applied to **contents only** in `UICollectionViewFlowLayout`.


See *Using the Flow Layout* of the Apple official documentation for more details.

![](https://developer.apple.com/library/content/documentation/WindowsViews/Conceptual/CollectionViewPGforIOS/Art/flow_section_insets_2x.png)

**Comment by Shivaprasad2452** [comment]
looks like its default behaviour of iOS.
 thanks  @flybrotherlixiang

**Comment by rupesh4545** [comment]
then how do I apply insets to header view?
