### ISSUE TITLE
performUpdates long perform on main thread

### ISSUE THREAD

**Issue by krysztalzg** [Instagram/IGListKit#803]
I have scroll view with multiple horizontal collections. After I finish downloading data from server I call performUpdates on specific adapter to accommodate with new data and in this moment the main thread hangs to perform lots of updates and contraint updates, which make the app becoming unresponsible for few seconds (depends on amount of data). I am looking into this for second day and have no idea where could I look to optimize it or move mostly into background thread, maybe I am doing something wrong and not realizing it?

I was testing on iPhone 4S (iOS 9.3), iPhone 5C and iPhone 6S (iOS 10.3) and the problem is largely visible on the first two. Performance of simulator and 6s makes it almost not visible there.

edit: Also when I had list of objects mocked so it loaded all collections before showing there was no time addition with more data.

## New issue checklist

- [✓ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [✓] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0
- iOS version(s): 9.3 and 10.3
- CocoaPods/Carthage version: 1.1.
- Xcode version: 8.3
- Devices/Simulators affected: Both

**Comment by shuhrat10** [comment]
Please, checkout https://instagram.github.io/IGListKit/best-practices-and-faq.html 

**I have a huge data set and -peformUpdatesAnimated: completion: is super slow. What do I do?**
If you have multiple thousands of items and you cannot batch them in, you’ll see performance issues with `-peformUpdatesAnimated: completion:`. The real bottle neck behind the scenes here is UICollectionView attempting to insert so many cells at once. Instead, call -reloadDataWithCompletion: when you first load data, which will be super fast. Behind the scenes, this method does not do any diffing and simply calls -reloadData on UICollectionView. For subsequent updates, you can then use -`peformUpdatesAnimated: completion:`.

**Comment by jessesquires** [comment]
That's right. Thanks for the answer @shuhrat10 ! 🎉

**Comment by krysztalzg** [comment]
thanks, must have missed this one entry in faq
