### ISSUE TITLE
Design the section controller

### ISSUE THREAD

**Issue by kanumuri9593** [Instagram/IGListKit#805]
Hi, I am exited to use this framework in my upcoming project but I am stuck at design phase

I want to achieve something shown in the image
design the section controller itself,
My design requires the whole cell to float with rounded edges and background color and shadow effect
If I design one single cell and add those effects its achievable but the whole point of using this framework is to modularize into components
so is there a way I can design my section controller itself rather than just the insets and then design my internal cells

![img_3271](https://user-images.githubusercontent.com/16531000/26887163-4969ffda-4b75-11e7-91be-59f853da726e.JPG)

If anyone can guide me how I ca achieve something similar with a example or source would be amazing

### General information

- `IGListKit` version:3.0
- iOS version(s):10
- CocoaPods/Carthage version:
- Xcode version:8.3
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by rnystrom** [comment]
@kanumuri9593 sorry for the delay! We've discussed having some sort of "background view" API in #142 and #749, but have been pushing people to use `UICollectionView`'s decoration view API instead. [Here is a tutorial](https://stackoverflow.com/a/39218108/940936) and some [Apple docs](https://developer.apple.com/library/content/documentation/WindowsViews/Conceptual/CollectionViewPGforIOS/CreatingCustomLayouts/CreatingCustomLayouts.html#//apple_ref/doc/uid/TP40012334-CH5-SW12). You should be able to subclass `UICollectionViewFlowLayout`, `IGListCollectionViewLayout`, or just create your own `UICollectionViewLayout` subclass from scratch!

**Comment by kanumuri9593** [comment]
Thank you for the response, currently trying out designing all my cells and supplementary views with some padding and shadow but for sure look into  UICollectionViewLayout

**Comment by varyP** [comment]
@kanumuri9593, were you able to crack this issue?
