### ISSUE TITLE
about -listAdapter:sectionControllerForObject: how can i get index of an object?

### ISSUE THREAD

**Issue by icefox57** [Instagram/IGListKit#807]
if my datasource is [Any]  ,and i have two array:[String] want to use different section Controller
how can i get the index of an object

 like this

```
var datasource:[Any] = ["test",["a","b"],123,["c","d"]]
func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
        return datasource as! [ListDiffable]
    }

func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController  {
    if index == 0 {
            return sectionController1
        } else index == 3 {
            return sectionController12
        }
}
```

### General information

- `IGListKit` version:3.0
- iOS version(s):10.3
- CocoaPods/Carthage version:
- Xcode version:8.3.2
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

**Comment by rnystrom** [comment]
@icefox57 if you need to do special handling for specific objects, we recommend storing them in an instance variable so you can just do a pointer equality check:

```swift
let datasource: [Any] = ["foo", "bar", 42]
var foo: String?

init() {
  self.foo = datasource.first
}

func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
  return datasource as! [ListDiffable]
}

func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController  {
  if object === self.foo {
    return sectionController1
  } else {
    return sectionController12
  }
}
```

Btw I'd also recommend casting your array as `[IGListDiffable]`, the compiler will be really helpful catching errors before that `!` crashes at runtime!
