### ISSUE TITLE
Protocol inheritance is not working with ListDiffable

### ISSUE THREAD

**Issue by andreaantonioni** [Instagram/IGListKit#809]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0
- iOS version(s): 10.3
- CocoaPods version: 1.2.1
- Xcode version: 8.3.2
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: 

### Debug information

Here is an example of what I'm trying to do:

```swift
protocol ExampleProtocol: ListDiffable { 
   // ...
}

class ExampleClass: ExampleProtocol {
   // ...

  func diffIdentifier() -> NSObjectProtocol {
        return uuid as NSObjectProtocol
    }
    
    func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
        guard self !== object else { return true }
        guard let object = object as? ExampleClass else { return false }
        return object.uuid == uuid
        
    }
}
```

Then here is the problem:

```swift
print(ExampleClass() is ListDiffable)

// Could not cast value of type 'Project.ExampleClass' (0x10182ad48) to 'IGListDiffable' (0x102444130).
```

**Comment by jessesquires** [comment]
Hm 🤔 

At first glance, seems to be a Swift and/or bridging bug -- not a ListKit bug.

@andreaantonioni -- what exactly are you trying to do? does this compile? what if you `as!` cast?

**Comment by andreaantonioni** [comment]
Yes, the example I wrote above compiles with this warning:

![image](https://user-images.githubusercontent.com/15701493/27258721-44191846-5402-11e7-8240-9ce24ce14863.png)

but then it crashes... Instead using `as!` as you suggested, it works:

```swift
let castedObject = ExampleClass() as! ListDiffable
print(castedObject is ListDiffable) // true
```
---

Here is an example of what I'm trying to do:

```swift

class ViewController: UIViewController {
    
    let models = [ListDiffable]()
    
    lazy var adapter: ListAdapter = {
        return ListAdapter(updater: ListAdapterUpdater(), viewController: self, workingRangeSize: 0)
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        models.appen(ExampleClass())
    }
    
}

extension ViewController: ListAdapterDataSource {
    
    public func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
        return models
    }
    
    public func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController {
        if object is ExampleClass() {
            return ExampleSectionController()
        }
        fatalError()
    }
    
    public func emptyView(for listAdapter: ListAdapter) -> UIView? {
        return nil
    }
    
}

extension ViewController: DelegateProtocol {
    
    func addObject(_ object: ExampleClass) {
        models.append(object)
        adapter.performUpdates(animated: false, completion: nil)
    }
    
}

```

And it breaks when I call `adapter.performUpdates(animated: false, completion: nil)`

**Comment by rnystrom** [comment]
@andreaantonioni is composing your class w/ both protocols, instead of just inheriting, an option? Not sure of your specific details, but composition seems like a more maintainable design to begin w/.

```swift
protocol ExampleProtocol: class { 
  // ...
}

class ExampleClass: ExampleProtocol, ListDiffable {

  func diffIdentifier() -> NSObjectProtocol {
    return uuid as NSObjectProtocol
  }

  func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
    guard self !== object else { return true }
    guard let object = object as? ExampleClass else { return false }
    return object.uuid == uuid
  }
}
```

**Comment by andreaantonioni** [comment]
Yep, It could be a solution. But I'm still asking to myself why `is` operator is not working, maybe @jessesquires is right and there's a bridging bug

**Comment by jessesquires** [comment]
Seems like this should work. I'd open an issue at bugs.swift.org
