### ISSUE TITLE
Consider adding a warning for beginners

### ISSUE THREAD

**Issue by weyert** [Instagram/IGListKit#811]
## New issue checklist

I have just started using IGListKist from the beginning and I was wondering maybe it makes sense to output a warning the debug console when you forgot to set the `dataSource`. As obviously nothing happens then. Well, the `completion`-callback returns `false`. Maybe a quick pointer to that would help? 

Feel free, to respond that I am just an idiot :)

**Comment by rnystrom** [comment]
I love this! A quick console log would be super useful when calling [perform updates](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L272) or [reload data](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L308). We even have a logging macro setup already, [like this](https://github.com/Instagram/IGListKit/blob/master/Source/IGListSectionController.m#L58-L59).

**Comment by weyert** [comment]
I will make this change :)

**Comment by weyert** [comment]
Great thank you :)
