### ISSUE TITLE
Add debug assert when diffIdentifier is used more than once in array

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#814]
From #810

Add another [debug assert](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L494-L498) to check that object diffIdentifiers only appear once in arrays as they are updated.

Warning should make it clear which object + identifier is duped. Something like:

```objc
NSCountedSet *identifierCounts = [[NSCountedSet alloc] initWithArray:[objects valueForKeyPath:@"diffIdentifier"]];
for (id<IGListDiffable> object in objects) {
  IGAssert([identifierCounts countForObject:[object diffIdentifier]] == 1, @"Diff identifier %@ for object %@ occurs more than once. Identifiers must be unique!", [object diffIdentifier], object);
}
```

**Comment by weyert** [comment]
Let me try to reproduce this problem and I will make a PR for this

**Comment by viktorgardart** [comment]
@rnystrom Will `valueForKeyPath` really work? Won't that force the users to extend `NSObject` in swift?
