### ISSUE TITLE
Investigate why Swift objects with duped identifiers can appear more than once

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#815]
Followup from #810. Duped identifier models should have just been omitted.

**Comment by yemodin** [comment]
@rnystrom Hello, looks like even NSNumbers can appear 2+ times if the data source has objects with the same diffIdentifier on initial setup. I can see assert for such duplication, but it will check it only on DEBUG and looks like better to trigger "objectsWithDuplicateIdentifiersRemoved" for initial objects, with logs of such duplicates.
