### ISSUE TITLE
sizeForItem in ListSectionController is not called after adapter.performUpdates(animated: true, completion: nil)

### ISSUE THREAD

**Issue by cikpis** [Instagram/IGListKit#816]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0.0
- iOS version(s): 10.3.1
- CocoaPods/Carthage version: Carthage 0.23
- Xcode version: 8.3.3
- Devices/Simulators affected: Device iPhone 7
- Reproducible in the demo project? (Yes/No): No demo project
- Related issues: None

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

As the title says, the `override func sizeForItem(at index: Int) -> CGSize` in ListSectionController is not called after `adapter.performUpdates(animated: true, completion: nil)`.
At the beginning I'm passing an empty array in:
```swift
func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
    return collapsibleModels
}
```

Then, after I update the models and call the update method like this:
```swift
func updateModels(collapsibleModels: [JCollapsibleModel]) {
    self.collapsibleModels = collapsibleModels
    adapter.performUpdates(animated: true, completion: nil)
}
```

The followed datasource methods are called:
```swift
func objects(for listAdapter: ListAdapter) -> [ListDiffable]
func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController
```
but inside the ListSectionController, the `override func sizeForItem(at index: Int) -> CGSize` is not called.
Instead, the follow ones are called:
```swift
override func numberOfItems() -> Int
override func cellForItem(at index: Int) -> UICollectionViewCell
override func didUpdate(to object: Any)
```
 
I also tried to use `adapter.reloadData()` but `override func sizeForItem(at index: Int) -> CGSize` is not called either.

Any clue why?

**Comment by rnystrom** [comment]
@cikpis what `UICollectionViewLayout` are you using? Can you provide an example project reproducing this issue?

That method may not be called when objects haven't changed when calling `performUpdates(...)`, but I'm confused why sizing isn't requeried when calling `reloadData()`. Would love to dig on this a bit more, but need a little more detail on your setup.

**Comment by cikpis** [comment]
@rnystrom  sorry for this issue. Was my fault. Basically I was using the `UIScrollViewDelegate` of the `UICollectionView` directly instead of using the one of `adapter.scrollViewDelegate`. For this that methos wasn't called.

**Comment by rnystrom** [comment]
@cikpis np! Thanks for posting an issue in the first place, helps document this stuff and I'm sure someone else will run into the same issue 😄
