### ISSUE TITLE
Swift 4 Examples Update

### ISSUE THREAD

**Issue by heshamsalman** [Instagram/IGListKit#819]
Hey y'all,

I've been looking at updating this for Swift 4. Looks like a _very_ straightforward update -- the one possible issue is the change in the Swift-facing API due to the addition of existentials (🎉). 

![screen_shot_2017-06-20_at_3_06_14_pm](https://user-images.githubusercontent.com/3388381/27351248-b1862e90-55ca-11e7-9c26-741be60f2aeb.png)

Wanted to double check with y'all about whether just changing the example implementation is the right move here as well as whether or not y'all wanted to wait a little bit on Swift 4 (given that there are still [changes being made](https://lists.swift.org/pipermail/swift-evolution-announce/2017-June/000386.html)).

**Comment by jessesquires** [comment]
nice 👌

**Comment by jessesquires** [comment]
i think i'd rather wait until we're out of beta to push this to master

**Comment by kimdv** [comment]
@rnystrom have pushed Swift 4 examples in commit f7220b5cfe2270fabd82bf2c45975c8e9e2253c9

**Comment by jessesquires** [comment]
Looks like we're already updated to Swift 4.
