### ISSUE TITLE
[QUESTION] What are ListSectionController for you?

### ISSUE THREAD

**Issue by cikpis** [Instagram/IGListKit#826]
Hi guys, sorry for bothering you but I have to ask a question. **What are ListSectionController for you?**

Let's start from zero. 
For me a section is, like we are used to, a block where you display cells under it. A `UITableView` or `UICollectionView` can have more sections.

In IGListKit seems that section are cells. At least in what I got from the `IGListKitExamples` project.
E.g. in `MixedDataViewController`
```swift
let data: [Any] = [
        "Maecenas faucibus mollis interdum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.",
        GridItem(color: UIColor(red: 237/255.0, green: 73/255.0, blue: 86/255.0, alpha: 1), itemCount: 6),
        User(pk: 2, name: "Ryan Olson", handle: "ryanolsonk"),
        "Praesent commodo cursus magna, vel scelerisque nisl consectetur et.",
        User(pk: 4, name: "Oliver Rickard", handle: "ocrickard"),
        GridItem(color: UIColor(red: 56/255.0, green: 151/255.0, blue: 240/255.0, alpha: 1), itemCount: 5),
        "Nullam quis risus eget urna mollis ornare vel eu leo. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.",
        User(pk: 3, name: "Jesse Squires", handle: "jesse_squires"),
        GridItem(color: UIColor(red: 112/255.0, green: 192/255.0, blue: 80/255.0, alpha: 1), itemCount: 3),
        "Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.",
        GridItem(color: UIColor(red: 163/255.0, green: 42/255.0, blue: 186/255.0, alpha: 1), itemCount: 7),
        User(pk: 1, name: "Ryan Nystrom", handle: "_ryannystrom")
]
``` 
```swift
func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController {
    switch object {
    case is String:   return ExpandableSectionController()
    case is GridItem: return GridSectionController()
    default:          return UserSectionController()
    }
}
```

Shouldn't be like:
```swift
struct MyModel {
    var title: String
    var gridItem: GridItem
    var user: User
}

class MySection: NSObject {
    var myModels: [MyModel] // those are the cells
    init(myModels: [MyModel]) {
        self.myModels = myModels
        super.init()
    }
}
```
```swift
let myModels: [MyModel] = [
        MyModel(title: "Maecenas faucibus mollis interdum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.",
                gridItem: GridItem(color: UIColor(red: 237/255.0, green: 73/255.0, blue: 86/255.0, alpha: 1), itemCount: 6),
                user: User(pk: 2, name: "Ryan Olson", handle: "ryanolsonk")),
        MyModel(title: "Praesent commodo cursus magna, vel scelerisque nisl consectetur et.",
                gridItem: GridItem(color: UIColor(red: 56/255.0, green: 151/255.0, blue: 240/255.0, alpha: 1), itemCount: 5),
                user: User(pk: 4, name: "Oliver Rickard", handle: "ocrickard")),
        MyModel(title: "Nullam quis risus eget urna mollis ornare vel eu leo. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.",
                gridItem: GridItem(color: UIColor(red: 112/255.0, green: 192/255.0, blue: 80/255.0, alpha: 1), itemCount: 3),
                user: User(pk: 3, name: "Jesse Squires", handle: "jesse_squires")),
        MyModel(title: "Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.",
                gridItem: GridItem(color: UIColor(red: 163/255.0, green: 42/255.0, blue: 186/255.0, alpha: 1), itemCount: 7,
                                   user: User(pk: 1, name: "Ryan Nystrom", handle: "_ryannystrom"))
]
mySection = MySection(myModels: myModels)
```
```swift
func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
    return [mySection]
}
func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController {
    return MySectionController()
}
```
```swift
class MySectionController: ListSectionController {

    private var mySection: MySection
    
    override func numberOfItems() -> Int {
        return mySection.myModels.count
    }

    override func sizeForItem(at index: Int) -> CGSize {
        return a_size
    }

    override func cellForItem(at index: Int) -> UICollectionViewCell {
        return the_cell
    }

    override func didUpdate(to object: Any) {
        self.mySection = object as? MySection
    }
}
```
 Is that right? I hope I'm right and the examples are wrong otherwise I'll be very confused :)

Thanks in advance for your answer, cheers!

**Comment by PhilCai1993** [comment]
In my opinion, most examples show that a sectionController provides only one cell, and the diff is diffing between sections. Unless the "bind" section controller.

```
func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
    return [sectionData0,sectionData1, sectionData2...]
}
```
```
class MySectionController
...
override func numberOfItems() -> Int {
        return datas_in_the_section
    }
```

**Comment by rnystrom** [comment]
@cikpis if your data is organized so that each `MyModel` has a title, grid item, and user, then yes you'd want to organize your data _and_ section controllers just as you have them.

The "Mixed data" demo is demonstrating how to mix different types of **unrelated** data into a single list. 

For a demonstration of using data and dynamic sections+cells, check out [this one](https://github.com/Instagram/IGListKit/blob/02f28fc994195fd5514c3ce66d0fad2d7226680f/Examples/Examples-iOS/IGListKitExamples/ViewControllers/ObjcDemoViewController.m) that has a [dynamic section controller (cells)](https://github.com/Instagram/IGListKit/blob/02f28fc994195fd5514c3ce66d0fad2d7226680f/Examples/Examples-iOS/IGListKitExamples/SectionControllers/PostSectionController.m).

But you're right, each section controller represents a whole section that can have _n_ cells in it 😉

**Comment by cikpis** [comment]
@rnystrom Great, thanks!

**Comment by cikpis** [comment]
@rnystrom but in the link example seems that the data are threatened like sections not cells :)

**Comment by rnystrom** [comment]
> in the link example seems that the data are threatened like sections not cells :)

@cikpis I'm not sure I follow. Each of [these Post models](https://github.com/Instagram/IGListKit/blob/02f28fc994195fd5514c3ce66d0fad2d7226680f/Examples/Examples-iOS/IGListKitExamples/ViewControllers/ObjcDemoViewController.m#L37-L42) will end up powering a single section in the `UICollectionView` (so 4 sections). Then judging by the number of comments in each, there will be a variable [number of cells](https://github.com/Instagram/IGListKit/blob/02f28fc994195fd5514c3ce66d0fad2d7226680f/Examples/Examples-iOS/IGListKitExamples/SectionControllers/PostSectionController.m#L32) in each section.

**Comment by cikpis** [comment]
My bad. I read the class by mobile phone and o didn't realize that. Sorry :)

Yes now everything is like should be :)

Thanks!
