### ISSUE TITLE
Sticky headers example

### ISSUE THREAD

**Issue by weyert** [Instagram/IGListKit#831]
Create an example that uses the IGList's collection view layout's support for sticky headers

**Comment by weyert** [comment]
I will update the Supplementary View example to use sticky headers

**Comment by bogren** [comment]
Not up to date in the sticky header discussion, I don't think it's been mentioned before. If the layout is set to `UICollectionViewFlowLayout `, you can set [sectionHeadersPinToVisibleBounds](https://developer.apple.com/documentation/uikit/uicollectionviewflowlayout/1617699-sectionheaderspintovisiblebounds) to the collection view it's set to support. 

Adding works fine for apps supporting iOS 9.
```
let layout = collectionView.collectionViewLayout as? UICollectionViewFlowLayout
        if #available(iOS 9.0, *) {
            layout?.sectionHeadersPinToVisibleBounds = true
        }
```

**Comment by aelam** [comment]
@bogren how about iOS 8

**Comment by bogren** [comment]
I'm currently reading up on the discussion here, and running a few tests in the examples. There is support and here is an [example](https://github.com/Instagram/IGListKit/pull/834) not using the `UICollectionViewFlowLayout` property.

**Comment by heumn** [comment]
Maybe close this as the PR to add it to the example was closed @rnystrom ? 🤔
