### ISSUE TITLE
Add an example for `workingRangeSize`

### ISSUE THREAD

**Issue by sanboxapps** [Instagram/IGListKit#84]
Currently in the read.me the `workingRangeSize` value proposed is a double (0.5), while the method actually requires an `UInt`, could you please add an example to show how it is properly used?

**Comment by ElizabethmParker** [comment]
Please help not sure whsts going on

**Comment by rnystrom** [comment]
@sanboxapps good eye, our documentation got out of sync w/ the project. 0.5 isn't a valid value so we need to clean up the readme along w/ adding a sample. On it!

**Comment by sanboxapps** [comment]
@rnystrom Thanks for the quick reply, and thanks for this fantastic library, I love it.

**Comment by ElizabethmParker** [comment]
On Oct 19, 2016 1:10 AM, "sanboxapps" <notifications@github.com> wrote:
>
> @rnystrom Thanks for the quick reply, and thanks for this fantastic
library, I love it.

**Comment by rnystrom** [comment]
Reopening since updating the docs doesn't totally satisfy this.
