### ISSUE TITLE
Remove "applyingUpdateData" property in favor of __block local scope var

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#840]
[This property](https://github.com/Instagram/IGListKit/blob/master/Source/Internal/IGListAdapterUpdaterInternal.h#L44) doesn't actually need to be a property. We can use a `__block` local variable to store the data and then use in other blocks. All usages are within the `performBatchUpdatesWithCollectionView:` method.

**Comment by bogren** [comment]
Requesting an update of the issue. ✌️

**Comment by rnystrom** [comment]
Closing this as I discovered it's used for debugging
