### ISSUE TITLE
Remove sectionController from superview

### ISSUE THREAD

**Issue by kowalskiy** [Instagram/IGListKit#844]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 2.1.0
- iOS version(s):10.0
- CocoaPods/Carthage version:
- Xcode version:8.2.1
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

I am having issues with deleting custom sectionController. I am showing simple banner view with title and dismiss button, which should be removed from superView after tapping on it's button. I am thinking I should do it using dateSource, so it's properly removed. Any suggestions here? Here is my code.

    import Foundation
    import IGListKit

       @available(iOS 9.0, *)
       class BannerSectionController: IGListSectionController, IGListSectionType {
       var sectionToken: SectionToken?
    
    func numberOfItems() -> Int {
        return 1
    }

    func sizeForItem(at index: Int) -> CGSize {
        return CGSize(width: collectionContext!.containerSize.width, height: 40)
    }
    
    func cellForItem(at index: Int) -> UICollectionViewCell {
        let cell =  collectionContext!.dequeueReusableCell(of: BannerViewCell.self, for: self, at: index) as! BannerViewCell
        cell.backgroundColor = .red
        //cell.button.addTarget(self, action: #selector(dismissView(_:)), for: .touchUpInside)
        return cell
    }
    
    func didUpdate(to object: Any) {
        sectionToken = object as! SectionToken
    }
    
    func didSelectItem(at index: Int) {
         }
    }

      @available(iOS 9.0, *)
        protocol Banner {
        var titleLabel: String { get }
         var style: BannerViewStyle { get }
   

      @available(iOS 9.0, *)
      protocol BannerViewStyle {
      var backgroundColor: UIColor { get }
  

    @available(iOS 9.0, *)
     class BannerViewCell : UICollectionViewCell {
    
    lazy var button: UIButton = {
        let button = UIButton()
        button.translatesAutoresizingMaskIntoConstraints = false
        button.setImage(UIImage(named: "Dismiss"), for: UIControlState.normal)
       // button.addTarget(self, action: #selector(dismissView(_:)), for: .touchUpInside)
        button.backgroundColor = .clear
        return button
    }()
    
    lazy var titleLabel: UILabel = {
        let titleLabel = UILabel()
        titleLabel.translatesAutoresizingMaskIntoConstraints = false
        titleLabel.textAlignment = .center
        titleLabel.text = NSLocalizedString("First Banner", comment: "")
        titleLabel.font = UIFont.systemFont(ofSize: 13.0, weight: UIFontWeightMedium)
        titleLabel.backgroundColor = .clear
        titleLabel.textColor = .white

        return titleLabel
    }()
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        
        // add views
        contentView.addSubview(titleLabel)
        contentView.addSubview(button)
        
        let views: [String : Any] = ["titleLabel" : titleLabel, "button" : button]
        //
        let constraints = [
            // view vertical constraints
            NSLayoutConstraint.constraints(withVisualFormat: "V:|-0-[titleLabel]-0-|",
                                           metrics: nil,
                                           views: views
            ),
            // view horizontal constraints
            NSLayoutConstraint.constraints(withVisualFormat: "H:|-0-[titleLabel]-0-|",
                                           metrics: nil,
                                           views: views
            ),
            NSLayoutConstraint.constraints(withVisualFormat: "V:|-0-[button(44)]-0-|",
                                           metrics: nil,
                                           views:views
            ),
            NSLayoutConstraint.constraints(withVisualFormat: "H:[button(44)]-0-|",
                                           metrics: nil,
                                           views:views
            )
        ]
        //
        contentView.addConstraints(constraints.flatMap { $0 })
     }
       //    func dismissView(_ button: UIButton) {
      //        contentView.removeFromSuperview()
  
    
    required public init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

**Comment by weyert** [comment]
I would introduce a delegate for the section controller which you then call in the `didSelectItem`-method of the section controller e.g:

```
func didSelectItem(at index: Int) {
   delegate?.bannerTapped(sectionController: self)
}
```

Then you can introduce implement this delegate in your view controller and then remove the item from your data source and then call performUpdates so IGListKit changes it's content

**Comment by kowalskiy** [comment]
@weyert Thanks for quick response. I guess I didn't explained this situation clearly. I want do dismiss, remove this banner (subView) after clicking on button which is placed in right corner of this view.

**Comment by weyert** [comment]
then you would need to make a delegate for a banner view with the button and pass it through via the section controller

**Comment by rnystrom** [comment]
@kowalskiy take a look one of our examples demonstrating empty views and an architecture to remove data dynamically.

- [Section controller](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/RemoveSectionController.swift)
- [Relevant view controller code](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/ViewControllers/EmptyViewController.swift#L79-L86)

**Comment by kowalskiy** [comment]
Thanks for input @rnystrom. I might go from here.
