### ISSUE TITLE
Test does not pass on iPhone 5 simulator iOS 8

### ISSUE THREAD

**Issue by PhilCai1993** [Instagram/IGListKit#845]
![image](https://user-images.githubusercontent.com/6828315/27895507-d2644bf6-6245-11e7-8604-67c3f1ae0d5c.png)

**Comment by rnystrom** [comment]
Ah, that's b/c `supplementaryViewForElementKind:atIndexPath:` is an iOS 9+ API. Hmm. I'll try and get a hack up to support this, but definitely not a big deal.

**Comment by rnystrom** [comment]
Actually, just going to close this. Travis and our internal CI aren't running on iOS 8, and I'm considering dropping support for it (would love all to add all of these supplementary view APIs into IGListKit...).
