### ISSUE TITLE
Common UICollectionView config in category

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#846]
After we removed `IGListCollectionView`, we started recommending people disable prefetching and setting a white background color for every view. Should we provide a `UICollectionView+IGListKit` category that does:

- Background to white
- Disables prefetching

That way you just do something like:

```objc
[UICollectionView ig_ConfigForIGListKit];
```

Instead of using the `UIAppearance`, checking if responds to prefetching, etc. Thoughts?

**Comment by BasThomas** [comment]
I think this makes a ton of sense: more transparant and more accessible, plus IGListKit has control over what happens there.

**Comment by jessesquires** [comment]
👍
