### ISSUE TITLE
Update visible Cell with updated data can not work

### ISSUE THREAD

**Issue by jindulys** [Instagram/IGListKit#848]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0
- iOS version(s): 10.3.1
- CocoaPods/Carthage version:
- Xcode version: 8.3
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

I am using IGListKit in my blog reader client which is used to show a list of companies and their latest blog's title.  However, I met an issue where I had my data model updated, but the visible cell itself could not be updated to reflect the changes.

For example, I have the first company with **Yelp** and its first blog title is **ABC is coming**, after refresh, I get a new title **New protocol practice within yelp**. I have my data source of `ListAdapter` updated and call `performUpdates(animated: completion:)` on it, however, if that "Yelp" cell is on screen, I can not get an update.

The setup of my controller is like following:

```swift
/// The view controller for engineering blogs list.
class EbloCompanyViewController: UIViewController {

  let collectionView: UICollectionView = {
    let layout = UICollectionViewFlowLayout()
    let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
    return collectionView
  }()

  var adapter: ListAdapter?

  var companyList: [EbloCompany]?

  var companySectionController: CompanySectionController?
  
  /// The data store of eblo company.
  let ebloCompanyDataStore = EbloCompanyRealmService()
  
  /// refresh control.
  var refreshControl: UIRefreshControl!

  override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()
    collectionView.frame = view.bounds
    collectionView.backgroundColor = .white
  }
  
  override func viewDidLoad() {
    super.viewDidLoad()
    self.title = "Eng Blogs"
    self.view.backgroundColor = UIColor.white
    self.navigationController?.navigationBar.isTranslucent = false
    self.view.addSubview(self.collectionView)
    let refresher = UIRefreshControl()
    refresher.tintColor = UIColor.gray
    refresher.addTarget(self, action: #selector(loadData), for: .valueChanged)
    self.refreshControl = refresher
    self.collectionView.addSubview(refresher)

    // Setup List adapter. 
    let updater = ListAdapterUpdater()
    self.adapter = ListAdapter(updater: updater, viewController: self, workingRangeSize: 0)
    adapter?.collectionView = self.collectionView
    adapter?.dataSource = self
    self.companyList = ebloCompanyDataStore.allCompany()
    self.adapter?.performUpdates(animated: true)
    :
    :
  }
  
  func loadData() {
    self.ebloCompanyDataStore.fetchNewCompanies { [weak self] companies in
      GCDQueue.main.async {
        // Update data source
        self?.companyList = companies
        self?.adapter?.performUpdates(animated: true, completion: { _ in
          self?.refreshControl.endRefreshing()
        })
      }
    }
  }
}
  
extension EbloCompanyViewController: ListAdapterDataSource {
  func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
    guard let companyList = self.companyList else {
      return []
    }
    return companyList
  }

  func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController {
    let companySectionController = CompanySectionController()
    self.companySectionController = companySectionController
    companySectionController.delegate = self
    return companySectionController
  }

  func emptyView(for listAdapter: ListAdapter) -> UIView? {
    return nil
  }
}
```

Below is my data model, I had already token properties which could result an UI difference into account. See my `isEqual(toDiffableObject:)` method

```swift
import Foundation
import IGListKit
import RealmSwift

/// Class represents a company.
public final class EbloCompany: Object {
  
  /// Blog's company name.
  dynamic var companyName: String = ""
  
  /// url string for this company.
  dynamic var urlString: String = ""
  
  /// The companyid
  dynamic var companyID: Int = 0
  
  /// This field is used for positioning this company object.
  dynamic var positionIndex: Int = 0
  
  /// The first blog title.
  dynamic var firstBlogTitle: String = ""
  
  /// Whether or not this company has update.
  dynamic var hasUpdated: Bool = false
  
  override public static func primaryKey() -> String? {
    return "companyID"
  }
  
  /// The ui identifier.
  public var uiIdentifier: String {
    return companyName + firstBlogTitle
  }
}

extension EbloCompany: Unique {
  public func identifier() -> String {
    return self.companyName
  }
}

extension EbloCompany: ListDiffable {
  
  public func diffIdentifier() -> NSObjectProtocol {
    return self.uiIdentifier as NSString
  }
  
  public func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
    guard let other = object as? EbloCompany else {
      return false
    }
    return (self.uiIdentifier == other.uiIdentifier) && (self.hasUpdated == other.hasUpdated)
  }
}
```

From debug, I found that when `EbloCompany`'s isEqual method get called, self has already updated to the latest object, which is same as `object` passed in, which makes `isEqual(toDiffableObject)` return `true`. See debug image below.

![screen shot 2017-07-09 at 11 13 27 pm](https://user-images.githubusercontent.com/1540225/28001738-f6fec3d8-64fc-11e7-83bd-2535401873a2.png)
![screen shot 2017-07-09 at 11 13 44 pm](https://user-images.githubusercontent.com/1540225/28001740-01423afa-64fd-11e7-95ee-598c40ed4de5.png)
![screen shot 2017-07-09 at 11 13 58 pm](https://user-images.githubusercontent.com/1540225/28001742-09370dda-64fd-11e7-94c8-f73a76a38273.png)

Pay attention to the `firstBlogTitle` and `hasUpdated` field change.

I open sourced my repo: You can also check my repo at: https://github.com/jindulys/Eblo

**Comment by heumn** [comment]
I might ahve misunderstand what you are doing here, but it looks like to you are mutating the original object and updating the ```hasUpdated``` directly in the model. When comparing the two objects you are comparing it against itself meaning that in the ```public func isEqual(toDiffableObject object: ListDiffable?) -> Bool {```

you will first check on identifier, they will be equal since you are comparing object A with object A and they will also have equal ```hasUpdated``` value ```true```

Meaning IGListKit will think this object has no changes, because the check returns ```true```

Possible fixes: 
- Make your objects immutable and rather rebuild them when they change. 
- change the check to:


```return (self.uiIdentifier == other.uiIdentifier) && !self.hasUpdated```

please not that this would only make sense if 
- your objects are mutable
- you keep track of changes in the model itself (```hasUpdated```)

**Comment by jindulys** [comment]
@heumn Thank you for replying my issue. I did not mutate my object directly I believe. For IGListKit, I have no control over how to directly update my `ListSectionController`'s data, what I can do is update `ListAdapter`'s dataSource's data.

Each time there is a new set of data come, I refresh the data source by calling `self.companyList = companies` where `companies` contains new set of objects, at this time properties of my data model like `firstBlogTitle` and `hasUpdated` have a different value than before.

I think 

1.  I have updated my adapter's data source
2. I have called `self.adapter.perforUpdates(animated: true, compilation: someCompletion)`

I should have my visible cell updated to use new companies, however, it did not work. My visible cell remains old data.

**Comment by heumn** [comment]
It would be difficult for me to evaluate what is happening here since I do not know what is the backing ```Object```, but based on the model object having variables that are mutable, it would indicate to me that these are reference types and that they are being modified when updated. Not re-created (that I highly recommend you consider).

Did you try to change the return method to this?

```return (self.uiIdentifier == other.uiIdentifier) && !self.hasUpdated```

**Comment by jindulys** [comment]
For my project, if you check my code `EbloCompanyViewController`, which is the view controller that uses `IGListKit`. The data source for my view controller's `ListAdapter` is that controller's `companyList`, which is an array of `EbloCompany`.  When I get new data set back, I change it by calling `self.companyList = companies`, in swift, array assignment is a copy operation. 

My model's hasUpdated is only a field, you can treat is as a `string` if you want. The semantic meaning of `return (self.uiIdentifier == other.uiIdentifier) && !self.hasUpdated` is not correct in my case. When compare two objects' equivalence, I care about the difference between `self` and `other`, there should be no dependencies on `self`'s properties.

I believe you thought my data source is only one `EbloCompany` object, but it is not, the data source is an array of `EbloCompany`

You can check my repo: https://github.com/jindulys/Eblo, if I confused you. Thank you again for replying.

**Comment by heumn** [comment]
Yeah sorry. I was and think I still am confused.

> My question is why `EbloCompany` object directly updates itself to new data?

If this is the question, meaning, that "why does a Realm object update itself under the hood?", I think that question is related to how Realm work. Not how IGListKit.

Because if the scenario is that you get `isEqual(toDiffableObject` called, with the objected called, already having the same updated properties that the received object has, I presume that is by design on Reals end. I am no Realm expepert, but I presume that is how it is designed work.

I noticed that there are some mentions of workarounds that makes sense and use built in properties of Realm (diffable)

https://github.com/Instagram/IGListKit/issues/624

**Comment by jindulys** [comment]
Probably you are right, I am using realm. It might be a realm thing, I will have another look.

**Comment by heumn** [comment]
I think it is safe to close this one @rnystrom. It is pretty clearl that @jindulys was banging his head against the same type of problems you _could_ potentially hit with CoreData if you are not careful :)

Maybe I should open a PR to warn future realmers? 🤔

**Comment by heumn** [comment]
Did you figure it out @jindulys?

**Comment by jindulys** [comment]
I had debugged and found indeed it was a realm related thing. Unfortunately, I had to use UICollectionView to work with realm.

**Comment by rnystrom** [comment]
Bummer. Ya I'd love to offer better interop w/ Realm, but their mutation architecture makes this _really_ tricky. `IGListKit` heavily favors an immutable model design. The best advice is to create "view models" derived from Realm models, but it adds extra overhead.

Not to mention I have basically 0 experience w/ Realm 😞

**Comment by naeemshaikh90** [comment]
I am also facing such issue with [ObjectMapper](https://github.com/Hearst-DD/ObjectMapper).
