### ISSUE TITLE
dequeueReusableSupplementaryViewOfKind kill the performance of app 

### ISSUE THREAD

**Issue by Shivaprasad2452** [Instagram/IGListKit#849]
Hi Just used the header and footer view after that scrolling become very hard, when i do performance testing with time profile I saw some 900x to 1000x time taken by the above methods 

Both header and footer are very simple footer have one button inside and header as just a label.

<img width="970" alt="screen shot 2017-07-10 at 4 14 23 pm" src="https://user-images.githubusercontent.com/1208524/28016445-fcd58a72-6591-11e7-9b19-936e40ff6250.png">
<img width="976" alt="screen shot 2017-07-10 at 4 15 20 pm" src="https://user-images.githubusercontent.com/1208524/28016446-fcd8322c-6591-11e7-84b2-2bfebe99be93.png">

 

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by heumn** [comment]
Would be valueable to know a bit more about your setup. Is this something you can modify the example project to show the same behaviour? We use headers and footers in our app and are not seing this performance hit.

**Comment by rnystrom** [comment]
Ya this is a little hard to debug w/out more details. A profiler trace or a sample project reproducing the issue would be super helpful.

**Comment by Shivaprasad2452** [comment]
HI @rnystrom  and @heumn 
This really strange issue I am facing when I try to write sample app for same I am not able to reproduce the issue its working fine.
 But when i run in my project the issue is coming always, when I removed the header and footer its working even either one is also bringing performance to track.
 _Are you using UICollectionViewFlowLayout?_
Yes its UICollectionViewFlowLayout 

I will try to add profiler trace

**Comment by Shivaprasad2452** [comment]
Profile templente 
https://drive.google.com/file/d/0B8daXS_CB88fNVo2S2hFUGdOVDQ/view?usp=sharing

**Comment by Shivaprasad2452** [comment]
any update guys?

**Comment by rnystrom** [comment]
I've got this in my queue, but debugging other implementations takes a much lower priority over our work here at Instagram. Will get to this when I can run through my backlog!

Also our IT security flagged this file, I'm not even sure I'll be able to open it :(

**Comment by heumn** [comment]
@Shivaprasad2452 do you think you could provide an example project and I will try help you?

**Comment by rnystrom** [comment]
Gonna close due to inactivity
