### ISSUE TITLE
Use of undeclared type IGListCollectionView

### ISSUE THREAD

**Issue by raviatri** [Instagram/IGListKit#851]
#850 # New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

Hey i am using Xcode 8.3.2 and using swift 3
i installed the pod "pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'"
and import IGListKit successfully.
But when i am going to define a IGListCollectionView it gives me this error"Use of undeclared type IGListCollectionView"

```
let collectionView: IGListCollectionView = {
        // 2
        let view = IGListCollectionView(frame: CGRect.zero, collectionViewLayout: UICollectionViewFlowLayout())
        // 3
        view.backgroundColor = UIColor.black
        return view
    }()
```

Is i missing something? please help me out of this.

**Comment by rnystrom** [comment]
@raviatri are you using IGListKit 3.0? If so, `IGListCollectionView` was removed. Context in #409 and https://github.com/Instagram/IGListKit/commit/2284ce389708f62d99f48ff2ec15644f1ec59537

**Comment by raviatri** [comment]
Actually i am't confirm its 3.O, i installed using
 `pod "pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'"`

which import latest one right?

**Comment by rnystrom** [comment]
@raviatri yup using that will put you on the tip of latest IGListKit development which is past 3.0.0. So in your branch `IGListCollectionView` doesn't exist anymore, you can just use `UICollectionView` instead.

**Comment by raviatri** [comment]
Thanks @rnystrom for the help. I got your point.
