### ISSUE TITLE
Can IGListKit be used with AsyncDisplayKit?

### ISSUE THREAD

**Issue by modLX4** [Instagram/IGListKit#86]
Can IGListKit be used with AsyncDisplayKit
https://github.com/facebook/AsyncDisplayKit

**Comment by rnystrom** [comment]
@modLX4 great question, and absolutely yes it can! In fact, I'm planning on adding an example using [ComponentKit](http://componentkit.org/), [AsyncDisplayKit](http://asyncdisplaykit.org/), `UIKit`, and even `WKWebView` **all within the same list**. IMO that's the power of what we're using.

Now to use this with `AsyncDisplayKit` there are a few caveats:

- You cannot use [`ASCollectionView`](http://asyncdisplaykit.org/appledoc/Classes/ASCollectionView.html)
  - Instead, you will create a standard `IGListCollectionView` + `IGListAdapter` and your own section controllers
- Use `UICollectionView` subclasses that use their own [`ASDisplayNode`](http://asyncdisplaykit.org/appledoc/Classes/ASDisplayNode.html)s internally
- The only tricky part is responding to async sizing
  - Within your section controller you could call `self.collectionContext?.reloadSectionController(self)` to reload everything when the sizing is finished
  - You can also make sizing synchronous but do async display

There's no best-practice for this yet until we try it though.

**Comment by jessesquires** [comment]
🎉 

Let's track that work at #94 👍
