### ISSUE TITLE
Any way to check when a cell in section display on screen?

### ISSUE THREAD

**Issue by quangpc** [Instagram/IGListKit#862]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0
- iOS version(s): 10.x
- CocoaPods/Carthage version: Cocoapods 1.2.1
- Xcode version: 8.3
- Devices/Simulators affected: iOS 10.3 simulator - iphone 7
- Reproducible in the demo project? (Yes/No): 
- Related issues:

Hi, is there any way to know when a cell in section appear like previous delegate function of UICollectionView does:

```
- (void)collectionView:(UICollectionView *)collectionView willDisplayCell:(UICollectionViewCell *)cell forItemAtIndexPath:(NSIndexPath *)indexPath
```

I just want perform some animation when cell appear to screen.

**Comment by heumn** [comment]
You can still add yourself as a delegate :)

Just see this part in the documentation on `IGListAdapter`: 

https://instagram.github.io/IGListKit/Classes/IGListAdapter.html#/c:objc(cs)IGListAdapter(py)collectionViewDelegate

**Comment by quangpc** [comment]
@heumn thank you, but I see the code:

```
IGAssert(![collectionViewDelegate conformsToProtocol:@protocol(UICollectionViewDelegateFlowLayout)],
             @"UICollectionViewDelegateFlowLayout conformance is automatically handled by IGListAdapter.");
```

In case, I use UICollectionViewFlowLayout, how can I do that.

**Comment by elrafael16** [comment]
Hi quangPC

I never quite make this work. Sorry I am still new with swift and IGListKit.
Which controller do i have to delagate UICollectionViewDelegare, in the section controller?

Can you share the code on how did you implemented this?

I cant seem to figure this out.

**Comment by heumn** [comment]
I do not really understand what is stopping you. Have you set yourself as the delegate and implemented the method? @elrafael16
