### ISSUE TITLE
Cell Dynamic height using autolayout 

### ISSUE THREAD

**Issue by iOSUser110** [Instagram/IGListKit#864]
I am using IGListKit , 
I have created cell with autolayout constraints storyboard.
I want it to be resize according to the views height inside it dynamic time. 
Cell contains three labels with dynamic height

but autolayout not working , not able to create dynamic height cell
please provide a solution for this.
Waiting for your reply

**Comment by heumn** [comment]
Not to be rude, but did you try to use the  [search function](https://github.com/Instagram/IGListKit/search?utf8=%E2%9C%93&q=Dynamic+&type=Issues) so see if this has been asked before?

There are tons of discussions about this. I propose you research one of these:

https://github.com/Instagram/IGListKit/issues/516 <--- golden

**Comment by rnystrom** [comment]
Closing since estimated heights seem to have issues, we're tracking already, and they are pretty low priority for the core team at Instagram (we don't use it at all).
