### ISSUE TITLE
Can iglistKit achieve waterfall flow?

### ISSUE THREAD

**Issue by broccolii** [Instagram/IGListKit#877]
Can iglistKit achieve waterfall flow?

**Comment by rnystrom** [comment]
@broccolii can you explain more what you mean or give an example?

**Comment by broccolii** [comment]
@ryanolsonk 
like this https://github.com/chiahsien/CHTCollectionViewWaterfallLayout

**Comment by jessesquires** [comment]
@broccolii 

layouts are decoupled from IGListKit. you can use any custom layout that you want.

**Comment by broccolii** [comment]
But I need to modify the data structure of the data source,because I use the Array, a section will only have an item.I need to use a two-dimensional Array. Is that so?

**Comment by michaeldong** [comment]
I search all about waterfall issue, but i can't find a solution to solve my question. can you give me a tips or example , ths .
![image](https://user-images.githubusercontent.com/1925773/34458604-e69e053a-ee13-11e7-918e-b02fda8ba0cf.png)

**Comment by rnystrom** [comment]
@michaeldong I'd recommend doing some searching around for open source `UICollectionViewLayout`s or how to build one from scratch. There are definitely ways to build a layout that looks like that. App-specific layouts are beyond IGListKit's scope though.
