### ISSUE TITLE
Swift._ContiguousArrayStorage "CustomModel"  to '__ObjC.IGListDiffable' 

### ISSUE THREAD

**Issue by iOSUser110** [Instagram/IGListKit#879]
Getting issues like this
Swift._ContiguousArrayStorage "CustomModel"  to '__ObjC.IGListDiffable' 

When  doing like as below : 

 func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController {

        
        switch object {
        case is [CustomModelArray]:
            return HorizontalSectionController()
        case is CustomModel:
            return ListSectionController()
        default:
            return ListSectionController()
        }        

    }

So to resolve unnecessarily need to put  [CustomModelArray] this in some other object 
as 
class CustomModelObj  {
     let var customModelArray:[CustomModelArray] ?
}

can we pass as it is instead creating another object around it

**Comment by rnystrom** [comment]
@iosuser110 using an array as the model is extremely dangerous in both ObjC and Swift. It's behavior for diffing is undefined. You'll need to use a custom wrapper to be safe and define how you want updates to be done.
