### ISSUE TITLE
Request: Make reloadData synchronous

### ISSUE THREAD

**Issue by dhavalcue** [Instagram/IGListKit#885]
Looks like [this line](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L383) makes `reloadData` an async operation. From my reading, it looks like there's no way to make a synchronous `reloadData` call. 

It's also not clear why we're doing a `dispatch_async` there, since we are already asserting main thread within the function.

Questions:
- Is there a way to make a sync `reloadData` call.
- Do we need to do a `dispatch_async` there?

**Comment by jessesquires** [comment]
hey @dhavalcue 😄 

the reason for this is that there *could be* batch updates in-progress. (or other calls to `reloadData` from elsewhere). this design serves 2 main goals: (1) coalesce all updates, (2) make update calls reentrant 

cc @rnystrom in case i've got this wrong

**Comment by jessesquires** [comment]
as far as synchronously calling `reloadData`, you *should* be able to simply call this on the `collectionView` (although this is discouraged for the reasons above because of how IGListKit tracks state)

cc @rnystrom again 😄

**Comment by dhavalcue** [comment]
@jessesquires: Thank you! The context helps!

I did not understand your workaround. Do we call `reloadData` from the view controller directly? How do we update `IGListKit`'s state?

**Comment by rnystrom** [comment]
@jessesquires is spot on. This is a performance optimization. We collect multiple calls for batch updates and reload within run loop turns (really just `dispatch_async`).

You def could just call `[UICollectionView reloadData]` but if your data sources have changed, nothing will actually happen. Calling `[IGListAdapter performUpdatesAnimated:completion:]` (with `animated:NO`) should suffice. Just use the completion block if there's something you need to do afterwards.

Curious, is there a reason you want it to be sync?

**Comment by dhavalcue** [comment]
Thanks @rnystrom!

We want to hold view controller transition until the content is ready so that the transition looks smooth (instead of a subtle flash that will happen when reload completes). 

The workaround I have at this time is to initialize the view controller, `listAdapter.reload`, wait on completion and then present the view controller. The workaround works great, the code is a little messy, however I can live with that.

Thanks for your quick responses @rnystrom, @jessesquires! 😄

**Comment by jessesquires** [comment]
Doesn't `-[IGListAdapter reloadDataWithCompletion:]` happen immediately? 

https://instagram.github.io/IGListKit/Classes/IGListAdapter.html#/c:objc(cs)IGListAdapter(im)reloadDataWithCompletion:

**Comment by dhavalcue** [comment]
Not if I use `IGListAdapterUpdater`. Because of [this](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.m#L383).

**Comment by weyert** [comment]
Can't you add a DispatchGroup semaphore to make this call synchronous in this case?
