### ISSUE TITLE
Relax SwiftLint Rules

### ISSUE THREAD

**Issue by heshamsalman** [Instagram/IGListKit#894]
Followup from #891

Some of the SwiftLint rules are causing us to write code in ways that we otherwise wouldn't. Let's have a discussion about which rules are causing that and put them up on the chopping block.

My initial guess would be treating bangs as warnings, and perhaps line spacing / trailing commas? 

@rnystrom @jessesquires @Sherlouk

**Comment by rnystrom** [comment]
💯 lets do it

**Comment by weyert** [comment]
I think this got merged and can be closed?
