### ISSUE TITLE
IGListCollectionViewLayout lacks support for UICollectionElementKindSectionFooter

### ISSUE THREAD

**Issue by tapi** [Instagram/IGListKit#898]
`IGListCollectionViewLayout` does not have support for `UICollectionElementKindSectionFooter`
Initially I thought this might be a bug, I assumed that since the layout was using the same symbol (`UICollectionElementKindSectionHeader`) from `UIcollectionViewFlowLayout` that the other supplementary kind would be supported.

After producing a small reproducible case [reproducible case](https://github.com/Instagram/IGListKit/files/1226063/IGListKitFooter-Issue.zip) it looks as though this may have been a deliberate choice. Is there a rational for leaving it out? Is this an enhancement we might see in the future? Would you accept contributions for this feature?

## New issue checklist

- [X ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0.0
- iOS version(s): 10.0
- CocoaPods/Carthage version: 1.2.1
- Xcode version: 9.3.3
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

### Debug information

```bash
IGListAdapter 0x60800015dd20:
  Updater type: IGListAdapterUpdater
  Data source: <IGListKitFooter_Issue.ViewController: 0x7fddc6f04da0>
  Collection view delegate: (null)
  Scroll view delegate: (null)
  Is in update block: No
  View controller: <IGListKitFooter_Issue.ViewController: 0x7fddc6f04da0>
  Is prefetching enabled: Yes
  Registered cell classes:
  {(
    UICollectionViewCell
)}
  Registered supplementary view identifiers:
  {(
    "UICollectionElementKindSectionHeaderIGListKitFooter_Issue.TestHeaderFooter"
)}
  IGListAdapterUpdater instance 0x6000000cbde0:
    Moves as deletes+inserts: No
    Allows background reloading: Yes
    Has queued reload data: No
    Queued update is animated: Yes
    State: Idle
  Section map details:
    Object and section controller at section: 0:
      <IGListKitFooter_Issue.DiffableObject: 0x610000003460>
      <IGListKitFooter_Issue.TestSectionController: 0x6100000fa080>
  Collection view details:
    Class: UICollectionView, instance: 0x7fddc8013000
    Data source: <IGListAdapter: 0x60800015dd20>
    Delegate: <IGListAdapter: 0x60800015dd20>
    Layout: <IGListCollectionViewLayout: 0x7fddc6f06250>
    Frame: {{0, 0}, {375, 667}}, bounds: {{0, 0}, {375, 667}}
    Number of sections: 1
      1 items in section 0
    Visible cell details:
      Visible cell at section 0, item 0:
      <UICollectionViewCell: 0x7fddcaa05040; frame = (0 60; 320 20); layer = <CALayer: 0x60000002f9c0>>
```

**Comment by rnystrom** [comment]
@tapi you're absolutely correct, we didn't support footers intentionally mostly b/c we wanted to get this layout out-the-door quickly, and we don't use footers at Instagram. 

I'm very open to community help in adding support! It's doubtful we will prioritize this anytime soon internally since there isn't a need for it (yet).

**Comment by vasilenkoigor** [comment]
@rnystrom Hi! There're progress for this enhancement? In my project I use IGListCollectionViewLayout and need footers :D

I can do it and make PR, if you are doesn't have a time for that feature

**Comment by rnystrom** [comment]
@vasilenkoigor we’d very much accept a PR with footer support! It’s not on my roadmap at the moment.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vasilenkoigor** [comment]
@rnystrom Thanks for response! Well, I'll try to do it today or before the end of this week.

**Comment by vasilenkoigor** [comment]
@tapi welcome to test enhancement 🕺
