### ISSUE TITLE
StackedListSectionViewController Acting Weirdly

### ISSUE THREAD

**Issue by yusuftor** [Instagram/IGListKit#902]
I have a `StackedListSectionViewController` that has two section controllers in. The second section controller has 5 cells two of which I've added to act as a header and footer. All cells have different sizes. For some reason there seems to be a bug with sizeForCell that sets the cell at index 1 to the exact same height as the cell at index 0. I've been checking through my code for hours trying to get around this and I'm assuming it must be an issue with IGListKit. Weirdly, when I press the Debug View Hierarchy button, it renders the view with the correct height. Any idea what might be happening here?

Another issue is that the section controller inside the stacked list cannot see the cells that are in the storyboard. I have to add them to Nibs and then dequeue them.

**Comment by rnystrom** [comment]
@yusuftor a little hard to tell w/out any sample code or projects. Can you provide more detail here?

- Model code
- Section controller setup
- What `UICollectionViewLayout` are you using?

**Comment by yusuftor** [comment]
Sorry, I was having a bit of a nightmare with it and couldn't be bothered to fill out the info! 
I've actually have to move the extra cell I'd added as a header to the previous section controller as a workaround to this bug.

Ok so I can't provide a sample project but I can give you some more detail. 
The page I'm trying to create is essentially a profile page with a section at the top that contains things like your username/profile pic. Below that there is a section that has its first cell dedicated as a header explaining the section. Then 3 cells full of content, and the last cell used as a footer with some text in.

The `UICollectionViewLayout` is the default vertical scrolling `UICollectionViewFlowLayout`.

The section controller setup is as follows (I've changed it since so I'm typing some parts from memory):

```
import UIKit
import IGListKit

final class ProfileSectionController : ListSectionController {
    var profileModel: ProfileJSONModel?
    
    override func sizeForItem(at index: Int) -> CGSize {
        guard let profile = profileModel,
            let recentContent = profile.recentContent
            else { return .zero }
        
        let width = collectionContext!.containerSize.width
      
        if index == 0 {
            // Header
            return CGSize(width: width, height: 40)
        }  else if index == recentContent.count {
            // Footer
            return CGSize(width: width, height: 86)
        } else {
           // I'm initialising a different section controller and returning the height here.
            let sectionController = getSectionController(at: index)
            var height: CGFloat!
            if recentContent[index].type == .text {
                height = (sectionController as! TextSectionController).heightForItem(withWidth: width)
            } else {
                height = (sectionController as! MediaSectionController).heightForItem(withWidth: width)
            }
            
            return CGSize(width: width, height: height)
        }
    }
    
    override func numberOfItems() -> Int {
        guard let profile = profileModel,
              let recentContent= profile.recentContent
        else { return 0 }
        
        // Add header and footer to this
        return recentContent.count + 2
    }
    
    override func didUpdate(to object: Any) {
        profileModel = object as? ProfileJSONModel
    }
    
    override func cellForItem(at index: Int) -> UICollectionViewCell {
        guard let profile = profileModel,
            let recentContent = profile.recentContent
            else { return UICollectionViewCell() }
        
        if index == 0 {
             // Header
             let cell = collectionContext!.dequeueReusableCell(withNibName: "ProfileSectionHeader", bundle: nil, for: self, at: index) as! ProfileSectionHeader
             // Fill out cell here...
             return cell
        } else if index == recentContent.count {
            // Footer
            let cell = collectionContext!.dequeueReusableCell(withNibName: "ProfileSectionFooter", bundle: nil, for: self, at: index) as! ProfileSectionFooter
            // Fill out cell here...
            return cell
        }
        
        if recentContent[index].type == .text {
            let cell = collectionContext!.dequeueReusableCell(withNibName: "TextCell", bundle: nil, for: self, at: index)  as! TextCell
            let sectionController = getSectionController(at: index) as! TextSectionController
            return sectionController.populate(cell: cell)
        } else {
            var cell = collectionContext!.dequeueReusableCell(withNibName: "MediaCell", bundle: nil, for: self, at: index) as! MediaCell
            let sectionController = getSectionController(at: index) as! MediaSectionController
            cell = sectionController.populate(cell: cell)
            return cell
        }
    }
}
```

Whenever I tried to use the following:
`
collectionContext!.dequeueReusableCellFromStoryboard(withIdentifier: "XXX", for: self, at: index) as! XXX
`
it kept crashing saying that there was no cell with the identifier (even though there was).

The header and footer models are simple with a couple of `IBOutlets`. The other cells full of content are quite complex.

**Comment by heumn** [comment]
Could you try to alter the example project to replicate your setup? It would be so much easier to try to help with some actual code to look at... 😅

**Comment by jessesquires** [comment]
Closing old issues that seem to be resolved or are inactive. 😄 

If this isn't resolved and you still need/want help, please re-open! 😊
