### ISSUE TITLE
obj-c sample code

### ISSUE THREAD

**Issue by lechium** [Instagram/IGListKit#904]
is there any objc sample code? its mind boggling that the library is (rightfully so) written in objective-c but all the sample code i can find is in swift. which to me i wont touch with a 1000 foot pole. i hope that im wrong, dont want to have to read fully read the source or translate examples to learn how to use it.

**Comment by rnystrom** [comment]
Good question! There is one example in ObjC (posts). We're trying to be future friendly with our docs and help adoption. We don't use **any** special Swift features, everything translates 1:1 to ObjC. If you have any questions about it let us know!

**Comment by lechium** [comment]
hmm i might not be looking hard enough, i didnt see any objc at all in any of the sample code on this repo..

**Comment by rnystrom** [comment]
@lechium https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/ViewControllers/ObjcDemoViewController.m

**Comment by lechium** [comment]
thanks! for some reason i never got a notification about your response!
