### ISSUE TITLE
Performance impacts when returning an array for the diffIdentifier

### ISSUE THREAD

**Issue by MathieuWhite** [Instagram/IGListKit#905]
Hey, 

I am wondering what is recommended as a return value for the `diffIdentifier` when conforming your model to `IGListDiffable?`

I noticed this issue in our project at work, but I can also reproduce it in the demo project with a couple modifications. If I return 1000 objects to the list adapter and modify the `diffIdentifier`of the model to return an array, the loading time for displaying the cells takes a very large hit. 

Let me explain the use case for this. 
The reason is that our list contains a filter which can combine or sort based on the item type. So it's possible to display objects that have the same id in the same collection. So the `diffIdentifier` returns an array like the following `return @[self.id, self.type]`.

Looking at examples in the project, I never see being done. So I'm not sure if it's not recommended or was never expected. If not recommended, can you recommend a better way to handle this?

If I only return `self.id` as the `diffIdentifier`, my 1000 items load instantly. 
Another thing to note is that these different item types are all subclasses of a base object. Should they all conform to `IGListDiffable` or just the base object?

Thanks!

## New issue checklist

- [YES] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [YES] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0.0
- iOS version(s): iOS 10.3.1
- CocoaPods/Carthage version: Latest
- Xcode version: Xcode 8.3.1
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

**Comment by jessesquires** [comment]
A better way to approach this would be a new type that holds `id` and `type` and implements `Equatable`.

Something like:

```swift
class MyDiffIdentifier {
     let id: String
     let type: String
}

extension MyDiffIdentifier: Equatable {
     static func == (left: MyDiffIdentifier, right: MyDiffIdentifier) -> Bool {
          return left.id == right.id && left.type == right.type
    }
}
```

Then return one of these as your `diffIdentifier`.

**Comment by rnystrom** [comment]
Another simple suggestion is to craft a function that transforms your `id` and `type` into a single string. You want your identifier to be simple, cheap, and immutable. Arrays are really inefficient for comparisons.

**Comment by MathieuWhite** [comment]
Thanks guys, I appreciate the quick replies! 

Based on both of your suggestions, I take it using an array as the identifier isn’t great. 

Since we are using Objective-C, going for something like a transform to create a string using the two properties seems like the better option. I’ve implemented it and now my cells are loading much faster. 

Thanks again!
