### ISSUE TITLE
Supplementary header view is wrongly positioned

### ISSUE THREAD

**Issue by weyert** [Instagram/IGListKit#906]
## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: `master`
- iOS version(s): 10.3.1
- CocoaPods/Carthage version: 1.2.1
- Xcode version: 8.3.3
- Devices/Simulators affected: iPhone 7
- Reproducible in the demo project? (Yes/No): No
- Related issues: N/A

### Debug information

I have bunch of section controllers each currently representing one type data which are being rendered on the screen. A few of the cells are using self-sizing cells by using the `preferredLayoutAttributesFitting`-method. Only I am experiencing issues when I start using header supplementary views for one of the section controllers. For some reason the header view is positioned at the wrong position. Looks like it's a the position before the cells have been resizing themselves. 

Has anyone seen this behaviour before? If I remove `estimatedItemSize`-property from the flow layout the issue doesn't occur but the cells are wrongly sized (obviously). Are the complications which has been discussed in earlier tickets or I am just doing it wrong?

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```
Yet to find out how to trigger this from my Swift project.

**Comment by rnystrom** [comment]
Another one for #516

> Yet to find out how to trigger this from my Swift project.

- Pause the app in Xcode
- Type `po [IGListDebugger dump]` into lldb/console

I'm going to close this as its not actually an issue w/ IGListKit, if you find a solution feel free to post since it'll help others who are struggling w/ estimated/self-sized cells!
