### ISSUE TITLE
Only SectionControllers of NSNumber and NSString can be reusable 

### ISSUE THREAD

**Issue by aelam** [Instagram/IGListKit#912]
## New issue checklist

Please see the `TestObject`, all the SectionControllers of my `TestObject` are not reusable. I tested in `NestedAdapterViewController `. 

New SectionControllers will be created in `func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any)  -> ListSectionController`. In addition I've implemented the `ListDiffable` for `TestObject` and keep the strings of Data same with the origin data after refreshed
If they are not reusable I can't keep some states in SectionControllers! 

I tried to trace the problem. I've found the `sectionMap` in `IGListAdapter`, the key is the object that I set from data. when `adapter.performUpdate`, adapter tries to reuse from sectionMap with THE object key, but the key is different from the ORIGIN object, so it can't be reused ?

Do I set up something wrong? 

```

class TestObject: NSObject, ListDiffable {
    var name: String
    
    init(_ name: String) {
        self.name = name
        super.init()
    }
    
    func diffIdentifier() -> NSObjectProtocol {
        return self
    }
    
    func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
        if let object = object as? TestObject {
            return object.name == self.name
        }
        
        return false
    }
}
```

Please see the sample code
In the origin code, the 
```
import UIKit
import IGListKit

class TestObject: NSObject, ListDiffable {
    var name: String
    
    init(_ name: String) {
        self.name = name
        super.init()
    }
    
    func diffIdentifier() -> NSObjectProtocol {
        return self
    }
    
    func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
        if let object = object as? TestObject {
            return object.name == self.name
        }
        
        return false
    }
    
}

final class NestedAdapterViewController: UIViewController, ListAdapterDataSource {

    lazy var adapter: ListAdapter = {
        return ListAdapter(updater: ListAdapterUpdater(), viewController: self)
    }()
    let collectionView = UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewFlowLayout())

    var data: [Any] = [
        TestObject("Ridiculus Elit Tellus Purus Aenean"),
        TestObject("Condimentum Sollicitudin Adipiscing"),
        14,
        TestObject("Ligula Ipsum Tristique Parturient Euismod"),
        TestObject("Purus Dapibus Vulputate"),
        6,
        TestObject("Tellus Nibh Ipsum Inceptos"),
        2,
        TestObject("Tellus Nibh Ipsum Inceptos"),
        TestObject("Tellus Nibh Ipsum Inceptos"),
        3,
        6,
        6,
        6,
        6,
        6,
        6
    ]

    override func viewDidLoad() {
        super.viewDidLoad()
        view.addSubview(collectionView)
        adapter.collectionView = collectionView
        adapter.dataSource = self
        
        let item = UIBarButtonItem.init(title: "Refresh", style: .plain, target: self, action: #selector(refresh))
        self.navigationItem.rightBarButtonItem = item
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        collectionView.frame = view.bounds
    }

    
    func refresh() {
        data = [
            15,
            16,
            TestObject("Ridiculus Elit Tellus Purus Aenean"),
            TestObject("Condimentum Sollicitudin Adipiscing"),
            TestObject("Ligula Ipsum Tristique Parturient Euismod"),
            TestObject("Purus Dapibus Vulputate"),
            6,
            TestObject("Tellus Nibh Ipsum Inceptos"),
            2,
            TestObject("Tellus Nibh Ipsum Inceptos"),
            TestObject("Tellus Nibh Ipsum Inceptos"),
            3,
            6,
            6,
            6,
            6,
            6,
            6
        ]
        
        adapter.performUpdates(animated: false, completion: nil)
    }
    
    // MARK: ListAdapterDataSource

    func objects(for listAdapter: ListAdapter) -> [ListDiffable] {
        return data as! [ListDiffable]
    }

    func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController {
        if object is Int {
            return HorizontalSectionController()
        } else {
            return LabelSectionController()
        }
    }

    func emptyView(for listAdapter: ListAdapter) -> UIView? {
        return nil
    }

}


```

- [TRUE ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [TRUE] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:  3.0.0
- iOS version(s):   
- CocoaPods/Carthage version: 
- Xcode version: 8.3.2
- Devices/Simulators affected: iOS 10
- Reproducible in the demo project? (Yes/No): Yes     Need modification 
- Related issues: SectionController reuse 

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]  can't log
```

**Comment by rnystrom** [comment]
You should **always** create new section controllers in that method. The infra is smart enough to know when to reuse controllers between updates. Unless you call reload, which rebuilds everything.

For other models, just use a non mutating value for the `diffIdentifier` (could even be a number or string) and your controllers will be reused.

**Comment by aelam** [comment]
@rnystrom   Do you mean if I want to record some states in SectionController, I need set diffIdentifier as a number or string?

**Comment by aelam** [comment]
@rnystrom  I called `adapter.performUpdate`, it always create new section controllers.

**Comment by rnystrom** [comment]
@aelam ya, you should be using a `diffIdentifier` that **uniquely identifies** that data, so that when updates are performed the diffing algo can check to see if anything has changed. Check out these guides for more in-depth info on creating models:

- [Diffing and equality](https://github.com/Instagram/IGListKit/blob/master/Guides/IGListDiffable%20and%20Equality.md)
- [Modeling](https://github.com/Instagram/IGListKit/blob/master/Guides/Modeling%20and%20Binding.md)
