### ISSUE TITLE
Adding gesture recogniser to backgroundView

### ISSUE THREAD

**Issue by weyert** [Instagram/IGListKit#913]
## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.0.0
- iOS version(s): 10.3
- CocoaPods/Carthage version: 1.3.1
- Xcode version: 8.3.3
- Devices/Simulators affected: iPad
- Reproducible in the demo project? (Yes/No): WIP
- Related issues: None

### Debug information

If you add a gesture recogniser to a UIView or anything else it appears that IGListKit doesn't revert to the background view when doing something performUpdates, [], performUpdates for some reason in between the background view get's nil (emptyView?) but sometimes it doesn't.

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by heumn** [comment]
> it appears that IGListKit doesn't revert to the background view when doing something performUpdates

I do not understand this sentence...

Have you tried adding a gesture recognizer to an example project to reproduce this? Could you share such a project?

**Comment by rnystrom** [comment]
Ya not sure I follow what is wrong here. Are you talking about the `backgroundView` API on `UICollectionView`? If so, that gets consumed by our `emptyView` API on the `IGListAdapterDataSource`. If you use the empty view, you can add gestures to that.

**Comment by weyert** [comment]
Whoops, sorry, I wasn't aware I already posted repo 😅

Yes, a search is happening in a search bar and I would like to be able to dismiss the keyboard by tapping on the UICollectionView so I added the tap gesture recogniser to the `backgroundView`. 

E.g. I created my own UIView assigned to my `UICollectionView` and then when I change the data source through ListAdapter my backgroundView appears to get lost.  Currently fixed it by doing the following in `performUpdates` completion handler.

```
if self.collectionView.backgroundView != self.contentBackgroundView {
    self.collectionView.backgroundView = self.contentBackgroundView
}
```

I would try to make the issue appear in the example app.

**Comment by rnystrom** [comment]
Oh ya, the background view is going to be overwritten/replaced and hidden/displayed based on whether or not there is content. Can you just add the tap gesture to the collection view itself?

**Comment by weyert** [comment]
Actually, I can't reproduce it anymore when I tried to make an example app. Earlier I had to the feeling that my backgroundView I assigned to my CV got nullified or a. new one got created but looks like it doesn't seem to be case. Or maybe the behaviour differ in other versions of iOS 🤔
