### ISSUE TITLE
Q: Using `IGListCollectionViewLayout` to fix default styling of headers

### ISSUE THREAD

**Issue by bogren** [Instagram/IGListKit#914]
Considered a lighter version of `IGListCollectionViewLayout`'s init methods with default values of like `stickyHeader: NO` etc? Would be nice to use the layout for the `SupplementaryViewController` example, since it looks a bit off with the scroll indicator behind the section headers.

**Comment by rnystrom** [comment]
@bogren can you describe the issue a little more? What prevents you from initializing the layout w/ your own values?

> since it looks a bit off with the scroll indicator behind the section headers

Is this an issue w/ `UICollectionViewFlowLayout`?

**Comment by bogren** [comment]
I can, works as expected. It's just that it's a bit verbose. 🙂

Yes so the indicator is given a `zPosition` of 1, blocking the scroll indicator. 
![simulator screen shot - iphone 5s - 2017-08-26 at 23 33 57](https://user-images.githubusercontent.com/2457281/29745300-439666bc-8ab7-11e7-98d6-875445a93972.png)
