### ISSUE TITLE
Remove all empty methods in examples

### ISSUE THREAD

**Issue by rnystrom** [Instagram/IGListKit#917]
e.g. [override func didSelectItem(at index: Int) {}](https://github.com/Instagram/IGListKit/blob/02f28fc994195fd5514c3ce66d0fad2d7226680f/Examples/Examples-tvOS/IGListKitExamples/SectionControllers/LabelSectionController.swift#L42)

This is all leftover from when we had the class+protocol requirement instead of just subclassing.

**Comment by agisilaos** [comment]
I want to work on that @rnystrom. Can I added as an assignee? Expect a PR from me this afternoon 💯

**Comment by weyert** [comment]
I think we already have a PR by Kim for this

**Comment by rnystrom** [comment]
Yup fixed in #945
