### ISSUE TITLE
crash at self.selectionDelegate didDeselectItemAtIndex:

### ISSUE THREAD

**Issue by mahomealex** [Instagram/IGListKit#918]
## New issue checklist
    new to check delgate method exist first, because it's optional.
- [ ] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [ ] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

**Comment by rnystrom** [comment]
@mahomealex can you provide more detail? At the very least we need a stack trace.

**Comment by jessesquires** [comment]
@rnystrom do we check `respondsToSelector:` for this method?

**Comment by rnystrom** [comment]
@jessesquires actually for the binding SC we don't:

https://github.com/Instagram/IGListKit/blob/6540f960e2e69bd4776e1e1d8c460ff812ba4c07/Source/IGListBindingSectionController.m#L127

For `IGListSectionController` it doesn't matter since it's in the base class.

Should we fix and push 3.1.1 for this? Kind of bad.

**Comment by jessesquires** [comment]
ooof. @rnystrom yeah let's push 3.1.1

**Comment by rnystrom** [comment]
Aight I'll PR the fix then follow up with cutting new version

**Comment by mahomealex** [comment]
@rnystrom Just subclass a SectionController and set ListBindingSectionControllerSelectionDelegate.
Since It's optional, means does't need to implement, so base class have to check first.
Btw, will IGList provide a waterFall extension with different ratio and column count? I have write one in swift, it's necessary and not that easy.
