### ISSUE TITLE
PR462 closed but not effective

### ISSUE THREAD

**Issue by Deub27** [Instagram/IGListKit#924]
Hi

To my understanding, the PR462 is merged and included in 3.0.0 version.
But code does not appear to be included at all.

Am i wrong somewhere ?

**Comment by rnystrom** [comment]
Yup we had to back out the changes as they had bugs. We haven't attempted to restore the PR as we've worked around what it was originally trying to do.

**Comment by Deub27** [comment]
OK, i understand.
My problem is the i have a top menu animated with collectionview offset.
When no data in my datasource, empty view is displayed but there is no more scroll because it is embedded in collectionview backgroundview

**Comment by rnystrom** [comment]
@Deub27 you'll probably want to create an actual section controller and cell to display when in an empty state. Then it will scroll with the view. Something like this:

https://github.com/rnystrom/GitHawk/blob/master/Classes/Notifications/NoNewNotificationsSectionController.swift

**Comment by Deub27** [comment]
Thanks, i will implement that
