### ISSUE TITLE
pre-loading  Scroll is little  jumping

### ISSUE THREAD

**Issue by nazmulkp** [Instagram/IGListKit#926]
I have a news feed app that is app when user scrolling  infinity scroll view like Instagram . every time  api request get 20 post. it is working fine but problem is   Scroll is little  jumping . do I miss anything 
 
```
  func scrollViewWillEndDragging(_ scrollView: UIScrollView,
                                   withVelocity velocity: CGPoint,
                                   targetContentOffset: UnsafeMutablePointer<CGPoint>) {
        
        let distance = scrollView.contentSize.height - (targetContentOffset.pointee.y + scrollView.bounds.height)

        print(distance)
        if !loading && distance < 300 {
            loading = true
            adapter.performUpdates(animated: true, completion: nil)
            DispatchQueue.global(qos: .default).async {
                self.oldestState(createdBefore: self.states.last?.createdAt, completion: { (isDOne) in
                DispatchQueue.main.async {
                    self.loading = false
                    self.adapter.performUpdates(animated: true, completion: nil)
                   }
                })
            }
        }
    }

  
  func oldestState(createdBefore createdAt: Date?, completion :  CheckResult? ){
        self.loadNewsFeeds(createdAfter: nil, createdBefore: createdAt, completion: {(statesResponse) in
            if let sortedStates = statesResponse {
                self.states += sortedStates
                completion?(true)
                return
            }
        } )
    }
```

**Comment by rnystrom** [comment]
@nazmulkp try setting `self.loading = false` in the completion block of `performUpdates(...)`. Calling that method could be triggering the scrolling delegate again.

Some other options:

- Does it still jump when `animated: false`?
- Set a BP on `-[UIScrollView setContentOffset:]` and see who all is changing the offset when jumping.
- Can you create an example app reproducing this? There are a _ton_ of things that could be causing jumpy scrolling/loading, its extremely difficult for us to debug w/out the whole setup.
- Try doing `(lldb) po [IGListDebugger dump]` and post the results.
- Could you fill in the info about what version of IGListKit you're using? What iOS version this happens on, etc.

**Comment by jessesquires** [comment]
Closing old issues that seem to be resolved or are inactive. 😄 

If this isn't resolved and you still need/want help, please re-open! 😊
