### ISSUE TITLE
Performance difference between Debug and Release build

### ISSUE THREAD

**Issue by DMCApps** [Instagram/IGListKit#935]
## New issue checklist

- [X] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [X] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: 3.1.1
- iOS version(s): 10.3
- CocoaPods/Carthage version:
- Xcode version: 8.3.2
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```

Hello I am having a major performance difference between creating Debug builds and creating Release builds. While in debug `performUpdates(animated:completion:)` runs in the milliseconds. Once I change my scheme settings to build release, my performance of the above method goes to seconds and scrolling becomes near impossible. Is there any known reason for this? I checked the debug statements of my code and nothing that I have should impede on the perform of the scrolling nor `performUpdates`.

One thing I noticed between the Debug build and the Release build is that the [`- (void)collectionView:(UICollectionView *)collectionView willDisplayCell:(UICollectionViewCell *)cell forItemAtIndexPath:(NSIndexPath *)indexPath`](https://github.com/Instagram/IGListKit/blob/master/Source/Internal/IGListAdapter%2BUICollectionView.m#L85) is called an extremely large amount of times in Release vs Debug (Debug calls it only when needed while Release calls it to the point that my console can't even keep up with it). I am calling `performUpdates` maybe once or twice, but every scroll or load on the page causes that method to fire a lot.

**Comment by DMCApps** [comment]
Figured out the issue, I was using a helper method that counted the number of items in an enum. This method performed differently in Release than it did in Debug causing it to result in a much higher number for the `ListSectionController.numberOfItems()` call.

**Comment by rnystrom** [comment]
@DMCApps thanks for following up! I'm really curious what about the release build made it slow? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DMCApps** [comment]
@rnystrom I didn't investigate the extension mentioned above too thoroughly, but the extension that I list above would return 256 for an enum with 3 items in it in Release, but in Debug would return 3. 

e.g.
```
enum SectionContent {
    case row1
    case row2
    case row3
}

// In ListSectionController
...
func numberOfItems() -> {
    return SectionContent.elementsCount // returned 3 in Debug, returned 256 in Release. 
}
...
```

This basically cause the collection view to create and attempt to display 256 cells in one section which  I had a default size of `CGSize(width: width, height: 0)` and a default cell of one of my custom cell types returned and had 3-4 section on the screen so it basically attempted to render over 1000 cells at any given time which brought the UI to an abrupt stutter.

**Comment by rnystrom** [comment]
Ah! Good to know.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
