### ISSUE TITLE
UIEdgeInsets for EmbeddedSectionController 

### ISSUE THREAD

**Issue by Valerun666** [Instagram/IGListKit#936]
Does anyone faced with such issue:

got EmbeddedSectionController with insets  UIEdgeInsets(top:0, left: 20, bottom: 63, right: 0), but I need to have the same distance between each cell and the edges of section. In current case I have something like:

| 20 [cell] 20 [cell] 20 [Cell] 0 | 

where:
-  20 is a distance between  cells and section edges. 
- "|" -  section edges

Expecting to have:

| 20 [cell] 20 [cell] 20 [Cell] 20 | 

Does anybody know how to make a dynamic UIEdgeInsets for each cell, or at least how to fix this situation? Appreciate any help with this.

**Comment by rnystrom** [comment]
@Valerun666 I need a little more detail about your setup. You want to uniformly space cells within a _single_ section or _multiple_ sections?

Either way, try exploring a combination of [-[IGListSectionController insets]](https://github.com/Instagram/IGListKit/blob/master/Source/IGListSectionController.h#L133) and [-[IGListSectionController minimumInterItemSpacing]](https://github.com/Instagram/IGListKit/blob/master/Source/IGListSectionController.h#L147).

You can have a `left: 20` _section_ inset as well as `minimumInterItemSpacing: 20`.

If none of that works, another hack I've seen is to check [isLastSection](https://github.com/Instagram/IGListKit/blob/master/Source/IGListSectionController.h#L126) and then append a 20 point blank cell (or just add 20 points to the last cell).

**Comment by Valerun666** [comment]
Thx for advice. Worked trick with empty cell. But anyway this is not really good way out.

Long story short, [IGListSectionController minimumInterItemSpacing] doesn't work EmbeddedSectionController cause as I correctly understand it doesn't know about existence of other Section Controllers. So when I check isLastSection, it says no. Cause it is the only one.  Don't know if it possible somehow to fix it, but maybe HorizontalSectionController may know if EmbeddedSectionController is the last one?

**Comment by rnystrom** [comment]
@Valerun666 any chance you could take the embedded example project we have and recreate your setup? Then I can mess around w/ it a little. Still a little hard for me to conceptualize what is and isn't working here.

Also might want to try using `IGListCollectionViewLayout` as its item-spacing logic is a little better than `UICollectionViewFlowLayout`.

**Comment by Valerun666** [comment]
Thx. Will try. Will prepare an example for you during this weekend.

**Comment by jessesquires** [comment]
Closing old issues that seem to be resolved or are inactive. 😄 

If this isn't resolved and you still need/want help, please re-open! 😊
