### ISSUE TITLE
Add examples for ASDK, ComponentKit, etc.

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#94]
Follow up task from #86.

Add examples using:
- [ ] ComponentKit
- [ ] AsyncDisplayKit
- [ ] UIKit
- [ ] WKWebView

> ⚠️ If submitting a PR, please submit 1 PR per type of example

**Comment by rnystrom** [comment]
@jessesquires are you gonna work on this? I have 24 hours of travel tomorrow and can get started.

**Comment by jessesquires** [comment]
lol. didn't mean to self-assign

**Comment by saraswatayu** [comment]
In #86, @rnystrom mentions using ComponentKit, AsyncDisplayKit, UIKit, and WKWebView within the same list. Is that still the goal or should four different lists be created, each using one of the aforementioned frameworks?

**Comment by ocrickard** [comment]
Here's my stab at simple ComponentKit integration: https://github.com/ocrickard/IGListKit-ComponentKit/blob/master/IGListKit-ComponentKit/CKComponentSectionController.mm

This has an item controller that can render an arbitrary number of sub-elements using ComponentKit. Uses async processing of components by default, but could easily be changed to support synchronous/asynchronous modes.

**Comment by jessesquires** [comment]
@ocrickard / @rnystrom 

We could add a CocoaPods subspec with a dependency on ComponentKit and add these IGLK+ComponentKit components (assuming they're reusable)

**Comment by rnystrom** [comment]
Would be super cool to explore

**Comment by stevejcox** [comment]
Has anyone taken a look at the AsyncDisplayKit example? Looking to try and improve feed performance and interested in anyones experience.

**Comment by Sherlouk** [comment]
@stevejcox To my knowledge @Adlai-Holler was looking into this?

Mentioned it here: https://github.com/Instagram/IGListKit/pull/375

**Comment by Adlai-Holler** [comment]
@stevejcox Hi, yep we've got it up and running, with an example. We're looking for comments, so please give it a try if you want! https://github.com/facebook/AsyncDisplayKit/pull/2848

**Comment by stevejcox** [comment]
Fantastic @Adlai-Holler ! I'll give it a whirl.

**Comment by Sherlouk** [comment]
@jessesquires @rnystrom 

Are we still wanting to bring examples into this repo? As linked there are examples for two of the listed tasks:
- AsyncDisplayKit Example: https://github.com/facebook/AsyncDisplayKit/tree/master/examples/ASDKgram
- ComponentKit Example: https://github.com/ocrickard/IGListKit-ComponentKit

If so, do we want them as a different project file entirely, or add it all to the `Examples-iOS` project?

> We could add a CocoaPods subspec with a dependency on ComponentKit

Do we want to do this (`IGListKit/ComponentKit`)? Same for ASDK (`IGListKit/AsyncDisplayKit`)?

**Comment by MarvinNazari** [comment]
@Sherlouk: there is another ASDK example here, pretty similar to the IGListKit search example https://github.com/facebook/AsyncDisplayKit/tree/master/examples_extra/RepoSearcher

**Comment by Sherlouk** [comment]
@MarvinNazari Thanks for linking that one. hadn't seen it! Much easier to move over (already in Swift)

**Comment by rnystrom** [comment]
B/c there are existing and examples, and we want to limit the scope of things we support within the repo directly, I'm going to close this out. Those examples are great, and I'm happy to promote and link to more as they come up. Just don't want to get our examples overly complicated for now.
