### ISSUE TITLE
Multiple rows with horizontal scroll

### ISSUE THREAD

**Issue by ChristianLysne** [Instagram/IGListKit#951]
I was't able to find an answer to this, but apologies if this has been answered before or I have misunderstood the documentation. 

After experimenting with the example projects, I tried to make the `Nested Adapter` support having 2 rows in the horizontally scrollable section, instead of 1. 

With a default `UICollectionView` with horizontal scroll and `cellHeight < (collectionViewHeight - insets) / numberOfRows)` I would expect a the cells to grow like the second section in this image:

![simulator screen shot - iphone 8 plus - 2017-09-26 at 11 56 14](https://user-images.githubusercontent.com/12391750/30855338-e42d3f14-a2b4-11e7-806f-aa7ab7fc255a.png)

But when decreasing the cellSize in the ExampleProject, they stay locked in at 1 row:

![test](https://user-images.githubusercontent.com/12391750/30855250-9f594158-a2b4-11e7-9372-a2b0900553e8.png)

This might be the behaviour you want, and if this is intended than how can I make it break into multiple rows? 

Keep up the good work 👍 🎉

**Comment by heumn** [comment]
If I understood you correctly you need to use / create a collection view layout that supports this :) The one in the example will not

**Comment by ChristianLysne** [comment]
Thanks @heumn 😄 Was hoping to not use a custom flow layout when the default works without `IGListKit`, but this works as a backup solution 👍

**Comment by rnystrom** [comment]
@ChristianLysne we just added horizontal support to `IGListCollectionViewLayout`, but tbh I don't recall the stacking-fit behavior. It _might_ work like this (cc @edmonston for details).

**Comment by edmonston** [comment]
Hi @ChristianLysne, as far as I can tell, the screenshot you show of the Nested Adapter uses `UICollectionViewFlowLayout` for its `EmbeddedCollectionViewCell`s, so you wouldn't get the benefit of the horizontal support that we just added to `IGListCollectionViewLayout` that @rnystrom mentions.

But `IGListCollectionViewLayout` should do want you want with little or no customization -- I have an example in [my fork of IGListKit](https://github.com/edmonston/IGListKit) if you want to clone and checkout the `try-new-demo` branch. Run the example app and go to Nested Horizontal Flow. It looks like the screenshot below, and I believe it stacks in the way you intend (stacks vertically until it runs out of room and needs to start a new row).

[This class](https://github.com/edmonston/IGListKit/blob/try-new-demo/Examples/Examples-iOS/IGListKitExamples/Views/EmbeddedFlowCollectionViewCell.swift) is where the horizontally-scrolling layout is used.

(I had thought about adding my example to the Demo, but didn't know how much interest there'd be...)

Hope this helps!

<img width="376" alt="horizontal-scrolling" src="https://user-images.githubusercontent.com/885428/30892133-e5a5fc64-a304-11e7-94bd-548f1fe60f38.png">

**Comment by ChristianLysne** [comment]
Thanks! Worked great and is exactly what I wanted ❤️

**Comment by tobitech** [comment]
@ChristianLysne Please how did you solve this I want to do something that looks like this: 
![img_9e5c9691aa8f-1](https://user-images.githubusercontent.com/8595853/39004211-b1d6d444-43f4-11e8-9cf5-e8ac0ece0a00.jpeg)
The items are stacked till they fill up the height of the cell and then wrap to the next cell
