### ISSUE TITLE
Background Color

### ISSUE THREAD

**Issue by tyyou77** [Instagram/IGListKit#953]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s):
- CocoaPods/Carthage version:
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Debug information

```bash
# Please include debug logs using the following lldb command:
po [IGListDebugger dump]
```
I'm currently using the IGListKit, but I am having a bit of trouble with colors. I currently have a table view and on top of that table view I have a tab bar with a clear background that is set to translucent. The problem is that the tab bar background appears to be a bit grey on views that utilize the IGListKit. My thought is that the background of the IGListKit is black and the scroll view doesn't extend until the very bottom of the tab bar, hence causing the tab bar to appear grey. Does anyone know how to change this or fix this?

**Comment by rnystrom** [comment]
The default background for `UICollectionView` is black. Have you tried setting it to white?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tyyou77** [comment]
Yes I have but it still has that greyish color.

**Comment by rnystrom** [comment]
@tyyou77 so you have an example that reproduces the issue? A little hard to debug this at the moment. It doesn’t sound like an IGListKit issue though 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tyyou77** [comment]
@rnystrom hmm.. it's a bit strange because we have two views that utilize the tab bar except on the view that doesn't use IGListKit, the tab bar (with the translucent option on) remains clear/white. However, on the view that utilizes IGListKit(ListAdapater), the tab bar is grey even though we set the background of the collection view white.

**Comment by weyert** [comment]
Really strange indeed, if you could reproduce the problem in a example project and post the repo here then we can have a look at it :)

**Comment by rnystrom** [comment]
To be clear, IGListKit isn’t doing anything with view controllers or how a collection view gets laid out. It sounds to me like some layout or insetting issue. But again really hard for me to debug without seeing it in action.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
Closing old issues that seem to be resolved or are inactive. 😄 

If this isn't resolved and you still need/want help, please re-open! 😊
