### ISSUE TITLE
Scroll to Bottom When Keyboard Toggled Causes Crash

### ISSUE THREAD

**Issue by Smiller193** [Instagram/IGListKit#960]
Well, I have successfully implemented IGLisrKit. Only thing is that I had this function where it scrolls to the bottom of the content when the keyboard is toggled.

Here is my code for that method:

     @objc func handleKeyboardNotification(notification: NSNotification){
            if let userinfo = notification.userInfo{
                
                let keyboardFrame = (userinfo[UIKeyboardFrameEndUserInfoKey] as! NSValue).cgRectValue
                self.bottomConstraint?.constant = -(keyboardFrame.height)
                
                let isKeyboardShowing = notification.name == NSNotification.Name.UIKeyboardWillShow
                self.bottomConstraint?.constant = isKeyboardShowing ? -(keyboardFrame.height) : 0
                
                UIView.animate(withDuration: 0, delay: 0, options: UIViewAnimationOptions.curveEaseOut, animations: {
                    self.view.layoutIfNeeded()
                }, completion: { (completion) in
                    if self.comments.count > 0  && isKeyboardShowing {
                        let indexPath = IndexPath(item: self.comments.count-1, section: 0)
                        self.collectionView.scrollToItem(at: indexPath, at: .top, animated: true)
                    }
                })
            }
        }

It seems to be causing this error
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'attempt to scroll to invalid index path: {length = 2, path = 0 - 3}' 

Any insight on how to fix this using iglist kit. I beleive it has to do with a count of the elements in the controller because that is what allowed me to do utilize it in my pre IGListKit Implementation

**Comment by rnystrom** [comment]
Can you repro this in an example app we can debug? There isn’t enough information for us to action yet.

You might also want to use the scrolling APIs on `IGListAdapter` instead.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Smiller193** [comment]
Ill take a look at that however this is my github repo
https://github.com/Smiller193/EventfulApp1
and this is a sample login
shawn@Makefool.com
Gohan114
Select one of the pictures and go click the comment/message bubble image and toggle the keyboard that will reproduce the error

**Comment by weyert** [comment]
```
let indexPath = IndexPath(item: self.comments.count-1, section: 0)
self.collectionView.scrollToItem(at: indexPath, at: .top, animated: true)
```

You need to be sure that indexPath is valid before scrolling.

**Comment by Smiller193** [comment]
Okay i found the scroll(toObject) method thanks ill look into it

**Comment by Smiller193** [comment]
listAdapter.scroll(to: <#T##Any#>, supplementaryKinds: <#T##[String]?#>, scrollDirection: <#T##UICollectionViewScrollDirection#>, scrollPosition: <#T##UICollectionViewScrollPosition#>, animated: <#T##Bool#>)


So how would this method trigger on keyboard toggle when the current object is in the listAdapter datasource function

**Comment by Smiller193** [comment]
@rnystrom @weyert

**Comment by weyert** [comment]
That's an implementation detail on your end?

**Comment by Smiller193** [comment]
Um well, the thing I copy and paste is just the function that comes when you attempt to use that function. Yeah, Im just trying to figure out where this function would fit in at.

**Comment by Smiller193** [comment]
Based on the function I had to accomplish goal to scroll to the bottom

**Comment by jessesquires** [comment]
Closing old issues that seem to be resolved or are inactive. 😄 

If this isn't resolved and you still need/want help, please re-open! 😊
