### ISSUE TITLE
Cell variants with `IGListKit`

### ISSUE THREAD

**Issue by tunidev** [Instagram/IGListKit#966]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information 
- `IGListKit` version: 4.0.0
- iOS version(s): iOS 11
- CocoaPods/Carthage version: Carthage 0.25.0
- Xcode version: 9

### Question:

Let's say we have two CollectionView cells, the only difference is the position of the labels and the layout constraints. It's better to have only one Cell for this case but have sort of variant parameter or options when the cell is inited, can this logic be applied with `IGListKit`

**Comment by weyert** [comment]
You still need to return the cell so while creating the cell, can't you set a property there and ensure the constraints get updated when this property change?

**Comment by tunidev** [comment]
@weyert that's an option, after dequeue a cell do something like `updateLayout(option:_)` but I was looking for something while the cell inited. For example I see that we can't use identifier to dequeue the cells since it has always a default identifier
