### ISSUE TITLE
Manual Install

### ISSUE THREAD

**Issue by andre1720** [Instagram/IGListKit#967]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version:
- iOS version(s): All
- CocoaPods/Carthage version: 1.2
- Xcode version: 9
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No): No
- Related issues: 

Hi, I have an issue while I try to install IGListKit. In my App I have googlemaps library and it's a static library so I can't use !use_framework in my pod file.
Can I install it manually? 
Where can I find the framework?

Thank you!

**Comment by rnystrom** [comment]
@andre1720 you’re using CocoaPods right? You can use IGListKit as a static or dynamic lib just fine. Installing manually works too, just drag the xcodeproj file into your workspace.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andre1720** [comment]
Hi @rnystrom thank you for your answer. 
How can I add it as a static? I haven't to add !use_framework? Because if I add it without !use_framework, Xcode say me 'module not found' :(
What have I to import? Only IGListKit.xcodeproj?

Thank you!

**Comment by rnystrom** [comment]
Hmm it should work with and without `use_frameworks` to my knowledge. Yes, you can just drag IGListKit.xcodeproj into your workspace.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andre1720** [comment]
Thanks, it works 👍 💯
