### ISSUE TITLE
Not working on xcode 9, swift 4

### ISSUE THREAD

**Issue by iOSUser110** [Instagram/IGListKit#968]
Not working with swift 3.2 or swift 4, getting many errors,
but i can run the example app using xcode 9.

my project i can not able to run ,even i have tried  manual installation for IGListKIt

**Comment by weyert** [comment]
Could you share some more details what kind of errors? The library is actively used by the GitHawk project and at work I don't experience any issues with xcode 9.

**Comment by rnystrom** [comment]
Yup @iOSUser110 I’ve been using IGListKit with Xcode 9 and Swift 4 for a couple weeks now. Definitely need more information Before we can help.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by otymartin** [comment]
@rnystrom Have you been using target ios11 or ios10? I see a number of warnings as well.
Please excuse the image but just quick snapshot of what im seing

![screen shot 2017-10-20 at 9 22 07 pm](https://user-images.githubusercontent.com/2222881/31846686-dcefa800-b5dc-11e7-935d-467ca3573b5a.png)

**Comment by rnystrom** [comment]
@otymartin Did you automatically update Xcode project settings? Those warnings show up with various Xcode 9 Settings. They’re also totally harmless and covered. I have a PR up to fix the block warnings tho.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by otymartin** [comment]
@rnystrom yes I blindly clicked all those recommended xcode settings <- is that the culprit?

**Comment by rnystrom** [comment]
Yup!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
looks like this is resolved? going to close
