### ISSUE TITLE
I have a question about Follower List in instagram

### ISSUE THREAD

**Issue by cpromise** [Instagram/IGListKit#971]
Hello, I am using IGListKit these days and really like it!!
Thank you for sharing.

Actually, what I wanna say is not an issue but just one question.
Does this ```CollectionView``` has one ```section``` and multiple ```cells```?
Or, does it have multiple ```sections``` and each section has one ```cell```?

![img_6dcce5320b8d-1](https://user-images.githubusercontent.com/5927910/31715856-6abd38da-b440-11e7-9ee4-76da734ce308.jpeg)

I'm asking this because it is really hard for me to update my ```model``` with UICollectionViewCell when adapting the former.
So, I'm considering adapting the latter, now.

If you don't feel like it, feel free to delete this issue.
Thank you for reading my question. ^^

**Comment by rnystrom** [comment]
Those are all individual models in their own `IGListSectionController`s (sections). Definitely the way to go!

**Comment by cpromise** [comment]
I appreciate your kindness.
