### ISSUE TITLE
Embedded SelfSizing CollectionView cell size bug after update

### ISSUE THREAD

**Issue by tunidev** [Instagram/IGListKit#972]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### Requirement 

- I have an `EmbeddedSelfSizingCollectionViewCell` that contains a horizontal `UICollectionView`.

- User can scroll the horizontal `UICollectionView` and tap the cells to select/unselect the button.

- All buttons needs to keep in sync with the cell viewModel `selected` property. 

- Horizontal `UICollectionView` needs to be updated each time user select/unselect a button.

### Bugs

- Wrong updated cell sizes when user tap the cell after `context.reload(self)` call.
 
- Horizontal `UICollectionView` does not keep the previous position after update.

### Analysis

- If I just disable the self sizing  feature. Everything works fine.

### Demo Project 

[IGListKitDemo](https://github.com/tunidev/IGListKitDemo)

### Gif 
<img src="https://user-images.githubusercontent.com/4885143/31721790-a5abaace-b41a-11e7-88cd-39cfe799aa6f.gif" width="300">
 
### Help wanted

- Make it work (check demo project) [Main request]
- Code review (If possible) [Optional]

Thank you

**Comment by rnystrom** [comment]
Closing this in favor of tracking all self-sizing cell issues in #516. Our recommendation is to not use the self-sizing cell's b/c of their bugs and inconsistencies 😢
