### ISSUE TITLE
I do not quite understand that readme never calls performBatchUpdates (_ :, completion :) or reloadData ()

### ISSUE THREAD

**Issue by broccolii** [Instagram/IGListKit#975]
I still need to manually call the Adapter `- (void)performUpdatesAnimated:(BOOL)animated completion:(nullable IGListUpdaterCompletion)completion;` or IGListBindingSectionController `- (void)updateAnimated:(BOOL)animated completion:(nullable void (^)(BOOL updated))completion;`

I do not quite understand that readme never calls performBatchUpdates

**Comment by rnystrom** [comment]
@broccolii can you be more specific about what is wrong? Are you saying there is something incorrect or missing in our documentation?

What do you mean you have to manually call the perform updates methods? What do you expect to be automatic?

**Comment by jessesquires** [comment]
Closing old issues that seem to be resolved or are inactive. 😄 

If this isn't resolved and you still need/want help, please re-open! 😊
