### ISSUE TITLE
performUpdate without moveItems

### ISSUE THREAD

**Issue by mlight3** [Instagram/IGListKit#978]
Calling `performUpdate` execute insertions, deletions and moves.
When I have a large data, sometimes bottom cell is moving to top too fast.
I think I looks bad for ux, so how can I animate cells only using insertion and deletions without move?

**Comment by rnystrom** [comment]
Yup! Just enable this flag on your updated:

https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapterUpdater.h

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mlight3** [comment]
Thanks! 👍
