### ISSUE TITLE
Preventing a cell getting removed when scrolling off of the screen

### ISSUE THREAD

**Issue by stevejcox** [Instagram/IGListKit#979]
Hi There,

I have a vertical list, with various different types of cells.

The first cell is a custom view with a colored background that extends below the size of the cell. This cell has clipToBounds = false, to bleed the background into the next cell beneath it.

This works fine until the first cell starts to go off screen. Once the bounds are off the cell is removed and the colored background that had bled into the cell below immediately disappears.

Any suggestions on how I might keep the first cell alive until it has fully gone off screen (incl the non-clipped area)?

Thanks,
Steve

**Comment by jessesquires** [comment]
Hey @stevejcox !

This generally sounds like it's probably not a great idea. 

You could try to retain the cell or something but that's going to require a lot of bookkeeping and probably introduce more (and worse) bugs. I'd ask myself: why do you need this behavior? is there another way to achieve this? etc.

It sounds like this view is purely decorative. If so, I'd consider using decoration views or event supplementary views. (This would probably require a custom collection view layout.)

**Comment by rnystrom** [comment]
@stevejcox you probably want to write your own layout to do this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
