### ISSUE TITLE
NestedAdapter for Horizontal CollectionView and List

### ISSUE THREAD

**Issue by mlight3** [Instagram/IGListKit#980]
My view has horizontal collection view and list like search tab on instagram.
I made a Section model and section controller for each type. For horizontal collection view, I referenced example code of `NestedAdapterViewController`. For list, I just created simple SectionController.
But the problem is when I'm updating data with `performUpdates`, horizontal section works fine but error occurred on list section. 

> 'Invalid update: invalid number of items in section 2.  The number of items contained in an existing section after the update (23) must be equal to the number of items contained in that section before the update (13), plus or minus the number of items inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).'

I thinks `performUpdates` only effects for objects in ListAdapter not in nested section.
Should I do performBatch manually in `didUpdate` function?

```
enum SectionType {
  case horizontal
  case list
}

class Section {
  let type: SectionType
  let items: [SectionItem]
}

func listAdapter(_ listAdapter: ListAdapter, sectionControllerFor object: Any) -> ListSectionController {
    let section = object as! Section
    switch section.type {
    case .horizontal: return HorizontalListSectionController()
    case .list: return VerticalListSectionController()
    }
  }
```

```
final class VerticalSectionController: ListSectionController {
  override func numberOfItems() -> Int {
    return section.itemCount
  }
  
  override func sizeForItem(at index: Int) -> CGSize {
    return CGSize(width: collectionContext!.containerSize.width, height: 50)
  }
  
  override func cellForItem(at index: Int) -> UICollectionViewCell {
    guard let cell = collectionContext?.dequeueReusableCell(
      of: CommentCell.self,
      for: self,
      at: index) as? CommentCell else { fatalError() }
    let viewModel = section.item(at: index) as! SectionItem
    cell.configure(with: viewModel)
    return cell
  }

  override func didUpdate(to object: Any) {
    section = (object as! Section)
  }
}
```

**Comment by rnystrom** [comment]
@mlight3 It's a little unclear where the error might be, but you definitely need to propagate any model changes to the nested adapter.

However if you connect the nested cell's `UICollectionView` to the nested `IGListAdapter` [like this](https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/HorizontalSectionController.swift#L39), then everything should work (it'll update data).

We did pick up on an embedding issue in #952 though too.

If you can provide an example reproducing the issues, that'd make it a lot easier for me to help debug.

**Comment by mlight3** [comment]
@rnystrom I found what I am doing wrong. Here is my models.

```
enum SectionType {
  case horizontal
  case vertical
}

class Section: NSObject {
  let type: SectionType
  let title: String
  let items: [SectionItem]
}

class SectionItem: NSObject {
  let text: String
}


import IGListKit
extension Section: ListDiffable {
  func diffIdentifier() -> NSObjectProtocol {
    return title as NSObjectProtocol
  }
  
  func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
    guard let object = object as? Section else { return false }
    guard self.type == object.type else { return false }
    return self.title == object.title
  }
}

extension SectionItem: ListDiffable {
  func diffIdentifier() -> NSObjectProtocol {
    return text as NSObjectProtocol
  }
  
  func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
    guard let object = object as? SectionItem else { return false }
    return self.text == object.text
  }
}
```

When I changed `isEqual` func to this code, it works well!

```
extension Section: ListDiffable {
  func diffIdentifier() -> NSObjectProtocol {
    return title as NSObjectProtocol
  }
  
  func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
    guard let object = object as? Section else { return false }
    guard self.type == object.type else { return false }
    guard self.title == object.title else { return false }
    return self.items == object.items
  }
}
```

Is it a good approach? or I'm doing wrong?

BTW the other problem is occurred. 
I have a header view inside each section controller. 
If I changed section items not key and title, the adapter is updating not only items but "section header". Header view is slightly flashing.

**Comment by mlight3** [comment]
I tested with `SupplementaryViewController` in Example, header is also flashing when update.

```
feedItems[0] = FeedItem(pk: 1, user: User(pk: 100, name: "Paul", handle: "header is flashing"), comments: ["You rock!", "Hmm you sure about that?"])
    adapter.performUpdates(animated: true, completion: nil)
```

**Comment by rnystrom** [comment]
@mlight3 sorry I'm having a little trouble understanding what the problem is. Can you give me some steps to using the code you provided so I can reproduce the issue?

**Comment by sasquatchgit** [comment]
Hi @mlight3, I am having the same issue. The section header is reloading indicating the parent section controller is reloading. I am getting the same >Invalid Update error.
Did you find a way to solve this? I can't understand how changing the `isEqual` function helps.
