### ISSUE TITLE
[Gardening] Fix comment headers in IGListKitExamples/ project files

### ISSUE THREAD

**Issue by jessesquires** [Instagram/IGListKit#99]
Some files in `IGListKitExamples/` have incorrect comment headers, like:

https://github.com/Instagram/IGListKit/blob/master/Example/IGListKitExamples/ViewControllers/WorkingRangeViewController.swift#L1-L7

Should be:

https://github.com/Instagram/IGListKit/blob/master/Example/IGListKitExamples/ViewControllers/DemosViewController.swift#L1-L13

cc @rnystrom 😏

**Comment by rnystrom** [comment]
😬
