### ISSUE TITLE
CollectionView has left padding on Landscape iPad (similar to tableview.cellLayoutMarginsFollowReadableWidth)

### ISSUE THREAD

**Issue by omerfarukyilmaz** [Instagram/IGListKit#996]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### General information

- `IGListKit` version: **3.1.1**
- iOS version(s): **iOS 11**
- CocoaPods/Carthage version: **1.3.1**
- Xcode version: **Version 9.1 beta (9B46)**
- Devices/Simulators affected: **Yes**
- Reproducible in the demo project? (Yes/No): **Yes**

As the title mentions, an extra space appears on Landscape that I could not get rid of for some reason. It looks very similar to of TableView's and I have a strong feeling it is caused by Safe Area on iOS 11, but I am not certain. I have tried both creating the views programmatically and via IB, same results.

Using the same CollectionView without IGListKit does **not** face the same issue.

Without keeping the text too long, I am attaching screenshots that show the issue and a sample repo that replicates it.

![simulator screen shot - ipad pro 9 7-inch - 2017-10-30 at 17 24 33](https://user-images.githubusercontent.com/5538485/32163446-4a775fe6-bd97-11e7-80f6-cb9d141d1d81.png)
![simulator screen shot - ipad pro 9 7-inch - 2017-10-30 at 17 24 34](https://user-images.githubusercontent.com/5538485/32163449-4bc5cbc6-bd97-11e7-8c19-ac79c7f7928f.png)

#### Steps to reproduce
- clone repo
- pod install
- run on an iPad
- Switch between Portrait and Landscape (sometimes a few times)

### **Repo:**
https://github.com/omerfarukyilmaz/IGListKitBug

**Comment by weyert** [comment]
I think this has to do that the cells don't get resized correctly when rotating the device so you sometimes end up the 'portrait' cell sizes while the device in landscape. Can you try to invalidate the layout while rotating? 

Try doing something like the code below in `func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator)`:

```
layout.invalidateLayout(with: layout.invalidationContext(forBoundsChange: CGRect(x: 0, y: 0, width: size.width, height: size.height)))
```

**Comment by omerfarukyilmaz** [comment]
Well, that actually freaking solved it. That was very quick and helpful. Thank you very much @weyert. 

 I'll close the issue because it does not seem like a problem of IGListKit. So no need to clutter up here.

**Comment by weyert** [comment]
Great!
