### ISSUE TITLE
Scroll to end of the collectionView when using EmbeddedSectionController

### ISSUE THREAD

**Issue by tunidev** [Instagram/IGListKit#998]
## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/Instagram/IGListKit/blob/master/README.md) and [documentation](http://instagram.github.io/IGListKit)
- [x] I have searched [existing issues](https://github.com/Instagram/IGListKit/issues) and this is not a duplicate

### Help Needed:

I have a horizontal collectionView embedded in a vertical collectionView just like https://github.com/Instagram/IGListKit/blob/master/Examples/Examples-iOS/IGListKitExamples/SectionControllers/HorizontalSectionController.swift 

Part of the requirement that after populating the collectionView with the data from the server it should scroll to the end (top right) how,  where and when is the perfect time and place to scroll the collectionView (embedded one in the Cell) to the end

**Comment by reveching** [comment]
I'm using a lot of self-sizing cells in my collectionView and the contentSize is not consistent as I scroll along. It's almost impossible to do accurate scrolling because of the inconsistency

**Comment by ShantiBhatt** [comment]
I'm facing the same issue with self sizing cells, have anyone any idea about it?
