### ISSUE TITLE
IGListBindingSectionController updateAnimated have copy BUG

### ISSUE THREAD

**Issue by YasinZhou** [Instagram/IGListKit#999]
IGListBindingSectionController.m
- (void)updateAnimated:(BOOL)animated completion:(void (^)(BOOL))completion{}
```
oldViewModels = self.viewModels;
```
and late
```
self.viewModels = [self.dataSource sectionController:self viewModelsForObject:object];
result = IGListDiff(oldViewModels, self.viewModels, IGListDiffEquality);
```

if `self.viewModels` is a NSMutableArray and just removeAllObjects and change the all value,
`result = IGListDiff(oldViewModels, self.viewModels, IGListDiffEquality);` is NOT right
so i think , oldViewModels need copy the self.viewModels([self.viewModels copy]) or self.viewModels's property replaces strong with copy.

and i think another ` updateAnimated ` have same BUG maybe

**Comment by rnystrom** [comment]
Thanks for investigating @YasinZhou! We [deduplicate](https://github.com/Instagram/IGListKit/blob/master/Source/IGListBindingSectionController.m#L64-L66) the models returned from the data source, so even if a mutable array is returned, it should be totally safe.

You made me double check everything though, and I did come across [this](https://github.com/Instagram/IGListKit/blob/master/Source/IGListBindingSectionController.m#L117), and you're right that if the data source returns an `NSMutableArray`, they could mutate the array and corrupt the models stored inside the binding section controller.

That'd be a really easy and useful fix if you want to submit a PR!

**Comment by rnystrom** [comment]
Good bug, but not world-ending. Leaving as a great starter task for someone!

**Comment by KashishGoel** [comment]
@rnystrom I decided to take care of this. However, I'm not sure if this is something we need to write a test for. I don't think we need to write one for this change. Any thoughts on this?
